### ISSUE TITLE
Fix circular dependencies 

### ISSUE THREAD

**Issue by patricklodder** [dogecoin/dogecoin#1015]
When (if) #1013 gets merged, we won't have active qt payment server tests until we fix the circular dependency issue between libbitcoin_wallet.a and libbitcoin_server.a ( and libbitcoin_wallet.a, and libbitcoin_server.a, I'm sure you get it :D)

The patch introduced by #386 (and re-implemented in #849) is no longer sufficient and has been disabled by #1013. I hope we (I) can fix the issue by fixing the cause, without having to create dummy modules :)

**Comment by rnicoll** [comment]
Can this be closed as 1.9 is abandoned?
