### ISSUE TITLE
Ubuntu dogecoin-qt will not finish loading, unresponsive, hard disk thrashes.  Too many transactions?

### ISSUE THREAD

**Issue by bronxDakota** [dogecoin/dogecoin#1038]
![screenshot from 2015-03-15 10 12 29](https://cloud.githubusercontent.com/assets/11253380/6655431/22c5d958-cb34-11e4-9d4f-b5ceeaf45394.png)

**Comment by Sporklin** [comment]
This looks really interesting. If you can could you log onto the freenode IRC and come to dogecoin-dev I would be more than happy to help try to figure out what happened and get more information.

**Comment by rnicoll** [comment]
Can we get a tag for "Inherited design issue from upstream"?

**Comment by bronxDakota** [comment]
No.

**Comment by langerhans** [comment]
Please attach your ~/.dogecoin/debug.log file. Thanks.

**Comment by rnicoll** [comment]
Pending logs, my money's on the database loading code doesn't scale, and essentially this is a design problem with using BDB. Something something Toshi something (although yes I know I need to actually write a Toshi-compatible wallet layer)

**Comment by bronxDakota** [comment]
Tried uploading the log, says it doesn't support that file type.

**Comment by bronxDakota** [comment]
I'm investigating the issue myself.

**Comment by prestotron** [comment]
@bronxDakota Please use Pastebin for the log. 

Thank you.

**Comment by langerhans** [comment]
Closing here since we know by now this was caused to thousands of retardedly small spam transactions.  
Spamming the Blockchain does not warrant an issue here ;)
