### ISSUE TITLE
Add support for watch-only addresses

### ISSUE THREAD

**Issue by majikpig** [dogecoin/dogecoin#111]
Many programs coded for bitcoin markets and online wallets require rpc call "importaddress" which imports a watch-only address for tracking, but from which coins cannot be spent (no private key).

See https://github.com/bitcoin/bitcoin/pull/2861 and
https://github.com/sipa/bitcoin/commit/a13f1e8f61f2c4f32c72c72409ea591228557434

**Comment by langerhans** [comment]
#1028 will close this

**Comment by mmoren73** [comment]
guys did they just update the doge core wallet? whats is up with the watch only crap, ive been using this wallet for two years with no issues, i open my wallet and all of a sudden all my coins are gone, they went from spendable to watch only...whyyy??????  i dont recognize this address, i have no idea whos it is or where it came from, ive never messed with the comsole, i dont even know how to check this watch only address or get my coins back from it. why would they do somethin gso stupid like update awith watch only, thats just another way hackers can steal coins, what is the matter with these developers, i mean really, thats just lazy if they cant check their wallets and have to be able to do it form one wallet. how am i going to get my coins back form that stupid useless watch only address, i dont know any of these console commands and crap, i dont know if i even own that address or how to find out, but these developers should be giving me my coins back, its their stupid software that sent my coins off to watch only land, i know i wasnt hacked, i have decent security, and my wallet was encrypted. so why did this happen?? and how do i get them back?
