### ISSUE TITLE
Error compiling 1.8.2 with Boost 1.58.0-1

### ISSUE THREAD

**Issue by naqern** [dogecoin/dogecoin#1128]
[...]
   CXX      rpcrawtransaction.o
In file included from /usr/include/boost/move/detail/type_traits.hpp:34:0,
                 from /usr/include/boost/move/core.hpp:54,
                 from /usr/include/boost/move/utility_core.hpp:29,
                 from /usr/include/boost/move/utility.hpp:28,
                 from /usr/include/boost/thread/detail/move.hpp:27,
                 from /usr/include/boost/thread/lock_types.hpp:11,
                 from /usr/include/boost/thread/pthread/mutex.hpp:16,
                 from /usr/include/boost/thread/mutex.hpp:16,
                 from allocators.h:13,
                 from serialize.h:9,
                 from bignum.h:9,
                 from chainparams.h:9,
                 from base58.h:17,
                 from rpcrawtransaction.cpp:6:
/usr/include/boost/variant/get.hpp: In instantiation of ‘typename boost::add_reference<T>::type boost::strict_get(boost::variant<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19>&) [with U = const CScriptID&; T0 = CNoDestination; T1 = CKeyID; T2 = CScriptID; T3 = boost::detail::variant::void_; T4 = boost::detail::variant::void_; T5 = boost::detail::variant::void_; T6 = boost::detail::variant::void_; T7 = boost::detail::variant::void_; T8 = boost::detail::variant::void_; T9 = boost::detail::variant::void_; T10 = boost::detail::variant::void_; T11 = boost::detail::variant::void_; T12 = boost::detail::variant::void_; T13 = boost::detail::variant::void_; T14 = boost::detail::variant::void_; T15 = boost::detail::variant::void_; T16 = boost::detail::variant::void_; T17 = boost::detail::variant::void_; T18 = boost::detail::variant::void_; T19 = boost::detail::variant::void_; typename boost::add_reference<T>::type = const CScriptID&]’:
/usr/include/boost/variant/get.hpp:284:33:   required from ‘typename boost::add_reference<T>::type boost::get(boost::variant<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19>&) [with U = const CScriptID&; T0 = CNoDestination; T1 = CKeyID; T2 = CScriptID; T3 = boost::detail::variant::void_; T4 = boost::detail::variant::void_; T5 = boost::detail::variant::void_; T6 = boost::detail::variant::void_; T7 = boost::detail::variant::void_; T8 = boost::detail::variant::void_; T9 = boost::detail::variant::void_; T10 = boost::detail::variant::void_; T11 = boost::detail::variant::void_; T12 = boost::detail::variant::void_; T13 = boost::detail::variant::void_; T14 = boost::detail::variant::void_; T15 = boost::detail::variant::void_; T16 = boost::detail::variant::void_; T17 = boost::detail::variant::void_; T18 = boost::detail::variant::void_; T19 = boost::detail::variant::void_; typename boost::add_reference<T>::type = const CScriptID&]’
rpcrawtransaction.cpp:299:77:   required from here
/usr/include/boost/variant/get.hpp:178:5: error: invalid application of ‘sizeof’ to incomplete type ‘boost::STATIC_ASSERTION_FAILURE<false>’
     BOOST_STATIC_ASSERT_MSG(
     ^
[...]

**Comment by patricklodder** [comment]
There's an advertised breaking change for `boost::get` in 1.58, so Dogecoin 1.8.2 is incompatible with that. We coded and tested it against 1.55.0.

What os/distro are you compiling on?

**Comment by naqern** [comment]
Oh, sorry, I missed the warning about the change. Thank you for the explanation I will downgrade boost.The distro is Archlinux and boost was updated (to 1.58) on 2015-04-28.

**Comment by patricklodder** [comment]
I have a script for compiling with userspace libs for centos here: https://gist.github.com/patricklodder/c7c067cc831f0d3190c2

Could work with Archlinux too.

**Comment by naqern** [comment]
Really thank you! Later I will try it.

**Comment by indywidualny** [comment]
The latest working boost and boost-libs version for Arch Linux is 1.57.0-4. Downgrade both of the packages and it will work like a charm ;)

**Comment by ShapeShifter499** [comment]
I have the identical issue described above. Also running Arch Linux, I'll try downgrading Boost in the meantime.

**Comment by SoniEx2** [comment]
I just changed the line to relaxed_get instead of get. So far it's working just fine.

**Comment by djadk84** [comment]
I was able to fixed issue applying to this patch
https://github.com/bitcoin/bitcoin/pull/6114/files

**Comment by rnicoll** [comment]
Thanks @djadk84, I've checked and that's merged into 1.10, so it will be fixed in that version.

**Comment by langerhans** [comment]
Since Beta 1 is out, we can close this. The fix is in :) If it still breaks, let us know!
