### ISSUE TITLE
RPC call to retrieve TxID's associated with an address

### ISSUE THREAD

**Issue by MachoSmurf** [dogecoin/dogecoin#1163]
Using the current RPC calls it is only possible to retrieve TxID's associated with an account in the build-in accounting system. However, since it is no longer advised to use this system there is no longer a possibility to retrieve TxID's using RPC calls. 

What I am suggesting is a call that returns an array of transactions and information about them (TxID, amount), associated with a given address.

For reference, the issue came up when rnicoll helped me improve the PHP Framework I build, based on RPC calls: https://github.com/MachoSmurf/DogeFrame/issues/3

**Comment by kaykurokawa** [comment]
So basically like "listtransactions" except you can put in an address as parameter?

**Comment by MachoSmurf** [comment]
exactly

**Comment by rnicoll** [comment]
Turns out the reason this isn't done by default is it would mean huge indexes. I'd suggest a block explorer with an API, although `-txindex=` should offer this functionality I believe.

**Comment by MachoSmurf** [comment]
Thanks for looking into it. I guess that means this issue is closed ;)
