### ISSUE TITLE
Request to keep gitian-descriptor file names consistent

### ISSUE THREAD

**Issue by stapler117** [dogecoin/dogecoin#1183]
gitian-osx-depends.yml --->> depends-osx.yml
gitian-osx-qt.yml --->> qt-osx.yml
gitian-osx-bitcoin.yml --->> gitian-osx.yml

This will change to osx ones to be more like the others. I have a PR incoming to fix a few things in those files as well. I just wanted to know if i should rename them in that PR or not

**Comment by langerhans** [comment]
We are currently in the process of switching our development strategy towards taking bitcoin 0.11 and porting the Doge specific changes again. 1.9-dev will not be continued to work on that way.

We can talk about it on IRC later or so ;)

**Comment by rnicoll** [comment]
These are now simplified and consistent in 1.10: https://github.com/dogecoin/dogecoin/tree/1.10-dev/contrib/gitian-descriptors
