### ISSUE TITLE
the gettxoutsetinfo command error

### ISSUE THREAD

**Issue by qianshanhai** [dogecoin/dogecoin#1203]
I want to fetch the currently mining total, when I use 'gettxoutsetinfo' command, it output:

{
    "height" : 788480,
    "bestblock" : "faf9cde37128227389991653e2911267937e01850f8a443bc6bb7ce6f5fef703",
    "transactions" : 4414277,
    "txouts" : 16550439,
    "bytes_serialized" : 579593118,
    "hash_serialized" : "9a9a3366f9c73d5253a35687bb759c5c33a536fb04c18cbf3c68a1b18cb90c48",
    "total_amount" : -84348075190.47520447
}

Why the total_amount value is not correct?
And how do get this value?
Thanks.

**Comment by langerhans** [comment]
It's counted in an int64_t which won't be able to hold the full amount of currently existing coins (in their smallest unit).  
We could check if we can fix that but it seems to be a small issue since it's just statistics, nothing crucial.

**Comment by langerhans** [comment]
Fixed in #1227
