### ISSUE TITLE
Block height in new block notification for 1.10

### ISSUE THREAD

**Issue by rnicoll** [dogecoin/dogecoin#1230]
Have a problem with merging #753 into 1.10. New blocks are now notified via a signal rather than inline with the new block code, and as a result block height isn't available. Looking at init.cpp line 455 BlockNotifyCallback() - if the height is important we can probably load the block from block store and get height this way. I don't think we can safely presume current tip is the height of the block we're notified about, as new blocks are received on a different thread to signal processing (so multiple blocks may arrive before the  signals are processed).

Thoughts?

Of relevance also to #1136

**Comment by langerhans** [comment]
The actual notification happens here: https://github.com/dogecoin/dogecoin/blob/1.10-dev/src/main.cpp#L2430  
Which has access to the height of the new active chain (which is the part we are interested in. Shouldn't that be okay for this use case, also given it is the same as #753 did it with just taking the active chain tip?

**Comment by rnicoll** [comment]
As in thread it through the signal? Yeah, could do.

**Comment by langerhans** [comment]
Yup, why not? If anyone is using it by now, they'd expect same behavior and if we just hand that through the same signal, it should be fine.

**Comment by rnicoll** [comment]
Resolved in #1238
