### ISSUE TITLE
User manual link in help menu?

### ISSUE THREAD

**Issue by peoplma** [dogecoin/dogecoin#1242]
Hey dev shibes, I was wondering what you guys thought about putting a link to this community maintained core wallet user guide/manual authored by /u/aesarium in the help menu?  https://www.reddit.com/r/dogecoin/wiki/dogecoincoreguide  It's definitely the most comprehensive and user friendly documentation to using a core client that I've seen in crypto.  Expanding the troubleshooting section for common questions and problems would definitely happen if this were to make it into the help menu.  Dogecoin has always been a crypto for newbies, and I think having some solid reference material for how to use the client would be very beneficial.

It could go next to "about dogecoin core".  If you'd rather not link to reddit for whatever reason, I'd be happy to take the lead in porting the manual over to dogecoin.com and putting a PR in to add a page there to link to instead.

Let me know what you think!

**Comment by langerhans** [comment]
Question: Who all would have access to edit that page? What if the link changes?  
Reason I ask is that I'm a bit hestitating linking to a site we don't control in full. I'd be okay to link to the guide it it'd be part of dogecoin.com.   

As long as it can be kept up to date easily :)

**Comment by peoplma** [comment]
Right now aesarium, patricklodder, and joshtheimpaler can edit it, as well as all the mods except mumzie.  I'd be happy to add any of you guys to edit as well (that goes for any of the wiki pages).  I was thinking it'd be easier to keep up to date on reddit, simply beacuse PRs sometimes take a while to get merged on dogecoin.com. But I agree that it'd probably be better to host it on a shibe-owned server.  I'd be happy to create a page on dogecoin.com also.  Or how about here on github?  Doesn't matter to me!

**Comment by langerhans** [comment]
Putting in on GitHub would have the advantage of an easy update since GitHub also supports Markdown just like reddit. So it would be really easy to keep it up to date with a simple copy/past of the complete page.  
The current wiki here is rather sparse, although I never noticed that someone added something to it :D

**Comment by peoplma** [comment]
Cool, I might suggest locking down the wiki here to "Restrict editing to collaborators only" to prevent wiki vandals, but yeah, sounds good :)  Shall I make the page?

**Comment by patricklodder** [comment]
I have one more thought to add to this. We have at any time multiple versions of Dogecoin Core that are maintained, so I'd suggest to release and link docs per version. Just look at the differences for QT layouts between 1.8.2 and 1.10-beta-1, both branches will be supported and likely, for some time to come.

**Comment by peoplma** [comment]
Yeah, agreed Patrick.  Most of the stuff is relevant for both versions, but as new features are added the manual should be updated along with it.  Can simply have two different pages for the manual, one for 1.8.2, which is the current one, and one for 1.10.  I'll make sure a 1.10 version of the guide gets done.  I can redo screenshots.  The beta version of 1.10 has undone some of the doge branding (wow, much receive, pls send, etc...) and changed the icons, will those changes be in the final release of 1.10 too or are they left over from bitcoin in the beta?  I'd be happy to get the 1.10 version of the guide out before your final release, but if screenshots will need to be redone then obviously I'd need the final version first.

**Comment by patricklodder** [comment]
> The beta version of 1.10 has undone some of the doge branding (wow, much receive, pls send, etc...) and changed the icons, will those changes be in the final release of 1.10 too or are they left over from bitcoin in the beta?

As I understood it from @langerhans, we'll do at least a release candidate for 1.10, which will contain fixes to UI, branding and "translations" as this is ongoing. Depending on what else we find from this point forward, we might need to do a beta-2, so there should be plenty of time between screenshots and release. Plus since it's online documentation, there are no real deadlines and we can tune things after release :)

PS: are we sure we want to be putting this on github wiki, not on dogecoin.com? The latter is an endpoint we can control, the former does bring in a dependency to github (it's troubling to build new binaries if github would change url structure or worse, especially for old versions)

**Comment by cryptodogeminer** [comment]
http://www.cryptodogeminer.com
Cryptodogemining we have strong partners and have latest eqipments through which in less than 2 months you can double doge coin. Crypto mining mainly focus on doge mining as dogecoin quickly developed its own online community and reached a capitalization of US $60 million in January 2014.
Dogecoin had a fast initial coin production schedule: 100 billion coins were in circulation by mid-2015, with an additional 5.256 billion coins every year thereafter. 
We have wide range of doge mining plans in which you can earn 524 Ðper day by investing 10,000 Ð, Earn 2750 Ð per day by investing 50,000 Ð, Earn 5750 Ð per day by investing 1,00,000 Ð, Earn 11500 Ð per day by investing 2,00,000 Ð . So we are best crypto currency mining that helps you to earn more by investing little in Doge mining.To invest in doge mining and to earn more,click on the link
http://www.cryptodogeminer.com

**Comment by ReverseControl** [comment]
@patricklodder @langerhans Any updates on this? Its been awhile.

**Comment by ReverseControl** [comment]
https://dogecoin.com/ now addresses this issue.
