### ISSUE TITLE
thin space in amounts

### ISSUE THREAD

**Issue by patricklodder** [dogecoin/dogecoin#1255]
Amounts look like this on osx:

![screenshot](https://cloud.githubusercontent.com/assets/1410115/9304478/e6592644-44e8-11e5-8dd4-6566d878bd9e.png)

Perhaps we should re-implement 2 decimals and locale-based separators?

**Comment by rnicoll** [comment]
If we can make locale-based separators work,that's probably the better solution.

**Comment by patricklodder** [comment]
Confirmed fixed by #1279, thanks @rnicoll :)
