### ISSUE TITLE
N5boost Error (current wallet)

### ISSUE THREAD

**Issue by flutestack** [dogecoin/dogecoin#1285]
So I just open up my wallet and this new error came up when opening dogecoin client.

EXCEPTION:N5boost12interprocess22interprocess_exceptionE
Access is denied.
Dogecoint-qt.exe in Runaway exception

Im wondering what could be the issue?

**Comment by langerhans** [comment]
Seems like this happens when the data directory is not accessible by the current user. Check the permissions and owner. Just to make sure: Your run 1.8.2, right?

**Comment by flutestack** [comment]
yup i am. 

permissions? how would I do that?

**Comment by langerhans** [comment]
Uhm, on the screenshot you posed on Reddit it says 1.4. Anyway. Go to C:\Users\YourUsernameHere\AppData\Roaming\ where you should find the Dogecoin folder. Right click, click Properties and check under Security. Owner should be you and access should be given to your user or "Everyone".

**Comment by flutestack** [comment]
oh sorry about that. yup under security it says I have everyone. still the same message when loading client.

**Comment by flutestack** [comment]
ahh I got it. everything was read only! Now I got it! Thanks!

**Comment by langerhans** [comment]
Glad to hear, gonna close here then :)
