### ISSUE TITLE
shared icon resource in osx desktop notification

### ISSUE THREAD

**Issue by patricklodder** [dogecoin/dogecoin#1298]
![img](http://gateway.ipfs.io/ipfs/QmRMdx8zDUoZBCuYEVo96SnbSBzk4VMU71NoSDwrr1v9Rt)

this just happened while I was running clam-qt and dogecoin-qt (testnet) concurrently

**Comment by langerhans** [comment]
Normally that should be based on the bundle identifier in the plist of the app bundle. But that is different for clams, so I suspect this might be an issue: https://github.com/dogecoin/dogecoin/blob/1.10-branding/src/qt/macnotificationhandler.mm#L16

**Comment by patricklodder** [comment]
Not sure if this is it, because it's: [`org.clamfoundation.Clam-Qt`](https://github.com/nochowderforyou/clams/blob/master/src/qt/macnotificationhandler.mm#L16) for clam

**Comment by himanshu007-creator** [comment]
Hi , I am new here and would like to work on this issue. Can you guide me how to fix this?

**Comment by ReverseControl** [comment]
@patricklodder I am closing this issue as out-of-date. If this becomes relevant again, we can open it again. Incidentally, that image link is now broken Patrick.
