### ISSUE TITLE
"Amounts" column in "coin control" are sorted alphabetically when col header is clicked

### ISSUE THREAD

**Issue by cdeverett** [dogecoin/dogecoin#1314]
See title

**Comment by langerhans** [comment]
Actually a duplicate of #1289 , but can you give me some sample amounts I'd need to reproduce this? Cause on my coin control it sorts fine still :/

**Comment by cdeverett** [comment]
Try creating a send tx, that directs 3, 200 and 10 doge to yourself. 

They should sort as 3 10 200, but will appear as 10 200 3.

Looks even weirder once you get thousands in there, with comma separators.

**Comment by langerhans** [comment]
![image](https://cloud.githubusercontent.com/assets/5160000/11159574/2eec6746-8a61-11e5-9b94-ef3e20c75c12.png)  
This might have something to do with the locale aware decimal separators, since it still looks perfectly fine for me in both sorting orders.

**Comment by ReverseControl** [comment]
@patricklodder @rnicoll @michilumin Close this one. Issue is fixed by 1.14.4-dev. Not sure when it was fixed, but it is fixed.

**Comment by patricklodder** [comment]
Fixed with 1.14.x
