### ISSUE TITLE
ARM gitian builds

### ISSUE THREAD

**Issue by patricklodder** [dogecoin/dogecoin#1318]
We currently only build ARM on travis, and the binaries there are discarded. Over the past year a couple of people have asked me for ARM builds (mostly to run it on a raspberry pi.) This came up again today, so I figured I'd raise it here to discuss it more openly.

The issue is 2-fold:
1. We currently don't have ARM gitian descriptors
2. We never build/test dogecoin-qt for ARM

@rnicoll / @langerhans any thoughts?

**Comment by GaryLittlemore** [comment]
I've just posted on the Raspberry Pi forum...

https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=131452

**Comment by dschaper** [comment]
I have a few spare RPi's sitting around, if you can talk a shibe puppy through the process I'll try to help out.

**Comment by langerhans** [comment]
I have an Odroid U2 I can test them against. All I really need is a new SD card to boot from. Otherwise I'd be okay with doing them. The Gitian descriptors should be fairly easy to handle.

**Comment by rllola** [comment]
up.

Currently building 1.14-branding for rpi3 as a docker image.

**Comment by rnicoll** [comment]
Nice!

**Comment by rllola** [comment]
I am able to build on arm64v8 in a docker image (using scaleway server) but for rpi3 and rpi2 so far it is a fail. It keeps crashing. I am trying just to build outside of docker but it is taking forever.

**Comment by rllola** [comment]
Also I want to do something similar to mimble wimble : https://github.com/mimblewimble/grin/blob/master/Dockerfile

It will make the image smaller.

**Comment by rllola** [comment]
For some reason I am not able to build dogecoin 1.14 with the wallet. I tried with db 5.3 and the recommended one db 5.1

Both times it just get stuck. I will try with 1.10 see how it goes.

**Comment by langerhans** [comment]
Closing here as we actually ship both arm and aarch64 through Gitian now with 1.14.
