### ISSUE TITLE
[Windows] 1.10 block corruption when syncing from scratch

### ISSUE THREAD

**Issue by DavidBurela** [dogecoin/dogecoin#1321]
I'm on Windows 10. 
Dogecoin-qt seems to have serious stability issues when trying to sync from scratch. I have tried both the 32 & 64bit versions without success.

It will start to synchronise with the network, and will randomly crash due to corruption errors. I have gone in and cleared out the entire data directory (blocks, chainstate, database, etc.) and tried around 7 times from scratch to try and sync without success. It just always seems to corrupt.

I saved the logs from each failure before I cleared out the data directory and attempted to sync again from scratch:

1:

```
UpdateTip: new best=35d871cefd3d91af3d60ca6fd968a223f734f4a8f956a46d64792c268eb4b76d  height=232691  log2_work=59.555727  tx=9910654  date=2014-05-23 11:53:56 progress=0.301076  cache=59.6MiB(21278tx)
Corruption: block checksum mismatch
*** System error while flushing: Database corrupted
```

2:

```
UpdateTip: new best=5c95f0b9ae32a21238bf9b9f0698adf7b1e7d227eb991eaecbf64e9ea0f33e7a  height=79499  log2_work=57.09843  tx=5890927  date=2014-01-30 20:49:35 progress=0.178742  cache=50.4MiB(155175tx)
LevelDB read failure: Corruption: block checksum mismatch
Corruption: block checksum mismatch
Error reading from database: Database corrupted
```

3:

```
UpdateTip: new best=b6753af7c4e5d53dce0c3b82871f8b5c6f6bb9c1aaf7bf393d17cb83cc31f0b2  height=77450  log2_work=57.005348  tx=5707848  date=2014-01-29 11:06:52 progress=0.173182  cache=59.1MiB(196705tx)
Corruption: block checksum mismatch
*** System error while flushing: Database corrupted
ERROR: ProcessNewBlock: ActivateBestChain failed
ERROR: ConnectBlock(): inputs missing/spent
Misbehaving: 51.255.219.119:22556 (0 -> 100) BAN THRESHOLD EXCEEDED
InvalidChainFound: invalid block=f9d96ca50c4fc704a699fe08f576f7dd79b9277580ef09e2a92c240b86905091  height=77451  log2_work=57.005394  date=2014-01-29 11:07:17
InvalidChainFound:  current best=b6753af7c4e5d53dce0c3b82871f8b5c6f6bb9c1aaf7bf393d17cb83cc31f0b2  height=77450  log2_work=57.005348  date=2014-01-29 11:06:52
ERROR: ConnectTip(): ConnectBlock f9d96ca50c4fc704a699fe08f576f7dd79b9277580ef09e2a92c240b86905091 failed
InvalidChainFound: invalid block=f9d96ca50c4fc704a699fe08f576f7dd79b9277580ef09e2a92c240b86905091  height=77451  log2_work=57.005394  date=2014-01-29 11:07:17
InvalidChainFound:  current best=b6753af7c4e5d53dce0c3b82871f8b5c6f6bb9c1aaf7bf393d17cb83cc31f0b2  height=77450  log2_work=57.005348  date=2014-01-29 11:06:52
```

4:

```
UpdateTip: new best=7ea4b42f547df77eef9d306c0416b155b3fce167ba43f11d8f06695eb0a43c3b  height=22468  log2_work=52.948915  tx=1246270  date=2013-12-22 03:34:37 progress=0.037804  cache=60.1MiB(223579tx)
Corruption: block checksum mismatch
*** System error while flushing: Database corrupted
```

5:

```
UpdateTip: new best=d4a92099298a058150228669c5e8360302004e288b0c6cd60f371aad4bb06acb  height=700121  log2_work=64.369288  tx=18769453  date=2015-05-09 19:08:20 progress=0.568560  cache=52.8MiB(28477tx)
LevelDB read failure: Corruption: block checksum mismatch
Corruption: block checksum mismatch
Error reading from database: Database corrupted
GUI: "registerShutdownBlockReason: Successfully registered: Dogecoin Core didn't yet exit safely..." 
```

**Comment by Sporklin** [comment]
Try starting Dogecoin core with `-par=1 -reindex` this might fix it.

**Comment by langerhans** [comment]
Also, you might want to check your hard drive and memory for any errors. This looks like some corruption of the block data happens on either one of those. Above tip might help though.

**Comment by DavidBurela** [comment]
I tried putting the data directory on 2 different hard drives, but it didn't make a difference. I tried clearing out my data directory, starting over and launching it each time with  `-par=1 -reindex` it would progress a bit further each time but was ultimately unsuccessful.

I then installed it on another machine (also Win10 x64) and it synced fine. I copied the data directory over to the first computer, started it with `-par=1 -reindex` so that it would rebuild from good data. But that eventually also broke while rebuilding

    LoadExternalBlockFile: Processing out of order child 23f3f388b9023369c0b55af262ac78ee040ee51a2b4df7806984eab9a8acdb6b of 862308311c7042f97859fe62840b816c5ff3c8a4172689ab6c74fe77a4e00536
    LevelDB read failure: Corruption: block checksum mismatch
    Corruption: block checksum mismatch

I've given up on getting it to work on this computer, but happy to help run any diagnostics that may help resolve this to harden DogeCoin

**Comment by rnicoll** [comment]
I'm wondering if this is bitcoin/bitcoin#6528

**Comment by patricklodder** [comment]
There's supposedly a fix for this in upstream, I will backport it.

**Comment by patricklodder** [comment]
@DavidBurela could you test if this problem still exists using the binary I linked in #1328?

**Comment by DavidBurela** [comment]
I tried it twice with a cleared out cache folder, but bootstrapping with bootstrap.dat.
No luck, it would still error out.

I'll try it again without the bootstrap file and just getting it from peers.

**Comment by ReverseControl** [comment]
@DavidBurela Is this still an issue in the latest version of dogecoin core?

**Comment by DavidBurela** [comment]
I haven't used it in years. No one else had reported the same issue, I'll just close it. Thanks for the help
