### ISSUE TITLE
emdedded libbitcoinconsensus

### ISSUE THREAD

**Issue by lexical** [dogecoin/dogecoin#1325]
Debian BTS bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=813973
and https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=813974

It looks like that dogecoin contains its own libbitcoinconsensus. 
Ask here for more advanced suggestions, if there is any special tweaks so that dogecoin needs its own version of libbitcoinconsensus. if not, is it safe to remove the embedded one and just to use the one in the distros, e.g. in Debian.

**Comment by patricklodder** [comment]
I think this is a naming error on our end, as we have more (at least scrypt) and potentially different things in this lib, we need to name ours libdogecoinconsensus, imho.

@langerhans : any thoughts?

**Comment by langerhans** [comment]
No issue with me, it should just be a rename in the Makefile. 
We did include scrypt.cpp in it, so no way we could just use the bitcoin one, also give that we can't make sure their changes would always be compatible.

**Comment by langerhans** [comment]
Fixed by #1327 so will arrive with 1.10.1.
