### ISSUE TITLE
HI:  I compiled using mingw dogecoin QT client, connection error, can you help me?

### ISSUE THREAD

**Issue by kevinfuwenke** [dogecoin/dogecoin#1349]
HI:
 I compiled using mingw dogecoin QT client, connection error, can you help me?
What reason be?

CXXLD  dogecoind.exe
dogecoind-bitcoind.o: In function `ZN5boost4asio3ssl6detail17openssl_init_base7
do_initC1Ev':
f:/deps/boost_1_60_0/boost/asio/ssl/detail/impl/openssl_init.ipp:39: undefined r
eference to`SSL_library_init'
f:/deps/boost_1_60_0/boost/asio/ssl/detail/impl/openssl_init.ipp:40: undefined r
eference to `SSL_load_error_strings'
dogecoind-bitcoind.o: In function`do_init':
f:/deps/boost_1_60_0/boost/asio/ssl/detail/impl/openssl_init.ipp:39: undefined r
eference to `SSL_library_init'
f:/deps/boost_1_60_0/boost/asio/ssl/detail/impl/openssl_init.ipp:40: undefined r
eference to`SSL_load_error_strings'
libbitcoin_server.a(libbitcoin_server_a-rpcserver.o): In function `engine':
f:/deps/boost_1_60_0/boost/asio/ssl/detail/impl/engine.ipp:38: undefined referen
ce to`SSL_new'
f:/deps/boost_1_60_0/boost/asio/ssl/detail/impl/engine.ipp:50: undefined referen
ce to `SSL_ctrl'
f:/deps/boost_1_60_0/boost/asio/ssl/detail/impl/engine.ipp:51: undefined referen
ce to`SSL_ctrl'
f:/deps/boost_1_60_0/boost/asio/ssl/detail/impl/engine.ipp:53: undefined referen
ce to `SSL_ctrl'
f:/deps/boost_1_60_0/boost/asio/ssl/detail/impl/engine.ipp:58: undefined referen
ce to`SSL_set_bio'
libbitcoin_server.a(libbitcoin_server_a-rpcserver.o): In function `context':
f:/deps/boost_1_60_0/boost/asio/ssl/impl/context.ipp:120: undefined reference to
`SSLv23_method'
f:/deps/boost_1_60_0/boost/asio/ssl/impl/context.ipp:120: undefined reference to
 `SSL_CTX_new'
libbitcoin_server.a(libbitcoin_server_a-rpcserver.o): In function`ZN5boost4asio
3ssl7context11set_optionsElRNS_6system10error_codeE':
f:/deps/boost_1_60_0/boost/asio/ssl/impl/context.ipp:295: undefined reference to
 `SSL_CTX_ctrl'
f:/deps/boost_1_60_0/boost/asio/ssl/impl/context.ipp:295: undefined reference to
`SSL_CTX_ctrl'
libbitcoin_server.a(libbitcoin_server_a-rpcserver.o): In function `ZN5boost4asio
3ssl7context20use_private_key_fileERKSsNS1_12context_base11file_formatERNS_6syst
em10error_codeE':
f:/deps/boost_1_60_0/boost/asio/ssl/impl/context.ipp:764: undefined reference to
`SSL_CTX_use_PrivateKey_file'
libbitcoin_server.a(libbitcoin_server_a-rpcserver.o): In function `Z15StartRPCTh
readsv':
f:\dogecoin\src/rpcserver.cpp:654: undefined reference to`SSL_CTX_set_cipher_l
ist'
libbitcoin_server.a(libbitcoin_server_a-rpcserver.o): In function `ZN5boost4asio
3ssl6detail6engine9do_acceptEPvj':
f:/deps/boost_1_60_0/boost/asio/ssl/detail/impl/engine.ipp:292: undefined refere
nce to`SSL_accept'
libbitcoin_server.a(libbitcoin_server_a-rpcserver.o): In function `ZN5boost4asio
3ssl6detail6engine10do_connectEPvj':
f:/deps/boost_1_60_0/boost/asio/ssl/detail/impl/engine.ipp:297: undefined refere
nce to`SSL_connect'
libbitcoin_server.a(libbitcoin_server_a-rpcserver.o): In function `ZN5boost4asio
3ssl6detail6engine8do_writeEPvj':
f:/deps/boost_1_60_0/boost/asio/ssl/detail/impl/engine.ipp:317: undefined refere
nce to`SSL_write'
libbitcoin_server.a(libbitcoin_server_a-rpcserver.o): In function `ZN5boost4asio
3ssl6detail6engine7do_readEPvj':
f:/deps/boost_1_60_0/boost/asio/ssl/detail/impl/engine.ipp:311: undefined refere
nce to`SSL_read'
libbitcoin_server.a(libbitcoin_server_a-rpcserver.o): In function `ZN5boost4asio
3ssl7contextD1Ev':
f:/deps/boost_1_60_0/boost/asio/ssl/impl/context.ipp:217: undefined reference to
`SSL_CTX_get_ex_data'
f:/deps/boost_1_60_0/boost/asio/ssl/impl/context.ipp:221: undefined reference to
 `SSL_CTX_get_ex_data'
f:/deps/boost_1_60_0/boost/asio/ssl/impl/context.ipp:223: undefined reference to
`SSL_CTX_set_ex_data'
f:/deps/boost_1_60_0/boost/asio/ssl/impl/context.ipp:226: undefined reference to
 `SSL_CTX_free'
libbitcoin_server.a(libbitcoin_server_a-rpcserver.o): In function`ZN5boost4asio
3ssl6detail6engineD1Ev':
f:/deps/boost_1_60_0/boost/asio/ssl/detail/impl/engine.ipp:63: undefined referen
ce to `SSL_get_ex_data'
f:/deps/boost_1_60_0/boost/asio/ssl/detail/impl/engine.ipp:65: undefined referen
ce to`SSL_get_ex_data'
f:/deps/boost_1_60_0/boost/asio/ssl/detail/impl/engine.ipp:66: undefined referen
ce to `SSL_set_ex_data'
f:/deps/boost_1_60_0/boost/asio/ssl/detail/impl/engine.ipp:70: undefined referen
ce to`SSL_free'
libbitcoin_server.a(libbitcoin_server_a-rpcserver.o): In function `ZNK5boost4asi
o3ssl6detail6engine14map_error_codeERNS_6system10error_codeE':
f:/deps/boost_1_60_0/boost/asio/ssl/detail/impl/engine.ipp:218: undefined refere
nce to`SSL_get_shutdown'
libbitcoin_server.a(libbitcoin_server_a-rpcserver.o): In function `ZN5boost4asio
3ssl7context26use_certificate_chain_fileERKSsRNS_6system10error_codeE':
f:/deps/boost_1_60_0/boost/asio/ssl/impl/context.ipp:620: undefined reference to
`SSL_CTX_use_certificate_chain_file'
libbitcoin_server.a(libbitcoin_server_a-rpcserver.o): In function `~engine':
f:/deps/boost_1_60_0/boost/asio/ssl/detail/impl/engine.ipp:63: undefined referen
ce to`SSL_get_ex_data'
f:/deps/boost_1_60_0/boost/asio/ssl/detail/impl/engine.ipp:65: undefined referen
ce to `SSL_get_ex_data'
f:/deps/boost_1_60_0/boost/asio/ssl/detail/impl/engine.ipp:66: undefined referen
ce to`SSL_set_ex_data'
f:/deps/boost_1_60_0/boost/asio/ssl/detail/impl/engine.ipp:70: undefined referen
ce to `SSL_free'
f:/deps/boost_1_60_0/boost/asio/ssl/detail/impl/engine.ipp:63: undefined referen
ce to`SSL_get_ex_data'
f:/deps/boost_1_60_0/boost/asio/ssl/detail/impl/engine.ipp:65: undefined referen
ce to `SSL_get_ex_data'
f:/deps/boost_1_60_0/boost/asio/ssl/detail/impl/engine.ipp:66: undefined referen
ce to`SSL_set_ex_data'
f:/deps/boost_1_60_0/boost/asio/ssl/detail/impl/engine.ipp:70: undefined referen
ce to `SSL_free'
f:/deps/boost_1_60_0/boost/asio/ssl/detail/impl/engine.ipp:63: undefined referen
ce to`SSL_get_ex_data'
f:/deps/boost_1_60_0/boost/asio/ssl/detail/impl/engine.ipp:65: undefined referen
ce to `SSL_get_ex_data'
f:/deps/boost_1_60_0/boost/asio/ssl/detail/impl/engine.ipp:66: undefined referen
ce to`SSL_set_ex_data'
f:/deps/boost_1_60_0/boost/asio/ssl/detail/impl/engine.ipp:70: undefined referen
ce to `SSL_free'
libbitcoin_server.a(libbitcoin_server_a-rpcserver.o): In function`ZN5boost4asio
3ssl6detail6engine7performEMS3_FiPvjES4_jRNS_6system10error_codeEPj':
f:/deps/boost_1_60_0/boost/asio/ssl/detail/impl/engine.ipp:241: undefined refere
nce to `SSL_get_error'
f:/deps/boost_1_60_0/boost/asio/ssl/detail/impl/engine.ipp:277: undefined refere
nce to`SSL_get_shutdown'
libbitcoin_server.a(libbitcoin_server_a-rpcserver.o): In function `ZN5boost4asio
3ssl6detail6engine8do_writeEPvj':
f:/deps/boost_1_60_0/boost/asio/ssl/detail/impl/engine.ipp:317: undefined refere
nce to`SSL_write'
libbitcoin_server.a(libbitcoin_server_a-rpcserver.o): In function `ZN5boost4asio
3ssl6detail6engine7performEMS3_FiPvjES4_jRNS_6system10error_codeEPj':
f:/deps/boost_1_60_0/boost/asio/ssl/detail/impl/engine.ipp:241: undefined refere
nce to`SSL_get_error'
f:/deps/boost_1_60_0/boost/asio/ssl/detail/impl/engine.ipp:277: undefined refere
nce to `SSL_get_shutdown'
libbitcoin_server.a(libbitcoin_server_a-rpcserver.o): In function`ZN5boost4asio
3ssl6detail6engine7do_readEPvj':
f:/deps/boost_1_60_0/boost/asio/ssl/detail/impl/engine.ipp:311: undefined refere
nce to `SSL_read'
libbitcoin_server.a(libbitcoin_server_a-rpcserver.o): In function`ZN5boost4asio
3ssl6detail6engine7performEMS3_FiPvjES4_jRNS_6system10error_codeEPj':
f:/deps/boost_1_60_0/boost/asio/ssl/detail/impl/engine.ipp:241: undefined refere
nce to `SSL_get_error'
f:/deps/boost_1_60_0/boost/asio/ssl/detail/impl/engine.ipp:277: undefined refere
nce to`SSL_get_shutdown'
collect2.exe: error: ld returned 1 exit status
Makefile:2479: recipe for target 'dogecoind.exe' failed
mingw32-make[2]: **\* [dogecoind.exe] Error 1

**Comment by patricklodder** [comment]
Looks like you didn't link correctly against openssl, please use the depends system to compile with mingw, as it will make sure you are linking against the correct version of openssl. See also https://github.com/dogecoin/dogecoin/blob/master/depends/README.md

For example:
```
make clean # make sure you have a clean working dir
pushd depends
make HOST=x86_64-w64-mingw32 # this compiles all dependencies
popd
./autogen.sh
./configure --prefix=`pwd`/depends/x86_64-w64-mingw32 # this configures dogecoind to compile against all w64 dependencies
make
```
