### ISSUE TITLE
Windows 1.10 Dogecoin wallet

### ISSUE THREAD

**Issue by peterelia** [dogecoin/dogecoin#1350]
I have downloaded 1.10 version and begin to sync (which is very slow finish only 5 weeks in 10 hours and 2 years and 20 weeks remaining ) 
but I transfer coin to the wallet before sync but the coins didn't appear in the wallet , is there any solution

**Comment by langerhans** [comment]
Please let it finish syncing for the transaction to confirm locally. Then you'll be able to use the coins.
