### ISSUE TITLE
Segfualt on Arch Linux with Berkely Database 5.1

### ISSUE THREAD

**Issue by ShapeShifter499** [dogecoin/dogecoin#1355]
Hi,

I need some help grabbing some logs but when I compile from GIT the client segfaults on my system.

```
[raansu@Y40-80 dogecoin-git]$ dogecoin-qt 
Segmentation fault (core dumped)
[raansu@Y40-80 dogecoin-git]$ dogecoind
Error: To use dogecoind, or the -server option to dogecoin-qt, you must set an rpcpassword in the configuration file:
/home/raansu/.dogecoin/dogecoin.conf
It is recommended you use the following random password:
rpcuser=dogecoinrpc
rpcpassword=EyKDboCUjxsRgodsjAYz8KqDP16gWbftHyGjUXPZFSKD
(you do not need to remember this password)
The username and password MUST NOT be the same.
If the file does not exist, create it with owner-readable-only file permissions.
It is also recommended to set alertnotify so you are notified of problems;
for example: alertnotify=echo %s | mail -s "Dogecoin Alert" admin@foo.com

Segmentation fault (core dumped)
[raansu@Y40-80 dogecoin-git]$ 
```

dmesg

```
[ 8055.775476] QThread[20696]: segfault at 0 ip 00007ff6573eb446 sp 00007ff63a19f108 error 4 in libc-2.24.so[7ff65736b000+195000]
[ 8064.570471] QThread[20713]: segfault at 0 ip 00007f5c56d6f446 sp 00007f5c35c92108 error 4 in libc-2.24.so[7f5c56cef000+195000]
[ 8068.806874] dogecoind[20725]: segfault at 0 ip 00007f947befc446 sp 00007ffc342ca908 error 4 in libc-2.24.so[7f947be7c000+195000]
[ 8202.617467] QThread[20808]: segfault at 0 ip 00007f19a9ae0446 sp 00007f19908e8108 error 4 in libc-2.24.so[7f19a9a60000+195000]
[ 8205.452045] dogecoind[20828]: segfault at 0 ip 00007f55730f5446 sp 00007ffc8f971d28 error 4 in libc-2.24.so[7f5573075000+195000]
```

**Comment by ShapeShifter499** [comment]
I reverted the Dogecoin code to accept Berkeley Database 4.8 again and I no longer see any segfaults. Since Litecoin and Bitcoin appear to still be on Berkeley Database 4.8 I'd suggest switching back to that.

**Comment by Thermi** [comment]
I'd very much appreciate it to revert to that version in master, too. @ShapeShifter499 What commits or code did you patch?

**Comment by langerhans** [comment]
Hold on please. You can not revert back to 4.8 once you ran on 5.1. The database formats are not compatible! You can use 4.8 indeed as long as it's with new wallets or you convert your wallet format back.

**Comment by Thermi** [comment]
Well, I need dogecoin to run on Arch with the berkeley db version that it ships with. If it doesn't we need to use the right version that we can use there.

**Comment by langerhans** [comment]
We officially ship with BDB 5.1. So for full compatibility of wallet files between systems you'd need to use this version. As said, you can use 4.8 just fine but lose compatibility to 5.1 wallets.  
As for why this segfault happens I have no clue from the logs I see up here. Looking at where the crash actually happens though makes it look like an upstream issue. I can try to reproduce it on my Arch box, but the nature of the system will probably show different behavior on my machine ;)

**Comment by ReverseControl** [comment]
@patricklodder @rnicoll @michilumin We can close this one.

**Comment by ReverseControl** [comment]
See #2483,  update to Berkely Database 5.3 for Dogecoin Core 1.14.5. I am closing this issue on the grounds of being outdated, dated 2016.  Should there be a reason to address this again we can open it again.
