### ISSUE TITLE
Beerwallet not registering Doge balance.

### ISSUE THREAD

**Issue by Sumisu77** [dogecoin/dogecoin#1365]
I recently made an exchange through blocktrades which went through, and which I even verified on the Dogechain. Beerwallet still shows my balance as zero, however. Anyone else experiencing this?

**Comment by langerhans** [comment]
This is the repository for Dogecoin Core. We are not affiliated with the Beerwallet developers. Please direct your question to them :)

**Comment by Sumisu77** [comment]
I was told by the developer to post in Github. Sorry if this is the wrong place.

**Comment by langerhans** [comment]
This seems to be the source: https://github.com/mperklin/beerwallet
But are you sure this is actually a Dogecoin wallet and not a mis-branded Defcoin wallet for whatever reason? This seems fishy but would explain why you didn't receive your coins.
