### ISSUE TITLE
segwit or LN?

### ISSUE THREAD

**Issue by briannyeko** [dogecoin/dogecoin#1367]
Will dogecoin core implement Segwit or Lightning-network?

**Comment by rnicoll** [comment]
At a 30 second analysis off the top of my head, I believe Segwit would cause us a lot of version number headaches due to interaction with AuxPoW, so it's not intended for 1.14 anyway. May re-examine once we see actual use-cases, but given we have 10x the throughput of Bitcoin, no immediate hurry.

**Comment by buddilla** [comment]
You will need them both if want to do side chain atomic swaps :)

**Comment by briannyeko** [comment]
^ this, and atomic swaps is a great feature + if dogecoin has lightning
network => MOON!

**Comment by bhb192** [comment]
I really would like to see segwit become part of Dogecoin's long term plan exactly for the benefit of atomic swaps. Not something we need to rush into, but will be necessary to stay on the same playing field as other similar coins continue to activate segwit.

**Comment by langerhans** [comment]
#1382
