### ISSUE TITLE
Can't Link LibBoost from Ubuntu Libboost1.58.0 packages

### ISSUE THREAD

**Issue by JRWR** [dogecoin/dogecoin#1368]
Installed Packages: http://paste.ubuntu.com/24596568/
Output from Config: http://paste.ubuntu.com/24596576/

```
checking whether to build Dogecoin Core GUI... no (Qt4)
checking for boostlib >= 1.20.0... yes
checking whether the Boost::System library is available... yes
checking for exit in -lboost_system... no
configure: error: Could not link against boost_system !
```

Updating the Unix Compile Docs is also requested, its very out of date for ubuntu 16.04

**Comment by langerhans** [comment]
Try installing `libboost-chrono1.58-dev`, at least that one seems missing in your list compared to the listing in #530.
