### ISSUE TITLE
contrib/linearize broken, Unable to read blockchain

### ISSUE THREAD

**Issue by JRWR** [dogecoin/dogecoin#1373]
> [cottus ~/dogecoin-bin/src/dogecoin/contrib/linearize] ./linearize-data.py example-linearize.cfg
> Read 1731901 hashes
> Input file ~/.dogecoin/blocks/blk00000.dat
> Premature end of block data
> 

Python 2.7.9

**Comment by rnicoll** [comment]
Sorry, the configuration that shipped in 1.10 is damaged. 1.14 should be fixed (I say, hoping I actually committed the fixed version).

**Comment by patricklodder** [comment]
Fixed with #1525
