### ISSUE TITLE
Make command not working on MAC OSx

### ISSUE THREAD

**Issue by AteqEjaz** [dogecoin/dogecoin#1376]
Hi,

I'm facing following issue while running 'make' command inside my dogecoin repo. Any help? thanks

AteqEjaz$ make
Making all in src
  CXX      wallet/libbitcoin_wallet_a-db.o
**wallet/db.cpp:46:9: error: ambiguous conversion for functional-style cast from
      'int' to 'DbEnv'
        DbEnv(0).remove(strPath.c_str(), 0);**
        ^~~~~~~
/usr/local/opt/berkeley-db/include/db_cxx.h:516:2: note: candidate constructor
        DbEnv(u_int32_t flags);
        ^
/usr/local/opt/berkeley-db/include/db_cxx.h:518:2: note: candidate constructor
        DbEnv(DB_ENV *dbenv);
        ^
/usr/local/opt/berkeley-db/include/db_cxx.h:916:2: note: candidate constructor
        DbEnv(const DbEnv &);
        ^
1 error generated.
make[2]: *** [wallet/libbitcoin_wallet_a-db.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1

**Comment by DomT4** [comment]
As far as I recall, this project is compatible with BDB 5.x, whereas the `berkeley-db` shipped by Homebrew is currently 6.2.23. There's likely an incompatibility there.

**Comment by AteqEjaz** [comment]
I found this bug, any thoughts? boost::filesystem::create_directory: Permission denied: \"/.dogecoin\"

**Comment by globaltoken** [comment]
Are you compiling as root ?

**Comment by Gargo** [comment]
@globaltoken ok I have the same problem with another repo - motocoin. I use QT Creator. How to run as root if it is UI (non-console) application?

**Comment by globaltoken** [comment]
@Gargo Compile it on Linux with GCC Compiler.
For example read it here: https://github.com/dogecoin/dogecoin/blob/master/doc/build-unix.md
