### ISSUE TITLE
No Block Source Available

### ISSUE THREAD

**Issue by iTFGamer** [dogecoin/dogecoin#1383]
Version: v1.10.0.0-bb4b082 (64-bit)
Current Numbers of Blocks: 195043

Need help. addnode doesn't work.

**Comment by langerhans** [comment]
Check your debug.log for any peering issues. DNS seed works fine so you shouldn't have an issue there apart when you have a firewall issue on your side.

**Comment by iTFGamer** [comment]
Here are a couple of issues:

ERROR: AcceptToMemoryPool: non-final
P2P peers available. Skipped DNS seeding (idk if this is an error)

**Comment by langerhans** [comment]
Latter pretty much says you actually have peers. Odd. You can try deleting peers.dat so the wallet can grab some fresh peers from the DNS seeds.

**Comment by iTFGamer** [comment]
That didn't work.

Should I try uninstalling it and reinstalling it?

**Comment by langerhans** [comment]
If that didn't work your network might have an issue. Attach a clean debug.log please. Don't think uninstalling will change anything.

**Comment by iTFGamer** [comment]
[debug.log.zip](https://github.com/dogecoin/dogecoin/files/1290946/debug.log.zip)

the log is in this zip.

**Comment by langerhans** [comment]
Weird. It seems like it synced just fine but then stopped for no reason at all. You actually do get connections to peers just fine according to the log but then receive no blocks. What you can try now is removing your blockchain data and then trying to use the bootstrap file hosted here: https://bootstrap.chain.so (instructions are there too).

**Comment by iTFGamer** [comment]
So far it is working, I will let you know if it works perfectly.

**Comment by iTFGamer** [comment]
This solution is working perfectly. Thanks for helping me!

**Comment by langerhans** [comment]
Glad to hear, closing here then 👍
