### ISSUE TITLE
Dogecoin 'Stache

### ISSUE THREAD

**Issue by adamhackbarth** [dogecoin/dogecoin#1384]
Saddened there wasn't a parody of the Bitcoin Cash fork for Dogecoin. I would love to see **Dogecoin 'Stache** with the mascot being a shibe with a handlebar mustache.

Also, the blocks would be made smaller instead of larger. No idea why this is funny to me. But I laughed to a point where I stopped laughing and started taking the idea seriously.

Just sayin'.

**Comment by hswick** [comment]
Nothing stopping you from forking this repo and making it a reality.

**Comment by langerhans** [comment]
Correct ;) Closing here as not relevant to our efforts at the moment.
