### ISSUE TITLE
Push Transaction Script

### ISSUE THREAD

**Issue by nyancodeid** [dogecoin/dogecoin#1387]
in API documentation already have push Transaction,
https://dogechain.info/api/blockchain_api

how can i make Transaction hash with javascript code like dogechain wallet?

**Comment by hswick** [comment]
You are referencing dogechain which is a different codebase than dogecoin.

You would need to create a transaction using something like a dogecoin node

**Comment by nyancodeid** [comment]
in dogechain they make their own Transactions raw with javascript, I see in Chrome Developer Console. They do not execute requests to any server when making raw transactions, after they make their transaction raw (hashed) and push them into their API.

This is a API for push some Hashed Raw Transaction to get Transaction ID from Dogecoin network
https://dogechain.info/api/v1/pushtx

I've tried to understand its code, but it's too complicated because they use uglify in their javascript.

**Comment by hswick** [comment]
Oh weird. Wouldn't it just be the raw transaction in binary (hex format)? Not sure how/what they convert though

**Comment by hswick** [comment]
Maybe they use something like this http://cryptocoinjs.com/modules/crypto/scryptsy/ to make a valid transaction

**Comment by rnicoll** [comment]
Sorry just saw this; thanks for addressing @hswick . Personally I don't work with Javascript much, I'd generally have suggested using the dogecoind JSON-RPC interface `sendtoaddress` command to generate a transaction rather than trying to do it manually. If you do want to build a TX manually I'm sure there are frameworks out there, but they're not something I've worked with.

**Comment by nyancodeid** [comment]
Thanks @rnicoll and @hswick 
They using this library `https://live-sochain-blockioinc.netdna-ssl.com/js/dogecoin.min.js`

that is a minimized version, that means the script is unreadable to minimize file size. if you know where is Github repository please tell me Thanks

**Comment by patricklodder** [comment]
That code is not open source so you shouldn’t use that.

Instead you could for example have a look around https://github.com/BlockIo/blockiojs for a JavaScript implementation that does all the same things, including the optimizations I wrote for the dogechain lib.

**Comment by nyancodeid** [comment]
Now i can sleep well, Dogechain using this library

https://bitcoinjs.org
