### ISSUE TITLE
complie error on linux

### ISSUE THREAD

**Issue by robrob80** [dogecoin/dogecoin#139]
i am using the following..
make -f makefile.unix USE_UPNP=1 USE_QRCODE=1 USE_IPV6=1

main.cpp:17:53: fatal error: boost/random/uniform_int_distribution.hpp: No such file or directory
compilation terminated.
make: **\* [obj/main.o] Error 1

**Comment by saddam1997** [comment]
checkpoints.cpp:56:5: warning: missing initializer for member ‘Checkpoints::CCheckpointData::fTransactionsPerDay’ [-Wmissing-field-initializers]
checkpoints.cpp: In function ‘int Checkpoints::GetTotalBlocksEstimate()’:
checkpoints.cpp:115:31: warning: unused variable ‘checkpoints’ [-Wunused-variable]
         const MapCheckpoints& checkpoints = *Checkpoints().mapCheckpoints;
                               ^
makefile.unix:190: recipe for target 'obj/checkpoints.o' failed
make: *** [obj/checkpoints.o] Error 1

**Comment by kavipal766** [comment]
heckpoints.cpp:56:5: warning: missing initializer for member ‘Checkpoints::CCheckpointData::fTransactionsPerDay’ [-Wmissing-field-initializers]
checkpoints.cpp: In function ‘int Checkpoints::GetTotalBlocksEstimate()’:
checkpoints.cpp:115:31: warning: unused variable ‘checkpoints’ [-Wunused-variable]
const MapCheckpoints& checkpoints = *Checkpoints().mapCheckpoints;
^
makefile.unix:190: recipe for target 'obj/checkpoints.o' failed
make: *** [obj/checkpoints.o] Error 1
