### ISSUE TITLE
MultiDoge is not opening

### ISSUE THREAD

**Issue by ghost** [dogecoin/dogecoin#1390]
Hi there, Can anyone help me with the following matter. When starting the MultiDoge 0.1.7, i hear and see (attachement) the program does something on the background but it is not opening the wallet.... Is there something to do about this?
![doge](https://user-images.githubusercontent.com/33354698/32384986-ee0e66fe-c0bc-11e7-9d6f-4009db74956b.JPG)

**Comment by kamisori** [comment]
You could backup your wallet.dat file and reinstall your multidoge client, perhaps that fixes it.
It is possible though, that it just needs more time to start.
Anyways, you should rather ask your question in [the multidoge repo](https://github.com/langerhans/multidoge) or on [reddit](https://www.reddit.com/r/dogeducation/)

**Comment by langerhans** [comment]
Wrong repo. There is a post on Reddit about how to fix it ;)
