### ISSUE TITLE
listtransactions/listsinceblock returning odd errors

### ISSUE THREAD

**Issue by Crypto2** [dogecoin/dogecoin#1393]
Not sure what is going on but with these two API calls I keep getting a return error of:

tinyformat: Not enough conversion specifiers in format string
or sometimes:
CTransaction::GetValueOut(): value out of range (this looks to be from src/primitives/transaction.cpp ?)

After these when I restart the dogecoind it will recover all the keys from the wallet saying the transactions are corrupt and do a rescan.

**Comment by Crypto2** [comment]
Any update on this? It just happened again today. It looks like it may be a TX the wallet itself is generating that is causing it:

2017-12-01 20:22:56 CommitTransaction:
CTransaction(hash=2a02c749c5, ver=1, vin.size=2, vout.size=2, nLockTime=1992967)
    CTxIn(COutPoint(f04217db68, 1), scriptSig=3045022100c99117f8cc9078, nSequence=4294967294)
    CTxIn(COutPoint(a2d8c0b715, 43), scriptSig=3045022100a4b6b2e4e53e9d, nSequence=4294967294)
    CTxOut(nValue=0.16392274, scriptPubKey=OP_DUP OP_HASH160 f2e507ea255d)
    CTxOut(nValue=0.-11864407, scriptPubKey=OP_DUP OP_HASH160 c1d95d42f0d1)
2017-12-01 20:22:56 keypool keep 578176
2017-12-01 20:22:56 AddToWallet 2a02c749c548d7dddfba997e3303c9259280b2e408e0b8ad23549e3d943d7008  new
2017-12-01 20:22:56 ERROR: CheckTransaction(): txout.nValue negative
2017-12-01 20:22:56 ERROR: AcceptToMemoryPool: CheckTransaction failed
2017-12-01 20:22:56 CommitTransaction(): Error: Transaction not valid

And from then on when the API is called we get the error replies. I added this debug output to the GetValueOut() function which is printing matching info to that TX when the API is called:

2017-12-01 22:31:13 CTransaction::GetValueOut(): value out of range
2017-12-01 22:31:13 CTransaction(hash=2a02c749c5, ver=1, vin.size=2, vout.size=2, nLockTime=1992967)
    CTxIn(COutPoint(f04217db68, 1), scriptSig=3045022100c99117f8cc9078, nSequence=4294967294)
    CTxIn(COutPoint(a2d8c0b715, 43), scriptSig=3045022100a4b6b2e4e53e9d, nSequence=4294967294)
    CTxOut(nValue=0.16392274, scriptPubKey=OP_DUP OP_HASH160 f2e507ea255d)
    CTxOut(nValue=0.-11864407, scriptPubKey=OP_DUP OP_HASH160 c1d95d42f0d1)

Then after killing dogecoind with SIGINT and restarting you get:

"Warning: error reading wallet.dat! All keys read correctly, but transaction data or address book entries might be missing or incorrect." And it rescans the blockchain.

**Comment by langerhans** [comment]
I can't say I've ever seen this beofre 🤔 
I would say wait and see if 1.14 fixes that (once we actually get this out as a release which might take a while). You could try starting with a clean wallet maybe if that's feasible.

**Comment by Crypto2** [comment]
In wallet.cpp do you think adding a CheckTransaction() near the top would have any adverse affects? Right now it adds to the wallet unconditionally it seems, adding this would find the problem first and reject it. I just don't know if a TX is supposed to be in the mempool before calling CheckTransaction or if there would be any adverse affects?

ie. something like this:

bool CWallet::CommitTransaction(CWalletTx& wtxNew, CReserveKey& reservekey)
{
    {
        LOCK2(cs_main, cs_wallet);
        LogPrintf("CommitTransaction:\n%s", wtxNew.ToString());

        CValidationState state;
        if (!CheckTransaction(wtxNew, state))
            return false;

**Comment by langerhans** [comment]
Without going through all the cases I don't see an issue with this, You're probably right that this is a tx created by the wallet itself, so rejecting it asap is probably fine.

**Comment by ReverseControl** [comment]
@Crypto2 Did 1.14.3 fix your issue?

**Comment by Crypto2** [comment]
I think so, I haven't seen it happen in a long time.

**Comment by ReverseControl** [comment]
@patricklodder @rnicoll @michilumin Close this one.
