### ISSUE TITLE
0.14 rebase

### ISSUE THREAD

**Issue by runn1ng** [dogecoin/dogecoin#1394]
Hello, what is the state of the various branches?

How production-ready is 0.14 rebase?

**Comment by langerhans** [comment]
Not at all stable for production as it currently does not sync past about 360k blocks. `-dev` branches are generally not considered production ready ;)

**Comment by runn1ng** [comment]
Thanks! So the -branding have the same problems, right?

Is there a working branch based on anything newer than 0.11?

**Comment by langerhans** [comment]
No, not at this time.

**Comment by runn1ng** [comment]
Thanks for the reply.
