### ISSUE TITLE
DogeCoin是否能改成pos出块？

### ISSUE THREAD

**Issue by UncleBitcoin** [dogecoin/dogecoin#1395]
我在想，目前旷工对dogecoin的帮助已经不是很大，是否将dogecoin改成pos算法来增加市场热度？或者是一个分叉，类似比特币现金？

**Comment by kamisori** [comment]
Sorry I dont speak chinese, but If you understand some english, perhaps [dogeducation](https://www.reddit.com/r/dogeducation/) is a better place to ask your question as it seems to be a general question about what dogecoin actually is in comparison to bitcoin.

**Comment by cxf739** [comment]
现在是怎么挖狗狗币？

**Comment by cxf739** [comment]
找了几个矿池都打不开网站了。。
