### ISSUE TITLE
Crash when using strace

### ISSUE THREAD

**Issue by h4ck3rm1k3** [dogecoin/dogecoin#1398]
On debian linux sid 
`Linux mdupont-Aspire-7750G 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u5 (2017-09-19) x86_64 GNU/Linux`

Running the gui  
`dogecoin-1.10.0$ ./bin/dogecoin-qt`

![Starting image](https://res.cloudinary.com/hpiynhbhq/image/upload/v1513256154/asgb345j3fh0zcksgqgl.png)

I downloaded the boostrap.dat using [bootstrap.chain.so](https://bootstrap.chain.so/)
and started to load it,

![image](https://res.cloudinary.com/hpiynhbhq/image/upload/v1513256208/ylyunhjlpck0zg7td5bf.png)

I want to determine if it is loading the boostrap.dat.
```
mdupont@mdupont-Aspire-7750G:/tmp$ ps xauf | grep doge
mdupont  28798 42.2 23.2 3759416 1869132 pts/5 Sl+  07:54   1:14          |   |   |   \_ ./bin/dogecoin-qt
```
`lsof -p  28798` shows
```
dogecoin- 28798 mdupont   29r      REG               8,17 2964733952       3889 /media/mdupont/disk/doge/bootstrap.dat
```

Now running strace to figure out where the time is going 
```
mdupont@mdupont-Aspire-7750G:/tmp$ strace -f -c -p 28798
strace: Process 28798 attached with 22 threads
```

![image](https://res.cloudinary.com/hpiynhbhq/image/upload/v1513256335/yhcnx9m2vdm0upxhzt23.png)

Then the process is defunct
```
mdupont  28798 26.1  0.0      0     0 pts/5    Zl+  07:54   1:39          |   |   |   \_ [dogecoin-qt] <defunct>
```

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@h4ck3rm1k3st33m/crash-when-using-strace">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by ReverseControl** [comment]
@patricklodder @rnicoll @michilumin I think we can close this one. Both strace and dogecoin have come a long way. This issue could be opened again if its still relevant. I would suggest closing it at this time.
