### ISSUE TITLE
Dogecoin Core not launching Win10

### ISSUE THREAD

**Issue by dojobel** [dogecoin/dogecoin#1400]
I was able to launch Dogecoin core once after installing, but I foolishly closed it forcibly via Task Manager (it appeared unresponsive) and it hasn't worked since.
The GUI doesn't display, but I can right-click the Tray icon and launch the debug window just fine. Pretty much the same issue as this thread: https://www.reddit.com/r/dogecoin/comments/6hhquo/dogecoin_core_1100_gui_interface_wont_open/

Running the latest release 1.10.0 and the latest Win10 release (1709). Have attached a screenshot of how it appears in the tray as a blank window. 

[debug.log](https://github.com/dogecoin/dogecoin/files/1566446/debug.log)
![image](https://user-images.githubusercontent.com/1475255/34087685-ca16fb08-e3f8-11e7-94ca-b0037e6c84e9.png)

**Comment by langerhans** [comment]
Is that left window maybe just moved out of your screen's bounds? If you right click it and select move can you move it back to the screen?

**Comment by dojobel** [comment]
Tried that but no luck unfortunately. If you look closely at the screenshot there's actually no text or controls in the main form, it's just a blank canvas (whereas debug clearly has tab control, buttons, text, etc).
I have tried to install over the top of this copy, completely uninstall and re-install, and renaming the folder under AppData\Roaming to generate a completely new copy of the data but nothing seems to fix it. I can actually see activity going on, the CPU goes up and down (not a constant high so it's not locked up), and the Debug window shows traffic and peers (screenshots attached)
![image](https://user-images.githubusercontent.com/1475255/34140624-185a8320-e4d0-11e7-9079-d7a81886d3b5.png)
![image](https://user-images.githubusercontent.com/1475255/34140631-245ed572-e4d0-11e7-903f-9c72dfc9a990.png)

**Comment by langerhans** [comment]
Can you check the solution listed in this upstream issue and see if that works? https://github.com/bitcoin/bitcoin/issues/7869

**Comment by dojobel** [comment]
tried both suggested CLI args but still no good I'm afraid

![image](https://user-images.githubusercontent.com/1475255/34182685-615c3208-e56b-11e7-9687-6c5de3104988.png)

**Comment by langerhans** [comment]
I start running out of ideas lol. But in this issue, there is a registry key listed that you can either try to edit or delete altogether to reset the settings: https://github.com/bitcoin/bitcoin/issues/11207

Oh and it appears the cli flag I mentioned wasn't added to Dogecoin yet, sorry about that.

**Comment by dojobel** [comment]
Deleting the registry key fixed it! You're a legend mate, thanks heaps for your help!

**Comment by langerhans** [comment]
Glad it worked out :)
