### ISSUE TITLE
Mobile wallet 1.8 version of a back up wallet into the mobile wallet 3.0 version  failed. 

### ISSUE THREAD

**Issue by CodeCanFly** [dogecoin/dogecoin#1401]
App system back to the desktop

**Comment by rnicoll** [comment]
I think Max has closed this because we can't decipher what you're meaning, but if you've copied a mobile wallet into one of the desktop apps - yeah, they're not compatible storage formats, that won't work.

**Comment by CodeCanFly** [comment]
the 1.8 version  Mobile wallet  can't   back up into the  3.0 version mobile.  the App error and  back to the desktop

**Comment by greenbigfrog** [comment]
@CodeCanFly this repo is about the desktop dogecoin core wallet. And not some mobile wallet

**Comment by rnicoll** [comment]
I think they want https://github.com/langerhans/dogecoin-wallet-new - I'm also guessing 1.8 should be 1.08 - part of why I got quite so confused is we have a desktop release v1.8, but no mobile v1.8!
