### ISSUE TITLE
Backupwallet RPC call destroyed wallet if target equals the source wallet file

### ISSUE THREAD

**Issue by rllola** [dogecoin/dogecoin#1402]
See this issue in bitcoin : https://github.com/bitcoin/bitcoin/issues/11375

Actually happened to me today.

**Comment by langerhans** [comment]
Might be worth pulling into 1.14. Thanks.

**Comment by rnicoll** [comment]
Cheers, will definitely try to get https://github.com/bitcoin/bitcoin/pull/11376 into 1.14

**Comment by rllola** [comment]
I took a look at the function if I understand it correctly it is happening here : 
https://github.com/dogecoin/dogecoin/blob/1.14-dev/src/wallet/wallet.cpp#L3901

I am wondering if it is safe to have the `boost::filesystem::copy_option::overwrite_if_exists` option here and if we should just let it fail if the file already exist ? Or maybe just create a different backup file that would look like this `wallet-timestamp.dat` ?

I also understand that some people might want to overwrite the wallet.dat file to update their backup and just export it so it might not be a good solution for this use case.

**Comment by rllola** [comment]
The PR that avoid this behavior has been merged. So this can be closed.
