### ISSUE TITLE
Move bug?

### ISSUE THREAD

**Issue by Affinity121** [dogecoin/dogecoin#1418]
I used 'Move' JSON-RPC call and it created a lot of new accounts which look like '"��������������\u0080�" : -20058300000.00000000,'. Now I can't do anything with that accounts, because their names contain control symbols. Any ideas? How to delete all these accounts and move all balance to ""?

**Comment by rnicoll** [comment]
If I remember correctly, the `move` command just moves money between accounts in the Dogecoin wallet, it doesn't actually control your ability to spend them. The accounting system from Bitcoin Core is unfortunately rather unstable (although I've never seen anything like this), and generally best avoided. I would suggest doing accounting externally, and use `sendtoaddress` when sending to other parties, which doesn't care which account it takes funds from.

**Comment by thijstriemstra** [comment]
> The accounting system from Bitcoin Core is unfortunately rather unstable

In this blatant **copy** it's unstable, in Bitcoin Core it's being improved and much more stable. Abandonware.

**Comment by langerhans** [comment]
![](https://i.imgur.com/kIVyizS.gif)
