### ISSUE TITLE
recipe for target

### ISSUE THREAD

**Issue by torxie** [dogecoin/dogecoin#1421]
Makefile:3657: recipe for target 'libbitcoin_server_a-alert.o' failed

Is it the memory of machine not enough?
[1G memory]

**Comment by D3m0nKingx** [comment]
If you could show more output from the failed build it would help determine the reason. But 1GB may not be enough, you could add/increase the swap file and retry.

**Comment by torxie** [comment]
make[2]: Entering directory '/home/torxie/dogecoin_version_1/dogecoin-master/src'
  CXX      libbitcoinconsensus_la-eccryptoverify.lo
  CXX      libbitcoinconsensus_la-ecwrapper.lo
  CXX      libbitcoinconsensus_la-hash.lo
  CXX      libbitcoinconsensus_la-pubkey.lo
  CXX      libbitcoinconsensus_la-uint256.lo
  CXX      libbitcoinconsensus_la-utilstrencodings.lo
  CXX      dogecoind-bitcoind.o
  CXX      libbitcoin_server_a-addrman.o
  CXX      libbitcoin_server_a-alert.o
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
Makefile:3643: recipe for target 'libbitcoin_server_a-addrman.o' failed
make[2]: *** [libbitcoin_server_a-addrman.o] Error 4
make[2]: *** Waiting for unfinished jobs....
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
Makefile:5848: recipe for target 'dogecoind-bitcoind.o' failed
make[2]: *** [dogecoind-bitcoind.o] Error 4
make[2]: Leaving directory '/home/torxie/dogecoin_version_1/dogecoin-master/src'
Makefile:6726: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/torxie/dogecoin_version_1/dogecoin-master/src'
Makefile:629: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by rnicoll** [comment]
Yeah `g++: internal compiler error: Killed (program cc1plus)` definitely suggests out of memory, or at least not something wrong with the source code.
