### ISSUE TITLE
#error "You must build your code with position independent code if Qt was built with -reduce-relocations

### ISSUE THREAD

**Issue by torxie** [dogecoin/dogecoin#1422]
1.  Question
/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h:1067:4: error: #error "You must build your code with position independent code if Qt was built with -reduce-relocations. " "Compile your code with -fPIC (-fPIE is not enough)."
 #  error "You must build your code with position independent code if Qt was built with -reduce-relocations. "

2. user -fPIC
./configure --with-gui=qt5 --enable-upnp-default --enable-hardening LDFLAGS="-L/home/torxie/dogecoin_version_1/db5/lib/" CPPFLAGS="-fPIC -I/home/torxie/dogecoin_version_1/db5/include/"

3. Dont work

**Comment by D3m0nKingx** [comment]
https://github.com/dogecoin/dogecoin/pull/1420/files

Make the changes in the code as above, and it will compile.

**Comment by torxie** [comment]
Thank u very much~
