### ISSUE TITLE
wrong portfolio on transfer

### ISSUE THREAD

**Issue by jocelinocrs** [dogecoin/dogecoin#1423]
friend how to rescue the dogecoin I sent 120 thousand doge for wrong wallet until hije do not go back that with which I recover them

**Comment by jocelinocrs** [comment]
Transaction | Block | Approx. Time | Amount | Currency
-- | -- | -- | -- | --
a09c9b9a…3d541b64 | 1938655 | 2017-10-23 07:01:31 -0700 | + 126,608.89989797 | DOGE

my  wallt D9M2rKjNNzpHSmjscRpaSWLPXwMubJ1LbW     wrong wallet D7PcvDY3Twh91iuXFp8yKKTqFz3NYemNFu

**Comment by jocelinocrs** [comment]
Please, how do I redeem my dogecoins?

**Comment by Fulvio55** [comment]
You can't recover them, unless you have the private key of the wallet they were sent to. It is not possible to recreate this key or reverse the transaction.

**Comment by jocelinocrs** [comment]
ok

**Comment by langerhans** [comment]
As already statedm, when you send coins to the wrong address you can't revers ethis process. If you know who owns the address you sent them to, then you can ask that person to send them back.
