### ISSUE TITLE
Getting this error message in the debug window: ERROR: AcceptToMemoryPool: non-final

### ISSUE THREAD

**Issue by spencercsheehan1** [dogecoin/dogecoin#1424]
Hi there, 

My experience in coding, much less in crypto coding is likely much less in comparison to yours, so thank you for humoring me in advance in listening me try to explain this issue. I searched google several times and couldn't find a good solution. My local wallet has been trying to sync for several days now, but I get this error. Any ideas? Thanks so much for any help you can provide. 

As a background, I uninstalled and reinstalled dogecoin core. It used to work fine.

**Comment by langerhans** [comment]
This isn't actually a hard error and has nothing to do with slow syncing. See for reference https://github.com/bitcoin/bitcoin/issues/5794 . So if you are unable to sync at all then it's a different cause. Maybe you have network issues, or you got a poorly connected node to download from.

**Comment by spencercsheehan1** [comment]
Thanks. Ok. Have you noticed the Dogecoin network is pretty slow in general? Seems like it to me.
