### ISSUE TITLE
Error -30973 when sending doges, please help

### ISSUE THREAD

**Issue by pekkapouta** [dogecoin/dogecoin#1428]
Hi, all my lovely doges that i mined back in 2014 seem to be stuck on the dogecoin core. When trying to send doges, the core crashes and gives an error message:

A fatal error occured. Dogecoin can no longer continue safely and will quit.

EXCEPTION: St13runtime_error CDB: Error -30973, cant open database C:\Program Files\Dogecoin\dogecoin-qt.exe in Runaway exception

Any technical shibes here having an idea how to solve this? Reinstalling doesn't seem to fix anything and I have tried even with 2 different computers. Is there something wrong with the most recent client version or with the wallet.dat file? Balances and past transfers (back in 2014) are displayed correctly however.

![kuva](https://user-images.githubusercontent.com/35260436/34719726-87813878-f544-11e7-885b-6feddf07354c.png)

**Comment by D3m0nKingx** [comment]
Check you don't have another instance of the dogecoin-qt.exe running. Look in task manager.
