### ISSUE TITLE
getheaders not serializing correctly in 1.14

### ISSUE THREAD

**Issue by rnicoll** [dogecoin/dogecoin#1442]
Seeing an issue with `1.14-dev` currently where a remote sendheaders command can trigger a client crash. It looks like the headers are being loaded from disk without their AuxPoW section, so when the client tries sending it back, serialization fails and it crashes.

Current example seems to be testnet block `1561d36f48fbc6799d803b94768e317c25b5aec6150c61ef7276f317af9ecf47` but currently confirming if it's always that block, or just random chance here.

**Comment by langerhans** [comment]
Is this still an issue?
