### ISSUE TITLE
-service no effict on mac run  Dogecoin-QT

### ISSUE THREAD

**Issue by zuoliang0** [dogecoin/dogecoin#1445]
i don't kown why i use the dogecoin.conf and set 
```
service=1
rpcuser=dogecoinrpc
rpcpassword=C5BnEkrpPPX1wLyqoVx6rnQkW43HuyyscH7boYuqmFzj
alertnotify="echo %s | ccc 127.0.0.1 5158"
blocknotify="echo %s | ddd 127.0.0.1 5159"
walletnotify="echo %s | fff 127.0.0.1 5160"
rpcport=18332
rpcallowip=192.168.9.1

```
when click the dogcoin icon  start ,telnet  127.0.0.1 18332  

```
telnet: connect to address 127.0.0.1: Connection refused
telnet: Unable to connect to remote host
```

and then i use command line `-service` to start also no effect

```
/Applications/Dogecoin-Qt.app/Contents/MacOS/Dogecoin-Qt  -service
```

who can help me ??

**Comment by rnicoll** [comment]
I think the problem is `rpcallowip=192.168.9.1` - you're connecting to `127.0.0.1` (that's the local machine) but authorizing connections from a remote IP (`192.168.9.1`). Presuming this is all on a single machine, try `rpcallowip=127.0.0.1` and see if that fixes it?

**Comment by zuoliang0** [comment]
no ,i test telnet just on the 127.0.0.1 local machine .not on 192.168.9.1
