### ISSUE TITLE
Balance not spendable 

### ISSUE THREAD

**Issue by ahmetax** [dogecoin/dogecoin#1446]
I transferred some dogecoins into my multidoge wallet. However my balance is showing as not spendable almost for 2 days.
What can I do?
Thanks.
Ahmet
![multidoge-2018-01-11 23-13-00](https://user-images.githubusercontent.com/16287915/34845684-cf675b20-f726-11e7-9d89-7cc27f50c5d3.png)

**Comment by langerhans** [comment]
This is the Dogecoin Core repo, not MultiDoge. Your sync seems to hang. try restarting the wallet a few times and also give it time to finish. You can see progress when you click on the progress bar.

**Comment by ahmetax** [comment]
Thanks. Resolved.
