### ISSUE TITLE
Electrum Vulnerability and Dogecoin Core

### ISSUE THREAD

**Issue by butterstuff** [dogecoin/dogecoin#1452]
I meant to ask this question when it was happening...

Does the vulnerability that affected Electrum and Electron-Cash wallets have any affect on the dogecoin core wallet?
Excuse the ignorance, but I am under the impression that the core wallet for dogecoin is a child of the bitcoin core wallet.  And, reading through the github issue thread for the electrum threat, i realized it could have had some impact on us.  It doesnt appear that it would upon further inspection, but it cant hurt to ask just in case.

original github issue:  https://github.com/spesmilo/electrum/issues/3374
mention of bitcoin core connection: 
[https://github.com/spesmilo/electrum/issues/3374#issuecomment-355852580](url)

**Comment by rnicoll** [comment]
Hi butterstuff,

We're fine; as the comment below on that thread says, by default Bitcoin Core (and by extension Dogecoin Core) don't open the RPC port, and if opened they should have a strong password set on them. The issue has been that Electrum doesn't support protecting the port.

Ross

**Comment by butterstuff** [comment]
I thought so - cant hurt to ask :)  thanks Ross
