### ISSUE TITLE
No Wallet Has Been Loaded

### ISSUE THREAD

**Issue by D3m0nKingx** [dogecoin/dogecoin#1453]
## System:

Ubuntu 16.04.3 LTS

## Wallet Version:

Dogecoin Core v1.10.0.0-bb4b082-dirty

Compiled from source

## Problem:

![image](https://user-images.githubusercontent.com/18432686/34950399-0f65d2a8-f9e1-11e7-87f0-962f7b76341b.png)

@rnicoll ?

**Comment by D3m0nKingx** [comment]
Very odd, I tried something to see what would happen. I deleted the folder `~/.config/Dogecoin`

Then after starting the wallet, I now have a wallet.dat which got loaded. However, the wallet is now resyncing from scratch again...

Anybody could give some input on what caused this?

**Comment by D3m0nKingx** [comment]
Maybe some setting in the ~/.config/Dogecoin/Dogecoin-Qt.conf isn't working correctly? I've come across smth like this happening with another coin before, where setting the Proxy line caused the GUI to actually stop opening.

**Comment by D3m0nKingx** [comment]
Current contents of Dogecoin-Qt.conf:

```
[General]
addrProxy=127.0.0.1:9050
bSpendZeroConfChange=true
fCoinControlFeatures=true
fFeeSectionMinimized=true
fListen=true
fMinimizeOnClose=true
fMinimizeToTray=false
fPayOnlyMinFee=false
fRestartRequired=false
fUseProxy=false
fUseUPnP=false
language=
nCustomFeeRadio=0
nDatabaseCache=100
nDisplayUnit=2
nFeeRadio=0
nRPCConsoleWindowPos=@Point(312 131)
nRPCConsoleWindowSize=@Size(740 450)
nSmartFeeSliderPosition=0
nThreadsScriptVerif=0
nTransactionFee=0
nWindowPos=@Point(255 25)
nWindowSize=@Size(850 602)
strThirdPartyTxUrls=https://dogechain.info/tx/%s|https://chain.so/tx/DOGE/%s
```

**Comment by D3m0nKingx** [comment]
In the debug.log:

```
2018-01-16 15:30:27 CTxMemPool::ReadFeeEstimates(): unable to read policy estimator data (non-fatal)
2018-01-16 15:30:27 Unsetting NODE_NETWORK on prune mode
2018-01-16 15:30:27 Wallet disabled!
2018-01-16 15:30:27 init message: Activating best chain...
```
**2018-01-16 15:30:27 Wallet disabled!**

What is causing that?

**Comment by D3m0nKingx** [comment]
Ok found the cause:

```bash
2018-01-16 15:42:43 AppInit2 : parameter interaction: -prune -> setting -disablewallet=1
2018-01-16 15:42:43 Prune configured to target 2200MiB on disk for block and undo files.
2018-01-16 15:42:43 
```

If I add to the dogecoin.conf file: `disablewallet=0` This error returns:

![screenshot from 2018-01-16 10-45-15](https://user-images.githubusercontent.com/18432686/34997455-8cf55ac6-faaa-11e7-9967-a577d94d9f9d.png)

And I see in the code:
    https://github.com/dogecoin/dogecoin/blob/7c52b213c870ac210b225110759308cd8c6b8e81/src/init.cpp#L753
https://github.com/dogecoin/dogecoin/blob/7c52b213c870ac210b225110759308cd8c6b8e81/src/init.cpp#L754

@rnicoll is SPV still not implemented?

**Comment by langerhans** [comment]
The referenced code is not present in 1.14 so I assume this works as intended now.
