### ISSUE TITLE
[Linux] Dogecoin-Qt SystemTray Menu Inoperable

### ISSUE THREAD

**Issue by D3m0nKingx** [dogecoin/dogecoin#1454]
![kazam_screenshot_00000](https://user-images.githubusercontent.com/18432686/34999755-91de3732-fab0-11e7-82bd-8dd3712e5a88.png)

Clicking on the dogecoin system tray icon has no menu :/

Also setting the "Minimize on close" option causes it to minimize to the tray instead of the taskbar when  "Minimize to the system tray instead of taskbar" is **not** set.

**Comment by langerhans** [comment]
Works on 1.14. Closing.
