### ISSUE TITLE
How to redeem doge coin in my wallet

### ISSUE THREAD

**Issue by vijayantjain** [dogecoin/dogecoin#1461]
Hi,
please help me 
I have mac book pro with Dogecoin Core QT 1.10 wallet
just for checking to receiving payment i transfer 10000 doge in my doge core wallet but not received yet , i check transition in doge block chain  its showing Confirmed transaction but Not yet redeemed ,so how its transfer in wallet pls help

**Comment by langerhans** [comment]
You need to provide more info than that. Transaction hash. Screenshot of wallet, attach debug.log. We can't help you by magically guessing these things.

**Comment by vijayantjain** [comment]
thanks for reply,
hash:-45c94e9978698ce3b569d1b58f184a3dd9ce87f46da98f54ac8f67fdc9124c12
and find the attachment of  wallet screenshot

thanks

**Comment by kobe2016** [comment]
终于找到你   还好没放弃
