### ISSUE TITLE
Dogecoin Core v1.10 takes up ~2gb of RAM

### ISSUE THREAD

**Issue by bolatovumar** [dogecoin/dogecoin#1472]
I was planning on running a Dogecoin Core full node on a Raspberry Pi alongside a Bitcoin Core node. However, I just noticed that Dogecoin Core takes up ~2gb of RAM on my desktop as compared to ~300mb for Bitcoin Core V1.15.

Is this a know issue? Are there plans to address this? Anything I can do to help?

**Comment by rnicoll** [comment]
1.14 (over in https://github.com/dogecoin/dogecoin/tree/1.14-branding ) uses a lot less memory, although we do have problems due to sheer number of blocks.

**Comment by bolatovumar** [comment]
Could you explain what was done to improve the memory consumption? Just
curious.

Also, are the blocks stored in RAM or something? How does the number of
blocks affect the memory usage?

**Comment by rnicoll** [comment]
So one of the biggest uses of memory is a block header index. With AuxPoW we have the entire block header of the parent chain as part of our full block headers, essentially doubling memory usage. It also scales (obviously) by number of blocks, worsening the situation. 1.14 (and the 1.11 alpha we never released) remove AuxPoW data from that index; it reduces our ability to sanity check internal state, but that's considered a reasonable trade-off given the data is validated when received.

**Comment by bolatovumar** [comment]
Wow so much cool. Such programming.

Gonna read up on AuxPoW now. Thanks!

**Comment by sattarovc** [comment]
Hello good time
I bought  Dogecoin on Chanelle but  Dogecoin has not been deposited with me
https://changelly.com/transaction/747c60b84b42


https://dogechain.info/tx/8611f9c5f276580551f9a37a017a74a8cb248892f4c7c99a617de22a60006364


Dogecoin Address: D7nfiu8VzfQVygujFjX6eAVotJHBGWsoN9
My wallet is at www.cryptonator.com
Please check why Dogecoin is not deposited in my account  help help help me

What is the meaning of the following statement?
Not yet redeemed


What time do you deposit to my account
please check it . Thank you
Please, please, I beg you to follow my work, I swear you

**Comment by langerhans** [comment]
A 1.14 node idles at around 880 MB resident memory for me so I'll close here for now.
