### ISSUE TITLE
Is it possible yet to run a wallet on a pruned dogecoind client?

### ISSUE THREAD

**Issue by spmedia** [dogecoin/dogecoin#1473]
I see in the notes on Dogecoin Core 1.10.0

>Block file pruning
>It is possible to run a Dogecoin node without keeping the full blockchain on your disk. This is currently incompatible with having a wallet on that client due to the fact that some actions regarding a wallet require the full block data. The minimum amount of kept blocks has been changed from Bitcoin to reflect our shorter block times.

Since this is a fresh alpha update, has this been fixed/changed yet? I'm looking to run a pruned version of dogecoind + a wallet. If not, is this planned in the near future/timeline?

very thanks!

**Comment by kaykurokawa** [comment]
Since 1.14 is based on Bitcoin Core 0.14 which has this feature,  it should be possible.

**Comment by spmedia** [comment]
Thanks @kaykurokawa
