### ISSUE TITLE
Dogecoind crashed after upgarding from 1.10 to 1.14alpha 2 

### ISSUE THREAD

**Issue by kaykurokawa** [dogecoin/dogecoin#1475]
I upgraded dogecoin from version 1.10 to 1.14 alpha2 (Ubuntu 16.04) and when I attempted to run dogecoind, it crashed with this error: 

dogecoind: chain.cpp:130: CBlockIndex* CBlockIndex::GetAncestor(int): Assertion `pindexWalk->pprev' failed.
Aborted (core dumped)

Upon clearing out the data directory, 1.14 alpha 2 starts working as expected.

Not sure if this is an important detail but when I upgraded, my chain was not yet fully synced , and was at height 20353 when I upgraded to 1.14 alpha 2.

**Comment by patricklodder** [comment]
Should be fixed with 1.14.2
