### ISSUE TITLE
Question: PROTOCOL_VERSION vs INIT_PROTO_VERSION?

### ISSUE THREAD

**Issue by mmlinford** [dogecoin/dogecoin#1478]
I've posted this twice on reddit (r/dogecoindev, r/coindev) but haven't gotten any responses :cry: :

So, version.h defines two constants, PROTOCOL_VERSION and INIT_PROTO_VERSION. PROTOCOL_VERSION seems self-explanatory, but for INIT_PROTO_VERSION there's a comment: "initial proto version, to be increased after version/verack negotiation". Does anybody know why that happens? What's the point of initially giving a bogus version then immediately changing it?

**Comment by langerhans** [comment]
If you haven't gotten an answer, then probably nobody knows ;) Regardless, this is a change that predates even Dogecoin's creation, see the upstream PR here: bitcoin/bitcoin#3155.  
Maybe try the bitcoin stackexchange. Closing since this is an issue tracker, not a knowledge base.
