### ISSUE TITLE
configure: error: Found Berkeley DB other than 5.1, required for portable wallets

### ISSUE THREAD

**Issue by glaksmono** [dogecoin/dogecoin#1479]
I'm getting the following error:

```
checking whether strnlen is declared... yes
checking whether le16toh is declared... no
checking whether le32toh is declared... no
checking whether le64toh is declared... no
checking whether htole16 is declared... no
checking whether htole32 is declared... no
checking whether htole64 is declared... no
checking whether be16toh is declared... no
checking whether be32toh is declared... no
checking whether be64toh is declared... no
checking whether htobe16 is declared... no
checking whether htobe32 is declared... no
checking whether htobe64 is declared... no
checking whether bswap_16 is declared... no
checking whether bswap_32 is declared... no
checking whether bswap_64 is declared... no
checking for MSG_NOSIGNAL... no
checking for library containing clock_gettime... none required
checking for visibility attribute... yes
checking for Berkeley DB C++ headers... default
configure: error: Found Berkeley DB other than 5.1, required for portable wallets (--with-incompatible-bdb to ignore or --disable-wallet to disable wallet functionality)
```

I've installed `berkeley-db4` through `homebrew`:

```
brew install berkeley-db4
brew unlink berkeley-db            # unlinking the default berkeley DB
brew link berkeley-db4 --force
Warning: Already linked: /usr/local/Cellar/berkeley-db@4/4.8.30
To relink: brew unlink berkeley-db@4 && brew link berkeley-db@4
```

Thoughts? I've been stuck in trying to build this (i.e. Step 2 of https://github.com/dogecoin/dogecoin/blob/master/doc/build-osx.md#building-dogecoind)

**Comment by Turupawn** [comment]
On Mar 12, 2018 12:30 AM, "Grady Laksmono" <notifications@github.com> wrote:
>
> I'm getting the following error:
>
> checking whether strnlen is declared... yes
> checking whether le16toh is declared... no
> checking whether le32toh is declared... no
> checking whether le64toh is declared... no
> checking whether htole16 is declared... no
> checking whether htole32 is declared... no
> checking whether htole64 is declared... no
> checking whether be16toh is declared... no
> checking whether be32toh is declared... no
> checking whether be64toh is declared... no
> checking whether htobe16 is declared... no
> checking whether htobe32 is declared... no
> checking whether htobe64 is declared... no
> checking whether bswap_16 is declared... no
> checking whether bswap_32 is declared... no
> checking whether bswap_64 is declared... no
> checking for MSG_NOSIGNAL... no
> checking for library containing clock_gettime... none required
> checking for visibility attribute... yes
> checking for Berkeley DB C++ headers... default
> configure: error: Found Berkeley DB other than 5.1, required for portable
wallets (--with-incompatible-bdb to ignore or --disable-wallet to disable
wallet functionality)
>
> I've installed berkeley-db4 through homebrew:
>
> brew install berkeley-db4
> brew unlink berkeley-db            # unlinking the default berkeley DB
> brew link berkeley-db4 --force
> Warning: Already linked: /usr/local/Cellar/berkeley-db@4/4.8.30
> To relink: brew unlink berkeley-db@4 && brew link berkeley-db@4
>
> Thoughts? I've been stuck in trying to build this (i.e. Step 2 of
https://github.com/dogecoin/dogecoin/blob/master/doc/build-osx.md#building-dogecoind
)

**Comment by glaksmono** [comment]
@Turupawn I don't get it. Can you elaborate and explain please?

**Comment by D3m0nKingx** [comment]
@glaksmono run the configure script:

`./configure --with-incompatible-bdb`

**Comment by langerhans** [comment]
It tells you to use BDB 5.1 and you install v4 ;) Of course that's not going to work. Anyway, you should ideally use the included dependency builder, but I have actually no idea if natively compiling on OSX even works. 

Before you compile with `--with-incompatible-bdb` actually make sure you understand the implications! You wallet.dat will be incompatible with different versions of Dogecoin Core. That also means you won't be able to restore from a backup created with anything newer than Dogecoin Core 1.6 (iirc).

**Comment by glaksmono** [comment]
```
-rw-r--r--    1 glaksmono  staff    7626 Mar 14 13:20 Makefile.am
-rw-r--r--    1 glaksmono  staff   41816 Mar 14 13:44 Makefile.in
```

After I did that, I noticed that there are 2 `Makefile`. Which one that I should be using for `make`?

I tried renaming each of them to `Makefile` but I'm getting this for both:

```
Makefile:15: *** missing separator.  Stop. # for Makefile.in
Makefile:7: *** missing separator.  Stop.   # for Makefile.am
```

**Comment by feizx** [comment]
I'm sure you haven't read the document carefully.

**Comment by quantumproducer** [comment]
@D3m0nKingx I tried that, then on `make` I got https://github.com/dogecoin/dogecoin/issues/1486

**Comment by quantumproducer** [comment]
@langerhans there's not a clear way to install 5.1 on OSX, at least with `brew`, which supports 6.X and 4.X .. 

Installing without berkeley db *today* means the wallet will work going forward, yes?

**Comment by langerhans** [comment]
There are more recent instructions for building on macOS here: https://github.com/dogecoin/dogecoin/blob/1.14-branding/doc/Building-Dogecoin-1.14-for-Mac.md
Feel free to open a new issue if these don't work out :)
