### ISSUE TITLE
ZMQ support

### ISSUE THREAD

**Issue by Polve** [dogecoin/dogecoin#1480]
Current dogecoin sw has no ZMQ support, is it possible to add it?

Or is there any plan to have an updated release of the node that supports it?

**Comment by langerhans** [comment]
This will be coming with the 1.14 release.

**Comment by RobertPaul01** [comment]
Is this still slated for 1.14?

**Comment by rnicoll** [comment]
Yup; if you're comfortable building your own versions you could actually try the `1.14-branding` branch now, which is essentially beta quality except we're having packaging problems.

**Comment by corymsmith** [comment]
@rnicoll What packaging problems are you having?
