### ISSUE TITLE
whereis rpc document?

### ISSUE THREAD

**Issue by jhomephper** [dogecoin/dogecoin#1484]
rpc文档在哪里，找不到啊

**Comment by mmlinford** [comment]
(For non-Chinese speakers, google translates that as "Where is the document?")

**Comment by rnicoll** [comment]
https://en.bitcoin.it/wiki/Original_Bitcoin_client/API_calls_list is currently the best guide outside of the client, but there's built-in help (the "help" command) that's more up to date. Hope that helps!
