### ISSUE TITLE
Doge wallet 1.10 Ubuntu 12,14 & 16 w/all lib's install error

### ISSUE THREAD

**Issue by ultra-pool** [dogecoin/dogecoin#1497]
`configure: error: libdb_cxx headers missing, Dogecoin Core requires this library for wallet functionality (--disable-wallet to disable wallet functionality)`

I have all the lib's installed. Tested on 2 VPS 1 full server and 4 VM's. Ubuntu 12,14 and 16, Mint and they all have the same error. All have different Lib releases. And all have the required lib's listed in the readme file and then some. And all tested on clean servers.

The small work around listed in the tickets here does not work. 

If you have also ran in this. Please reply. 

Thank you.

**Comment by rllola** [comment]
I remember seeing this error in the past...
I have a fresh ubuntu 16 install. I will try to reproduce this.

I am mostly using docker when I want to use dogecoind (running 1.10). Maybe this can help you : 
https://github.com/BitcoinAmiens/docker-dogecoin

Will report tomorrow with more info.

**Comment by rnicoll** [comment]
Err, which version of Berkeley DB do you have installed?

**Comment by rllola** [comment]
I believe I have 5.3

**Comment by rllola** [comment]
Nope my bad. I actually wasn't installed. But 5.1 doesn't seems available like in the documentation however I found 5.3 

So I did :
```
sudo apt install libboost-all-dev libdb5.3-dev libdb5.3++-dev
```

but now I have this error : 
```
checking for Berkeley DB C++ headers... default
configure: error: Found Berkeley DB other than 5.1, required for portable wallets (--with-incompatible-bdb to ignore or --disable-wallet to disable wallet functionality)
```
So I believe I have to download and build 5.1

**Comment by rllola** [comment]
Actually no need to download 5.1 with incompatible db flag.

I have done a short gist. I hope it helps @ultra-pool 
https://gist.github.com/rllola/0e46feae5a41cb7d29352a84fb388304

@rnicoll If you think it is needed I can update the documentation ?

**Comment by rnicoll** [comment]
I'm trying to decide if we want to update the docs, or move to 5.3/later. Probably yes can you raise a documentation update against the 1.14-branding branch, and we'll move to a later BDB for 1.15+.

**Comment by rllola** [comment]
@rnicoll I believe this issue can be close now.
