### ISSUE TITLE
null dereference by static analysis tools

### ISSUE THREAD

**Issue by wudigithub1** [dogecoin/dogecoin#1499]
rpcblockchain.cpp 38

    if (blockindex == NULL)
    {
        if (chainActive.Tip() == NULL)
            return 1.0;
        else
            blockindex = chainActive.Tip();  //may return null,   CBlockIndex *Tip() const {
        return vChain.size() > 0 ? vChain[vChain.size() - 1] : NULL;
    }
    }

    int nShift = (blockindex->nBits >> 24) & 0xff;  //null dereference

**Comment by Nolaan** [comment]
if (chainActive.Tip() == NULL)

**Comment by mmlinford** [comment]
@wudigithub1 , just curious, what tool did you use?

**Comment by langerhans** [comment]
False positive :)
