### ISSUE TITLE
!!!ATTENTION!!! THE THIEVES !!! ROBBERS !!! AFERISTS !!!

### ISSUE THREAD

**Issue by mor943k** [dogecoin/dogecoin#1503]
!!!ATTENTION!!! THE THIEVES !!! ROBBERS !!! AFERISTS !!!
Good afternoon!
There was an unpleasant situation in which Dogecoin was used in a fraudulent activity.
I'm talking about the website
WWW.DOGEMINER. cc
This site has been advertised on many crypto-currency resources. And without any problems, all advertising has worked for a long time.
As a result this site
WWW.DOGEMINER.cc
offered to invest dogecoins in cloud mining.
After that, by itself, when people invested dogecoin, this site was closed.
At the moment, the funds that were invested in cloud mining were in the hands of intruders.
In this regard, please raise this topic on the forum, as the site WWW.DOGEMINER. cc
stole a huge amount of dogecoins.
I think that the community should be informed about the situation.
There is a list of wallets, which are owned by intruders.
Here are a couple of links to this site and its groups with social networks:
https://dogeminer.cc/index.php
https://twitter.com/invest_cc
https://mobile.twitter.com/invest_cc

**Comment by langerhans** [comment]
Yeah that's bad and all, but the issue tracker is not the right place for this message. Try one of the various communities ;)
