### ISSUE TITLE
Can not find any working faucet.

### ISSUE THREAD

**Issue by vipsaini** [dogecoin/dogecoin#1505]
Need some testnet dogecoins at this address nf3rLxshXfGWtgRc593vkaxDHE6DZJ86nt

**Comment by PhoenixDiscord** [comment]
faucets give you Dogecoin if you have some coins in your wallet :p

**Comment by guchenglin111** [comment]
Can not find any working faucet. can you transfer me some test coin ncdisZ6YczH7dVgrEx2GDcchBYGKzgV34t

**Comment by greenbigfrog** [comment]
@guchenglin111 done. Bust as @rnicoll already said, just mine some the next time. It's not that hard.

I'd like to add though, that another option is to use the built in miner. If you've got a working core wallet (which I will assume you do, when you want some testnet coins), just send `setgenerate [number of threads/true` to start mining, and `setgenerate false` to stop. (It's also possible to set this in `dogecoin.conf`, but I can't recall the exact parameter. (Something like `generate=[threads/true]`)

**Comment by guchenglin111** [comment]
Thank you. Your answer is very helpful

**Comment by rllola** [comment]
There is now a testnet faucet : https://doge-faucet-testnet.ggcorp.fr/

I also have lots of testnet dogecoin. Feel free to ping.
