### ISSUE TITLE
estimatefee output error

### ISSUE THREAD

**Issue by jadeydi** [dogecoin/dogecoin#1513]
Operating system:

Ubuntu 17.10 (GNU/Linux 4.13.0-19-generic x86_64)

Dogecoin version: 

dogecoin-1.10.0, Block synchronize works well.

dogecoin-cli estimatefee 1 always return -1.00000000

Anyone has problem, will it be fixed, thanks?

**Comment by nandubatchu** [comment]
I am also facing the same issue for testnet version.

**Comment by ReverseControl** [comment]
@patricklodder @rnicoll @michilumin We can close this one.
