### ISSUE TITLE
Systemd can't capture logs because they go to debug.log instead of stdout/stderr

### ISSUE THREAD

**Issue by fxer** [dogecoin/dogecoin#1540]
I'm running dogecoin 1.10 on ubuntu 18.04 and noticed Systemd isn't capturing any logs for dogecoind. It looks like this is because all the output (new blocks syncing) is being written to debug.log. Is there a way to configure dogecoind so systemd will capture the log data instead?

(also I'm not using the `-daemon` flag because modern init systems handle daemonizing themselves, and don't need the app to do it. in fact when the app tries to _also_ do it, it can cause more problems than it solves)

My systemd unit file:

```
[Unit]
Description=dogecoind-mainnet
After=network.target

[Service]
Type=simple
User=coinnode
Group=coinnode

EnvironmentFile=/etc/secrets/dogecoind.env

ExecStart=/opt/dogecoin/bin/dogecoind \
            -datadir=/mnt/chaindisk/coinnode \
            -maxconnections=25 \
            -rpcuser=${DOGECOIND_RPCUSER} \
            -rpcpassword=${DOGECOIND_RPCPASS} \
            -port=22556 \
            -server \
            -rpcport=22555 \
            -rpcallowip=127.0.0.1 \
            -txindex \
            -disablewallet

Restart=on-failure

# systemd hardening
PrivateTmp=true
NoNewPrivileges=true
DevicePolicy=closed

[Install]
WantedBy=multi-user.target
```

**Comment by langerhans** [comment]
You can use `-printtoconsole` to redirect debug-log output to stdout. Let me know if it works for you :)

**Comment by fxer** [comment]
Boom that was it, thanks @langerhans! I see the systemd unit file in [contrib/init/dogecoin.service](https://github.com/dogecoin/dogecoin/blob/master/contrib/init/dogecoind.service) in 3y old, do you think it could use a PR to more closely resemble what I have above (cleaned up/generified some)?

**Comment by langerhans** [comment]
I'm not a Linux user myself so I don't have a strong opinion here. Given we pull in changes mostly from upstream bitcoin you might want to make your PR there. If you want to make it here, please do so to the `1.14-branding` branch because that would be the upcoming release :)

**Comment by ekryski** [comment]
Yeah this is pretty standard and not doge specific imo. Could probably close this. Setting the printtoconsole flag is the way this is supposed to be handled in Bitcoin right now.

**Comment by langerhans** [comment]
Closing as solved for now :)
