### ISSUE TITLE
ERROR & crash after linking data dir .dogecoin to external device dir

### ISSUE THREAD

**Issue by owjack5** [dogecoin/dogecoin#1549]
Reproduce the issue:
When starting up dogecoin-qt v1.10.0 in Ubuntu 18.04 and whether you choose to store the data in another dir OR whether you choose /home/user/.dogecoin dir and you previously linked to an external device with:  `ln -s /media/sf_DB/Dogecoin/ .dogecoin`

dogecoin-qt will open up and throw an error in either case.
Error is:
`Error opening block database`
`Do you want to rebuild the block database now?`

In the debug.log is the following

> 2018-10-24 18:31:50 Dogecoin version v1.10.0.0-208dc1b (2015-11-01 18:31:30 +0000)
> 2018-10-24 18:31:50 Using OpenSSL version OpenSSL 1.0.1l 15 Jan 2015
> 2018-10-24 18:31:50 Using BerkeleyDB version Berkeley DB 5.1.29: (October 25, 2011)
> 2018-10-24 18:31:50 Default data directory /home/user/.dogecoin
> 2018-10-24 18:31:50 Using data directory /home/user/.dogecoin
> 2018-10-24 18:31:50 Using config file /home/user/.dogecoin/dogecoin.conf
> 2018-10-24 18:31:50 Using at most 125 connections (1024 file descriptors available)
> 2018-10-24 18:31:50 Using 3 threads for script verification
> 2018-10-24 18:31:50 Using wallet wallet.dat
> 2018-10-24 18:31:50 init message: Verifying wallet...
> 2018-10-24 18:31:50 scheduler thread start
> 2018-10-24 18:31:50 CDBEnv::Open: LogDir=/home/user/.dogecoin/database ErrorFile=/home/user/.dogecoin/db.log
> 2018-10-24 18:31:50 Cache configuration:
> 2018-10-24 18:31:50 * Using 2.0MiB for block index database
> 2018-10-24 18:31:50 * Using 32.5MiB for chain state database
> 2018-10-24 18:31:50 * Using 65.5MiB for in-memory UTXO set
> 2018-10-24 18:31:50 init message: Loading block index...
> 2018-10-24 18:31:50 Opening LevelDB in /home/user/.dogecoin/blocks/index
> 2018-10-24 18:31:50 IO error: /home/user/.dogecoin/blocks/index: Invalid argument
> 2018-10-24 18:31:57 init message: Loading block index...
> 2018-10-24 18:31:57 Wiping LevelDB in /home/user/.dogecoin/blocks/index
> 2018-10-24 18:31:57 Opening LevelDB in /home/user/.dogecoin/blocks/index
> 2018-10-24 18:31:57 IO error: /home/user/.dogecoin/blocks/index: Invalid argument
> 2018-10-24 18:32:03 scheduler thread interrupt
> 2018-10-24 18:32:03 Shutdown: In progress...
> 2018-10-24 18:32:03 StopNode()
> 2018-10-24 18:32:04 Shutdown: done

I tested Bitcoin/Litecoin and they run perfectly whether they are links to external devices for the data dir or whether you set the data dir from the beginning to external devices.

The only data dir it doesnt crash in is if i set it to one like /home/user/Documents or some other in $HOME

Why is this happening?  Does this need to be fixed for next release?

**Comment by rnicoll** [comment]
This is generally a sign something has damaged the files on disk. Generally the solution (although yes it takes a while) is to run Dogecoin with the `-reindex` option, which will cause it to rebuild the database that's been damaged.

**Comment by owjack5** [comment]
@rnicoll yes i agree with you but in this case its not. Because i tried -reindex on the default folder and it finished but when i linked to it after it still gives that error. So something is up with it trying to read from a link maybe?
Maybe i should also mention that i tried this from a shared VM folder from VirtualBox but that wouldn't make a difference, as the link is exactly how i posted it above.

**Comment by langerhans** [comment]
I can't reproduce this on 1.14. Even on 1.10 I have hardlinked (on Windows) my datadir and it works fine. On 1.14 I have mounted my datadir into a VM and just bass `-datadir=7mnt/ngfs/doge-data` and that reads the shared datadir just fine. Mind you both times I have made sure my linked directory was empty. Maybe that has something to do with it? I'll close here for now cause this was inactive for a while, feel free to post again if that is still an issue.

**Comment by owjack5** [comment]
@langerhans this problem still persists.
I tried both of your methods, and i get the same error. This is from running dogecoin from **scratch** with an empty dir `/media/sf_DB/Dogecoin` linked to `.dogecoin`
`ln -s /media/sf_DB/Dogecoin/ .dogecoin`
Then i ran
`./dogecoin-1.10.0/bin/dogecoin-qt`
then the popup of 
```
Error opening block database
Do you want to rebuild the block database now?
```

i tried putting: strDataDir=/home/user/.dogecoin inside the config file and started up with the same error.  The error that it says in the logs before it crashes is:
```
2018-10-24 18:31:57 Opening LevelDB in /home/user/.dogecoin/blocks/index
2018-10-24 18:31:57 IO error: /home/user/.dogecoin/blocks/index: Invalid argument
```
For some reason it is not seeing the data in the linked dir properly.

The funny thing is, that this has happened (and ive tested just out of curiosity) also for Navcoin client.
When i test litecoin, vertcoin and bitcoin clients.  all work fine from linked dirs from the VM
The VM guest OS is the same as the host OS. Ubuntu 18.04

Please could you try and explain this strange error phenomenon.

**Comment by langerhans** [comment]
I'm still running the same setup as I outlined in my previous comment and haven't encountered any issue. You have also not really tried what I said. `strDataDir` is not a valid param and it doesn't go into the config file either. And the dir you put there is the default anyway. Try this: Make an empty folder on your share, then start Dogecoin Core with `./dogecoin-qt -datadir=/media/sf_DB/Dogecoin` or whatever you call the directory. The symlink isn't really required, it was just convenient for me on Windows. On vmware I just use the datadir param pointing to the shared folder that is linked directly to the host's datadir.

**Comment by owjack5** [comment]
@langerhans i tried what you said. please check the small vid i made on a new VM.
![2019-05-06](https://user-images.githubusercontent.com/44449880/57214282-d1d57080-6fe9-11e9-9bb2-9113e6544f22.gif)
