### ISSUE TITLE
get chain size through rpc

### ISSUE THREAD

**Issue by roccomuso** [dogecoin/dogecoin#1550]
Is it possible to get chain size on disk through rpc?
The equivalent of bitcoind `size_on_disk` property from the `getblockchaininfo` rpc method.

**Comment by rnicoll** [comment]
This is in the 1.16 release when we get there, but we're currently trying to get deterministic builds of 1.14 done and can then look at finishing off 1.16, so it's a while out.

**Comment by patricklodder** [comment]
Fixed with #1637
