### ISSUE TITLE
no vsize/size result on decoderawtransaction 

### ISSUE THREAD

**Issue by billyadelphia** [dogecoin/dogecoin#1556]
I am implementing dogecoin on my app. Any other coin that based from bitcoin source return vsize/size in decoderawtransaction function in RPC call, but dogecoin does not.
Any idea why ? I need vsize/size to determine transaction fee.

**Comment by ivanslav1517** [comment]
Alert compyter

**Comment by langerhans** [comment]
These will be available in 1.14. Closing as fixed :)
