### ISSUE TITLE
Missed TXID

### ISSUE THREAD

**Issue by ikamran** [dogecoin/dogecoin#1559]
I sent 1818 Dogecoin to the address D6gNNBLc3xF93Eky7X8eKXaRrcVDEV6mH6 via dogecoin core 1.14 wallet on ubuntu server 

root@localhost:~/.dogecoin# ./dogecoin-cli gettransaction "484351b991dd9541bc45ef57c8bbe7818b0bc20fa2e7d0b4809773c8d3a9a005"
{
  "amount": -1818.00000000,
  "fee": -1.00000000,
  "confirmations": 0,
  "trusted": false,
  "txid": "484351b991dd9541bc45ef57c8bbe7818b0bc20fa2e7d0b4809773c8d3a9a005",
  "walletconflicts": [
  ],
  "time": 1545769060,
  "timereceived": 1545769060,
  "bip125-replaceable": "unknown",
  "details": [
    {
      "account": "",
      "address": "D6gNNBLc3xF93Eky7X8eKXaRrcVDEV6mH6",
      "category": "send",
      "amount": -1818.00000000,
      "vout": 0,
      "fee": -1.00000000,
      "abandoned": false
    }

but it is not there and when i use txid on any dogecoin explorer it shows that TXID donst exist!!!

where is coins?

**Comment by ikamran** [comment]
strange issue
I went to https://live.blockcypher.com/btc-testnet/pushtx/
then I entered the Transaction Hex and I clicked on Broadcast Transactions and then it appears on dogecoin blockchain explorer, 

why this happened at all?
can somebody please explain it to me?

**Comment by D3m0nKingx** [comment]
>"confirmations": 0,

When you checked, it had 0 confirmations at the time.

**Comment by Fulvio55** [comment]
https://bitinfocharts.com/dogecoin/tx/484351b991dd9541bc45ef57c8bbe7818b0bc20fa2e7d0b4809773c8d3a9a005

You checked too early.

BTW, you could have sent this for free using coinb.in with your keys. You DO have your keys backed up outside of the client, right?

**Comment by ikamran** [comment]
no I didn't check too early, after 3 hours I checked and when I find there is no txid on the dogecoin explorer I tried to broadcast transaction again using the above site,
I am interested to know why this happened anybody  has an idea?

**Comment by rnicoll** [comment]
One thought - what client version are you on?

**Comment by ikamran** [comment]
I installed Litecoin Core on Ubuntu 1.14.2

**Comment by greenbigfrog** [comment]
This repository is for dogecoin, not litecoin.
(Also 1.14.2 is the version of the Linux kernel, not the Ubuntu version)

**Comment by ikamran** [comment]
root@localhost:~/dogecoin/dogecoin-1.14.2/bin# ./dogecoin-cli getinfo
{
  "version": 1140200,
  "protocolversion": 70015,
  "walletversion": 130000,
  "balance": 0,
  "blocks": 2532901,
  "timeoffset": -1,
  "connections": 8,
  "proxy": "",
  "difficulty": 1995634.54135584,
  "testnet": false,
  "keypoololdest": 1544824252,
  "keypoolsize": 100,
  "paytxfee": 1.00000000,
  "relayfee": 1.00000000,
  "errors": "This is a pre-release test build - use at your own risk - do not use for mining or merchant applications"
}

**Comment by rnicoll** [comment]
Ah, that's it, there's a transaction compatibility fix in the third alpha, you've for the second alpha. Still if you could upgrade to the beta ( https://github.com/dogecoin/dogecoin/releases/tag/v1.14-beta-1 ) that would be best, as it will fix this among other issues.

**Comment by ikamran** [comment]
is is enough just to replace the files?

**Comment by bicubebime** [comment]
Since upgrading to 1.4 my node is experiencing this issue, the workaround it's what is suggested here: https://github.com/dogecoin/dogecoin/issues/1559#issuecomment-449879661

**Comment by bicubebime** [comment]
it has been fixed on https://github.com/dogecoin/dogecoin/releases/tag/v1.14.1 ?

**Comment by ReverseControl** [comment]
@ikamran Were you able to resolve your issue?

**Comment by ReverseControl** [comment]
Given the original question was answered, i.e. the transaction did indeed happen and I could confirm it as well. I am closing this issue. If the why becomes relevant, this issue could be opened again.
