### ISSUE TITLE
Can't sync blockchain 1.13 & 1.14 B1

### ISSUE THREAD

**Issue by komer83** [dogecoin/dogecoin#1563]
Installed on a new system, copied my wallet.dat, trying to sync and it keeps crashing. Both in 1.13 and 1.14 B1. 

Edit: Using MacOS High Sierra 10.13.06

Attaching the log. 
[debug.log](https://github.com/dogecoin/dogecoin/files/2722780/debug.log)

**Comment by komer83** [comment]
First of all, in the title I meant 1.10, not 1.13

So far nothing I've tried fixed it. I cleaned everything use AppCleaner, removed everything from /ApplicationSupport/Dogecoin 

Trying to sync again, and getting this error over and over again.

**Comment by ReverseControl** [comment]
@komer83 Were you able to resolve this issue?

**Comment by ReverseControl** [comment]
@patricklodder @rnicoll @michilumin I'd suggest closing this one. The shibe could re-open it if problem stills exist.
