### ISSUE TITLE
FTBFS with boost 1.67

### ISSUE THREAD

**Issue by lexical** [dogecoin/dogecoin#1564]
Current Dogecoin can be built with boost 1.62 in Debian, but FTBFS with bootst 1.67.
boost 1.62 is planned be to removed in the next release of Debian (buster).

Any chance to fix the build failure with boost 1.67.
Details are available from https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=914146

**Comment by lexical** [comment]
FYI, a Debian Developer provided a [patch](https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=914146;filename=fix_ftbfs.patch;msg=29) fixing the FTBFS.
I will apply it first to get dogecoin package back to Debian Testing.

I will look at 1.14-branding later.

**Comment by ReverseControl** [comment]
@patricklodder @rnicoll @michilumin Close this one.

**Comment by patricklodder** [comment]
Fixed with #1655
