### ISSUE TITLE
Core dump when running dogecoind

### ISSUE THREAD

**Issue by reactionstudio** [dogecoin/dogecoin#1565]
After following the build instructions and compiling dogecoin core i get the following errors when trying to start the daemon.

The first time it's run this is the output:

> $ dogecoind -testnet
> Error: To use dogecoind, or the -server option to dogecoin-qt, you must set an rpcpassword in the configuration file:
> /home/serveruser/.dogecoin/dogecoin.conf
> It is recommended you use the following random password:
> rpcuser=dogecoinrpc
> rpcpassword=4694wPkxMkmidd8jdoSmZego8qjxnz4epGmntYo3uehy
> (you do not need to remember this password)
> The username and password MUST NOT be the same.
> If the file does not exist, create it with owner-readable-only file permissions.
> It is also recommended to set alertnotify so you are notified of problems;
> for example: alertnotify=echo %s | mail -s "Dogecoin Alert" admin@foo.com
> 
> Error: 
> dogecoind: /usr/include/boost/thread/pthread/mutex.hpp:111: boost::mutex::~mutex(): Assertion `!res' failed.
> Aborted (core dumped)

When i run it again:

> $ dogecoind -testnet
> Error: To use dogecoind, or the -server option to dogecoin-qt, you must set an rpcpassword in the configuration file:
> /home/serveruser/.dogecoin/dogecoin.conf
> It is recommended you use the following random password:
> rpcuser=dogecoinrpc
> rpcpassword=ALX3AS271TcKsqAun449v4nfAkkVeJvSKPGh95t8WkUt
> (you do not need to remember this password)
> The username and password MUST NOT be the same.
> If the file does not exist, create it with owner-readable-only file permissions.
> It is also recommended to set alertnotify so you are notified of problems;
> for example: alertnotify=echo %s | mail -s "Dogecoin Alert" admin@foo.com
> 
> Error: 

and when i run it a 3rd time i get:

> $ dogecoind -testnet
> Error: To use dogecoind, or the -server option to dogecoin-qt, you must set an rpcpassword in the configuration file:
> /home/serveruser/.dogecoin/dogecoin.conf
> It is recommended you use the following random password:
> rpcuser=dogecoinrpc
> rpcpassword=DSYRETgsBDGdTJWNhFZn5rZYZhwwxZxzPPbZSXCDfC5E
> (you do not need to remember this password)
> The username and password MUST NOT be the same.
> If the file does not exist, create it with owner-readable-only file permissions.
> It is also recommended to set alertnotify so you are notified of problems;
> for example: alertnotify=echo %s | mail -s "Dogecoin Alert" admin@foo.com
> 
> Error: 
> dogecoind: scheduler.cpp:17: CScheduler::~CScheduler(): Assertion `nThreadsServicingQueue == 0' failed.
> Aborted (core dumped)

The output of the 3rd attempt continues for every time i run dogecoind, if i remove the testnet folder in ~/.dogecoin and re-run the cycle starts again.

I'm running ubuntu 16.04 inside a virtualbox vm on a 64-bit cpu. Bitcoin, Litecoin, Zcash, Namecoin and Dash all compiled from source on the same machine run fine, i've tried re-compiling dogecoin from scratch a number of times, done a "make clean" and even removed the repo completely and tried again from scratch but still get the same results.

**Comment by rnicoll** [comment]
While it shouldn't crash on an aborted start (which is what's happening here), if you correct the error it specifies immediately after start up it should work.

Can you let me know which version of Dogecoin this is, as well? There's a more recent beta, please try that if you haven't: https://github.com/dogecoin/dogecoin/releases/tag/v1.14-beta-1

**Comment by reactionstudio** [comment]
i downloaded the beta source and compiled, it was going well until it began to compile dogecoin-qt and i get the following errors:

> /mnt/19147e71-842a-4727-a01b-78a1267804ed/github_temp/dogecoin-1.14-beta-1/src/wallet/test/crypto_tests.cpp:217: undefined reference to `boost::unit_test::decorator::collector_t::instance()'
> /mnt/19147e71-842a-4727-a01b-78a1267804ed/github_temp/dogecoin-1.14-beta-1/src/wallet/test/crypto_tests.cpp:217: undefined reference to `boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector_t&, unsigned long)'
> collect2: error: ld returned 1 exit status
> Makefile:3851: recipe for target 'test/test_dogecoin' failed
> make[2]: *** [test/test_dogecoin] Error 1
> make[2]: *** Waiting for unfinished jobs....
> qt/libdogecoinqt.a(qt_libdogecoinqt_a-guiutil.o): In function `_GLOBAL__sub_I__ZN7GUIUtil11dateTimeStrERK9QDateTime':
> /mnt/19147e71-842a-4727-a01b-78a1267804ed/github_temp/dogecoin-1.14-beta-1/src/qt/guiutil.cpp:71: undefined reference to `boost::filesystem::detail::utf8_codecvt_facet::utf8_codecvt_facet(unsigned long)'
> collect2: error: ld returned 1 exit status
> Makefile:3705: recipe for target 'qt/test/test_dogecoin-qt' failed
> make[2]: *** [qt/test/test_dogecoin-qt] Error 1
> qt/libdogecoinqt.a(qt_libdogecoinqt_a-guiutil.o): In function `_GLOBAL__sub_I__ZN7GUIUtil11dateTimeStrERK9QDateTime':
> /mnt/19147e71-842a-4727-a01b-78a1267804ed/github_temp/dogecoin-1.14-beta-1/src/qt/guiutil.cpp:71: undefined reference to `boost::filesystem::detail::utf8_codecvt_facet::utf8_codecvt_facet(unsigned long)'
> collect2: error: ld returned 1 exit status
> Makefile:3677: recipe for target 'qt/dogecoin-qt' failed
> make[2]: *** [qt/dogecoin-qt] Error 1
> make[2]: Leaving directory '/mnt/19147e71-842a-4727-a01b-78a1267804ed/github_temp/dogecoin-1.14-beta-1/src'
> Makefile:9351: recipe for target 'all-recursive' failed
> make[1]: *** [all-recursive] Error 1
> make[1]: Leaving directory '/mnt/19147e71-842a-4727-a01b-78a1267804ed/github_temp/dogecoin-1.14-beta-1/src'
> Makefile:686: recipe for target 'all-recursive' failed
> make: *** [all-recursive] Error 1

The version of dogecoin i compiled from originally was from the github repo, i vaguely remember the docs saying i needed to checkout a specific version before compiling although i may be mistaken as i cannot find this reference in the build instructions anymore.

**Comment by buzztiaan** [comment]
i -think- this is wrong libboost version

**Comment by patricklodder** [comment]
@reactionstudio please build using provided dependencies to get a working build to start with. It's easy to get non-supported versions of boost/bdb/Qt/OpenSSL. 

See [depends/README.md](https://github.com/dogecoin/dogecoin/blob/master/depends/README.md) for more info.
