### ISSUE TITLE
can NOT sync in testnet

### ISSUE THREAD

**Issue by Irvingyao** [dogecoin/dogecoin#1566]
Hi,

When I start a dogecoin node with testnet=1, it seems it can't find a valid peer to sync. So is this testnet chain still valid? or if anyone could provide me a valid node, that will be great!

`
2019-01-28 07:31:26 0 addresses found from DNS seeds
`
`
2019-01-28 07:31:26 dnsseed thread exit
`
`
2019-01-28 07:32:19 Adding fixed seed nodes as DNS doesn't seem to be available.
`

Thanks!

**Comment by Irvingyao** [comment]
> Turns out it was compiled against old libraries and crashing, it should be up again now, can you let me know if it's still problematic.

Hi,

I still can't sync in doge testnet. But doge mainnet is alright and can be synced fast.

**Comment by qqil** [comment]
@Irvingyao try to launch your node with [-addnode=<nodeip>, ....]

-addnode=testnets.chain.so
-addnode=suchdig.com
-addnode=testdoge.lionservers.de
-addnode=senatorwhiskers.com

**Comment by Irvingyao** [comment]
> @Irvingyao try to launch your node with [-addnode=, ....]
> 
> -addnode=testnets.chain.so
> -addnode=suchdig.com
> -addnode=testdoge.lionservers.de
> -addnode=senatorwhiskers.com
> 
> But, probably testnet is dead, at least i did not found any way to get coin there (no working faucets)

sad to hear

**Comment by rnicoll** [comment]
@langerhans I've just checked, my seeder is up, but seeing no DNS requests. Everything okay on your side?

@Irvingyao Try `-addnode=node.jrn.me.uk` for now, that's my own node and has 39 connections, so you should do fine from there

**Comment by langerhans** [comment]
I don't run a testnet seed. And so far I had no issues to find a node after a while but I guess my peers.dat is well stocked up 😉

**Comment by rnicoll** [comment]
I was thinking DNS, but realised I'm managing the DNS records for testnet. I've rebuilt them, but do note I get different records if I query the nameserver directly, vs from the nearest cache, and wonder if that's the problem.
