### ISSUE TITLE
Exodus Support Outreach?

### ISSUE THREAD

**Issue by rchasman** [dogecoin/dogecoin#1580]
Hey guys, it's been a while since this post:
[Exodus wallet dropping support for Dogecoin](https://support.exodus.io/article/63-dogecoin)

I couldn't find any related Issues by searching. I'm curious if there was any discussion or progress made on the "erratic Insight API" reported here? IMHO, I think regaining Exodus support would be a boon for Dogecoin.

If it's already fixed... I hope a core contributor reaches out to Exodus and tells them that they can bring Dogecoin back!

**Comment by patricklodder** [comment]
It's there now, closing this.
