### ISSUE TITLE
Invalid use of incomplete type dogecoin make

### ISSUE THREAD

**Issue by MrCryptoBillionaire** [dogecoin/dogecoin#1581]
I got issue like ivalid use of incomplete type doing 

> sudo make

```
usr/include/openssl/ec.h:1099:16: note: forward declaration of .ECOSA_SIG [aka struct ECOSA_SIG_st. typedef struct ECOSA_SIG_st ECOSA_SIG: cwrapper.cpp:79:91: invalid use of incomplete type .ECOSA_SIG [aka struct ECOSA_SIG_str if (IBN_mod_mul(sor, ecsig s, rr, order, ctx)) [ ret=-1; goto err;

 In file included from ecwrapper.h:11:0, from ecwrapper.cPP:S: usr/include/openssl/ec.h:1099:16: note: forward declaration of .ECOSA_SIG [aka struct ECOSA_SIG_st. typedef struct ECOSA_SIG_st ECOSA_SIG: [Zs:t2Ng2gSirrILsII).: EIN_binan(8064[0], r92, sig7r); 

In file included from ecwrapper.h:11:0, from ecwrapper.cPP:S: usr/include/openssl/ec.h:1099:16: note: forward declaration of .ECOSA_SIG [aka struct typedef struct ERSp75195 ECOSA_SIG; 

cwrarir,i=1::z97;2). 32. malg.use of incomplete type .ECOSA_SIG [aka struct ECOSA_SIG_str In file included from ecwrapper.h:11:0, from ecwrapper.cPP:S: usr/include/openssl/ec.h:1099:16: note: forward declaration of .ECOSA_SIG [aka struct typedef struct ECOSA_SIG_st ECOSA_SIG; 

akefile:5750: recipe for target .libbitcoinconsensus_la-ecwrapper.lo' failed .e[2]: m [libbitcoinconsensus_la-ecwrapper.lo] Error 1 .e[2]: Leaving directory Vdownloads/dogecoin/sre akefile:6726: recipe for target 'all-recursive. failed .e[1]: m [all-recursive] Error 1 .e[1]: Leaving directory Vdownloads/dogecoin/sre akefile:628: recipe for target 'all-recursive. failed eke: m [all-recursive] Error 1 ,thur.core:/downloads/dogecoin$ 
```

Also I have my terminal output sreen 
https://pasteboard.co/If9ZltX.png

**Comment by rnicoll** [comment]
It would help to know which version you're trying to compile and on what OS, but before that it might be an idea to try 1.14rc1 which is a bit more recent. Can you try the tagged `v1.14-rc-1` version please, as in https://github.com/dogecoin/dogecoin/tree/v1.14-rc-1

**Comment by MrCryptoBillionaire** [comment]
My OS is 

> ubuntu-18.04.2-live-server-amd64

and I compiled from 

> sudo git clone https://github.com/dogecoin/dogecoin

I will try with `v1.14-rc-1`. Also my OS does not has `libdb5.1` but `libdb5.3`
And some issue about `libssl` but I have `libssl`, I made 

> ./configure --with-incompatible-bdb --with-libressl

As found this solution in clossed dogecoin issues

**Comment by MrCryptoBillionaire** [comment]
So I tried with provided link but I thinks that's was the same before. The same errors 
`configure: error: Detected LibreSSL: This is NOT supported, and may break consensus compatibility!`

I made `./configure --with-incompatible-bdb --with-libressl`

And got the same errors on `make `

https://pasteboard.co/If9ZltX.png

Waiting for advices
I need to install dogecoin node using wallet futures for be able to accept automated payments

**Comment by rnicoll** [comment]
If you're actually using LibreSSL (as in it's been detected correctly), the notice about it being unsupported does really mean it's unsupported. AFAIK it doesn't support some of the cryptographic elements we need, so simply will not work.

If you're using OpenSSL and it's being incorrectly detected, it might be out of date or the install is damaged. Try re-installing the `libssl-dev` package in that case?

**Comment by MrCryptoBillionaire** [comment]
I purgen and installed again `libssl-dev`
However LibreSSL error is still availiable

https://pasteboard.co/IfiYxhJ.png

**Comment by MrCryptoBillionaire** [comment]
Anyone still can help? Any ideas?

**Comment by langerhans** [comment]
It's way easier and safer to just build all dependencies from source with the dependency builder mechanism: 

```make clean
pushd depends
make
popd
./configure --prefix=`pwd`/depends/x86_64-unknown-linux-gnu
make```
You might need to edit the prefix depending on your host triplet.

**Comment by MrCryptoBillionaire** [comment]
Okay helped install again `libssl-dev`
But you should do `libssl1.0-dev` don't know why but then works fine
If not, that does not working well
