### ISSUE TITLE
1.17-dev out of scope error

### ISSUE THREAD

**Issue by kl1059** [dogecoin/dogecoin#1582]
qt/test/addressbooktests.cpp: In function ‘void {anonymous}::TestAddAddressesToSendBook()’:
qt/test/addressbooktests.cpp:59:5: error: ‘TestChain100Setup’ was not declared in this scope
     TestChain100Setup test;
     ^~~~~~~~~~~~~~~~~
since it is unused i commented it out to complete the build FYI

**Comment by rnicoll** [comment]
Wow you are super enthusiastic - 1.17 is very much a work in progress right now, but the code in this repo even more so. If you have time to review https://github.com/dogecoin/dogecoin/pull/1546 it would help, but what's in `1.17-dev` definitely won't sync.

The code I'm working on right now is in https://github.com/rnicoll/dogecoin/tree/1.17-branding and is a lot more functional, but definitely has issues (I wouldn't expect fees to be correct, the switchover values for the softfork in 1.14 aren't set, etc.) so don't try it unless you're sure you know what you're doing.
