### ISSUE TITLE
dogecoind it's running but it doesn't show anything.

### ISSUE THREAD

**Issue by m4hdi1995** [dogecoin/dogecoin#1586]
hello, i'm running the daemon it's syncing but it doesn't show anything on terminal (blocks data, the progress ,..) i'm using Ubuntu 16.04

**Comment by rnicoll** [comment]
`dogecoind` is intended to run as a background service, it doesn't present a UI itself. Normally you'd use `dogecoin-qt` if you want a user interface, or you can interact with the `dogecoin` using `dogecoin-cli`.

There's no up to date online guide to the commands unfortunately, but https://en.bitcoin.it/wiki/Original_Bitcoin_client/API_calls_list does cover most of the commands `dogecoin-cli` supports.
