### ISSUE TITLE
 dogecoin-1.14.0-osx.dmg 'no mountable file systems'

### ISSUE THREAD

**Issue by thylacine** [dogecoin/dogecoin#1593]
### Describe the issue
Attempting to attach the latest release .dmg does not work on any OS X prior to 10.13, as it is in APFS format.
If there is a minimum supported OS X version for the official releases, it would be nice to have that listed somewhere, but I could not find such anywhere either in the release notes nor on the website. (Maybe I just missed it, in which case maybe it could be made more prominent.)
Of course, more awesome would be an official release for the older OSXes, but I understand if that would be a pain to support.

### Can you reliably reproduce the issue?
1.  Attempt to open .dmg on old system.

### Expected behaviour
Find new shiny doge app to install.

### Actual behaviour
'The disk image couldn't be opened. no mountable filesystems'

### What version of Dogecoin Core are you using?
Official 1.14.0 release.

### Machine specs:
- OS: OS X 10.11.6 (El Capitan)
- CPU: 2.66 GHz Intel Core i7
- RAM: 8Gb
- Disk size: 512GB
- Disk Type (HD/SDD): SSD

**Comment by patricklodder** [comment]
Fixed with 1.14.2

**Comment by dmontag** [comment]
FYI getting this same error with 1.14.2 on OSX 10.11.6.

**Comment by bigpianist** [comment]
Likewise!

**Comment by lefink** [comment]
i have same problem but with 1.14.2 on 10.11.6 osx version

**Comment by atefalshehri** [comment]
I download Dogecoin Core in Big Sur and mount it. Copy it to a flash drive then drop it into the Application app in El Capitan. 

Worked like a charm.

Try using the one on the attachment.
[Dogecoin-Qt.zip](https://github.com/dogecoin/dogecoin/files/5985114/Dogecoin-Qt.zip)
