### ISSUE TITLE
Unspent Txs not detected even after -rescan

### ISSUE THREAD

**Issue by uniibu** [dogecoin/dogecoin#1594]
### Describe the issue
We updated our Dogecoin core from 1.10 to 1.14 and upon updating, the wallet seemed to have rescan by itself. Once that is done and after it fully synced, we ran `getbalance "*" 1` which gave us a negative value. Running `getbalance` only with out params gives us a positive value but a wrong one, it is missing a lot of unspent inputs(about 3.8M doge). 

Troubleshooting that we did:
1. We restarted the dogecoin wallet with `-rescan`. It seems to work fine as we see `AddToWallet` on the logs. And after sometime, it finishes and it starts to sync with the latest block. `getbalance "*" 1` still gives us negative balance, and `getbalance` still gives us a wrong balance.

2. We restarted the dogecoin wallet again with `-reindex`. It finishes reindexing and this time `getbalance "*" 1` and `getbalance` both gives us a positive balance but a wrong one.

3. We restarted again with `-rescan` and same result as no. 2, positive balance but wrong one.
4. Our total balance was supposed to be more than 7.2M doge. It was only showing about 3.38M doge. We tried to run `listunspent 1 9999999  "[\"DDiXUq2LGcF29v9XE18BKvgWjZtu8bjSoW\"]"`  and it only gave us a few unspent inputs.

5. We secured first the balance that can be "seen" and sent the 3.38M doge to another external address using `sendtoaddress`, and this works fine, after sending, doing `getbalance` gives us about 1000 doge left. Our hot wallet address is https://blockchair.com/dogecoin/address/DDiXUq2LGcF29v9XE18BKvgWjZtu8bjSoW In which you can see that it still has a balance of 3.88M doge and you can also see that we sent out 3.38M doge to another address. Given the fact that we where able to send it, just means that the address is ours, and doing `validateaddress` also says `ismine:true`.

6. Now we are on the last straw of our patience, and we'd like to try to simply delete the blocks and chainstate folder and try to start it from that.  If you guys have another suggestion, feel free to comment.

### Expected behaviour
It should give the correct balance after `-reindex` and `-rescan`

### Actual behaviour
It gave us wrong balance

### What version of Dogecoin Core are you using?
https://github.com/dogecoin/dogecoin/releases/tag/v1.14.0

### Machine specs:
- OS: Ubuntu 18.04.1 LTS
- CPU: Intel(R) Xeon(R) CPU E5-1660 v3 @ 3.00GHz
- RAM: 125G
- Disk size: 4TB
- Disk Type (HD/SDD): HD

**Comment by rnicoll** [comment]
It's not a problem I've seen myself, so it's hard to be sure where to start with this, but I'll see if I can generate a significantly more complex wallet on testnet to reproduce this.

**Comment by uniibu** [comment]
To update on this, deleting the blocks and chainstate folder did not worked either. So we suspect a corrupted wallet.dat file somehow since we had thousands of transactions for this wallet file.

So we ended up creating a new wallet.dat file. However, we still have about 3.9M doge left plus any balances on other addresses on the old wallet.dat file. We plan to simply dump the private keys and recover the balances, however, we have thousands of addresses and it would be great if we could simply export the private keys of addresses that has balance in them. Any suggestion would be appreciated.

**Comment by satoshi-n** [comment]
How did you fix it? i have been trying for years. all my doge is gone.

**Comment by iwhoo** [comment]
> How did you fix it? i have been trying for years. all my doge is gone.
you should delete mempool.dat  first , then rescan

**Comment by ReverseControl** [comment]
@patricklodder @rnicoll @michilumin We can close this one.
