### ISSUE TITLE
transaction is not propagated to the network

### ISSUE THREAD

**Issue by Mr23Cso** [dogecoin/dogecoin#1597]
Having trouble to send mined DOGE on testnet. Hope someone can help an old shibe?

Client 1.14
OS: macos

I'm initializing the client with: _open -a Dogecoin-Qt --args -testnet -setgenerate true 2_
then, debug console: _generate_

The mined coins do appear in the client and get credited after 241 confirmations but I'm having trouble sending them to another wallet.

Transaction Example:

Status: 144 confirmations
Date: 12.07.19 08:25
To: 2NFy8J5AhD6uQ6GfSiT48bQ46ona4oDSwJz
Debit: -100.00000000000 kDOGE
Transaction fee: -0.00200000000 kDOGE
Net amount: -100.00200000000 kDOGE
Transaction ID: 9f5fc8164827f8d88c7ef8faf1d0e025b22a3d24bddfd35886e73346727cce3d
Transaction total size: 1328 bytes
Output index: 1

The transaction does not appear in the blockchain despite having been confirmed 144 times.
What am I doing wrong?

**Comment by Mr23Cso** [comment]
Heres another example: 

Status: 6 confirmations, broadcast through 4 nodes
Date: 12.07.19 14:54
To: nXNKKUTd169qKw5uNzbMfGiEhgiLcc6K4P
Debit: -50.00000000 DOGE
Transaction fee: -1.00000000 DOGE
Net amount: -51.00000000 DOGE
Transaction ID: 9ecafeecc8dc89948a33ea4728d55d6ed5f970abe2fc2aa5d943a6fcd5ca90f5
Transaction total size: 225 bytes
Output index: 0

**Comment by rnicoll** [comment]
How are you checking it's on the network? Specifically, if it's `chain.so`, it's because they need to upgrade their client, rather than your end.

**Comment by Mr23Cso** [comment]
Hi, yeah I was checking on chain.so. Didn’t know they are running an old client. Thanks for clarifying. Guess we need to update our client too since the coins didn’t reach my wallet either

**Comment by rnicoll** [comment]
I had exactly the same problem last night, which is how I know. It only affects their testnet client, so if you see it in production do let me know, but chasing them to upgrade now.
