### ISSUE TITLE
importaddress error with v1.10.0 regtest address

### ISSUE THREAD

**Issue by chrisc93** [dogecoin/dogecoin#1609]
### Describe the issue
So I am upgrading to the latest version of dogecoin-core and I am having issues importing a watch only address that was created in v1.10.0. I have only tried this in regtest mode. I think it might be related to the soft-fork. But maybe there is a way I can get these old addresses imported into the new version wallet?

### Can you reliably reproduce the issue?
Yes
#### If so, please list the steps to reproduce below:
1. run `dogecoin-cli importaddress nWcHz8LoDaqvyRsUoV96Qze9eGnDFmFiKF "change" false`

### Expected behaviour
Address is successfully imported as watch-only 

### Actual behaviour
I get this error code:
```
error code: -5
error message:
Invalid Dogecoin address or script
```
### What version of Dogecoin Core are you using?
v1.14.0

**Comment by chrisc93** [comment]
@rnicoll Do you know why this is happening?

**Comment by rnicoll** [comment]
I'm mostly in awe and confusion at what you're trying to achieve. You've... got a regtest account? That's... only intended for regression testing, hence the name.

**Comment by chrisc93** [comment]
@rnicoll right. This is only being run for a regression test. I wanted to run my regtests to be sure the code I have for importing addresses works. If it passes regtests, then I see no reason why it would fail in the mainnet. Did anything with regtest address creation change in new release?

**Comment by khosro** [comment]
@chrisc93 , i have the same problem with all version 1.14.* .
Have you ever know what changed since version 1.14.*? Or any workaround?
