### ISSUE TITLE
configure: error: PKG_PROG_PKG_CONFIG macro not found. Please install pkg-config and re-run autogen.sh

### ISSUE THREAD

**Issue by love386** [dogecoin/dogecoin#1610]
ubuntu 16.04
dogecoin-1.14.0
![image](https://user-images.githubusercontent.com/45838695/65383983-1d957600-dd4f-11e9-8a9c-565a4734f8ed.png)
![image](https://user-images.githubusercontent.com/45838695/65383984-25551a80-dd4f-11e9-9663-4c14553687ac.png)

**Comment by FyreDemonyte** [comment]
This is referring to the pkg.m4 macro file that is part of the pkg-config package. 

You'll need to determine the location of the file (if it exists), and make sure it's defined in the environment.

Refer to the answer here: 

https://askubuntu.com/questions/468661/how-to-fix-pkg-prog-pkg-config-command-not-found-error

**Comment by love386** [comment]
Thank you, there are other problems, I have installed openssl and libssl-dev, but still prompted configure: error: openssl not found

**Comment by love386** [comment]
![image](https://user-images.githubusercontent.com/45838695/65385026-15900300-dd5c-11e9-8c97-e66dc104573d.png)

**Comment by rnicoll** [comment]
Can you try `make distclean` to clear out everything, then redo from `autogen.sh` first? Basically I have no idea though

**Comment by love386** [comment]
ok

**Comment by love386** [comment]
root@8ad8ac3aa28b:~/dogecoin# 
root@8ad8ac3aa28b:~/dogecoin# 
root@8ad8ac3aa28b:~/dogecoin# make distclean
make: *** No rule to make target 'distclean'.  Stop.
root@8ad8ac3aa28b:~/dogecoin#

**Comment by rnicoll** [comment]
Hmmm. I mean the other thing that occurs is you're on a very old Ubuntu, but I don't think it should be too old :-/

Are all the dependencies from https://github.com/dogecoin/dogecoin/blob/master/doc/build-unix.md#dependency-build-instructions-ubuntu--debian installed?

**Comment by love386** [comment]
I am using the system of ubuntu16.04

**Comment by love386** [comment]
The dependencies in the link are installed.

**Comment by FyreDemonyte** [comment]
Ya start fresh. maybe even clone a new copy of the branch, otherwise do :

make distclean && git clean -fd && ccache -Cc

Then try again.

Also make sure you have openssl installed with `dpkg -l|grep libssl

or install: https://ubuntu.pkgs.org/16.04/ubuntu-updates-main-amd64/libssl-dev_1.0.2g-1ubuntu4.15_amd64.deb.html

**Comment by love386** [comment]
Thank you

**Comment by ReverseControl** [comment]
@patricklodder @rnicoll @michilumin Close this one.
