### ISSUE TITLE
when fork to enable BIP-65

### ISSUE THREAD

**Issue by ruyichang** [dogecoin/dogecoin#1612]
hello, is there a precise time point or block height main net fork to enable BIP-65?

And when dose  testnet fork?

**Comment by rnicoll** [comment]
The fork conditions are similar to Bitcoin's; it will trigger when most of the miners (I think it was 75% for testnet, and 90% for production) are producing the more recently block version. This mostly requires that miners update to the recent 1.14 release (ideally 1.14.1, which is currently only available as source code, but is a tagged release in this repository).

I believe testnet has forked already.

**Comment by ruyichang** [comment]
thank you
