### ISSUE TITLE
send tx failed, reture insufficient priority

### ISSUE THREAD

**Issue by yu-qingyun** [dogecoin/dogecoin#1613]
hi,i send first tx,success.but i send secound tx fialed.return error is insufficient priority.

**Comment by rnicoll** [comment]
@langerhans has identified a bug in the transaction fee logic in 1.14, it sounds like this might be the same thing? It would help to know what version you're using, to be sure, though.

If it is the bug we've seen, a fix is being worked on.

**Comment by yu-qingyun** [comment]
thanks for your ask,what version can we use??

**Comment by yu-qingyun** [comment]
thanks for your answer,what version can we use??

**Comment by yu-qingyun** [comment]
my version is Dogecoin Core 1.14 Beta 1

**Comment by rnicoll** [comment]
https://github.com/dogecoin/dogecoin/pull/1615 may be the answer to this, we'll hopefully confirm if it fixes the bug we know about, and do a release, shortly

**Comment by yu-qingyun** [comment]
i got it,thanks,if you release a new version,please tall me in this issue.

**Comment by yu-qingyun** [comment]
hi,has the issue been solved about the version of Dogecoin Core 1.14.2

**Comment by yu-qingyun** [comment]
hi,my node had upgrade to the version of Dogecoin Core 1.14.2，but the issue still exists.i sand first tx and i got the utxo of change，I use the utxo to structural tx，then send it,but i got 'insufficient priority'.

**Comment by rnicoll** [comment]
What do you mean by "structural tx"?

**Comment by yu-qingyun** [comment]
sorry,What I want to say is to create a tx

**Comment by ReverseControl** [comment]
@yu-qingyun Was issue resolved in later versions of dogecoin?

**Comment by ReverseControl** [comment]
I am closing this as outdated. If this issue persists in the latest version of doge, which seems highly unlikely, we can reopen this one.

@yu-qingyun For future reference, enough information about this issue needs to be provided so we may diagnose it and fix it.
