### ISSUE TITLE
Dogecoin client sendtoaddress never have confirmations or appear in blockchain

### ISSUE THREAD

**Issue by MrCryptoBillionaire** [dogecoin/dogecoin#1617]
I do `sendtoaddress` via rpc of dogecoin client v1.14-rc-1 on Ubuntu

`"{\"jsonrpc\": \"1.0\", \"method\": \"sendtoaddress\", \"params\": [\"$address\",$amount] }"`

And some of my reponses returns txs however they never appear in blockchain and have 0 confirmations unless I push transaction hex in https://live.blockcypher.com/doge/pushtx/

Here is example of this transaction

`https://dogechain.info/tx/0fb6a740b8e1e19d4a3b466d590602577d35c74b38001c13fee52c04bd54b5a9`

```
stdClass Object
(
    [result] => stdClass Object
        (
            [amount] => -20.005
            [fee] => -1
            [confirmations] => 0
            [trusted] => 
            [txid] => 0fb6a740b8e1e19d4a3b466d590602577d35c74b38001c13fee52c04bd54b5a9
            [walletconflicts] => Array
                (
                )

            [time] => 1573568266
            [timereceived] => 1573568266
            [bip125-replaceable] => unknown
            [details] => Array
                (
                    [0] => stdClass Object
                        (
                            [account] => 
                            [address] => DRAXeUEhQTpCQGRuqFGhT4DbwSUzRKk2Ai
                            [category] => send
                            [amount] => -20.005
                            [vout] => 1
                            [fee] => -1
                            [abandoned] => 
                        )

                )

            [hex] => I will remove this line for security reasons
        )

    [error] => 
    [id] => 
)
```

Difference between wrong transaction and normal that wrong transaction [bip125-replaceable] => unknown
And normal is [bip125-replaceable] => no

After some transaction appear to be broke all next sendtoaddress transactions never appear in blockchain as well

Any solutions? How to avoid this?

**Comment by rnicoll** [comment]
As a first step can you try 1.14.2, as there's a bugfix for a fee calculation issue, which might help here.

**Comment by MrCryptoBillionaire** [comment]
Well
Thank you for your time and attention. You are doing a great work
I upgrated to a 1.14.2 and here I will leave small tips how do that

`dogecoin-cli stop`
thats will stop dogecoin daemon(client)
`cd dogecoin`
move to our old dogecoin folder
`git pull origin master`
get latests commits of dogecoin project. If you before 'gitted' the folder
`./autogen.sh`
`./configure`
`make`
`make install`
Standart install

**Comment by rnicoll** [comment]
Glad that worked!
