### ISSUE TITLE
Over 1 million coins lost after turning off laptop though I have wallet.dat.How to restore!

### ISSUE THREAD

**Issue by rwestbrook64** [dogecoin/dogecoin#1620]
This issue tracker is only for technical issues related to Dogecoin Core.

For general questions about Dogecoin please use one of the various communities, e.g. Reddit, IRC, Discord, etc.

#### If so, please list the steps to reproduce below:
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of Dogecoin Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by rwestbrook64** [comment]
I had my Dogecoin Core wallet up to date and had it running on my laptop. I forgot it was running while i was playing World of warcraft and when my game frozen I restarted my laptop. When I restarted my laptop and restarted my wallet everything was messed up because I turned off my wallet the wrong way. Then using my backed up wallet.dat I synced my wallet to learn it was now saying all my dogecoins were sent to another address way back in 2018. How could this be when I just had my coins in my wallet? How do I correct this? I had over 1 million coins.

**Comment by Wlinc** [comment]
@rwestbrook64 it would be helpful to know your public addresses(s).

**Comment by rnicoll** [comment]
My hunch is you've got a backup that doesn't contain recent keys, so you're seeing the funds send to a change address, but it's hard to tell.

Do you have the original broken `wallet.db`? There's a few things we can try on it, if so.

**Comment by Emobe** [comment]
`For general questions about Dogecoin please use one of the various communities, e.g. Reddit, IRC, Discord, etc.`

**Comment by langerhans** [comment]
No need to post this on such an old issue :P Gonna close here for inactivity.

**Comment by KrishPat1** [comment]
> This issue tracker is only for technical issues related to Dogecoin Core.
> 
> For general questions about Dogecoin please use one of the various communities, e.g. Reddit, IRC, Discord, etc.
> 
> ### Describe the issue
> ### Can you reliably reproduce the issue?
> #### If so, please list the steps to reproduce below:
> 
> ### Expected behaviour
> Tell us what should happen
> 
> ### Actual behaviour
> Tell us what happens instead
> 
> ### Screenshots.
> If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.
> 
> ### What version of Dogecoin Core are you using?
> List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.
> 
> ### Machine specs:
> * OS:
> * CPU:
> * RAM:
> * Disk size:
> * Disk Type (HD/SDD):
> 
> ### Any extra information that might be useful in the debugging process.
> This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

Hello, were you able to fix it? I have emailed you just in case you need any assistance with this issue.

**Comment by pythonboy20** [comment]
@rwestbrook64 
did you het back your dogecoin wallet? I can solve your problem
so if you want help to get your lost doge wallet, send me email:
[[anywalletrecovery@gmail.com]

**Comment by mclauncherlinux** [comment]
> @rwestbrook64
> did you het back your dogecoin wallet? I can solve your problem
> so if you want help to get your lost doge wallet, send me email:
> [[[anywalletrecovery@gmail.com](mailto:anywalletrecovery@gmail.com)]

Scammer XD
