### ISSUE TITLE
Dogecoin: Spot's Version

### ISSUE THREAD

**Issue by mr-word** [dogecoin/dogecoin#1622]
Dogecoin: Spot's Version
---

Spot thinks Dogecoin can validate 100k+ tps because [Dogecoin transactions are logically sequential but validate in logarithmic time](https://word.site/2019/11/25/rtxi/).

### what

Time is running low! A few fat cats had a clever plan. They sent out their minions to run circles around the neighborhood dogs, making them all confused and angry at each other.

Spot used to play chase with lots of cats, and he knows how they think. They hate the idea of being outsmarted.

**Spot's 3 Requests**

* Commit to sunset segwit and P2SH on a reasonable timeframe
* Remove the block limit immediately (4 weeks)
* Resync with BSV upstream until Satoshi's opcodes are implemented and rigorously verified

Or else,

* Dogecoin SV forks off of Dogecoin and disables segwit/P2SH soft fork validation on **December 28, 2019**.

## Expected behaviour
The dogecoin chain merkelizes all data necessary for verification and has no block limit. 

## Actual behaviour
The dogecoin chain currently snips signatures and p2sh data and has a block limit. Additonally, some opcodes appear disabled.

**Comment by mr-word** [comment]
(reserved comment)

**Comment by langerhans** [comment]
Cute story, but I have no idea what the issue here is. We don't even have segwit and you ask us to disable it?
Please outline what issue you're trying to solve here, and make sure those issues are of technical nature cause I'm not in the mood to start a debate about Satoshis intentions as they have literally zero relevance to Dogecoin.

**Comment by ReverseControl** [comment]
@patricklodder @rnicoll @michilumin Close this.
