### ISSUE TITLE
Wallet 1.14.2 and 1.14.0 do not leave 0 confirmations.

### ISSUE THREAD

**Issue by cosmo9able** [dogecoin/dogecoin#1624]
I am trying to use the new wallet (version 1.14.2), but when I send dogecoin to other addresses txid is not recognized in the block explorers and also does not start the configuration, it is infinitely 0 confirmations, it has been 5 days. 0 confirmations, the fee charged was 1 DOGE, I'm using dogecoind and dogecoin-cli is there any way to fix this problem? I really want to use the doge wallet in this version, I've tried 1.14.0 too, and the bug also happens the same way.

Portuguese (My native language)
Estou tentando usar a nova carteira (versão 1.14.2), porém quando eu envio dogecoin para outros endereços a txid não é reconhecida nos exploradores de blocos e também não inicia a configuração, fica infinitamente em 0 confirmações, ja faz 5 dias que esta em 0 confirmações, a taxa cobrada foi de 1 DOGE, estou usando dogecoind e dogecoin-cli existe alguma forma de corrigir esse problema? eu quero muito usar a carteira de doge nessa versão, , ja tentei também a 1.14.0, e o bug também acontece da mesma forma.

**Comment by wcostaprijo** [comment]
I have this same error.

**Comment by rnicoll** [comment]
Do you have an example transaction hash? Definitely 1.14.0 had a problem relaying transactions so won't be better,

If you can extract the raw transaction from `dogecoin-cli` using `getrawtransaction` that would be even better.

**Comment by ReverseControl** [comment]
@cosmo9able @wcostaprijo Please gives us an update on this.

**Comment by patricklodder** [comment]
The most likely cause of this is a stuck parent transaction in the wallet.

The steps to resolve (from [the 1.14.6 release discussion](https://github.com/dogecoin/dogecoin/discussions/3054#discussioncomment-5292130)) are as follows and should be performed before upgrading to 1.14.5 or later:

#### Purging all pending wallet transactions automatically

To automatically purge all pending transactions, restart `dogecoind` or `dogecoin-qt` once, with the `-zapwallettxes=1` option, eg:

```console
$ dogecoind -zapwallettxes=1

> Dogecoin-Qt.exe -zapwallettxes=1
```

#### Manually searching for and removing pending wallet transactions

To manually check and remove pending transactions, use the `listtransactions` RPC call, either using dogecoin-cli, or from the Debug console. Look for transactions with 0 confirmations, or filter them with `jq`, like so:

```console
$ dogecoin-cli listtransactions "*" 100000 0 | jq -r '.[] | select(.confirmations == 0)'
{
  "account": "",
  "address": "D9gEMMtCNT5GHvFvSQMjfSnbZFRRUjjDPX",
  "category": "send",
  "amount": -420.69,
  "vout": 0,
  "confirmations": 0, <---- this means the transaction has never been mined
  "trusted": true,
  "txid": "47a84a30159ed15d36e91ef6ae161fe5254aa9c2c906dc614d5aba03659e65ed",
  "walletconflicts": [],
  "time": 1678343421,
  "timereceived": 1678343421,
  "bip125-replaceable": "no",
  "abandoned": false <---- this means the transaction is stuck and has not been purged from the wallet
} 
```

These transactions can then be removed with `abandontransaction` individually, if desired:

```console
$ dogecoin-cli abandontransaction 47a84a30159ed15d36e91ef6ae161fe5254aa9c2c906dc614d5aba03659e65ed
```

#### Post-upgrade checks

After abandoning transactions, it should be safe to update the software to version 1.14.6. If you want to double check after you upgraded the software, you can mimic the 1.14.2 dust relay rules by setting the hard dust limit when starting dogecoind or dogecoin-qt with `-harddustlimit=1`. This sets the minimum amount of DOGE in a transaction output to 1.0 and rejects any transactions that attempt to transfer lower amounts. Alternatively, you can run the software once while not connected to the internet. 1.14.6 ships with a new `liststucktransactions` RPC method that can be used to check if there are still stuck transactions in the wallet:

```console
$ src/dogecoin-cli liststucktransactions
[]
```

-----

If this did not resolve this issue, please leave a comment here and we'll reopen it.
