### ISSUE TITLE
Faucet Testnet or some doges...

### ISSUE THREAD

**Issue by Droppix** [dogecoin/dogecoin#1634]
Hi,

I'm desperately looking for "faucet testnet" to get some DOGES for my tests, would you know of one? 
Or if someone could send me to the address: 2NEVg7yQyW5n8Q1hBSUK57H6q43LZVqjFiS

Thanks

**Comment by Vertian** [comment]
Sent.

**Comment by Droppix** [comment]
many thanks...:)
