### ISSUE TITLE
Virus detection

### ISSUE THREAD

**Issue by tunisiano187** [dogecoin/dogecoin#1643]
### Description
The releases are detected as virus on 17/71 tests

### Can you reliably reproduce the issue?
https://www.virustotal.com/gui/file/dc8cd7efd1318b293c473fbe4ab5aac994e78b9e379aa03fb166cee352f06e28/detection/f-dc8cd7efd1318b293c473fbe4ab5aac994e78b9e379aa03fb166cee352f06e28-1596319959

### Expected behaviour
Not detected

### Screenshots.
https://www.virustotal.com/gui/file/dc8cd7efd1318b293c473fbe4ab5aac994e78b9e379aa03fb166cee352f06e28/detection/f-dc8cd7efd1318b293c473fbe4ab5aac994e78b9e379aa03fb166cee352f06e28-1596319959

**Comment by rnicoll** [comment]
If you read the report, it's saying it contains a cryptocurrency miner. There's not really a lot we can do about VirusTotal deciding that cryptocurrency miners are virii

**Comment by tunisiano187** [comment]
Thank you for your answer, i'll add it to the description
