### ISSUE TITLE
Dogecoin-qt doesn't work on Ubuntu 20.10

### ISSUE THREAD

**Issue by MrCyjaneK** [dogecoin/dogecoin#1647]
# Describe the issue

Dogecoin-qt doesn't work on Ubuntu 20.10.
When I try to run it I get following output:

```
cyjan@ubudubu ~> dogecoin-qt
dogecoin-qt: error while loading shared libraries: libprotobuf.so.17: cannot open shared object file: No such file or directory
```

Steps to reproduce:

1. `sudo do-release-upgrade --devel-release` if running ubuntu 20.04
2. run `dogecoin-qt`

### Expected behaviour
Dogecoin-qt should work

### Actual behaviour
It doesn't

### What version of Dogecoin Core are you using?
Latest v1.14.2
### Machine specs:
- OS: Kubuntu 20.04 Groovy Gorilla (development branch) x86_64

**Comment by MrCyjaneK** [comment]
Self-compiling the wallet have resolved the issue

**Comment by rnicoll** [comment]
Thanks - I was going to say 1.14.3 may also be better, but glad self-compiling worked.
