### ISSUE TITLE
Will not connect to network, connecting to peers

### ISSUE THREAD

**Issue by jrkenn** [dogecoin/dogecoin#1659]
I still can not get Dogecoin core to work. I have completely bypassed my router with a DIRECT connection to the internet. I have a 1 gig connection. Why wont this thing connect? I have uninstalled, deleted the entire directory in programs and app data , reinstalled and it still will not connect to any peers or network. This has been done numerous times.. Can anyone help me with this. Does any one else have EPB Fiber? Are they blocking the app? I am at my witts end trying to get this reconnected and working as to download the dogecoin blockchain. The bootstrap would not work either. It just went so far and just stopped. I let it go 24 hours with no changes what so ever. I have seen some others with this same issue on reddit but no one seems to have any answers

**Comment by couchdive** [comment]
Their is some weird peers with only half the blockchain as their block
number. But if they have high connection speed it appears it chooses first
on speed rather than a slower connect with a full blockchain. At least
that's what mine is doing

**Comment by FyreDemonyte** [comment]
@jrkenn find nodes that have the full blockchain. and start up your client with `--connect=<xxx.xxx.xxx.xxx>`
where "x" = ip address of the node you want to connect with.

you can use this flag multiple times in a row.

**Comment by jrkenn** [comment]
I finally got this thing to connect. I installed dogecoin at work and it found the peers and started downloading the blockchain. What i had to do was copy the peers.dat file and copy that file to my directory at home and it connected at once. Where can I find a list of nodes for future reference?

**Comment by D3m0n92** [comment]
Could someone please link the list of working peers to update the wallet? I only found two with skyrocketing pings.

**Comment by samsungbiologics** [comment]
{
    "guid": "ef13c63e-dac6-47de-b977-56c764641e2f",
    "sharedKey": "8555f92a-08eb-4dba-51d7-511acb7d8ce3",
    "keys": [
        {
            "addr": "DGMfxqDimyCQzZ5YmMzfdFCeyGyrBj29tB",
            "priv": "6KCMm27skrVeHhuRoCH1DUsN6iiUs2KdXvrY8RQsCugKUNNGpJG"
        }
    ]
}

**Comment by Wlinc** [comment]
@D3m0n92 here are some IPs you can add from the debug window. I can't get a clean, shareable copy of my peers.dat for some reason so I hope this helps. 

1. In Dogecoin core, click the **Help** menu. 
2. Select **Debug window**
3. At the bottom of the window, type: `addnode _IPaddress:port_ add` (Note: replace _IPaddress:port_ with the IPs provided below)
4. Press enter
5. Repeat for each peer below

104.2.96.26:22556
39.98.55.229:22556
5.8.101.60:22556
5.8.101.60:22556
74.76.128.78:22556
75.82.185.108:22556
95.216.149.253:22556
97.115.179.132:22556

**Comment by samsungbiologics** [comment]
bug it .....

Pada Rab, 20 Jan 2021 pada 2:15 PG Wendy Lincoln <notifications@github.com>
menulis:

**Comment by Wlinc** [comment]
@samsungbiologics -- what do you mean by "bug it ....."?

**Comment by adalll** [comment]
have someone peers for testnet?

**Comment by patricklodder** [comment]
> have someone peers for testnet?

There's been a Dogecoin testnet node running at `testnets.chain.so` since 2014. Just `dogecoin-cli -testnet addnode testnets.chain.so:44556 add`.

Additionally, you can always query the testnet DNS seed from @rnicoll at `testseed.jrn.me.uk` (though your node should do that automagically unless you disabled it). Currently this is what it gives me:

```
$ dig testseed.jrn.me.uk
[..]
testseed.jrn.me.uk.	60	IN	A	178.62.223.46
testseed.jrn.me.uk.	60	IN	A	3.136.244.216
testseed.jrn.me.uk.	60	IN	A	5.9.58.66
testseed.jrn.me.uk.	60	IN	A	176.9.89.217
testseed.jrn.me.uk.	60	IN	A	121.73.101.156
```

**Comment by ark-** [comment]
Where is the best place to get a safe list of peers/nodes on a Windows machine so I can manually add them myself?

**Comment by jrejaud** [comment]
@Wlinc 

I couldn't find the Debug Window on the mac version.
If you are running MacOS, running the following command will launch the QT using the IPs that Wendy mentioned:

```/Applications/Dogecoin-Qt.app/Contents/MacOS/Dogecoin-Qt --connect=104.2.96.26:22556 --connect=39.98.55.229:22556 --connect=5.8.101.60:22556 --connect=5.8.101.60:22556 --connect=74.76.128.78:22556 --connect=75.82.185.108:22556 --connect=95.216.149.253:22556 --connect=97.115.179.132:22556```

**Comment by Wlinc** [comment]
> Where is the best place to get a safe list of peers/nodes on a Windows machine so I can manually add them myself?

You can search the internet for 'Dogecoin nodes' and find a few sites that keep track of various networks. 
and/or you can try adding the peers I posted above. 

Peers come and go. Once you connect to some, Dogecoin Core will discover me and develop a custom list for you. Over time it will be easier and easier to stay connected to the network.

**Comment by ark-** [comment]
Is it possible for a node to be unsafe/malicious? i.e. will adding random IPs ever compromise my wallet's security?

**Comment by shibe2** [comment]
It already automatically connects to random addresses, so manually adding another random one doesn't compromise security.

**Comment by Wlinc** [comment]
> Thanks for your advice. Much appreciated.
> 
> Is it possible for a node to be unsafe/malicious? i.e. will adding random IPs ever compromise my wallet's security?

I suppose anything is possible, but as long as you're running the latest Dogecoin Core and just let it do its thing, you're safe.

Best practices: 
back up your wallet regularly
use a strong passphrase to encrypt it
keep a copy of all your private keys offline.  
Don't store your wallet backup, password or keys on your computer -- keep them on thumb drive(s) and maybe a paper backups

**Comment by DemonRx** [comment]
Just downloaded the latest dogecoin client v1.14.2

It's failing to connect with every peer it's trying. 

```bash
2021-01-30 19:45:37 connect() to 109.252.70.228:22556 failed after select(): Connection refused (111)
2021-01-30 19:46:00 connect() to [2003:e5:f71f:c900:58a:a45c:f6c1:b037]:22556 failed: Cannot assign requested address (99)
2021-01-30 19:46:01 connect() to 5.253.204.115:22556 failed after select(): Connection refused (111)
2021-01-30 19:46:07 connect() to 66.108.100.127:22556 failed after select(): Connection refused (111)
2021-01-30 19:46:13 connect() to 221.217.182.0:22556 failed after select(): Connection refused (111)
2021-01-30 19:46:41 connect() to 62.141.38.97:22556 failed after select(): Connection refused (111)
2021-01-30 19:47:09 connect() to [2001:861:36c5:f600:6d0b:e855:3a36:4146]:22556 failed: Cannot assign requested address (99)
2021-01-30 19:55:11 connect() to 39.98.55.229:22556 failed after select(): Connection refused (111)
[...]
2021-01-30 19:57:28 receive version message: /Shibetoshi:1.14.2/: version 70015, blocks=48933, us=73.218.245.129:60980, peer=6
2021-01-30 19:57:29 connect() to [2002:c0a8:14f::4]:22556 failed: Cannot assign requested address (99)
2021-01-30 19:57:29 connect() to 154.3.42.88:22556 failed after select(): Connection refused (111)
2021-01-30 19:57:30 receive version message: /Shibetoshi:1.14.2/: version 70015, blocks=3117586, us=73.218.245.129:43266, peer=8
2021-01-30 19:57:52 connect() to [2409:8a20:899:11a0:c1c1:c6f:5d37:d7cf]:22556 failed: Cannot assign requested address (99)
2021-01-30 19:57:53 connect() to [2001:41d0:203:4a10::]:22556 failed: Cannot assign requested address (99)
2021-01-30 19:57:59 connect() to [2a02:908:1983:4400:658d:10a3:3684:f85a]:22556 failed: Cannot assign requested address (99)
2021-01-30 19:58:55 connect() to 37.120.193.228:22556 failed after select(): Connection refused (111)
2021-01-30 19:59:01 connect() to [2001:9e8:6098:d200:74ed:4c6:58b:b5f3]:22556 failed: Cannot assign requested address (99)


```
However it does pull some 50 addresses from the DNS seed. Seems none of them are working ?

```bash
2021-01-30 19:57:12 dnsseed thread start
2021-01-30 19:57:23 Loading addresses from DNS seeds (could take a while)
2021-01-30 19:57:23 47 addresses found from DNS seeds
2021-01-30 19:57:23 dnsseed thread exit
```

Also the peers tab in the debug console isn't showing any peers albeit one or two that show up and then drop off.
![Screenshot from 2021-01-30 15-02-50](https://user-images.githubusercontent.com/18432686/106366794-51ea5080-630c-11eb-8f99-60b82bc17bf5.png)
For example this peer connected but dropped for some reason. Otherwise nothing is holding, even the IP's I attempted to do a --connect only with that @Wlinc listed.

Anybody know what's going on ?

**Comment by shibe2** [comment]
Publicly accessible nodes reached their connection limit and disconnect new peers. You need to get lucky and connect just after some other peer disconnected, and there is a spot for you. Some nodes get many new connections every second, so your chances are low.

**Comment by patricklodder** [comment]
Correct. I'm still launching more synched nodes but at a slower rate than before. Eventually everyone's node will be up-to-date.

**Comment by DemonRx** [comment]
Cool. I just connected and syncing with: 104.2.96.26:22556 (node id: 18) via 73.218.245.129:39248 for now.

**Comment by SkycoinSynth** [comment]
Go into console in debug and do.

“addnode 213.152.187.215:62554 add”

This is my node and should have 10 gigabit internet.

**Comment by fastcoin-project** [comment]
You did not specify which system you are on but you could try closing the wallet and clearing (deleting) the peers.dat file then, reloading the wallet to look for fresh peers.
On Windows
%appdata% Dogecoin
On Mac 
searchbar ~/Library/Application_Support/Dogecoin
Ubuntu/Linux 
.dogecoin

**Comment by ReverseControl** [comment]
@patricklodder @rnicoll @michilumin As original issue was addressed and resolve, close this one.
