### ISSUE TITLE
Unconfirmed transaction refusing to fall off at 3+ weeks

### ISSUE THREAD

**Issue by hobbzey** [dogecoin/dogecoin#1663]
Tried to send 94k coins using the official Android app, the app "auto-calculated" the fee, and I trusted it. Big mistake. The transaction is now unconfirmed and refuses to fall off, even though it's been 22 days.

I've made it a point to not open the Android app in these 22 days, for fear of it prolonging the 14 fall off period, and have been checking the transaction every few days with this link: 
https://blockchair.com/dogecoin/transaction/4f69933e91cc5fbfa5cc01e9228e1b89dc6fa7f16595e71cf402a37edf4b8146

What should I do? Being the Android app I can't just move to another wallet without access to the master keys...? I can't do a RBF transaction if the wallet shows a zero balance...? I'm at my wit's end, and it's been a loooong 22 day wait, please help....

**Comment by uranik777** [comment]
The oldest transactionin mempool is now from 2020-12-29 
 - https://blockchair.com/dogecoin/transaction/423fee49c86789540982c53f11610b51fc0e5104e32ac71db78e4f5bb4dc1937
It turns out that the maximum time for finding transactions will be 2021-01-26 - 2020-12-29 = 29 days. I don’t know where it was written about 14 days.

**Comment by shibe2** [comment]
Waiting is not necessary. If you create re-sending transaction with appropriate fee, you can immediately submit it to nodes running latest version of Dogecoin Core, and it will be mined soon.

Besides, stuck transactions are stored in mempools of nodes running older software. Even if we change the mempool behavior and release a new version, it will not make those nodes to drop stuck transactions.

**Comment by ReverseControl** [comment]
@patricklodder @rnicoll @michilumin Close this one.
