### ISSUE TITLE
My dogecoin is moved out on 25th Jan.

### ISSUE THREAD

**Issue by maloysis** [dogecoin/dogecoin#1665]
I had my dogecoins in dogechain wallet since 2018. 
2 days back all my dogecoins are removed from my wallet. 
When I check the transaction details, it's mentioned as " appeared in block". 
It also shows link for raw transactions.
I do not understand any of this. Can someone help me to know what has happened? 
Is there any way to get back my dogecoins.
Is there any customer support number for dogechain.info site?
Please help.

**Comment by langerhans** [comment]
This is not a support forum for dogechain.info., sorry. Make sure to use secure passwords and ideally 2FA if you're dealing with cryptocurrencies.
