### ISSUE TITLE
Windows Build instructions hyperlink leads to a 404 error

### ISSUE THREAD

**Issue by roschler** [dogecoin/dogecoin#1667]
The link to the Wnidows Build instructions gets a 404 error:

https://github.com/dogecoin/dogecoin/blob/master/doc/build-msw.md

OSX and Linux links work fine.

Doge not much wow for Windows? :)

**Comment by slightlyskepticalpotat** [comment]
Looking through my threads, I noticed this is fixed now. @patricklodder this issue should probably be closed.

**Comment by ReverseControl** [comment]
Also, see https://github.com/dogecoin/dogecoin/blob/1818c33a548ef3515aaf0a1b24e6a943dc9eaac7/doc/build-windows.md.

@patricklodder @rnicoll @michilumin We can close this one.
