### ISSUE TITLE
I was scammed

### ISSUE THREAD

**Issue by giogio6899tw** [dogecoin/dogecoin#1670]
DNovLyaNQwBuTLjMrFeKQvBr4tupfcYhE4   Is a scam wallet address ,

He used Musk's name cheat DOGECOIN ,The following is :

<-link removed->

I was cheated 100,000 DOGECOIN ........Can I find it back ?

**Comment by langerhans** [comment]
I have removed that link. Also if you send your coins somewhere you can not reverse the transaction. Sorry that you got scammed, but there is nothing we can do here.
