### ISSUE TITLE
Help, Dogecoin core not connecting and I've done something silly

### ISSUE THREAD

**Issue by dogenoob1** [dogecoin/dogecoin#1671]
Heya,

I transferred coins to my dogecoin core wallet- and it hasn't synced. 
It's trying to find peers, and has been for 24h. 

I dont have any interest in using it, and meant to transfer it to my other wallet. 
I have an online doge wallet and tried to imported via my private key....
Although it hasnt synced so it's saying there's nothing to import...

Below are images, thanks so much for any imput!
It's been stuck at 0.003% for 24h.

<img width="859" alt="Screenshot 2021-01-29 at 23 41 40" src="https://user-images.githubusercontent.com/78241493/106341967-00ec4500-6297-11eb-9d8c-b1f35aa03f62.png">

**Comment by mooseburger** [comment]
Yeah, I'm having the same problem, but I have some of the blockchain already. It's 3 years and 42 weeks behind, but I'm getting no connections to the Dogecoin network.

**Comment by dogenoob1** [comment]
Hey,
I solved this by:

Dogecoin> help>de-bug

Debug then press consol

Here you type in, walletpassphrase "your wallet passpharse" 600

if you know the wallet that the coins are deposited into, Dumkey "wallet
address"

It should then provide you with a key you can use this to get your coins in
your wallet.
I chose Exodus at the recommendation of a friend and it worked seamlessly

You dont have to sign up and you find dogecoin, and once you're on the
dogecoin screen press the three dots in the top right hand corner

import wallet
use your key to get your coins.

I hope this helps, Im very new to this so any technical questions you have
I wont be good at answering, but I managed to do this process haha

Good luck!

**Comment by mooseburger** [comment]
Thanks! Ended up following the advice here though to sync up the blockchain and restore usability to Dogecoin Core: https://www.reddit.com/r/dogecoin/comments/l8b7d4/dogecoin_blockchain/

**Comment by dogenoob1** [comment]
My internet is so slow, that would have still taken days! Glad you found a
way, good luck :)

**Comment by MyNameIsBaron** [comment]
There is solution! Here is my post on redit: https://www.reddit.com/r/dogecoin/comments/mw6by9/dogecoin_core_syncing_for_ages_there_is_solution/

**Comment by ReverseControl** [comment]
@patricklodder @rnicoll @michilumin Close this one.

**Comment by michilumin** [comment]
Note to anyone who may be coming through this:   The vast majority (pretty much all) links that are posted and claim to "recover your lost dogecoins" are scams trying to do the opposite.

**Comment by hastiAu** [comment]
@michilumin but for me honestly , he recover mine 
I have any documents

**Comment by henrysabah226-star** [comment]
i have a problem with my dogecoin in wallet, i lost over $50,000 last week trying to investment not knowing i was investing with a scammer when the times comes for me to withdrawal my savings it was no where to be found then a friend ask me to contact SYLVESTER BRYANT at Yt7cracker@gmail. com if i am serious in getting all what has been stolen from me , After contacting him i follow his procedures and instruction after some time he was able to recover back my stolen dogecoin and also apprehend the scammer
