### ISSUE TITLE
Provide a bootstrap for users

### ISSUE THREAD

**Issue by DemonRx** [dogecoin/dogecoin#1673]
I wish to suggest that a bootstrap be provided for users to download, as this would be more attractive for new users coming into the community.

Matter of question is where would be the best cloud location to host it ? And someone that could also keep it updated every 6 months or so.

Open to ideas and discussion.

**Comment by FyreDemonyte** [comment]
I'm aware of this currently hosted file: https://bootstrap.sochain.com/, however it's not up-to-date.

And there is prior issue #898 referencing this. but either way, whoever is hosting that link hasn't updated the bootstrap. 

Let's discuss.

**Comment by IncognitoJam** [comment]
A more recent bootstrap is available, being seeded by the Dogecoin discord server https://dogecoin.gg/dogecoin-bootstrap-2021-01-29.torrent

**Comment by DemonRx** [comment]
Should get that posted on the main OP for bitcointalk too

**Comment by DemonRx** [comment]
> A more recent bootstrap is available, being seeded by the Dogecoin discord server https://dogecoin.gg/dogecoin-bootstrap-2021-01-29.torrent

Could you please tell me where exactly that link is available in discord please. Thanks :+1:

**Comment by IncognitoJam** [comment]
It's in the #faq channel in the official dogecoin discord server https://dogecoin.gg/invite

**Comment by DemonRx** [comment]
> It's in the #faq channel in the official dogecoin discord server https://dogecoin.gg/invite

![Screenshot from 2021-01-30 13-52-27](https://user-images.githubusercontent.com/18432686/106365281-8953ff80-6302-11eb-8b6d-e1897bcfb307.png)

Says it's lockdown ? What happened there ?

**Comment by IncognitoJam** [comment]
@DemonRx We're getting a lot of new users so the bot will kick people during influx, you can try again now

**Comment by DemonRx** [comment]
@IncognitoJam just want to point out that the torrent is technically not a "bootstrap" where a bootstrap is in the file format *bootstrap.dat* ofc I'm sure you know this. But whoever is maintaining that torrent should actually concatenate the block files within the dogecoin data directory blocks folder with:

`cat blk*.dat > bootstrap.dat`

**Comment by patricklodder** [comment]
actually, there is https://github.com/dogecoin/dogecoin/tree/master/contrib/linearize

which is > cat blk*

**Comment by IncognitoJam** [comment]
@DemonRx @patricklodder Thank you both! I knew about the `cat blk*.dat` trick but didn't realise there was a tool 😄 I think after the network calms down we can create a new bootstrap, and I'll make sure to do it the proper way

**Comment by DemonRx** [comment]
@IncognitoJam so I just ran the tool, and the bootstrap.dat file is 41gb instead of 44gb, and synced up to block 3587855 :)

Just need place to host it.

**Comment by IncognitoJam** [comment]
I have no idea where to host a 41GB file for cheap. That would cost about $0.41 for each download after the first 4TB with the provider I normally use... This is why I chose to torrent the last one 😅

**Comment by DemonRx** [comment]
I would love to torrent but the ISP decided to put a cap on the bandwidth/$ :disappointed: this year with the realization more people are at home streaming movies, etc. 

Probably the least financial impact would be to spin up a vps for around 10$/month, keeping in mind the key configuration it needs is plenty of storage to accommodate for future blockchain size, and at least 2gb of ram.  Might as well run a full node on it as opposed to hosting a bootstrap, unless you have storage on it to do both.

Otherwise I did see a couple cloud-based storage solutions that provide 100gb free space (as long as the account stays active). That probably would last a few more years, however I prefer the former as the goal is also to improve network reliability by running a full node on the vps.

**Comment by IncognitoJam** [comment]
@DemonRx I was told about a good deal on file hosting at https://www.feralhosting.com/. I've started seeding the current bootstrap on a £10 server and it's working great so far!
![image](https://user-images.githubusercontent.com/4038174/106396935-da4b1d00-6402-11eb-8825-a108c440c7f5.png)

This could be of use? They let you install things like torrent clients and databases, and also offer regular SSH/FTP file upload.

**Comment by integrate-your-mind** [comment]
> @DemonRx I was told about a good deal on file hosting at https://www.feralhosting.com/. I've started seeding the current bootstrap on a £10 server and it's working great so far!
> ![image](https://user-images.githubusercontent.com/4038174/106396935-da4b1d00-6402-11eb-8825-a108c440c7f5.png)
> 
> This could be of use? They let you install things like torrent clients and databases, and also offer regular SSH/FTP file upload.

What about using something like a fork off https://github.com/webtorrent for this use-case?

**Comment by DemonRx** [comment]
@IncognitoJam nice find ! That's definitely good. Just need to have the torrent posted for people to access. Like on the Dogecoin OP on bitcointalk, or linked on the [README.md](https://github.com/dogecoin/dogecoin/blob/master/README.md) of this repo.  

@patricklodder Could we update the README for that ?

**Comment by gallogox** [comment]
if you are not specialist on programming like me you can download this file on torrent then run on the cdm as it says in this website here https://coinguides.org/creating-bootstrap-file/
run this text file i made on the cmd ,if you dont know how to use the cmd just drag it inside the folder you wanna use and execute there 
[ssdisd.txt](https://github.com/dogecoin/dogecoin/files/5916156/ssdisd.txt)

**Comment by greenbigfrog** [comment]
Biggest advantage of just sharing the blocks & chainstate folder, is that you can continue seeding them during node operation without having to store the files twice.
Just point the download location in your torrent client of choice to `.dogecoin` (or link the directories, if your client doesn't allow changing the location)

**Comment by greenbigfrog** [comment]
From my understanding, the only advantage a actual bootstrap would offer, is not potentially sharing orphaned blocks etc, and allowing easier sharing via "normal" file downloads, where you end up having to put files into archives, if wanting to share multiple directories.

**Comment by ppumkin** [comment]
Hi All

Been trying to synchronise DOGE for a few days its just slow. Found this thread.
- I deleted everything and strated fresh.
- Started DOGE-QT it made all the default files
- ShutDown DOGE
- Placed the downloaded files from this torrent over the directories it created
- Started it . 
- ❌ Had an error about database . Rebuild? Yes, 
- ❌ Another error could not access some files or something strange 
- Moved it all out into a backup directory
- Started DOGE again it booted fine and started trying to synch form 0 again. 
- Closed DOGE

So I have concatenated the blocks as per @gallogox shared his file above thanks for that 👍
- Started DOGE
- Shows "Processing blocks on disk"

So I am not really sure how its supposed to work as explained above but I think the bootstrap.dat is pretty much newb friendly. Maybe include a Linux and Windows batch with the torrent to made the bootstrapper? 

Thanks all for all of this any way! 💯💯💯

**Comment by shibe2** [comment]
Ideally, bootstrap file should not have been needed. Typically, you need to download all the same data in any case, the difference is just in how you download it. BitTorrent can reach high transfer speed by downloading simultaneously from many peers. I don't see a reason why Dogecoin network should perform any worse. Currently we have a problem because download logic is not good enough, and the software is very slow. As soon as we improve that, automatic download from Dogecoin peers should become the fastest option.

Current stopgap measure of sharing ready to use blockchain database is bad in the long term. If there are errors in the database, it may cause network split at some point. Normally, each node verifies all the data while it builds its own database, so any potential errors don't propagate to many nodes. An operator who runs many nodes can copy the database between his own nodes if he is careful and knows exactly what he is doing. But sharing it with random users is not a good practice.

Long time ago Bitcoin Core developers provided ready to use Bitcoin blockchain database, but that practice was deprecated and replaced by "bootstrap file" function, which performs full verification of the data.

**Comment by DemonRx** [comment]
I'm just gonna put my sole opinion here that a bootstrap is more security conscious too. Why ? because it insures that the only files contained are **validated** blocks, and the files therein. Torrents are not "secure" methods of file transfers. and I'm not saying it would happen, but there could be malicious files or modified files within a "shared" torrent and/or folder/files that are being transferred. How many really take the time to check ? Furthermore, bootstraps are also smaller in file size (even by the gigabytes in difference), and as @ppumkin said, "newb friendly". And for crypto adoption that is truly a key point to keep in mind. Keep it simple stupid :kissing:  :stuck_out_tongue_closed_eyes:

**Comment by ppumkin** [comment]
I just want to move my assets to a live ledger. Neither of these ways worked. I did something similar with LTC and it just worked so I dont know what is going on. But found this now (more detailed steps of doing it - the readonly stuff may have been my issue)
https://www.reddit.com/r/dogecoin/comments/l8b7d4/dogecoin_blockchain/

**Comment by gallogox** [comment]
> I just want to move my assets to a live ledger.
> Neither of these two ways worked for me. I did something similar with LTC and it just worked so I dont know what is going on. But found this now (more detailed steps of doing it - the readonly stuff may have been my issue)
> https://www.reddit.com/r/dogecoin/comments/l8b7d4/dogecoin_blockchain/
> 
> --EDIT
> Its working now with the drop in files as in the torrent. It saying rescanning. I had to untick readonly on all the files form the torrent

did you manage to make it work  ?

**Comment by ppumkin** [comment]
Yes. But the network synchronisation is very slow. Only 3 peers for some reason.  I opened up ports and added nodes.
But it’s done now. I’m a full node “I hope”???

On 5 Feb 2021, at 18:23, gallogox <notifications@github.com> wrote:

﻿

I just want to move my assets to a live ledger.
Neither of these two ways worked for me. I did something similar with LTC and it just worked so I dont know what is going on. But found this now (more detailed steps of doing it - the readonly stuff may have been my issue)
https://www.reddit.com/r/dogecoin/comments/l8b7d4/dogecoin_blockchain/

--EDIT
Its working now with the drop in files as in the torrent. It saying rescanning. I had to untick readonly on all the files form the torrent

did you manage to make it work ?

**Comment by greenbigfrog** [comment]
My guess for why the "read-only" protection is turned on for some users, is due to their bittorrent client setting it automatically on any files it downloads, to prevent them from being changed, since you want to seed the same files you downloaded.
If I look at the permissions on the files on my end
```
-rw-r--r-- 1 root root  21975035 Feb  1 22:24 rev00306.dat
-rw------- 1 root root  20034215 Feb  3 13:31 rev00307.dat
```
it might be possible that windows interprets the permissions differently. 306 being from the  torrent, 307 created by core itself.
Someone else is gonna have to confirm this.

Other then that, I highly suggest we only start a new bootstrap monthly tops.

**Comment by ReverseControl** [comment]
We now have a discussion section (https://github.com/dogecoin/dogecoin/discussions) for topics that merit thought and time, such as this. Should there be any interest in continuing this conversation please open a discussion for it.

**Comment by MiguelSilvaViana** [comment]
This bootstrap no longer works, download link, does anyone have another one? Waiting 3 days sucks

**Comment by georgeartem** [comment]
Interesting. Please feel free to comment on #3471
