### ISSUE TITLE
Please reintroduce a supply cap (hear me out)

### ISSUE THREAD

**Issue by thematgraf** [dogecoin/dogecoin#1696]
This isn't about wanting to make money or making the price "go to the moon". This about creating trust in the currency.
If Dogecoin supply is unlimited, then it will lose value even MORE than regular fiat. This is because sure the governments print money, but its nowhere near as linear and constant as Doge. They print it when they need it. Doge is printed constantly.
Overall setting a cap would just expand Doge to more people. It would be more "safe" in terms of value.
I will probably get destroyed here in comments for saying something everyone has been saying, but I just think this should still be subject to discussion.

**Comment by patricklodder** [comment]
Please join the discussion here: https://www.reddit.com/r/dogecoindev/comments/la1hk3/continuation_of_1674/
