### ISSUE TITLE
Dogecoin balance stuck in an unconfirmed transaction from 2017.

### ISSUE THREAD

**Issue by Matches1134** [dogecoin/dogecoin#1699]
I just downloaded Dogecoin Core v1.14.2 and tried to recover my old wallet using the .dat file I had backed up. My entire balance is stuck in an unconfirmed transaction from 2017.
![Doge reddit](https://user-images.githubusercontent.com/78518973/106838128-504cbf80-6661-11eb-9303-04b764faad23.png)

![Doge reddit post](https://user-images.githubusercontent.com/78518973/106838158-5b9feb00-6661-11eb-834e-6816c2a0deb4.png)

If anyone could please help?

**Comment by slightlyskepticalpotat** [comment]
The oldest transaction in the mempool is only a few months old, your blockchain probably just needs to sync. After that, it should show as confirmed.

**Comment by Matches1134** [comment]
> 
> 
> The oldest transaction in the mempool is only a few months old, your blockchain probably just needs to sync. After that, it should show as confirmed.

I sync'd 100% before I swapped out the .dat file.

**Comment by DemonRx** [comment]
Not in memory pool means the transaction never hit the network, there's no miner waiting to confirm the transaction. You need to rescan your blockchain so it can clear the orphan transaction. This usually happens if after you sent the transaction you didn't wait until it was in the memory pool or at least 1 confirmation before shutting down the wallet. 

To fix:
Start the client with `dogecoin-qt -rescan -reindex-chainstate`

Be patient this can take a while.

**Comment by sonph** [comment]
I made a transaction from ledger wallet app and it also got stuck in unconfirmed state (8 hrs so far), probably closed it too soon? The transaction is visible on dogechain.info so I suppose it got broadcasted? Only paid 0.9 doge as the fee (I'm clueless).

Can someone help recommend what are my options here? Can I push the raw transaction? I run a full node but doesn't use the core wallet.

**Comment by Matches1134** [comment]
> 
> 
> Not in memory pool means the transaction never hit the network, there's no miner waiting to confirm the transaction. You need to rescan your blockchain so it can clear the orphan transaction. This usually happens if after you sent the transaction you didn't wait until it was in the memory pool or at least 1 confirmation before shutting down the wallet.
> 
> To fix:
> Start the client with `dogecoin-qt -rescan -reindex-chainstate`
> 
> Be patient this can take a while.

Thank you so much for taking the time to answer. I was hoping you would be willing to elaborate a little on the fix? I start the qt client and can't find options to rescan or reindex?

**Comment by Matches1134** [comment]
> 
> 
> @Matches1134 you need to start the qt client from the command prompt exactly as I wrote it to you.

In the windows command prompt? I tried it both in widows and the console tab in Doge wallet core, and neither worked. I copied and pasted the line exactly. Thank you for your help, I'm not very good at this, and google has not been much help.

**Comment by DemonRx** [comment]
Type it in the windows command prompt, from same directory where your dogecoin-qt client resides.

For example if your dogecoin-qt is in the dogecoin-1.14.2\bin folder on C:\ drive
then you would do the command like:

`C:\dogecoin-1.14.2\bin> dogecoin-qt -rescan -reindex-chainstate`

So just change the path to match the same location as your client is.

**Comment by shibe2** [comment]
Isn't zapwallettxes needed to get rid of stuck transactions?

**Comment by Matches1134** [comment]
> 
> 
> Type it in the windows command prompt, from same directory where your dogecoin-qt client resides.
> 
> For example if your dogecoin-qt is in the dogecoin-1.14.2\bin folder on C:\ drive
> then you would do the command like:
> 
> `C:\dogecoin-1.14.2\bin> dogecoin-qt -rescan -reindex-chainstate`
> 
> So just change the path to match the same location as your client is.

The qt application file is in C: Program files/Doecoin.
This is the way im trying to type it in.
![Command prompt](https://user-images.githubusercontent.com/78518973/106946685-0c080080-66ef-11eb-9f92-7d13547b85db.png)
Thank you so much for the help thus far, I feel like I'm almost there but am definitely not doing something correctly.

**Comment by shibe2** [comment]
`"C:\Program Files\Dogecoin\dogecoin-qt" -rescan -zapwallettxes=1`

**Comment by Matches1134** [comment]
> 
> 
> `"C:\Program Files\Dogecoin\dogecoin-qt" -rescan -zapwallettxes=1`

I keep getting the same error message saying C:\Program is not recognized. This is how I tried to type it in.
![Cmdprmpt](https://user-images.githubusercontent.com/78518973/106948208-09a6a600-66f1-11eb-8442-e4c93fb315a6.png)
The first C:\Users\match> I cant get rid of. Do I need to run Command prompt as admin?

**Comment by shibe2** [comment]
Look closely at my command. You missed the first quote character.

**Comment by DemonRx** [comment]
@Matches1134 I would highly recommend you learn how to change directories and how to use the windows command prompt in general. 

But I'll show this once here for you. You need to **change** to the directory where the client is by doing:

`cd C:\Program Files\Dogecoin`

then type type the command after the "**_>_**" symbol:

`dogecoin-qt -rescan -zapwallettxes`

The other method is typing the entire directory path + program name as such:

`C:\Program Files\Dogecoin\dogecoin-qt -rescan -zapwallettxes=1`

**Make sure everything is typed exactly as we've shown you. One incorrect/extra symbol or letter can make things not work.

@shibe2 I agree, but sometimes -rescan alone takes care of it too.
