### ISSUE TITLE
System error: CDB() : can't open database file wallet.dat, error -30974

### ISSUE THREAD

**Issue by DanTheBritish** [dogecoin/dogecoin#170]
Doge client 1.5, already tried deleting everything (Excluding wallet.dat).

Title is the first error message, after pressing OK another comes up:

"A fatal error occurred. Dogecoin can no longer continue safely and will quit.

EXCEPTION: St13runtime_error
CDB() : can't open database file wallet.dat, error -30974
D:\Crypto\Dogecoin\dogecoin-qt.exe in Runaway exception"

Pastebin of the debug log where the error occurred: http://pastebin.com/MA2u1YwK

EDIT: Solved with the -salvagewallet option. Closed for this reason.

**Comment by bzamecnik** [comment]
Also, check that the wallet.dat is not read-only as in my case.

**Comment by 3083487167** [comment]
> 此外，请检查 wallet.dat 是否不是只读的，就像我的情况一样。

You are my God！！！！
