### ISSUE TITLE
MultiDoge not working under MAC OSX 11.1

### ISSUE THREAD

**Issue by xela1601** [dogecoin/dogecoin#1702]
# Error Details
Process:               JavaApplicationStub [7388]
Path:                  /Applications/MultiDoge.app/Contents/MacOS/JavaApplicationStub
Identifier:            org.multibit
Version:               0.1.x beta
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           JavaApplicationStub [7388]
User ID:               1845725233

Date/Time:             2021-02-04 22:03:50.236 +0100
OS Version:            macOS 11.1 (20C69)
Report Version:        12
Anonymous UUID:        73BAF096-6147-B524-F03C-4E3C5B53E6BC

Sleep/Wake UUID:       578C0AE6-B288-4AC6-BEE6-F37AC7A72A7C

Time Awake Since Boot: 78000 seconds
Time Since Wake:       4000 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  dyld: Using shared cache: 467A83CB-BA86-3F07-B652-B9256C74080A
Library not loaded: /System/Library/PrivateFrameworks/JavaApplicationLauncher.framework/Versions/A/JavaApplicationLauncher
  Referenced from: /Applications/MultiDoge.app/Contents/MacOS/JavaApplicationStub
  Reason: image not found

Binary Images:
       0x1001a9000 -        0x1001a9fff +org.multibit (0.1.x beta) <E6764CDA-0042-C2D2-A7E1-C960883281BB> /Applications/MultiDoge.app/Contents/MacOS/JavaApplicationStub
       0x107a3e000 -        0x107ad9fff  dyld (832.7.1) <DEA51514-B4E8-3368-979B-89D0F8397ABC> /usr/lib/dyld

Model: MacBookPro11,3, BootROM 429.0.0.0.0, 4 processors, Quad-Core Intel Core i7, 2,5 GHz, 16 GB, SMC 2.19f12
Graphics: kHW_IntelIrisProItem, Intel Iris Pro, spdisplays_builtin
Graphics: kHW_NVidiaGeForceGTX750MItem, NVIDIA GeForce GT 750M, spdisplays_pcie_device, 2 GB
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x802C, 0x31364B544631473634485A2D314736453120
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x802C, 0x31364B544631473634485A2D314736453120
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x134), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1675.1)
Bluetooth: Version 8.0.2f9, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0512F, 500,28 GB
USB Device: USB 3.0 Bus
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 17.1

**Comment by shibe2** [comment]
https://github.com/langerhans/multidoge/issues

**Comment by xela1601** [comment]
@shibe2 sorry, my bad
