### ISSUE TITLE
Burn or not ? =D <3

### ISSUE THREAD

**Issue by majinssj3** [dogecoin/dogecoin#1704]
Hello EveryBody
Are you going to burn about a 100 Billons of token soon please ? :) I bought 3 120 dogecoin and we cant wait to see that one to the MOOOOON !!!

Everybody are like  trashtalkin about the Doge ! Zip'em Mouse with a 100,000,000,000 BURN :D !!!! 

We love y'all dear dogecoin developers ! <3

DDD !

**Comment by patricklodder** [comment]
You buy 100B DOGE and then I'll personally make you an app to burn them, complimentary.

Doesn't need Core Devs though, we can just do it permission-less, anywhere, any time.

🚀🚀🚀
