### ISSUE TITLE
Trying to send coins to exchange

### ISSUE THREAD

**Issue by meagan5785** [dogecoin/dogecoin#1713]
I tried to exchange my dogecoins to Bitcoin through changenow.io. The coins are gone from wallet but changenow support claims they have not received a deposit.

**Comment by CryptoForeignAffairs** [comment]
Please provide screenshots if possible.

**Comment by meagan5785** [comment]
![image](https://user-images.githubusercontent.com/78673715/107136722-dcfeb400-68d3-11eb-815c-4a929b55027a.jpeg)

**Comment by gewure** [comment]
This has nothing to do with the dogecoin sourcecode.

**Comment by shibe2** [comment]
Nice screenshotting skills! It says that the transaction was broadcast to 6 nodes, but it seems, these nodes didn't propagate it further. If you still want the transaction to be confirmed, you can get it from the wallet with `gettransaction` and submit it to the network manually. If you want to cancel the transaction, make a backup copy of your wallet and start Dogecoin Core with `-rescan -zapwallettxes=1` command line arguments. After you see that coins returned to your balance, send them to yourself. That will invalidate the original transaction.

**Comment by CryptoForeignAffairs** [comment]
You're awesome!

**Comment by meagan5785** [comment]
I have a backup of the wallet from before I made the transaction, so if I want to cancel the transaction I need to close the wallet and reopen with the command line options? Forgive my ignorance, where do I enter the command line options? I see the list of them in the drop down menu but I don't see where to manually enter them

**Comment by shibe2** [comment]
Copy current wallet as a new backup, just in case. Replace wallet.dat in Dogecoin data directory with your previous backup. When you start Dogecoin Core, you should see your coins in the wallet. Send all coins (minus fee) to yourself.

**Comment by meagan5785** [comment]
I got it thank you very much for your help

**Comment by rnicoll** [comment]
Thank you to the community for answering this!
