### ISSUE TITLE
Dogecoin Wallet Help needed.

### ISSUE THREAD

**Issue by Brianmaha** [dogecoin/dogecoin#1715]
### Expected behaviour
Normal start up of my wallet

### Actual behaviour
error message when my wallet was starting up.
Assertion failed!
Program: C:\Program Files (x86)Dogecoin\dogecoin-qt.exe
File: chain.cpp, Line 130

Expression: pindexWalk ->pprev

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### Machine specs:
- OS: Windows 8
-

**Comment by patricklodder** [comment]
Did you start this from a fresh installation? Did any C&P of your chain data from another (64bit?) platform?

**Comment by Brianmaha** [comment]
Thanks Patrick for your time and efforts

No, to be more precise:
2017 --> installation & syncing
2018 --> syncing
2019 --> nothing
2020 --> nothing
2021 --> start syncing again --> 2 yrs and few weeks to catch in, but is was syncing and blocks where loaded. Closed the computer and the next day I received this error.

One thing to add. I had some windows updates which perhaps can be relevant to know. Furthermore I don't have done anything.

I hope this clarifies a bit.

BR,
Brian

**Comment by patricklodder** [comment]
In that case, this could be just an index corruption. Did you try starting the wallet with `-reindex`? It will take some time to run through this process.

**Comment by Brianmaha** [comment]
Hi Patrick,

I have not don that yet. Doesn't matter if it will take some time. One thing though, I am not that technical at all. I have never programmed. Can you describe or share a good link how to reindex the database? That would really help.

Thanks in advance,
Brian

**Comment by patricklodder** [comment]
Brian,

It's done like this (off the top off my head, because I don't have any windows here):
1. Open a command prompt (`cmd`)
2. Go to the directory where Dogecoin is installed, eg `cd "C:\Program Files\Dogecoin"`
3. Type `dogecoin-qt -reindex`, this starts the wallet software with reindexing enabled
4. Wait until it's done
5. Hopefully don't ever do this again :-)

Hope that helps!

Patrick

**Comment by free-man123** [comment]
please, i was using iOS wallet in 2018 maybe and my mobile is formatted and I didn’t find iOS app in your website.. i find it in App Store but not support.. i loaded it to laptop and i have back phrases that from 12 words but I didn’t find blanks to fill it .. please can you send me the iOS app? or what can i do ? please help me my money will lose

**Comment by patricklodder** [comment]
> please, i was using iOS wallet in 2018 maybe and my mobile is formatted and I didn’t find iOS app in your website.. i find it in App Store but not support.. i loaded it to laptop and i have back phrases that from 12 words but I didn’t find blanks to fill it .. please can you send me the iOS app? or what can i do ? please help me my money will lose

Doughwallet? I owe the community a recovery guide for that. Will write it tomorrow.

**Comment by ColinLaws** [comment]
> please, i was using iOS wallet in 2018 maybe and my mobile is formatted and I didn’t find iOS app in your website.. i find it in App Store but not support.. i loaded it to laptop and i have back phrases that from 12 words but I didn’t find blanks to fill it .. please can you send me the iOS app? or what can i do ? please help me my money will lose

Use the doughwallet recovery tool. You can find it at [https://www.doughwallet.net/](https://www.doughwallet.net/) 

Type in the mnemonic, and the first row you see in the generated table is an address and private key pair for your wallet. Check the address on dogechain.info to confirm it is the expected address with your funds. Keep that private key safe. You can use a desktop wallet like dogecoin core or multidoge and restore the private key.

**Comment by ReverseControl** [comment]
@Brianmaha Were you able to resolve this issue?
@patricklodder Did you ever write that recovery guide?

**Comment by kevincheungs** [comment]
Just letting folks know running 
dogecoin-qt -reindex

got me past the error
"Assertion failed!"

**Comment by skontny** [comment]
ok
