### ISSUE TITLE
MultiDoge wallet won´t sync. (not Core)

### ISSUE THREAD

**Issue by Lukepuke91** [dogecoin/dogecoin#1717]
Multidoge light wallet won´t sync. I have DOGE in it, but i can´t send it. I tried to change: addnote= and peers=, but without success. Any advice on how to get Doge out of wallet or sync? 

Thank you!

![problem](https://user-images.githubusercontent.com/78728855/107204797-678f0280-69fd-11eb-81f8-373dca5bac92.PNG)

**Comment by patricklodder** [comment]
Hi! Definitely wrong repo!

However, to save you time, did you read this: https://www.reddit.com/r/dogecoin/comments/l9qgii/updating_your_multidoge_checkpoints_to_skip_ahead/ ?
