### ISSUE TITLE
Addnode (Peers)

### ISSUE THREAD

**Issue by AltCoinBuilders** [dogecoin/dogecoin#1722]
It Would Be Helpful If We Could As A Community Keep An Updated Log Of Add nodes Here.

Im having difficulty finding any up to date nodes

**Comment by rnicoll** [comment]
There are multiple active DNS seeds, but the problem we're seeing is the vast majority of the network doesn't allow incoming connections, so we have maybe 90% of nodes trying to reach out to other nodes, and only 10% can accept incoming connections.

Try opening TCP port 22556, and restart the node to ensure the DNS seeds know about your node, that should help.

**Comment by AltCoinBuilders** [comment]
> There are multiple active DNS seeds, but the problem we're seeing is the vast majority of the network doesn't allow incoming connections, so we have maybe 90% of nodes trying to reach out to other nodes, and only 10% can accept incoming connections.
> 
> Try opening TCP port 22556, and restart the node to ensure the DNS seeds know about your node, that should help.

Bit of a noob question here im abit rusty had a year break, would that be ufw allow for ubuntu?

**Comment by DemonRx** [comment]
@AltCoinBuilders I prefer `ufw limit 22556` this monitors for any malicious activity such as repeat attempted connections that happen around 5-6 times within a 30 second period, and then blocks that ip for 10 mins or so before they can retry the connection.

**Comment by DemonRx** [comment]
> It Would Be Helpful If We Could As A Community Keep An Updated Log Of Add nodes Here.
> 
> Im having difficulty finding any up to date nodes

There's block explorers that do that already for us. 

You can use this simple line of code to pull the latest active nodes and add them to your dogecoin.conf:

### Run this command within your ~/.dogecoin directory

```bash
wget -q api.blockchair.com/dogecoin/nodes -O - | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' > dogecoinNodeList.txt && sed -i "s/^/addnode=/" dogecoinNodeList.txt | && cat dogecoinNodeList.txt | tee -a dogecoin.conf
```

**Comment by AltCoinBuilders** [comment]
> > It Would Be Helpful If We Could As A Community Keep An Updated Log Of Add nodes Here.
> > Im having difficulty finding any up to date nodes
> 
> There's block explorers that do that already for us.
> 
> You can use this simple line of code to pull the latest active nodes and add them to your dogecoin.conf:
> 
> ### Run this command within your ~/.dogecoin directory
> ```shell
> wget -q api.blockchair.com/dogecoin/nodes -O - | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' > dogecoinNodeList.txt && sed -i "s/^/addnode=/" dogecoinNodeList.txt | && cat dogecoinNodeList.txt | tee -a dogecoin.conf
> ```

thanks got 10 connections now but is really slow syncing ben on for over 2 hours and only on block 1997

**Comment by RobertAClayton** [comment]
I also noticed how long it was taking to sync, so I set up a full node on a high end server (to try and help the overall health of the network). 

Feel free to add my node: 35.225.204.5

**Comment by AltCoinBuilders** [comment]
> 35.225.204.5

thanks my server is high end also and thanks for the node, much appreciated

**Comment by DemonRx** [comment]
@AltCoinBuilders to speed up sync. You can download a copy of the blockchain here: https://dogecoin.gg/dogecoin-bootstrap-2021-01-29.torrent (45gb download)

Place all the folders/files from the torrent into your ~/.dogecoin folder.

**Comment by ReverseControl** [comment]
Closing this issue as it has been addressed.
