### ISSUE TITLE
How to use Paperwallet Private key with a password?

### ISSUE THREAD

**Issue by MaDMaxiBo** [dogecoin/dogecoin#1723]
i had a paper wallet for Dogecoin in 2017, from walletgenerator.net

now i have the Private key , Public key and a password.

when i tried to importprivkey "privatekey" to the consol, i get this error  👍 

Invalid private key encoding (code -5)

can i use my paper wallet ? how ?

**Comment by MaDMaxiBo** [comment]
should i wait for Dogecore to synic %100 ?

**Comment by vertiond** [comment]
I know that if your private key begins with `6P`, that means you selected BIP38 encryption when you created it and that is where your password would come in.

**Comment by MaDMaxiBo** [comment]
yes, it begins with a 6P, but how can i use the password ?

**Comment by vertiond** [comment]
You have to decrypt it yourself; this isn't an issue with Dogecoin-Core.

Here is a starting point:
https://github.com/bitcoinjs/bip38#decryptencryptedkey-passphrase-progresscallback-scryptparams

FWIW, I tried reproducing your steps by creating a BIP38 encrypted Dogecoin key on both v2017.01.03 and master branches of the WalletGenerator repo.  The base58 prefix of `0x80` in this example is for Bitcoin. I tried modifying that to `0x9e` which is the base58 prefix for Dogecoin and it wouldn't work.  I do not know why.

**Comment by MaDMaxiBo** [comment]
then the question is "how to decyript a paper wallet?" :(

i dont understand that Code section ! sorry

**Comment by MaDMaxiBo** [comment]
i found this : https://www.reddit.com/r/dogecoin/comments/2bqfuq/decrypting_bip_38_paper_wallet/

is it safe ? that sites dogechain dogeaddress etc ? i dont think so !

> http://dogeaddress.com/ go to wallet details tab then in there enter your private BIP38 key.

It will ask for the passphrase to unencrypt it, when it is unencrypted it will give you the private key then you can use to wipe the paper wallet to your wallet ;).

You can wipe the paper wallet to an address at https://my.dogechain.info select redeem paper wallet option


2

Share
Report
Save
User avatar
level 1
jonstern
racing shibe
6 years ago
You can decrypt it here.

https://bitcoinpaperwallet.com/bitcoinpaperwallet/generate-wallet.html?design=alt-dogecoin#

**Comment by MaDMaxiBo** [comment]
There's a Wallet Details tab on the walletgenerator.net page. If you click that and enter your private key and passphrase (offline of course!) it will successfully decrypt.

Someone said that, i see the page but Decyrption doesnt seem to work !

**Comment by rywards** [comment]
Let's close this thread
