### ISSUE TITLE
Computer locked up

### ISSUE THREAD

**Issue by marcher01** [dogecoin/dogecoin#1724]
Windows auto update caused lock up-->

Windows is trying to close dogecoin, dogecoin screen say “do not turn off computer until this window disappears “
Computer locked up and I don’t want to power down in case of corruption.
Dogecoin Core had still 7 years of uploading yet to install. 
SDD is still on and computer disc light off

### Can you reliably reproduce the issue? No , computer power on but screen blank

1. Should I just power off or will that cause issues
2.
3.

### Machine specs:
- OS:windows 10
- CPU: intel i7
- RAM:8gb
- Disk size:3tb
- Disk Type (HD/SDD): SDD

**Comment by DemonRx** [comment]
If you have a backup of your wallet.dat file. You can safely power off, and restart.
