### ISSUE TITLE
Malware? Not verified developer.

### ISSUE THREAD

**Issue by angstg** [dogecoin/dogecoin#1728]
<img width="262" alt="Screen Shot 2021-02-11 at 10 08 03 PM" src="https://user-images.githubusercontent.com/67191459/107665690-cbdbeb80-6cb5-11eb-91d8-9d46c90f0555.png">

**Comment by langerhans** [comment]
Please stop opening issues for Multidoge here. This repository is for Dogecoin Core. The dialog you show is not an issue, it does not indicate malware. You'll be fine as long as you downloaded the wallet from multidoge.org.

**Comment by angstg** [comment]
lol i am not engineer. new here. so wanted to help you guys. Doge to the moon.
