### ISSUE TITLE
Hello, I transfer dogcoin through this wallet address. But the account balance is 0. My email address: Email: 1904570224@qq.com

### ISSUE THREAD

**Issue by shuriyong** [dogecoin/dogecoin#1729]
![_-1610941845_Screenshot_20210212_114552_1613101552000_xg_0](https://user-images.githubusercontent.com/78950406/107741208-57637580-6cd2-11eb-8c7a-7c118433785b.jpg)
![_-1741066150_Screenshot_20210212_121838_1613103518000_xg_0](https://user-images.githubusercontent.com/78950406/107741213-5a5e6600-6cd2-11eb-96d2-8852b3ee7e40.jpg)
![5dcc8cba4bbfec73](https://user-images.githubusercontent.com/78950406/107741287-7d891580-6cd2-11eb-9dd6-fcdaeb57b32f.jpg)

**Comment by shuriyong** [comment]
Ask for advice

**Comment by shuriyong** [comment]
Ask for advice

**Comment by shuriyong** [comment]
Is it not synchronized yet

**Comment by John-Gee** [comment]
Can you see the transaction on a block explorer? If so, what does it say?

**Comment by shuriyong** [comment]
> 您能看到块资源管理器上的事务吗？如果是的话，它是怎么说的？

The balance of the wallet is 0, and the trading platform shows that it has arrived. The balance of the wallet address can also be displayed on the website, but the wallet is still 0. I'm a novice. Thank you for your reply

**Comment by shuriyong** [comment]
> Can you see the transaction on a block explorer? If so, what does it say?

The balance of the wallet is 0, and the trading platform shows that it has arrived. The balance of the wallet address can also be displayed on the website, but the wallet is still 0. I'm a novice. Thank you for your reply

**Comment by lzhlo** [comment]
The wallet must be completed synchronously

**Comment by lzhlo** [comment]
这种新交易的订单钱包必须同步完成才能看见币

**Comment by rywards** [comment]
Wait for the wallet to sync with the blockchain, then report back.

**Comment by ReverseControl** [comment]
@shuriyong If this is still an issue let us know. Your wallet should be well synced by now.
