### ISSUE TITLE
Doge android wallet

### ISSUE THREAD

**Issue by hippimichi** [dogecoin/dogecoin#1736]
Hello, 

I am kind of a big noob. 

So I installed the doge android wallet and I've send some coins from anycoin to my wallet. 

Back then I didn't understand that I have to wait for it to synchronize. I reinstalled the app and of course I didn't do a backup. 

Now my old address is not anymore on my address book (those linked to my app) 

Is there any way to get my old address back so I can access my coin? 

Thank you have a nice day!

**Comment by DBLESSED1** [comment]
Oh sorry for the mistake on your part with regret I inform you that there is no way to get the account and the money back as all backup phrase are not stored on any server because all Cryptocurrency are create to provide privacy and security to all users.thank you

**Comment by hippimichi** [comment]
Damn OK thank you. Was not much Atleast
