### ISSUE TITLE
Why not increase the supply once people adopt it as means of exchange? Cap the market now and increase supply later.

### ISSUE THREAD

**Issue by angstg** [dogecoin/dogecoin#1739]
Just increasing supply now is worthless. Nobody is using it in the market. Why not cap now and increase supply later? We do not have billions of users who are exchanging Dogecoins with each other like US dollar. The supply at the moment does not make any sense.

**Comment by patricklodder** [comment]
Hi! Please have these type of ideas / discussions on https://www.reddit.com/r/dogecoindev/, unless you have working code or a worked out proposal for people to read.

Thank you!
