### ISSUE TITLE
Configure ignores --with-incompatible-bdb on 1.14 and fails even when libdb_cxx 5.1 is present on master

### ISSUE THREAD

**Issue by ss32** [dogecoin/dogecoin#1740]
This issue tracker is only for technical issues related to Dogecoin Core.

For general questions about Dogecoin please use one of the various communities, e.g. Reddit, IRC, Discord, etc.

### Describe the issue

`./configure` fails on Ubuntu 18.04 despite building Berkley DB 5.1 from source and installing to `/usr/local/`.  It also fails after installing 5.3 via apt and passing `--with-incompatible-bdb`

#### If so, please list the steps to reproduce below:

**Building From Source**
```bash
$ cd dogecoin/deps/db-5.1.29.NC/
$ cd build_unix/
$ ../dist/configure --prefix=/usr/local
$ make -j
$ sudo make install
$ find /usr/local/ -name db_cxx*
/usr/local/include/db_cxx.h
$ cd ~/dogecoin
$ ./autogen.sh
$ ./configure
.
.
.
checking for Berkeley DB C++ headers... no
configure: error: libdb_cxx headers missing, Dogecoin Core requires this library for wallet functionality (--disable-wallet to disable wallet functionality)
```

**Ok let's try building with the latest 5.3 in the repo**

```bash
$ git checkout 1.14-branding
$ sudo apt-get install libboost-all-dev libdb5.3-dev libdb5.3++-dev libevent-dev
$ ./autogen.sh 
$ ./configure 
$ ./configure --with-incompatible-bdb
.
.
.
checking for Berkeley DB C++ headers... no
configure: error: libdb_cxx headers missing, Dogecoin Core requires this library for wallet functionality (--disable-wallet to disable wallet functionality)
```

### Expected behaviour
It should configure

### Machine specs:
```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 19.3 Tricia
Release:	19.3
Codename:	tricia
$ uname -r
5.4.0-65-generic
```

### Any extra information that might be useful in the debugging process.
https://pastebin.com/2NR7SS9T

**Comment by ss32** [comment]
Got past configuring, but now there are include errors.

Line 23153 in `configure`
```diff
-  bdbpath=X
+  bdbpath="/usr/local/include"
```

**Comment by vertiond** [comment]
Try `sudo apt install libdb++-dev`

**Comment by ss32** [comment]
> Try `sudo apt install libdb++-dev`

No dice.  Same results on master and 1.14 and lib_db 5.1

**Comment by vertiond** [comment]
I would build using the depends system.

**Comment by ss32** [comment]
Can you elaborate on that?  What do you mean, exactly, by "the depends system"?

**Comment by vertiond** [comment]
Oops, that doesn't solve the issue; you must install the libdb5.1 packages manually as 

`wget http://mirrors.edge.kernel.org/ubuntu/pool/universe/d/db/libdb5.1_5.1.29-7ubuntu1_amd64.deb
sudo apt install ./libdb5.1_5.1.29-7ubuntu1_amd64.deb
wget http://mirrors.edge.kernel.org/ubuntu/pool/universe/d/db/libdb5.1++_5.1.29-7ubuntu1_amd64.deb
sudo apt install ./libdb5.1++_5.1.29-7ubuntu1_amd64.deb
wget http://mirrors.edge.kernel.org/ubuntu/pool/universe/d/db/libdb5.1-dev_5.1.29-7ubuntu1_amd64.deb
sudo apt install ./libdb5.1-dev_5.1.29-7ubuntu1_amd64.deb
wget http://mirrors.edge.kernel.org/ubuntu/pool/universe/d/db/libdb5.1++-dev_5.1.29-7ubuntu1_amd64.deb
sudo apt install ./libdb5.1++-dev_5.1.29-7ubuntu1_amd64.deb`

./configure then works on Ubuntu 18.04

**Comment by ss32** [comment]
I also solved it by following [these steps](https://github.com/dogecoin/dogecoin/blob/master/doc/build-unix.md#berkeley-db) that are called out later in the Unix build.

**Comment by ss32** [comment]
>Oops, that doesn't solve the issue; you must install the libdb5.1 packages manually.

Update:  After linking against a newer version of bdb I kept hitting a segfault (https://github.com/bitcoin/bitcoin/issues/12047).  Your method worked, thanks!
