### ISSUE TITLE
dogecoin trans

### ISSUE THREAD

**Issue by bgt0526** [dogecoin/dogecoin#1744]
Is there any way to move multidoge's backup wallet to dogcoin core?
<font class="papago-parent"><font class="papago-source" style="display:none;">
</font><!- 적용되지 않는 섹션 제거 ->
</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>

</font><font class="papago-parent"><font class="papago-source" style="display:none;">This issue tracker is only for technical issues related to Dogecoin Core.</font>이번 이슈 트래커는 도게코인코어와 관련된 기술적 이슈에만 해당된다.</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>

</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>

</font><font class="papago-parent"><font class="papago-source" style="display:none;">For general questions about Dogecoin please use one of the various communities, e.g. Reddit, IRC, Discord, etc.
</font>도게코인에 대한 일반적인 질문은 레드딧, IRC, 불협화음 등 다양한 커뮤니티 중 하나를 사용하십시오.
</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>

</font><font class="papago-parent"><font class="papago-source" style="display:none;">### Describe the issue
</font>### 이슈 설명
</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>

</font><font class="papago-parent"><font class="papago-source" style="display:none;">### Can you reliably reproduce the issue?</font>### 이슈를 안정적으로 재현할 수 있는가.</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>

</font><font class="papago-parent"><font class="papago-source" style="display:none;">#### If so, please list the steps to reproduce below:</font>#### 그렇다면 아래에 재생산할 단계를 나열하십시오.</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>

</font><font class="papago-parent"><font class="papago-source" style="display:none;">1.
</font>1.
</font><font class="papago-parent"><font class="papago-source" style="display:none;">2.
</font>2.
</font><font class="papago-parent"><font class="papago-source" style="display:none;">3.
</font>3.
</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>

</font><font class="papago-parent"><font class="papago-source" style="display:none;">### Expected behaviour
</font>### 예상 행동
</font><font class="papago-parent"><font class="papago-source" style="display:none;">Tell us what should happen
</font>우리에게 무슨 일이 일어나야 하는지 말해줘.
</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>

</font><font class="papago-parent"><font class="papago-source" style="display:none;">### Actual behaviour
</font>### 실제 행동
</font><font class="papago-parent"><font class="papago-source" style="display:none;">Tell us what happens instead
</font>대신 무슨 일이 일어나는지 말해줘
</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>

</font><font class="papago-parent"><font class="papago-source" style="display:none;">### Screenshots.</font>### 스크린샷.</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>

</font><font class="papago-parent"><font class="papago-source" style="display:none;">If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.</font>문제가 GUI와 관련된 경우 드래그 앤 드롭을 통해 스크린샷을 이 문제에 추가할 수 있다.</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>

</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>

</font><font class="papago-parent"><font class="papago-source" style="display:none;">### What version of Dogecoin Core are you using?</font>### 어떤 버전의 도게코인코어를 사용하십니까?</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>

</font><font class="papago-parent"><font class="papago-source" style="display:none;">List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.</font>버전 번호/커밋 ID를 나열하고 공식 바이너리, 자체 컴파일 또는 PPA와 같은 배포 패키지를 나열하십시오.</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>

</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>

</font><font class="papago-parent"><font class="papago-source" style="display:none;">### Machine specs:
</font>### 기계 사양:
</font><font class="papago-parent"><font class="papago-source" style="display:none;">- OS:
</font>- OS:
</font><font class="papago-parent"><font class="papago-source" style="display:none;">- CPU:
</font>- CPU:
</font><font class="papago-parent"><font class="papago-source" style="display:none;">- RAM:
</font>- 램:
</font><font class="papago-parent"><font class="papago-source" style="display:none;">- Disk size:</font>- 디스크 크기:</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>

</font><font class="papago-parent"><font class="papago-source" style="display:none;">- Disk Type (HD/SDD):
</font>- 디스크 유형(HD/SDD):
</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>

</font><font class="papago-parent"><font class="papago-source" style="display:none;">### Any extra information that might be useful in the debugging process.</font>### 디버깅 프로세스에 유용할 수 있는 추가 정보.</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>

</font><font class="papago-parent"><font class="papago-source" style="display:none;">This is normally the contents of a `debug.log` or `config.log` file.</font>이것은 보통 debug.log 또는 config.log 파일의 내용이다.</font><font class="papago-parent"><font class="papago-source" style="display:none;"> Raw text or a link to a pastebin type site are preferred.</font> 원시 텍스트 또는 페이스트빈 유형 사이트 링크가 선호된다.</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>

</font>

**Comment by rnicoll** [comment]
This isn't, they're very different file formats. The best option is likely to be to send coins as a transaction from one to the other.
