### ISSUE TITLE
PGP signs

### ISSUE THREAD

**Issue by bohdanyurov-gl** [dogecoin/dogecoin#1753]
Hi,

Are there any PGP signs available? How can we check binary releases?

**Comment by patricklodder** [comment]
Hi!

We use the gitian process for builds, you can see the build output hashes at https://github.com/dogecoin/gitian.sigs which are pgp signed, and you can find the pub keys here: https://github.com/dogecoin/dogecoin/tree/master/contrib/gitian-keys

Hope that helps!

**Comment by bohdanyurov-gl** [comment]
Thanks!

**Comment by bohdanyurov-gl** [comment]
@patricklodder well, gpg tells me signature is wrong:
#8 3.859 gpg: assuming signed data in 'dogecoin-1.14.2-x86_64-linux-gnu.tar.gz'
#8 4.125 gpg: Signature made Wed Nov  6 19:20:39 2019 UTC
#8 4.125 gpg:                using RSA key 1DDC450B45DB5ADCCF5DDA7F8E4217C6D47D946D
#8 4.134 gpg: BAD signature from "Maximilian Keller <mail@maxkeller.io>" [unknown]

**Comment by bohdanyurov-gl** [comment]
#8 3.809 gpg: assuming signed data in 'dogecoin-1.14.2-x86_64-linux-gnu.tar.gz'
#8 3.964 gpg: Signature made Wed Nov  6 08:57:55 2019 UTC
#8 3.964 gpg:                using RSA key 51A2D746AE8A58A4101A4030E679E30C312B94E0
#8 3.964 gpg:                issuer "jrn@jrn.me.uk"
#8 3.968 gpg: BAD signature from "J Ross Nicoll <jrn@jrn.me.uk>" [unknown]

**Comment by bohdanyurov-gl** [comment]
Strangely sha256 check passes:
dogecoin-1.14.2-x86_64-linux-gnu.tar.gz: OK

**Comment by patricklodder** [comment]
> #8 3.859 gpg: assuming signed data in 'dogecoin-1.14.2-x86_64-linux-gnu.tar.gz'

Please note that `dogecoin-linux-1.14-build.assert.sig` signs `dogecoin-linux-1.14-build.assert` and not the tarball.

You can then verify the hash from https://github.com/dogecoin/gitian.sigs/blob/master/1.14.2-linux/langerhans/dogecoin-linux-1.14-build.assert#L10 to the hash of your tarball.

**Comment by langerhans** [comment]
I might be mistaken here, but afaik the binaries themselves are not what's signed. You would verify the signature of the assert file in the gitian.sigs repo against the provided assert.sig file. That way you authenticate the contents and can cross check all file hashes to make sure the binaries are equal to has been signed at release time.

**Comment by bohdanyurov-gl** [comment]
Fair point, thanks!
