### ISSUE TITLE
Wallet synced, old TX uncnfrmed. No TX history on blockchain from all walletdump addresses.

### ISSUE THREAD

**Issue by PaekNikler** [dogecoin/dogecoin#1756]
![IMG_9112](https://user-images.githubusercontent.com/79470429/108745714-ce3e1100-7511-11eb-8055-5534481571dc.jpeg)

**Was cleaning out storage room and stumbled across old PC from 2014. Opened old PC. Saw old dogecoin client. Opened it up.**

Exited old version of qt and downloaded most up to date client (1.14.2 WIN 64bit).
Went through the sync process (used bootstrap), but no updates to balance and all transactions remained unconfirmed. TXIDs not in mempool and zero history on the blockchain for the addresses from/to transactions.

I remember the passphrase, but not the wallet address. 
Walletdumped and checked all addresses. No history on any of them.

There were no additional transactions added to the TX history after full sync. 

Any ideas?

From new client:

![IMG_9113](https://user-images.githubusercontent.com/79470429/108746688-0a25a600-7513-11eb-87f0-75bf45c902ba.jpeg)

**Comment by patricklodder** [comment]
Is it possible that those unconfirmed transactions were mined on the wrong side of a fork?

**Comment by PaekNikler** [comment]
I really don't know. I had a traumatic brain injury in 2014. I wouldn't know where to begin to look to investigate.

**Comment by PaekNikler** [comment]
Transaction dates on the wallet encompassed between Jan 24, 2014 to Jan 26, 2014.

**Comment by patricklodder** [comment]
> I wouldn't know where to begin to look to investigate.

You'll want to start up your old client and dump the mempool txs, you can parse them with a dogecoin-tx from your new client and check what the origins of these coins were. Note down the inputs and then compare what happened on the recorded chain using a block explorer.

**Comment by PaekNikler** [comment]
Sorry, but I'm afraid that's beyond my capabilities.

**Comment by DemonRx** [comment]
> Is it possible that those unconfirmed transactions were mined on the wrong side of a fork?

Only way he could check this is if he still had the original blockchain at that time and do a comparison of the block hashes against the explorer ?

**Comment by DemonRx** [comment]
@PaekNikler once you have your client started (the new version), run the command `dogecoin-cli getrawmempool`

**Comment by ReverseControl** [comment]
@PaekNikler Were you able to recover your coins?

**Comment by PaekNikler** [comment]
No, unfortunately I was unable to sync them. I'm guessing the wallet was from another coin and the file inadvertently placed in the Dogecoin folder.

**Comment by ReverseControl** [comment]
@PaekNikler Given the amount of coins in the wallet I'd suggest to ascertain if in fact you have a dogecoin wallet, and furthermore, if you do, recover the coins. I can do this work for you. You can reach me at ``dogecoinboost@pm.me`` to discuss further.
