### ISSUE TITLE
Let's add msvc/Visual Studio support!

### ISSUE THREAD

**Issue by soma42** [dogecoin/dogecoin#1759]
Bitcoin Core added something nice a while ago...Visual Studio build/debugging for 'developer convenience'.

It works really like a charm, enables super-fast builds and comfortable debugging on Windows.

It's here: https://github.com/bitcoin/bitcoin/tree/master/build_msvc

Using it is ofc easier than the initial work to make it work.

Is anyone intersted?

**Comment by rnicoll** [comment]
We're rebuilding Dogecoin around Bitcoin Core 0.21, which will include this. You can follow progress at https://github.com/dogecoin/dogecoin/tree/1.21-dev
