### ISSUE TITLE
estimatesmartfee always returns -1

### ISSUE THREAD

**Issue by bubudod** [dogecoin/dogecoin#1764]
I tried to call the `estimatesmartfee` so that I can get the `feerate`, but it always returns the -1. So I want to know the reason. And is there a default `feerate` that I can use when it returns -1.
**request:**
```
curl --location --request POST 'localhost:44555' \
--header 'Authorization: Basic dGVzdDp0ZXN0MTIzNA==' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc":"1.0",
    "id":"curltest",
    "method":"estimatesmartfee",
    "params":[
        6
    ]
}'
```
**response:**
```
{"result":{"feerate":-1,"blocks":25},"error":null,"id":"curltest"}
```

**Comment by shibe2** [comment]
Note that currently, transaction size is rounded in Dogecoin fee calculation. The recommended fee consists of:

1 DOGE per transaction
1 DOGE per 1000 bytes rounded down
1 DOGE per dust output

So fee per kilobyte is 1 DOGE, but if you don't add per-transaction and per-dust components, your calculation will result in insufficient fee.

**Comment by uranik777** [comment]
> Note that currently, transaction size is rounded in Dogecoin fee calculation. The recommended fee consists of:
It is bad if the price of the coin increases, but the min fee is always fixed at 1 doge

**Comment by shibe2** [comment]
@uranik777 You are welcome to discuss it on reddit: https://redd.it/lg4hp7

**Comment by exp0nge** [comment]
Are you on regtest?

**Comment by exp0nge** [comment]
Actually, I take that back ^. This happens if you start requesting nblocks large enough (like 100, etc)

**Comment by p-j01** [comment]
Do you know how to reproduce with the `dogecoin-cli`?

**Comment by exp0nge** [comment]
@p-j01 `dogecoin-cli estimatesmartfee  100`

**Comment by p-j01** [comment]
@exp0nge How many blocks do you need to have synced? I get 

```
{
  "errors": [
    "Insufficient data or no feerate found"
  ],
  "blocks": 0
}
```

**Comment by rnicoll** [comment]
Confirming Dogecoin doesn't use smart fees, and has no plans to adopt them. Instead we use fixed fee rates as per early Bitcoin. @shibe2 's comment is nearly perfect, except that we round up transaction size to the nearest 1kB, not down. Hope that helps.
