### ISSUE TITLE
High cpu usage

### ISSUE THREAD

**Issue by hberg539** [dogecoin/dogecoin#1772]
Hello,

i'm running a dogecoin 1.14.2 on a Ubuntu 20.04 server without GUI. Some specs about the server:

Kernel: Linux misc 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
CPU: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
Mem: 64GB
Filesystem: ZFS encrypted

The blockchain was synced from torrent, as given by this reddit [post](https://www.reddit.com/r/dogecoin/comments/l8b7d4/dogecoin_blockchain/).

getinfo:
`{
  "version": 1140200,
  "protocolversion": 70015,
  "walletversion": 130000,
  "balance": 0.00000000,
  "blocks": 3626250,
  "timeoffset": -3,
  "connections": 42,
  "proxy": "",
  "difficulty": 6419283.340495096,
  "testnet": false,
  "keypoololdest": 1614365255,
  "keypoolsize": 100,
  "paytxfee": 0.00000000,
  "relayfee": 1.00000000,
  "errors": ""
}
`

getblockchaininfo:
`{
  "chain": "main",
  "blocks": 3626249,
  "headers": 3626250,
  "bestblockhash": "fcdb22a1cd545447d204b96a85a910b59bc43ea3d2d5374cb1a5839b5a2f5eb2",
  "difficulty": 5884340.199196151,
  "mediantime": 1614496691,
  "verificationprogress": 0.9999992529901931,
  "initialblockdownload": false,
  "chainwork": "0000000000000000000000000000000000000000000004a8f3639eaed5a081f3",
  "pruned": false,
  "softforks": [
    {
      "id": "bip34",
      "version": 2,
      "reject": {
        "status": true
      }
    },
    {
      "id": "bip66",
      "version": 3,
      "reject": {
        "status": true
      }
    },
    {
      "id": "bip65",
      "version": 4,
      "reject": {
        "found": 2000,
        "required": 1900,
        "window": 2000,
        "status": true
      }
    }
  ],
  "bip9_softforks": {
    "csv": {
      "status": "failed",
      "startTime": 1462060800,
      "timeout": 1493596800,
      "since": 1703520
    }
  }
}
`

I'm also running a full bitcoin node on this server (with much less cpu usage), see here.
![grafik](https://user-images.githubusercontent.com/902223/109410902-9534ef00-799e-11eb-91e5-085b19f2a159.png)

The disks are mostly idle:
![grafik](https://user-images.githubusercontent.com/902223/109410911-a3830b00-799e-11eb-96d8-ed0a9d6d8e77.png)

The complete debug.log is here:
[debug.log.tar.gz](https://github.com/dogecoin/dogecoin/files/6056371/debug.log.tar.gz)

It seems that the cpu only goes to 100% when dogecoin is idle. While downloading the latest blocks, the cpu usage was normal.

**Comment by patricklodder** [comment]
This performance issue has been fixed with v1.14.3 though #1676 and I'd recommend you to update to that as soon as you can. There will still be high CPU when serving a lot of unsynchronized nodes at once, but it will stop locking the msghandler thread so your node will behave much better.

**Comment by hberg539** [comment]
Thanks, i've updated and now it is running fine.
