### ISSUE TITLE
MAC OS: Cannot obtain a lock on data directory

### ISSUE THREAD

**Issue by poll456** [dogecoin/dogecoin#1778]
As first time user tried to install Dogecoin Core first time on Mac. Tried to install it on external hardware.

1. Open Dogecoin Core Version v1.14.3
2. Error Message: Cannot obtain a lock on data directory ........ Dogecoin Core is probably already running. No such file or directory.

- OS: Big Sur
- CPU: 1,6 Ghz i5
- RAM: 8gb
- Disk size: 128gb
- Disk Type (HD/SDD): 1000gb

**Comment by patricklodder** [comment]
Assuming this is QT, if you open `~/Library/Preferences/org.dogecoin.Dogecoin-Qt.plist`, what does `strDataDir` say and does that location exist?

**Comment by gYxjuTyK** [comment]
If the datadir was copied from another system, maybe you need to remove the lock file with
rm .lock
?

**Comment by jakusb** [comment]
Same problem. Removing .lock file does not help. Moving the folder triggers question to choose a folder, resulting in again same problem

**Comment by ReverseControl** [comment]
@poll456 @jakusb Were you able to solve this issue?

**Comment by jakusb** [comment]
I did, I believe it was something to do with permissions.
