### ISSUE TITLE
Dogecoin fatal error while downloading wallet

### ISSUE THREAD

**Issue by LobsterKing88** [dogecoin/dogecoin#1779]
I am having issues with the Dogecoin wallet download, at about 80%, and now suddenly the application does not start up anymore, and gives a fatal error:

"A fatal internal error occure, see debug log for details"

This is the error in the debug log:

2021-03-02 14:58:01 ERROR: CheckAuxPowProofOfWork : block does not have our chain ID (got 0, expected 98, full nVersion 0) 2021-03-02 14:58:01 ERROR: ReadBlockFromDisk: Errors in block header at CBlockDiskPos(nFile=240, nPos=10406780) 2021-03-02 14:58:01 *** Failed to read block 2021-03-02 14:58:02 Loaded 65219 addresses from peers.dat 482ms

Please help, since there are dogecoins sent to this wallet, and since they did not yet arrive, I can not retrieve them, thank you.

I am using Windows 10 and Dogecoin version 1.14.2

**Comment by patricklodder** [comment]
What version did you upgrade this from?

**Comment by LobsterKing88** [comment]
This is my first version, I started it newly

**Comment by patricklodder** [comment]
in the `%AppData%\Dogecoin\blocks` folder, are there any files with a higher number than blk00240.dat?

**Comment by LobsterKing88** [comment]
yes blk00241 and 242,dat

**Comment by patricklodder** [comment]
okay. This sounds like a data corruption on disk (because the client will never accept a blockheads with version 0), but to be absolutely sure, I'd recommend the following steps:

- shut down the wallet software completely
- in `%AppData%\Dogecoin` make a copy of peers.dat to elsewhere
- delete peers.dat (DO NOT remove wallet.dat)
- in `%AppData%\Dogecoin\blocks`, make a copy of blk00240 / 241 / 242 .dat files to elsewhere
- remove the 240 / 241 / 242 files
- restart dogecoin-qt.exe from the command line as: `dogecoin-qt.exe -reindex`

it will take a bit of time to run through the reindex (couple of hours) but that should reset you.

**Comment by LobsterKing88** [comment]
Okay, thank you, I will try this, hopefully it can resolve the issue

**Comment by LobsterKing88** [comment]
Hello, I have done all you advised me, and now I want to  restart dogecoin-qt.exe from the command line as: dogecoin-qt.exe -reindex, but when i do it, my system tells me dogecoin-qt.exe -reindex is not recognized as an internal or external command, operable program or batch file. Please let me know where I should use this command line, I now used it in C:\users in windows

Thanks !

**Comment by patricklodder** [comment]
Sorry! It's most likely `C:\Program Files (x86)\Dogecoin\` or `C:\Program Files\Dogecoin\`

**Comment by LobsterKing88** [comment]
hmm, ok thanks, but both also don't work.....

**Comment by patricklodder** [comment]
You can find the exact location of your executable by searching dogecoin in the start menu, and then choose "open file location", which should open an explorer window to the location where it is installed.

**Comment by LobsterKing88** [comment]
ok, found it, but it does not have any progress......already 2 hours running

**Comment by LobsterKing88** [comment]
update, its re-indexing the blocks on disk now, thank you so much for your support!!

**Comment by patricklodder** [comment]
Was this now solved?

**Comment by LobsterKing88** [comment]
Yesterday it was finally updated and I can use the wallet now, thank you!
