### ISSUE TITLE
UI for importprivkey

### ISSUE THREAD

**Issue by countable** [dogecoin/dogecoin#179]
A lot of paper wallets are being distributed to nontechnical new users but redeeming a paper Wallet requires a console command which is intimidating and error prone. An import paper wallet dialog that accepts a private key would be a vast improvement.

**Comment by uvok** [comment]
Any activity on this?
Maybe we should discuss whether to actually import the private key (including all the reindexing) or rather sweep the wallet (creating a transaction that spends all the dogecoin).

**Comment by rnicoll** [comment]
Resolved in #1856
