### ISSUE TITLE
Syncing node for BtcPay is stuck at 99%

### ISSUE THREAD

**Issue by IsaaacD** [dogecoin/dogecoin#1792]
### Describe the issue
I'm trying to sync the blockchain to run a node for BtcPay and it's stuck at 99%. I posted to BtcPay GitHub page and they said to reach out to the appropriate community.

This is my posting over there https://github.com/btcpayserver/btcpayserver/issues/2357 I'm on mobile ATM so don't have anything else to add but wondering if anyone has any idea what's happening?

### What version of Dogecoin Core are you using?
Not sure what version it is but if this is important i can figure it out.

### Machine specs:
- OS: Docker
- CPU: 2 cores
- RAM: 4gb
- Disk size: 50gb
- Disk Type (HD/SDD): HDD

**Comment by vertiond** [comment]
Is the tip height correct?  Sometimes `progress=` doesn't always reach 1.000000.

**Comment by vertiond** [comment]
I don't know if this applies in your situation but I've used `maxtipage=99999999` before on chains that aren't being mined regularly in order to force the node to believe it's synced.

**Comment by IsaaacD** [comment]
Thanks for the quick reply @vertiond! I'm sorry but I'm sure I didn't do any additional configuration and just using the vanilla btcpayserver_dogecoind instance. Is this a setting I'd have to change in the image? I tried googling maxtipage but not getting good results. Any clarification you could provide would be appreciated

**Comment by IsaaacD** [comment]
![Screenshot_20210313-153543](https://user-images.githubusercontent.com/5303125/111043903-4e6ddd00-8413-11eb-993f-dbc011da2ffd.jpg)
![Screenshot_20210313-153535](https://user-images.githubusercontent.com/5303125/111043905-52016400-8413-11eb-9c6e-57a2601f2400.jpg)
The node seems to be on the right block, is that what the tip means?

**Comment by vertiond** [comment]
It would go into the configuration file, dogecoin.conf, inside the data directory.  

Not sure either if that image is up to date with the recent soft fork - can you manually supply your own instead?  If so, there are recent images we could point you to.

**Comment by IsaaacD** [comment]
I checked the version and it's 1.14.2 so it's out of date. This seems like it could be the issue. As for supplying my own dogecoind Docker image I'd imagine there's a way to do so but not too sure. If you could point me to a Docker image I could try to get it setup

**Comment by IsaaacD** [comment]
I found the dockerfile for Dogecoin on BtcPay repo, so i guess I'd just need to update this with the proper image https://github.com/btcpayserver/btcpayserver-docker/blob/d73cbf6ad96b3909aa6f735c61d04027c4a48769/docker-compose-generator/docker-fragments/dogecoin.yml

**Comment by vertiond** [comment]
1.14.2 should be okay so the problem must be elsewhere?

**Comment by IsaaacD** [comment]
Hmm I added `maxtipage=99999999` to dogecoin.conf and it's not starting now. I'll have to look at it more when I'm home tomorrow. Thanks for your help so far!

**Comment by IsaaacD** [comment]
I'm still having an issue with this, this is the last logs from dogecoind docker image: 
![image](https://user-images.githubusercontent.com/5303125/111301416-90bc3780-8628-11eb-80f4-c90553b07747.png)
And this is nbxplorer:
![image](https://user-images.githubusercontent.com/5303125/111301738-f01a4780-8628-11eb-9c34-7116f7f58286.png)
And here's dogecoin.conf:
![image](https://user-images.githubusercontent.com/5303125/111301918-23f56d00-8629-11eb-84ae-f2e7fb8077fc.png)

I noticed when I tried to add `maxtipage=99999999` it gets re-written when I restart the container, so I'll try and find where BtcPay Server is overwriting the .conf file to put that in, but is there something that sticks out here? I'm still not really sure what's going on.

**Comment by patricklodder** [comment]
Did you add the `prune=25000` to dogecoin.conf yourself, or is that something that comes preconfigured? This could be a cause for the ReadBlockFromDisk error there at the top of your dogecoind log.

**Comment by IsaaacD** [comment]
`prune=25000` was added automatically as part of the install. I have enough space to run the un-pruned node but not sure how to update it as when I restart the container it re-writes the dogecoin.conf

**Comment by cent2sat** [comment]
FYI, you can view amount of nodes stuck at block 0 here:
https://blockchair.com/dogecoin/nodes 

Currently at 67 and rising every ~30min

**Comment by ReverseControl** [comment]
@IsaaacD Were you able to resolve this issue?

**Comment by Dibbyo456** [comment]
Having the exact same issue, has anyone found a fix?

**Comment by IsaaacD** [comment]
My issue was that I had setup a sync of both BTC and DOGE, I think they ran in contention for available resources on the server. I just installed a DOGE node, maybe it would be possible to add more coins once synced but I've not tried.

**Comment by ReverseControl** [comment]
@Dibbyo456  See @IsaaacD solution. Closing.

**Comment by ReverseControl** [comment]
@rnicoll  Could you look into this?

**Comment by eskimo** [comment]
I can also say that I synced a full node outside of btcpay then once I symbolic linked it to btcpay and it was pruned it broke it.

**Comment by patricklodder** [comment]
> I can also say that I synced a full node outside of btcpay then once I symbolic linked it to btcpay and it was pruned it broke it.

Broke it how? Have a debug log?

**Comment by eskimo** [comment]
It would get stuck on block 0

**Comment by rnicoll** [comment]
BtcPay really shouldn't be able to change the sync process. Can you check you're running 1.14.5, there's a lot of improvements in each version and the most likely explanation is something odd is happening with an older version.

If not, can you check your debug.log please? It will be in the Dogecoin data directory, i.e. "~/.dogecoin" on Linux - anything that might give us a hint, in the last hundred lines or so of the log?

**Comment by eskimo** [comment]
The version in btcpay is one version behind. Also, linking the directory is only for the chain stored, it doesn’t link the dogecoind.

**Comment by patricklodder** [comment]
@eskimo What was the value assigned to `prune` in the dogecoin.conf? Was it `prune=25000` as shown in the screenshot up above? Because that would not work in any case, as that means for dogecoind to always keep 25GB of data - so you won't have the first block if you sync with that parameter. 

Instead you probably want `prune=1` so that your explorer's indexer can call the height to prune to via RPC.

**Comment by eskimo** [comment]
Yes it had that in the config. I’m not super familiar with how btcpay works but it adds that to the conf somehow.

**Comment by patricklodder** [comment]
Alright, then that is probably the thing we'd want fixed. I'll have a look at their repo later this week but feel free to beat me to it 😁
