### ISSUE TITLE
Update max money

### ISSUE THREAD

**Issue by rnicoll** [dogecoin/dogecoin#1795]
The max money fix from https://github.com/dogecoin/dogecoin/commit/1be681a1b97b686f838af90682a57f2030d26015 needs to be introduced to Dogecoin, probably not mixed in with other work this time.

**Comment by CHIPofficial** [comment]
When will this major update be release

**Comment by rnicoll** [comment]
This work is in PR https://github.com/dogecoin/dogecoin/pull/1927, closing this to track in the PR instead.
