### ISSUE TITLE
Paper wallet generator crops out last character of dogecoin address

### ISSUE THREAD

**Issue by kumikumi** [dogecoin/dogecoin#1804]
#### If so, please list the steps to reproduce below:
1. Boot up tails linux from USB
2. Download and open Dogecoin core (qt)
3. File -> Print paper wallets

### Expected behaviour
User should be able to see entire dogecoin address

### Actual behaviour
User sees partial dogecoin address, with last character partially or entirely cropped out

### Screenshots.
The address in screenshot is not in use
![image 5VTX00](https://user-images.githubusercontent.com/3090631/111814585-8e7d0600-88d2-11eb-83ce-e7e9fa5d3f3b.png)

### What version of Dogecoin Core are you using?
1.14.3

### Machine specs:
- OS: Tails Linux (Live usb)

**Comment by patricklodder** [comment]
Confirm same behavior on OSX. Can someone on windows confirm?

**Comment by patricklodder** [comment]
Had it confirmed elsewhere that this is not the case on Windows.

Affected platforms: Linux and OSX.

**Comment by nukolauyi** [comment]
![Screenshot_2021-05-07-13-48-46-0541337064_EDIT_1](https://user-images.githubusercontent.com/22927632/117403702-2f835700-af3b-11eb-81d7-4f888143c328.png)
After printing paper wallet to PDF，there are white blocks cover some of the key and QR code. I have no idea to recover the correct private key and get my dogecoin back.

**Comment by slightlyskepticalpotat** [comment]
You can try the following steps. I was able to recover the address from
this, and I think you should be able to recover the private key.

1. Use an image editor to make the corner black boxes complete like this (
https://imgur.com/jzVqZE9).

2. Use QRazyBox (https://merricx.github.io/qrazybox/) New Project => Import
from Image => Tools => Extract QR Information

3. A window will pop up with part of the private key, you can
cross-reference that against the portion blanked out and/or the characters
at both ends.

Please let me know how this goes!

**Comment by slightlyskepticalpotat** [comment]
I am sorry to hear that you were not able to recover the key. However, I
tried manually reconstructing parts of the QR code and decoded more data
that correspond to parts of your private key. Do you have an email address
that I could contact you at, to send you the information?

**Comment by p-j01** [comment]
@patricklodder Seems fixed in #1805. Should it be closed?

**Comment by micaelmalta** [comment]
@patricklodder should it be closed?

**Comment by patricklodder** [comment]
Github closes this automagically on release of the functionality.
