### ISSUE TITLE
[QT] Feature request: Add a form dialog for adding peers

### ISSUE THREAD

**Issue by patricklodder** [dogecoin/dogecoin#1807]
### Rationale

Currently, shibes using the QT wallet do not have an easy way to add known peers other than using the RPC Console, but do have ways to disconnect and temporarily ban peers. By adding a dialog that can be triggered from the Debug Window -> Peers screen, interaction with the RPC Console can be prevented, which helps overall ease of use.

### Requested functionality

1.	Add a button to the "Peers" screen.
2.	Create a form dialog that allows input of an `address[:port]` combination (with the port as optional element defaulting to the network’s default port)
3.	Allow for adding and removing peers permanently and one-shot, without registering the peer as “addnode”, default to one-try.
4.	Add a kind warning to this dialog to not blindly trust anyone that tells you to add their node.

This feature should be relatively easy for new developer shibes to start contributing to Dogecoin Core.

**Comment by alamshafil** [comment]
This is my first time contributing to a open source project! Can't wait to put my first pull request! I attempted to implement the form dialog to add peers. I was not sure how to correctly use the RPC protocol, so I just used the RPCExecutor from the RPC Console. I will upload the pull request soon.

**Comment by patricklodder** [comment]
Merged into 1.14.4-dev with #1825
