### ISSUE TITLE
Feature request: Proof Of Stake, Smart Contracts

### ISSUE THREAD

**Issue by 0xnft** [dogecoin/dogecoin#1810]
Lets make Dogecoin great again making it useful with Proof Of Stake protocol and Smart Contracts

**Comment by shibe2** [comment]
Is Dogecoin not great already?

Current merge-mined PoW scheme is fine. We may want to rethink it at some point in the future, so go ahead and make your detailed proposal of transition to PoS, we will put it into archive until it will be needed, if ever.

**Comment by 0xnft** [comment]
> Is Dogecoin not great already?
> 
> Current merge-mined PoW scheme is fine. We may want to rethink it at some point in the future, so go ahead and make your detailed proposal of transition to PoS, we will put it into archive until it will be needed, if ever.

OK!
