### ISSUE TITLE
Dogecoin foundation 2.0?

### ISSUE THREAD

**Issue by jorellano** [dogecoin/dogecoin#1815]
How do we start this again, maybe focus on lessons learned from the first dogecoin foundation.

Who could i speak to and ask about starting a new foundation
@patricklodder ?

**Comment by shibe2** [comment]
Is this related to Dogecoin Core?

**Comment by patricklodder** [comment]
Dogecoin foundation 2.0 already was there and has failed. Feel free to start a discussion on https://reddit.com/r/dogecoindev if you want developer input to that idea.
