### ISSUE TITLE
Location of simplified variant of scrypt replacement from the sha256

### ISSUE THREAD

**Issue by bvandorf** [dogecoin/dogecoin#1826]
wherein the codebase was this done? I would like to look at it.

"although it does not use SHA256 as its proof of work (POW). Taking development cues from Tenebrix and Litecoin, Dogecoin currently employs a simplified variant of scrypt"

**Comment by patricklodder** [comment]
https://github.com/dogecoin/dogecoin/blob/0b46a40ed125d7bf4b5a485b91350bc8bdc48fc8/src/primitives/pureheader.cpp#L28

**Comment by bvandorf** [comment]
Thank You so much for the help
