### ISSUE TITLE
1.21 Update miner test blocks

### ISSUE THREAD

**Issue by rnicoll** [dogecoin/dogecoin#1832]
Once we have Dogecoin consensus parameters in place, we need to generate 240 blocks for `miner_tests.cpp`, as per the comment https://github.com/dogecoin/dogecoin/pull/1780/files#diff-b12066a688b85bea440eb38f079fb8ecc1984318470631bca7e3547a98effaa9R218 , and then re-enable this test.

**Comment by rnicoll** [comment]
Resolved by https://github.com/dogecoin/dogecoin/pull/1828

**Comment by ReverseControl** [comment]
@rnicoll Closing as it has been resolved.
