### ISSUE TITLE
Make not working in Build.

### ISSUE THREAD

**Issue by NtemKenyor** [dogecoin/dogecoin#1837]
This issue tracker is only for technical issues related to Dogecoin Core.

For general questions about Dogecoin please use one of the various communities, e.g. Reddit, IRC, Discord, etc.

### Describe the issue
I have issues installing the latest version of dogecoin.
### Can you reliably reproduce the issue?
I installed all the necessary packages following the guide in build doc. However, The last command, that is the make command does not work on my PC.
#### If so, please list the steps to reproduce below:
1. Install all Necessary Packages
2. Make the build for dogecoin-qt

### Expected behaviour
I felt this commands "make" or "make install" should build the entire project and create the dogecoin.qt

### Actual behaviour
make command returns an error saying "target is not specified". the make install command returns an error saying "no rule to install"

### What version of Dogecoin Core are you using?
I am using the most recent version.

### Machine specs:
- OS: Linux
- RAM:4
- Disk size:500
- Disk Type (HD/SDD):HD

I would like to know if there is a better way or a complete way to type the make command.

**Comment by alamshafil** [comment]
I am not sure what problem you might have. I am not a expert in C++. I got my dogecoin-qt to compile by using these commands:
```
./autogen.sh  
./configure --with-incompatible-bdb  
make
```
I used `--with-incompatible-bdb` because I had an incompatible version of BerkelyDB.

Make sure you have the Qt libraries and Boost libraries and also make sure you are in the right folder.

**Comment by NtemKenyor** [comment]
ok thanks guys. I found out that I was not in the right directory. I moved to App_root/depends and then everything worked just fine.

**Comment by alamshafil** [comment]
The app will be in `App_root/src/qt/dogecoin-qt`, so if you can't find it, try doing `make` in `App_root/src`.
The first compile will take a while, but the second compile will be fast.

Glad I could help!!

**Comment by jesuasir007** [comment]
./configure --disable-wallet 

use this to fix that problem .

**Comment by ReverseControl** [comment]
Closing issue as it has been resolved.
