### ISSUE TITLE
I might have someone who can recover your wallet.dat file - waiting for confirmation

### ISSUE THREAD

**Issue by kitcateleven** [dogecoin/dogecoin#1839]
> > Yes. I agree that there is something wrong with the older doge core version or network. I still have old wallet.dat and a dump file. No such address in it. Again, to remind, I never entered output change address. My only mistake was that I closed Doge Core not waiting for full synchronization after I sent coins. Could it be previous wallet.dat ? I recovered all old wallet.dat files with EasUS Data Recover with no such address. Perhaps data got corrupted as I was experimenting with other cryptos ( EarthCoin, Philosopherstone,...), But why other transactions went through without a glitch? I am not an expert.....
> > P.S. If someone is a reputable expert in recovering corrupted wallet.dat or have any ideas let me know. Bounty 10%-20%

_Originally posted by @tcon44 in https://github.com/dogecoin/dogecoin/issues/1823#issuecomment-821990236_

**Comment by kitcateleven** [comment]
I am pooling resources....let me know if you were able to recover the wallet. When I hear back, I will connect you with the experts directly

**Comment by etherx-dev** [comment]
Hey everyone! don't send wallets to people you found online watch out for scams. i can't find my wallet either but no reason to get scammed.

**Comment by kitcateleven** [comment]
Very true!  

When/if I hear back from my resources - what’s a safe way to connect someone w a corrupt wallet with someone who can fix it?  I have to be secure, on my end too.  

Thank you!

Cat Mayville, President
Spot Digital Media
404-357-4503

**Comment by dannydeezy** [comment]
Hello, I have experience doing this. Here is my Twitter account where I've helped several people with wallet.dat files.
https://twitter.com/dannydiekroeger/status/1350481631069437954
Feel free to DM me there on Twitter, or email me at dannydiekroeger@gmail.com

**Comment by dannydeezy** [comment]
Hey, sorry for the delay. I can definitely help! Can you describe more
details about your situation?

**Comment by dannydeezy** [comment]
I'm pretty sure that "phantom" address is a change address that your
private key controls, but the wallet has fallen out of sync so it appears
like you don't own it, when in fact you do

**Comment by dannydeezy** [comment]
Have you tried going into your Dogecoin Debug Console and typing
"listaddressgroupings" ?

**Comment by tcon44** [comment]
Yes I have tried list address groupings.  It might be on Poloniex.   In one of my accounts there.  I remember when I was trading Potcoin on Poloniex you could tell from the block explorer all the accounts that were in Poloniex.   I would like to be able to do that here

**Comment by dannydeezy** [comment]
In that case you should try logging into Poloniex and look at your
transaction history to see if that transaction is showing up.

I know Poloniex was deactivated for US customers but you can still login
here
https://poloniexus.circle.com/

**Comment by tcon44** [comment]
They are denying that they have control of that address.  So either they are lying or I am back to square 1.
 Either way one thing is for sure.....I did not send the coins to that address.  The wallet automatically sent the coins.  So the address has to be either known to the wallet and you would think it was because it has a label of Poly or the Waller generated the address when it sent the coins.  I have both laptops I used during that time.  I had a Dogecoin developer log into my one laptop and saw that the address was labeled.  The answer has to be on one of these two laptops

**Comment by michaelnwanna** [comment]
I have a similar issue. My funds are stuck in the Phantom address which recieved the Doge immediately after I backed up my wallet from the Doge Android client app.
https://dogechain.info/tx/8d0005ce525ddfc55835563011f98cba86b4c5dca71690308cee21f3202b2928

**Comment by tcon44** [comment]
I think that is the issue that several people have had .  And I’m sorry but that is a network issue and of the coins cannot be recovered the developers community founders - someone needs to help us here.  If it’s user error we take it on the head but not when atleast 5 cases have turned up in the past month.  Some recent and some like mine 5 years old this June.  

What it means is this is a persistent problem and needs to be addressed and taken care of retroactively.
