### ISSUE TITLE
how to create a wallet in dogecoin-cli 

### ISSUE THREAD

**Issue by jackynanshan** [dogecoin/dogecoin#1847]
how to create a wallet in dogecoin-cli 

This issue tracker is only for technical issues related to Dogecoin Core.

For general questions about Dogecoin please use one of the various communities, e.g. Reddit, IRC, Discord, etc.

#### If so, please list the steps to reproduce below:
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of Dogecoin Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by Mouradif** [comment]
when your node is running you already have a wallet with a default account that has no name (empty string). You can do
```
$ dogecoin-cli listaccounts
```
to see it (and its balance). You can get the address with
```
$ dogecoin-cli getaccountaddress ""
```

Sadly, everyone seems to think the info is obvious but it's not. I've been searching for a long time on how to use the cli, I found countless links to forums where someone asked the question and people answered "RTFM". Running `dogecoin-cli --help` shows the options but not the commands. I ended up looking for bitcon cli commands instead and so far, everything seems to work the same : 

https://en.bitcoin.it/wiki/Original_Bitcoin_client/API_calls_list

**Comment by jackynanshan** [comment]
Hi Mourad,

got some help, Thanks!

Jacky

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Mourad Kejji ***@***.***>
发送时间: Friday, April 23, 2021 12:33:37 AM
收件人: dogecoin/dogecoin ***@***.***>
抄送: jackynanshan ***@***.***>; Author ***@***.***>
主题: Re: [dogecoin/dogecoin] how to create a wallet in dogecoin-cli (#1847)


when your node is running you already have a wallet with a default account that has no name (empty string). You can do

$ dogecoin-cli listaccounts


to see it (and its balance). You can get the address with

$ dogecoin-cli getaccountaddress ""


Sadly, everyone seems to think the info is obvious but it's not. I've been searching for a long time on how to use the cli, I found countless links to forums where someone asked the question and people answered "RTFM". Running dogecoin-cli --help shows the options but not the commands. I ended up looking for bitcon cli commands instead and so far, everything seems to work the same :

https://en.bitcoin.it/wiki/Original_Bitcoin_client/API_calls_list<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fen.bitcoin.it%2Fwiki%2FOriginal_Bitcoin_client%2FAPI_calls_list&data=04%7C01%7C%7C110e5e8232c44efea5f108d905ac61c3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637547060196558351%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=5tEBg7lG6gp1JHRtfYrhxYe7hifhoATOpHlCuXFH3sY%3D&reserved=0>

―
