### ISSUE TITLE
无法发送

### ISSUE THREAD

**Issue by erhuodoudou** [dogecoin/dogecoin#1848]
![Screenshot_2021-04-22-20-23-14-563_de langerhans wallet](https://user-images.githubusercontent.com/80367004/115724544-9e957300-a3b3-11eb-892e-a10a7b1a784c.jpg)

**Comment by shibe2** [comment]
https://github.com/langerhans/dogecoin-wallet-new/issues

**Comment by rnicoll** [comment]
Looks like the software's out of date?

**Comment by btc2dogecom** [comment]
try to update your wallet first. make a backup first. you can get 4.0.0 software here: https://github.com/langerhans/dogecoin-wallet-new/releases/download/4.0.0/wallet-4.0.0-prod-release.apk

**Comment by erhuodoudou** [comment]
> 看起来软件已经过时了吗？

on，is 4.0.0

**Comment by erhuodoudou** [comment]
NO is 4.0.0

**Comment by erhuodoudou** [comment]
Android 4.0.0 app

**Comment by erhuodoudou** [comment]
> https://github.com/langerhans/dogecoin-wallet-new/issues

要在电脑上操作吗？我想下次钱包更新，这个问题能自己解决吗？
