### ISSUE TITLE
Can the DogeCoind work with a miner directly?

### ISSUE THREAD

**Issue by jackynanshan** [dogecoin/dogecoin#1851]
Hi, 

Can the DogeCoind work with a miner in solo? I want to mine the DogeCoin.

My platform are:
Ubuntu
RTX 1080
CUDA 11.2

If you can give me some help, I will appreciate you in DogeCoin.

Thanks!

Jacky Wang

**Comment by muheezahamed** [comment]
No It doesn't

**Comment by jackynanshan** [comment]
How can I mine the DogeCoin in solo not in pool? Can you give me some suggestion?

Thanks!

Jacky

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: ***@***.***>
发送时间: 2021年4月25日 0:14
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [dogecoin/dogecoin] Can the DogeCoind work with a miner directly? (#1851)


No It doesn't

―

**Comment by nformant1** [comment]
I hope it is ok to post the link to my summary on [reddit](https://www.reddit.com/r/dogeducation/comments/mtjo6a/solo_merged_mining_doge_and_ltc_local_cpu_and_asic/)!
In the comments there is a link to bitcointalk where you can get additional information!

This shows how to setup a **local P2Pool with merged mining** (LTC and Dogecoin).

I hope you don't mind the additional LTC node you need for this. For all mining software pointing directly at the Dogecoin Core Wallet, I had issues with the `getblocktemplate`. But usually it makes great sense to always take advantage of AuxPoW as a miner.

If you want to send a tip: D8kAJRyL9UzUjNaBQCLbe6TxxgE8xT66NA

**Comment by sxtysgj** [comment]
您好我有一个蚂蚁L3++目前在蚂蚁矿池挖矿，如何切换到自己挖狗币

**Comment by jackynanshan** [comment]
你好！
我对蚂蚁矿机不了解，该矿机是运行什么操作系统的？如果是Linux或windows的，还有可能。但蚂蚁矿机是ASIC专用芯片架构，算法是固定的，不知道能不能用。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: ***@***.***>
发送时间: 2021年4月26日 12:56
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [dogecoin/dogecoin] Can the DogeCoind work with a miner directly? (#1851)


您好我有一个蚂蚁L3++目前在蚂蚁矿池挖矿，如何切换到自己挖狗币

―

**Comment by ReverseControl** [comment]
I think this question has been asked before. As the question has been answered, and help provided on the follow up, I am closing this one.
