### ISSUE TITLE
Dogecoins gone??

### ISSUE THREAD

**Issue by paulpur** [dogecoin/dogecoin#1852]
Hi, sorry if this has been covered before but i couldnt see anything, i recently transferred some dogecoin from binance to my dogecoin core wallet, however, it was immediately transferred out and now my wallet shows zero as balance....was it stolen? 

any help would be much appreciated

the only transaction that is actually mines, is the 190 transferred into the wallet, i am not sure what is going on...

![doge1](https://user-images.githubusercontent.com/83097258/115934143-597a4b00-a45e-11eb-9a84-9458c86be808.jpg)

**Comment by paulpur** [comment]
anyone any help please?

**Comment by shibe2** [comment]
You seem to have both incoming and outgoing transactions that you don't recognize. It may be that you tried to use someone else's wallet. In that case, they have control over it.

One possible explanation is that it accidentally generated the same seed as someone else.

One possible explanation is that you already had wallet.dat on your computer when you installed Dogecoin Core.

**Comment by paulpur** [comment]
thanks for the reply shibe2, this is my 1st experience with dogecoin, so have never installed dogecoin core until now, ive no idea how i could possibly use someone elses wallet, i just installed this :(

**Comment by mrbianchi** [comment]
binance's tx id?

**Comment by delbonis** [comment]
@paulpur Your best bet would be to reinstall Windows and/or use a mobile wallet.  Your computer appears to be compromised.  Unfortunately there probably isn't anything you can do to recover the funds.

**Comment by paulpur** [comment]
thank you for your help folks, oh well, least it wasnt a lot of money lol :)

**Comment by darrenkis** [comment]
> Hi, sorry if this has been covered before but i couldnt see anything, i recently transferred some dogecoin from binance to my dogecoin core wallet, however, it was immediately transferred out and now my wallet shows zero as balance....was it stolen?
> 
> any help would be much appreciated
> 
> the only transaction that is actually mines, is the 190 transferred into the wallet, i am not sure what is going on...
> 
> ![doge1](https://user-images.githubusercontent.com/83097258/115934143-597a4b00-a45e-11eb-9a84-9458c86be808.jpg)

LoL

**Comment by patrickdugan** [comment]
If anyone wants to give me admin privs enough to close all the random non-dev related tickets like this, feel free.
