### ISSUE TITLE
Listing with PundiX

### ISSUE THREAD

**Issue by toneavii** [dogecoin/dogecoin#1854]
It has come to my attention that the majority of our clients are requesting to accept payments in dogecoin at physical business locations. 

The issue is they are currently accepting coins/tokens via the PundiX XPOS (PundiX Point of sales system) which does not have the developer listing via the Open Platform listed PundiX official website.   

[](https://developer.pundix.com)

![image](https://user-images.githubusercontent.com/81331047/115971598-356e4680-a4fe-11eb-8fad-a1c4d95fb300.png)

**Comment by shibe2** [comment]
>accept payments in dogecoin at physical business locations

That's cool!

>which does not have the developer listing

What needs to be listed? How is it related to Dogecoin Core?

**Comment by toneavii** [comment]
To my knowledge there is two methods which can only be achieved by dogecoin devs [listing](https://developer.pundix.com/login)

Or by direct email to list so all of our stores can start accepting doge. That's all our stores want to accept now. 

Direct contact with PundiX which has been prepared by PundiX telegram for immediate response is Peko@pundix.com

Thanks a lot guys. 
Cameron

**Comment by shibe2** [comment]
What needs to be listed? How is it related to Dogecoin Core?

**Comment by toneavii** [comment]
A developer from team must submit or list with PundiX due to regulatory monetary compliance standards. 

If this does not relate to your line of contributions, excuse my questioning.

**Comment by patricklodder** [comment]
> regulatory monetary compliance standards.

Could you please link the standards you are referring to? Also would be great to know how you have solved this with Bitcoin.

**Comment by toneavii** [comment]
>> Could you please link the standards you are referring to? Also would be great to know how you have solved this with Bitcoin.

Tbh, I am currently not part of official PundiX team. Our clients, which posses the POS System is requesting the option to allow dogecoin. 

The standards I am referring to are in place for ALL pos systems, which PundiX has partnered with. This includes the 3 largest pos companies as well as the standards which are required for integration with PayPal, which PundiX has accomplished.  

If more information is needed please email peko@pundix.com

**Comment by incognitojam** [comment]
Dogecoin is not an ERC20 / BEP2 token, so I'm not sure whether it can actually be listed on this site.
![Screenshot 2021-04-25 at 16 45 35](https://user-images.githubusercontent.com/4038174/115999889-aa687b80-a5e5-11eb-8a91-7bb02b4d8092.png)

**Comment by shibe2** [comment]
@toneavii Then maybe you could contact PundiX yourself and find out what exactly is required and why. And whether they can support Dogecoin payments at all.

**Comment by toneavii** [comment]
> @toneavii Then maybe you could contact PundiX yourself and find out what exactly is required and why. And whether they can support Dogecoin payments at all.

![image](https://user-images.githubusercontent.com/81331047/116001148-f85e8e80-a5a7-11eb-8384-a1c423959b72.jpeg)

I asked via telegram yesterday and he response was to directly email peko so they can get everything setup. 

In relation to the erc or bep, I believe with the main net launch they will accept doge. 

Don't quote me on that. I'm only a dedicated noob.

**Comment by patricklodder** [comment]
Noted. Will reach out. Since this has nothing to do with Dogecoin Core, though, I will close this issue.

**Comment by toneavii** [comment]
![image](https://user-images.githubusercontent.com/81331047/116960536-821bf500-ac55-11eb-857f-3797a3e5a4f7.png) received email today stating no contact yet. I know your busy guys. Our businesses that use the XPOS are requesting the eligibility to utilize doge. 

Only thing is that PundiX has to have listing information. indra@pundix.com is for direct contact.

**Comment by toneavii** [comment]
> Noted. Will reach out. Since this has nothing to do with Dogecoin Core, though, I will close this issue. 
@patricklodder I left email for direct contact above.

**Comment by shibe2** [comment]
@toneavii Maybe you could accelerate the process if you obtained and shared the following information:
* What exactly needs to be listed for Dogecoin?
* What kind of person would be eligible to represent Dogecoin for regulatory purposes?
* Text of applicable laws and regulations that require such listing.
* Did they make an exception from the requirement for Bitcoin and Ethereum?
* Could they make the same exception for Dogecoin?

**Comment by toneavii** [comment]
Response from PundiX 

Thanks for your email. For Bitcoin and Ethereum, there is an exception from Monetary Authority of Singapore to exclude all the required documents and it is acceptable by the law.

For Dogecoin, we will need the team to send us these documents for Compliance review :
- Company registration
- Legal Opinion issued by Singapore law firm that covers the Payment act requirement ( can discuss with me for more details, if the team has any question).

We will need this for review before we can move forward to the next step.

**Comment by Splash0Beach** [comment]
WTAF I have zero idea who scammers are. Remove me from this

**Comment by shibe2** [comment]
>Company registration

It looks like we are stuck here. AFAIK, there is no company / legal entity for Dogecoin, and thus there is no registration. I see two ways from here:
1. You or some other interested party registers a company that will represent Dogecoin for Singapore's authority.
2. Require official exception for Dogecoin, similar to existing exceptions.

Here some further information would be useful:
* What kind of company would be eligible to represent Dogecoin for regulatory purposes?
* Text of applicable laws and regulations.
* What is the basis for the exception for Bitcoin and Ethereum?

**Comment by toneavii** [comment]
PundiX response; 

Hi Cameron,

We cannot register the entity for Dogecoin, it must be done by the team. And for the exception, we have no control on it because it come from regulators itself.

Regarding for the entity registration, I do not think there is a regulations on it, but usually the token owner/issuer is using a Foundation.

Again, this needs to come from the team itself.

Please let us know if there is any update on this.

Thanks in advance.

-- 
Best Regards,
Indra Winarta

**Comment by shibe2** [comment]
>And for the exception, we have no control on it because it come from regulators itself.

Yeah, my idea was that exception for Dogecoin would also come from the regulator. I think, we should contact the regulator about that and not PundiX.

>usually the token owner/issuer is using a Foundation

AFAIK, currently, there is no functioning Dogecoin Foundation or something like that.

>Regarding for the entity registration, I do not think there is a regulations on it

Then anyone can do it and not necessarily "the team". To be sure, we could read

>Text of applicable laws and regulations.

**Comment by sabotagebeats** [comment]
Hello, 
Dogecoin is decentralized and does not have a foundation nor a business entity. Therefore no business registration is required and the only work need be done by the pundix team. This should be an issue on pundix not on dogecoin. I have looked there seem to be a variety of repos, but mostly referring to only erc20 tokens. 
https://github.com/pundix
@toneavii can you please advise where we need to file this as an issue for the pundix team?

**Comment by toneavii** [comment]
> @toneavii can you please advise where we need to file this as an issue for the pundix team? 

I can. TY

**Comment by toneavii** [comment]
> Dogecoin is decentralized and does not have a foundation nor a business entity. Therefore no business registration is required and the only work need be done by the pundix team. This should be an issue on pundix not on dogecoin. I have looked there seem to be a variety of repos, but mostly referring to only erc20 tokens. 
> 

Now that Elon is working with you guys direct, is there a way to make this possible. Such as foundation?

**Comment by sabotagebeats** [comment]
@toneavii 

This isn't an issue with Dogecoin, this is an issue with Pundix. As has been said multiple times Dogecoin is decentralized and doesn't have a foundation. Kindly advise me where to add the issue on Pundix GitHub for them to add Dogecoin and I will be happy to raise the issue.

**Comment by toneavii** [comment]
> Noted. Will reach out. Since this has nothing to do with Dogecoin Core, though, I will close this issue.

Have you been able to reach Peko at PundiX? 

@sabotagebeats please allow Patrick and the devs to work on this. Thanks for your input.

**Comment by shibe2** [comment]
@toneavii Have you contacted Monetary Authority of Singapor about exception for Dogecoin? Have you obtained the text of laws and regulations that require company registration and legal opinion for cryptocurrencies?

**Comment by toneavii** [comment]
I am in direct contact with PundiX. Will hold conference call tomorrow morning.

**Comment by toneavii** [comment]
> @toneavii Have you obtained the text of laws and regulations that require company registration and legal opinion for cryptocurrencies?

[MAS](https://www.mas.gov.sg/~/media/MAS/News%20and%20Publications/Monographs%20and%20Information%20Papers/Guide%20to%20Digital%20Token%20Offerings%20last%20updated%20on%2030%20Nov.pdf) SCANNING THE DOCUMENT FOR FURTHER INFORMATION

**Comment by shibe2** [comment]
I read the beginning of "A GUIDE TODIGITAL TOKENOFFERINGS". It is clear that it is not applicable to our case of accepting Dogecoin payments. The guidance is about securities, and Dogecoin is not a security. I haven't read the referred laws, but at least Dogecoin doesn't match any of the criteria listed in the guidance. Case study 6, while is not an exact match for our case, is an example of how Dogecoin would be treated:

>digital payment tokens (such as Bitcoin) that do not constitute securities, derivatives contracts or units in CIS

>the SFA will not apply

>while the activity of establising or operating a digital payment tokens exchange is presently not regulated by MAS, MAS intends to regulate such activity for AML/CFT purpose only under the PSB

I think that Pundi X activity would be regulated under "Payment Services Act" https://sso.agc.gov.sg/Act/PSA2019 We need to read that instead.

Important things to note are that current Dogecoin developers:
* did not create Dogecoin,
* do not issue dogecoins,
* do not operate the Dogecoin network,
* do not have direct control over Dogecoin (any changes to Dogecoin software need to be accepted by Dogecoin users and miners, or they will have no effect).

Most likely, the developers don't have to be involved in legal formalities required for accepting Dogecoin payments.

**Comment by toneavii** [comment]
"Most likely, the developers don't have to be involved in legal formalities required for accepting Dogecoin payments."

Your assumption here is correct after speaking with PundiX team. 

Pundi X can only list the token that follows the MAS regulations, or if there is no entity registered, it should be in the list provided by MAS (Which is not).

Good note: PundiX is currently in the process of obtaining the payment license.

No time frame given. Will establish contact with MAS for entry into listing. This is the way!

**Comment by toneavii** [comment]
> Most likely, the developers don't have to be involved in legal formalities required for accepting Dogecoin payments.


Your assumption here is correct after speaking with PundiX team. 

Pundi X can only list the token that follows the MAS regulations, or if there is no entity registered, it should be in the list provided by MAS (Which is not).

Good note: PundiX is currently in the process of obtaining the payment license.

No time frame given. Will establish contact with MAS for entry into listing. This is the way!

**Comment by toneavii** [comment]
@shibe2 ![image](https://user-images.githubusercontent.com/81331047/118572301-f619cb00-b734-11eb-9062-b13c2b5e2a57.png)

Spoke with New York division. Email response. Will follow with updates as they are received.

**Comment by sabotagebeats** [comment]
Since this issue is closed I will be muting this further notifications. Best regards.

**Comment by toneavii** [comment]
Now that there is a foundation, can we continue with the PundiX listing?

**Comment by shibe2** [comment]
@toneavii Why did you stop? What do you need foundation for? I thought that Dogecoin would be handled the same way as Bitcoin and Ethereum, and no formal organization would be needed for your purposes.

If it will turn out that you absolutely do need Dogecoin foundation to accept payments, please contact the foundation directly.

**Comment by toneavii** [comment]
@shibe2 My good sir I have worked tirelessly to make this a reality. I am not a team member of PUNDI, therefore I have limited power. 

That is the reasoning. Who shall be the direct contact for foundation?

**Comment by shibe2** [comment]
I don't know much about Dogecoin Foundation. It was doing charity projects in the past. All I that heard about new foundation is couple of tweets and this handle: https://twitter.com/DogecoinFdn
