### ISSUE TITLE
[Feature] Purge function

### ISSUE THREAD

**Issue by LLKoder** [dogecoin/dogecoin#1855]
Hello,

Do plan to make Purge function for Dogecoin Core like in Bitcoin Core? It would be nice if the database has a smaller size (2GB or any fixed size).

For likers MultiDoge, sorry, but I like Dogecoin Core.

**Comment by patricklodder** [comment]
Hi! Have you tried configuring pruning? You can set the pruning parameters in dogecoin.conf just like with Bitcoin Core.

**Comment by LLKoder** [comment]
I don't see it on the menu. Or do you mean it existent but not via GUI and I have to edit the config manually?

**Comment by patricklodder** [comment]
You'll have to add the following in your `dogecoin.conf` file:

```
prune=SIZE_IN_MB
```

Where `SIZE_IN_MB` is greater than `2200`. Alternatively you can set this to `1`, and then you can prune the blockchain manually from the RPC console, using `pruneblockchain HEIGHT`, where `HEIGHT` is the height you'd like to prune to.

This will become more user-friendly when we release the next major release.

Hope it helps!

**Comment by LLKoder** [comment]
It is great news for me I thought Dogecoin Core didn't support this function for now. I'm glad I'm wrong. :)
