### ISSUE TITLE
make command not working in Mac OS 

### ISSUE THREAD

**Issue by jesuasir007** [dogecoin/dogecoin#1860]
dogecoin % make   

make: *** No targets specified and no makefile found.  Stop.

Clone the dogecoin source code and cd into dogecoin

 git clone https://github.com/dogecoin/dogecoin
 cd dogecoin
Build dogecoin:

Configure and build the headless dogecoin binaries as well as the GUI (if Qt is found).

You can disable the GUI build by passing --without-gui to configure.

./autogen.sh
./configure
make

I have used this steps 

make command not working ,I have try with macOS terminal.

**Comment by incognitojam** [comment]
What is the output from the `./configure` command? The output from `make` suggests that configure never ran successfully.

**Comment by jesuasir007** [comment]
./configure --disable-wallet 

I have run that code to fix that problem .
