### ISSUE TITLE
error: no matching function for call to 'objc_msgSend'

### ISSUE THREAD

**Issue by jesuasir007** [dogecoin/dogecoin#1862]
I have run the make command in  Mac terminal

facing this issues  

qt/macdockiconhandler.mm:35:18: error: no matching function for call to 'objc_msgSend'
    id appInst = objc_msgSend((id)cls, sel_registerName("sharedApplication"));
                 ^~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/objc/message.h:63:1: note: candidate function not viable: requires 0 arguments, but 2 were provided
objc_msgSend(void /* id self, SEL op, ... */ )
^
qt/macdockiconhandler.mm:38:23: error: no matching function for call to 'objc_msgSend'
        id delegate = objc_msgSend(appInst, sel_registerName("delegate"));
                      ^~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/objc/message.h:63:1: note: candidate function not viable: requires 0 arguments, but 2 were provided
objc_msgSend(void /* id self, SEL op, ... */ )
^
qt/macdockiconhandler.mm:39:33: error: no matching function for call to 'objc_msgSend'
        Class delClass = (Class)objc_msgSend(delegate,  sel_registerName("class"));
                                ^~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/objc/message.h:63:1: note: candidate function not viable: requires 0 arguments, but 2 were provided
objc_msgSend(void /* id self, SEL op, ... */ )
^
3 errors generated.
make[2]: *** [qt/dogecoin_qt-macdockiconhandler.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1

I am using Mac OS bigsur how can I fix it please share your solutions .

**Comment by kobiebotha** [comment]
I am having the same issue, macOS Big Sur

**Comment by kobiebotha** [comment]
@jesuasir007 something that seems to have worked for me is just to disable Qt support as a workaround and just use the CLI:

./configure --with-gui=no
make

**Comment by jesuasir007** [comment]
ok thank you.

**Comment by jesuasir007** [comment]
hi how to customise the doge coin source code to other coin .

**Comment by jesuasir007** [comment]
> @jesuasir007 something that seems to have worked for me is just to disable Qt support as a workaround and just use the CLI:
> 
> ```
> ./configure --with-gui=no
> make
> ```


hi how to create own blockchain by using dogecoin source code ,to rename and create a new coin like lite coin .

**Comment by BitLox** [comment]
Hi, same issue with `objc_msgSend`, it's something with Qt, what version were you guys using? I'm using Qt 5.15.2

**Comment by jesuasir007** [comment]
https://github.com/michelvankessel/blackcoin-more/commit/110367de6acf168afbcc522d83817f5a646e8eb5

please check to fix the issues.

**Comment by jesuasir007** [comment]
> Hi, same issue with `objc_msgSend`, it's something with Qt, what version were you guys using? I'm using Qt 5.15.2

try it

https://github.com/michelvankessel/blackcoin-more/commit/110367de6acf168afbcc522d83817f5a646e8eb5

**Comment by BitLox** [comment]
Hey thanks, I noticed they had resolved this in the latest Bitcoin versions, but it was too deeply enmeshed to pull just the relevant parts from there. This looks much more concise.

**Comment by BitLox** [comment]
This error appears to be fixed in 1.21-dev which compiles and runs fine as far as I can tell, but does not have the branding assets ported.

**Comment by ReverseControl** [comment]
Issue fixed by #2333.
