### ISSUE TITLE
Core detected as malware in McAfee

### ISSUE THREAD

**Issue by ak77388** [dogecoin/dogecoin#1864]
![Capture](https://user-images.githubusercontent.com/61809266/116720087-6ab4e180-a9a1-11eb-9ab2-29c11cfa8816.JPG)

**Comment by CHIPofficial** [comment]
Turn off the antivirus when downloading any mining software.

**Comment by freelancing-solutions** [comment]
Well the only possible fix is to uninstall Mcafee or ....yeah there's is nothing, 
Why are you using McAfee to start with ....

**Comment by patricklodder** [comment]
Did you contact McAfee?

**Comment by gubatron** [comment]
does this happen when you build from source? or did you download a binary? watch out.

**Comment by sunnirise** [comment]
You should be able to create an exception for this particular file. 

https://service.mcafee.com/webcenter/portal/oracle/webcenter/page/scopedMD/s55728c97_466d_4ddb_952d_05484ea932c6/Page29.jspx?wc.contextURL=%2Fspaces%2Fcp&articleId=TS102056&_afrLoop=497186380287715&leftWidth=0%25&showFooter=false&showHeader=false&rightWidth=0%25&centerWidth=100%25#!%40%40%3FshowFooter%3Dfalse%26_afrLoop%3D497186380287715%26articleId%3DTS102056%26leftWidth%3D0%2525%26showHeader%3Dfalse%26wc.contextURL%3D%252Fspaces%252Fcp%26rightWidth%3D0%2525%26centerWidth%3D100%2525%26_adf.ctrl-state%3Dnsdb36fc3_9
