### ISSUE TITLE
Web3 connection with Etherscan.io

### ISSUE THREAD

**Issue by atyhieu** [dogecoin/dogecoin#1868]
Web3 connection with Etherscan.io

__Originally posted by @PaulinaParangerHr in https://github.com/etherscan/writecontract/pull/68__

__Originally posted by @atyhieu in https://github.com/crypto-com/swap-token-list/issues/53__

__Originally posted by @atyhieu in https://github.com/atyhieu/cd-facebook-java-ads-sdk-/issues/3__

**Comment by shibe2** [comment]
How is this related to Dogecoin?
