### ISSUE TITLE
Detected as malware by major antivirus

### ISSUE THREAD

**Issue by vishwaphansal7** [dogecoin/dogecoin#1870]
This issue tracker is only for technical issues related to Dogecoin Core.

For general questions about Dogecoin please use one of the various communities, e.g. Reddit, IRC, Discord, etc.

#### If so, please list the steps to reproduce below:
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of Dogecoin Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by patricklodder** [comment]
Could you please give more details?

**Comment by vishwaphansal7** [comment]
its getting blocked by the antivirus when trying to install core need to disable antivirus or uninstall it is there any other way around if you can tell

**Comment by patricklodder** [comment]
1. If you are using one of the binaries from our release page, contact your antivirus provider and tell them they have a false positive and they should exclude this particular file, or
2. if you built the binaries by yourself, make sure you don't have any supply chain injections, and then do the same.

**Comment by sunnirise** [comment]
You must create an exception within the antivirus to allow the download to proceed.

**Comment by ReverseControl** [comment]
@patricklodder @sunnirise Already addressed this issue above.
