### ISSUE TITLE
Update CONTRIBUTING.md to remove the references to Bitcoin Core and produce an actual contribution guideline document

### ISSUE THREAD

**Issue by danielmbradley** [dogecoin/dogecoin#1872]
### Describe the issue

The document outlining contribution guidelines for this project appears to still contain significant references to the Bitcoin Core project it was forked from. This would probably need to be addressed and an actual document specific to the Dogecoin Project produced with input from all current contributors.

**Comment by patricklodder** [comment]
Fair point. I don't think anyone ever considered updating that document, but it's good documentation to have.

I'll put it on my TODO for later on, and hope someone beats me to it 😁

**Comment by danielmbradley** [comment]
> Fair point. I don't think anyone ever considered updating that document, but it's good documentation to have.
> 
> I'll put it on my TODO for later on, and hope someone beats me to it 😁

Great! I might give it a look too, but have uni exams for the next 3 weeks so may not be able to get to it before you. Would be good to give a general outline in terms of a style guide, who needs to approve a pull request, etc!

**Comment by miaryafar** [comment]
don't worry about that.
that file was edited in 1.14.4-dev

**Comment by micheleberardi** [comment]
hi guys how can i help you ? i can work on italia translate if you need it

**Comment by rnicoll** [comment]
I've raised https://github.com/dogecoin/dogecoin/pull/2111 which includes some earlier work as well, hopefully that's a step in the right direction.
