### ISSUE TITLE
bitcoin_en.ts out of date

### ISSUE THREAD

**Issue by slightlyskepticalpotat** [dogecoin/dogecoin#1875]
### Expected behaviour
src/qt/bitcoin_en.ts should be updated with the strings inside Dogecoin's source code to make the other translations work. 

### Actual behaviour
It still has the original strings (as far as I can tell) from Litecoin.

**Comment by patricklodder** [comment]
On which branch?

**Comment by slightlyskepticalpotat** [comment]
My bad, I thought I had switched to the main branch but I was on the 1.21.1 dev branch.
