### ISSUE TITLE
Forgot dogewallet password

### ISSUE THREAD

**Issue by uzair552** [dogecoin/dogecoin#1885]
Kindly someone help me to recover my dogechain wallet password please

**Comment by danielmbradley** [comment]
> Kindly someone help me to recover my dogechain wallet password please

This is not possible if you do not have the password. The application encrypts the wallet and as such, loss of the password means loss the of the underlying asset contained in the wallet. Apologies but whatever was in that wallet is now permanently lost.

**Comment by darrenkis** [comment]
> Kindly someone help me to recover my dogechain wallet password please

No.

**Comment by doge2021** [comment]
> Kindly someone help me to recover my dogechain wallet password please
the password cant reset as they dogechain dont store your password. but there is way to bruteforce it if you have wallet ID and a rough idea/hints for your password to build a list to try them.  you can try [dogechain.info recovery](https://btc2doge.com/dogechain-wallet-recovery/) they can resolve password. i have hired them on this to recover my btc and doge.

**Comment by pythonboy20** [comment]
@uzair552 
did you het back your dogecoin wallet? I can solve your problem
so if you want help to get your lost doge wallet, send me email:
[anywalletrecovery@gmail.com]

**Comment by ScofieldFE** [comment]
If you have any password issues, sent coins to the wrong wallet, or got scammed, reach out to easybinarysolutions via g.mail , for swift recovery
