### ISSUE TITLE
An open "letter" from someone who contributes to F@H

### ISSUE THREAD

**Issue by Luca-Ziesler** [dogecoin/dogecoin#1887]
Dear Dogecoin developers,

My name is Luca Ziesler and I'm a volunteer over at F@H (Folding@Home). Since I haven't found any formal contact information on your website, I'm afraid I have to open an issue here. To make this as short as possible, please add a disclaimer or something to your website, since we at F@H have been quite literally spammed with questions about Dogecoin, along with other similar questions. Mostly we can't answer these questions, can't solve them or they're the same over and over again.

Kind regards,

Luca Ziesler

**Comment by rnicoll** [comment]
Hi Luca,

We try to tackle questions in an open medium, so an issue is great actually.

I'm okay with adding a disclaimer, I've also asked the other devs if they have ideas how we can ensure people read it (trickier). The Dogecoin Folding site ( https://www.dogecoinfah.com/ ) does list a lot of resources, so it sounds like people aren't paying attention to it either.

Ross

**Comment by Luca-Ziesler** [comment]
Hi Ross,

Thank you very much for your quick comment. Your engagement is greatly appreciated.

Luca

**Comment by Luca-Ziesler** [comment]
Just write me, if I can be of any assistance.

**Comment by rnicoll** [comment]
We've updated the English & German versions of the site, I need to find someone to hand translations for the remaining languages. Hopefully that will slow down the queries.

**Comment by rnicoll** [comment]
Going to keep it open until I've sorted translations, or I'll forget!

**Comment by AstroOrbis** [comment]
Does anyone need help with French translations?

**Comment by rnicoll** [comment]
@AstroOrbis Yes please - please see the changes in https://github.com/dogecoin/dogecoin.com/pull/176/files , need the same language update applied to `fr`.

**Comment by AstroOrbis** [comment]
It seems the commit was deleted- Should I make a PR on the main branch?

**Comment by Luca-Ziesler** [comment]
Is everything sorted?

**Comment by AstroOrbis** [comment]
I believe so!

**Comment by Luca-Ziesler** [comment]
Should we close this issue in that case?

**Comment by AstroOrbis** [comment]
I think that would be the best option.

**Comment by Luca-Ziesler** [comment]
Pardon me, but has the disclaimer been deleted on https://www.dogecoinfah.com ?

**Comment by rnicoll** [comment]
Ah, sorry, just saw this. We don't run dogecoinfah, but I'll see if I can find contact details. It might be worth asking in their Discord server though.

**Comment by rnicoll** [comment]
The dogecoinfah.com site itself isn't managed here. The link to it now seems to be on https://dogecoin.com/dogepedia/articles/get-dogecoin/ which I'm sure I should know where that file is, I'm not. Also as I'm in theory not involved, I should stop meddling.
