### ISSUE TITLE
SVG to replace png files as desktop icons

### ISSUE THREAD

**Issue by Chewbakka-Wakka** [dogecoin/dogecoin#1891]
Would you be able to include a SVG file in source alongside the PNGs? For a desktop app the SVG will be most appropriate for which I'm building.

May also want to rename bitcoin to doge for those existing png files as well. i.e. /share/pixmaps/bitcoin32.png

**Comment by ReverseControl** [comment]
Do you already have the file?

**Comment by Chewbakka-Wakka** [comment]
I have no SVG icon for this no. No idea how I'd make an appropriate SVG for the Doge haha

**Comment by ReverseControl** [comment]
Thanks @Chewbakka-Wakka . I don't know that we need an SVG icon, but certainly we do need to update logo names in the documentation for doxygen, the file names themselves and any reference in code to those image files should be updated as well. Can anyone take this up and submit a PR?

This should be fairly easy if you are new and want to contribute this is a good simple task.

Thanks.

**Comment by slightlyskepticalpotat** [comment]
As far as I can tell, all dogecoin icon files were already updated in https://github.com/dogecoin/dogecoin/commit/c42dba492ba9c12a79a3dcf8526e17b4215c452e.

The doxygen uses a [Bitcoin logo](https://github.com/dogecoin/dogecoin/blob/master/doc/bitcoin_logo_doxygen.png), I can replace it with the proper icon and change the references to it in the code. Can I please be assigned to this issue?

**Comment by Olasunkanmi4270** [comment]
I did not have file

**Comment by iam-agf** [comment]
Why is this issue still open if was already merged?

**Comment by ReverseControl** [comment]
@iam-agf That merge updates the names of the icon files from `bitcoin` to `dogecoin` everywhere as appropriate. We still do not have `.svg` files for the icons. Would you like to provide one? We can merge it and then we can close this.

**Comment by iam-agf** [comment]
I'm going to focus in the issue of the f-strings you answered me, but while not doing that I'm going to try to see how to generate these `.svg`.

**Comment by ReverseControl** [comment]
Go for it. I don't think there should be any issues. @rnicoll

**Comment by iam-agf** [comment]
Ok. Let me try it. Hope I don't crash my branch in the attempt.

**Comment by iam-agf** [comment]
I added the svg files without deleting the png, is it ok?

**Comment by ReverseControl** [comment]
@iam-agf That's fine. Someone will take a look at it and merge it.

**Comment by rnicoll** [comment]
Resolved by #2791
