### ISSUE TITLE
dogecoin core and dogechain.info don't agree

### ISSUE THREAD

**Issue by Evax68** [dogecoin/dogecoin#1898]
### Describe the issue

Dogecoin core qt wallet shows different transactions than dogechain.info

### Can you reliably reproduce the issue?

Yes.

### Expected behaviour

Dogecoin core qt client should show same transactions as dogechain.info

### Actual behaviour

Transactions stealing (?) funds appear in dogechain.info.  Same transactions do not appear in the doge core qt client.

### Screenshots.

Fully synchronized dogecoin core & dogechain.info shown simultaneously

![doge](https://user-images.githubusercontent.com/83884248/117551912-2f757b00-b051-11eb-8f54-fd38944aee5c.png)

Account id: D9oNofQPqaR353iHY5LhP8K6QZiiVTYq8T
Dogecoin core qt shows balance of 359408
dogechain info shows balance of 100215

### What version of Dogecoin Core are you using?
v1.14.3, official binary

### Machine specs:
- OS: ubuntu 18.04 LTS
- CPU: i7s
- RAM: 8+ GB
- Disk size: 2 TB
- Disk Type (HD/SDD): SDD

**Comment by Evax68** [comment]
Uh.. seems to be this:
https://support.bitpay.com/hc/en-us/articles/115003063823-What-is-a-bitcoin-change-address-
stupid me.

**Comment by shibe2** [comment]
Dogecoin Core shows transactions for all addresses that are in the wallet. If you look up all these addresses on Dogechain, you will see the same transactions. If you add up balances of all these addresses, you should get the same balance that is displayed by Dogecoin Core.

**Comment by rnicoll** [comment]
Thanks @Evax68 . I swear I'm going to start a tag just for change addresses.
