### ISSUE TITLE
signmessage / verifymessage is incompatible with old signatures in v1.5

### ISSUE THREAD

**Issue by dooglus** [dogecoin/dogecoin#190]
I have a message I signed using dogecoind v1.2.  The signature verifies correctly using v1.2 through v1.4, but not using v1.5.  It looks like something must have changed with the signing algorithm in v1.5 breaking compatibility with old signatures:

```
$ dogecoin-1.2/src/dogecoind verifymessage DSYLEu6N3fjD9tGmJzq3ZBDV1or9cbNMxM H9uAM7QgqOffYf1ar+Rp+zuEWfVgPnSkhj6EYvsovfRG/g/KKMLo04UKet3qogxg7jMsk1hZzIafODuGzWJbQd4= "This address is owned by Doge-Dice.com and is used for offsite storage."
false
$ dogecoin-1.2/src/dogecoind verifymessage DSYLEu6N3fjD9tGmJzq3ZBDV1or9cbNMxM ICBNSmERx22O1naSo5BnmqGq1nLOwwht4TItiYGRUAR6zsadWbuzmzUnM5kw1USf3Pe7lIFcN1Vo0YTPbtgKieQ= "This address is owned by Doge-Dice.com and is used for offsite storage."
true

$ dogecoin-1.3/src/dogecoind verifymessage DSYLEu6N3fjD9tGmJzq3ZBDV1or9cbNMxM H9uAM7QgqOffYf1ar+Rp+zuEWfVgPnSkhj6EYvsovfRG/g/KKMLo04UKet3qogxg7jMsk1hZzIafODuGzWJbQd4= "This address is owned by Doge-Dice.com and is used for offsite storage."
false
$ dogecoin-1.3/src/dogecoind verifymessage DSYLEu6N3fjD9tGmJzq3ZBDV1or9cbNMxM ICBNSmERx22O1naSo5BnmqGq1nLOwwht4TItiYGRUAR6zsadWbuzmzUnM5kw1USf3Pe7lIFcN1Vo0YTPbtgKieQ= "This address is owned by Doge-Dice.com and is used for offsite storage."
true

$ dogecoin-1.4/src/dogecoind verifymessage DSYLEu6N3fjD9tGmJzq3ZBDV1or9cbNMxM H9uAM7QgqOffYf1ar+Rp+zuEWfVgPnSkhj6EYvsovfRG/g/KKMLo04UKet3qogxg7jMsk1hZzIafODuGzWJbQd4= "This address is owned by Doge-Dice.com and is used for offsite storage."
false
$ dogecoin-1.4/src/dogecoind verifymessage DSYLEu6N3fjD9tGmJzq3ZBDV1or9cbNMxM ICBNSmERx22O1naSo5BnmqGq1nLOwwht4TItiYGRUAR6zsadWbuzmzUnM5kw1USf3Pe7lIFcN1Vo0YTPbtgKieQ= "This address is owned by Doge-Dice.com and is used for offsite storage."
true

$ dogecoin-1.5/src/dogecoind verifymessage DSYLEu6N3fjD9tGmJzq3ZBDV1or9cbNMxM H9uAM7QgqOffYf1ar+Rp+zuEWfVgPnSkhj6EYvsovfRG/g/KKMLo04UKet3qogxg7jMsk1hZzIafODuGzWJbQd4= "This address is owned by Doge-Dice.com and is used for offsite storage."
true
$ dogecoin-1.5/src/dogecoind verifymessage DSYLEu6N3fjD9tGmJzq3ZBDV1or9cbNMxM ICBNSmERx22O1naSo5BnmqGq1nLOwwht4TItiYGRUAR6zsadWbuzmzUnM5kw1USf3Pe7lIFcN1Vo0YTPbtgKieQ= "This address is owned by Doge-Dice.com and is used for offsite storage."
false
```

**Comment by ddekob15-boop** [comment]
> لديّ رسالة وقّعتها باستخدام دوجكويند الإصدار 1.2. يتم التحقق من صحة التوقيع باستخدام الإصدارات من 1.2 إلى 1.4، ولكن ليس باستخدام الإصدار 1.5. يبدو أن شيئًا ما قد طرأ على خوارزمية التوقيع في الإصدار 1.5، مما أدى إلى خلل في التوافق مع التوقيعات القديمة:
> 
> ```
> $ dogecoin-1.2/src/dogecoind verifymessage DSYLEu6N3fjD9tGmJzq3ZBDV1or9cbNMxM H9uAM7QgqOffYf1ar+Rp+zuEWfVgPnSkhj6EYvsovfRG/g/KKMLo04UKet3qogxg7jMsk1hZzIafODuGzWJbQd4= "This address is owned by Doge-Dice.com and is used for offsite storage."
> false
> $ dogecoin-1.2/src/dogecoind verifymessage DSYLEu6N3fjD9tGmJzq3ZBDV1or9cbNMxM ICBNSmERx22O1naSo5BnmqGq1nLOwwht4TItiYGRUAR6zsadWbuzmzUnM5kw1USf3Pe7lIFcN1Vo0YTPbtgKieQ= "This address is owned by Doge-Dice.com and is used for offsite storage."
> true
> 
> $ dogecoin-1.3/src/dogecoind verifymessage DSYLEu6N3fjD9tGmJzq3ZBDV1or9cbNMxM H9uAM7QgqOffYf1ar+Rp+zuEWfVgPnSkhj6EYvsovfRG/g/KKMLo04UKet3qogxg7jMsk1hZzIafODuGzWJbQd4= "This address is owned by Doge-Dice.com and is used for offsite storage."
> false
> $ dogecoin-1.3/src/dogecoind verifymessage DSYLEu6N3fjD9tGmJzq3ZBDV1or9cbNMxM ICBNSmERx22O1naSo5BnmqGq1nLOwwht4TItiYGRUAR6zsadWbuzmzUnM5kw1USf3Pe7lIFcN1Vo0YTPbtgKieQ= "This address is owned by Doge-Dice.com and is used for offsite storage."
> true
> 
> $ dogecoin-1.4/src/dogecoind verifymessage DSYLEu6N3fjD9tGmJzq3ZBDV1or9cbNMxM H9uAM7QgqOffYf1ar+Rp+zuEWfVgPnSkhj6EYvsovfRG/g/KKMLo04UKet3qogxg7jMsk1hZzIafODuGzWJbQd4= "This address is owned by Doge-Dice.com and is used for offsite storage."
> false
> $ dogecoin-1.4/src/dogecoind verifymessage DSYLEu6N3fjD9tGmJzq3ZBDV1or9cbNMxM ICBNSmERx22O1naSo5BnmqGq1nLOwwht4TItiYGRUAR6zsadWbuzmzUnM5kw1USf3Pe7lIFcN1Vo0YTPbtgKieQ= "This address is owned by Doge-Dice.com and is used for offsite storage."
> true
> 
> $ dogecoin-1.5/src/dogecoind verifymessage DSYLEu6N3fjD9tGmJzq3ZBDV1or9cbNMxM H9uAM7QgqOffYf1ar+Rp+zuEWfVgPnSkhj6EYvsovfRG/g/KKMLo04UKet3qogxg7jMsk1hZzIafODuGzWJbQd4= "This address is owned by Doge-Dice.com and is used for offsite storage."
> true
> $ dogecoin-1.5/src/dogecoind verifymessage DSYLEu6N3fjD9tGmJzq3ZBDV1or9cbNMxM ICBNSmERx22O1naSo5BnmqGq1nLOwwht4TItiYGRUAR6zsadWbuzmzUnM5kw1USf3Pe7lIFcN1Vo0YTPbtgKieQ= "This address is owned by Doge-Dice.com and is used for offsite storage."
> false
> ```
