### ISSUE TITLE
MAKE A DOGECOIN VISA BLOCKCARD

### ISSUE THREAD

**Issue by Goyco** [dogecoin/dogecoin#1900]
This issue tracker is only for technical issues related to Dogecoin Core.

For general questions about Dogecoin or wallet recovery please use one of the various communities:

* [Dogeducation on reddit](https://www.reddit.com/r/dogeducation/)
* [Discord](https://discord.com/invite/dogecoin)

### Describe the issue
There is no Dogecoin Visa Blockcard available
#### If so, please list the steps to reproduce below:
1. Open wallet
2. Look for Doge Visa blockcard
3. Its not there

### Expected behaviour
Tell us what should happen
I open my wallet and see my Doge visa card
### Actual behaviour
Tell us what happens instead
Theres no DOGE
### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of Dogecoin Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by Goyco** [comment]
Seriously make a Doge Visa Blockcard

**Comment by langerhans** [comment]
Closing as unrelated to the repo. For business ideas feel free to contact a VC company or something.

**Comment by Goyco** [comment]
My bad sorry about that.
Thanks for letting me know!
