### ISSUE TITLE
Sync Screen Wrong

### ISSUE THREAD

**Issue by slightlyskepticalpotat** [dogecoin/dogecoin#1902]
#### If so, please list the steps to reproduce below:
I tried reproducing it several times but could not consistently do so, I think it is related to network conditions.
1. Launch Dogecoin core
2. Look at the sync screen after headers have synced

### Expected behaviour
The screen should show a percent value for increase per hour and a time for estimated time left to sync.

### Actual behaviour
The "Progress increase per hour" field shows -0.00% increase per hour (I tried making it more negative by throttling internet speed, but it only ever showed -0.00%). Additionally, the "Estimated time left until synced" field shows "%n second:

### Screenshots.
![image](https://user-images.githubusercontent.com/31290848/117589579-65216f00-b0f8-11eb-8f90-5429c8195a41.png)

### What version of Dogecoin Core are you using?
1.14.3, official Linux binary from the Github releases page.

### Machine specs:
- OS: Ubuntu 20.04.2 LTS
- CPU: AMD Ryzen 5 3500U
- RAM: 8GB
- Disk size: 500 GB
- Disk Type (HD/SDD): The binary is on a SSD, but the blocks are on another HDD.

### Any extra information that might be useful in the debugging process.
I looked at the debug.log, but it's just a bunch of `UpdateTip`s and `connect()`s so I don't think it's useful here.

**Comment by ReverseControl** [comment]
@slightlyskepticalpotat As this issue has been addressed (See #1908) I will close it. If it becomes relevant again, it can be re-opened.
