### ISSUE TITLE
No wallet.dat ?

### ISSUE THREAD

**Issue by megagerzog** [dogecoin/dogecoin#1905]
Hello! 
Help, what to do? I had, and now another laptop Dogecoin Core 1.10.0 and nowhere to download - Dogecoin Core 1.14.3 , can a different one come up and replace wallet.dat? I downloaded another wallet.dat Dogecoin Core 1.14.3, but there is no wallet.dat in the kernel folder, where to look and what to do?

**Comment by rnicoll** [comment]
I'm not sure I've understood the question. The `wallet.dat` file is the file created by Dogecoin Core. Presuming you're on Windows, I believe it's in the folder `%AppData%\Dogecoin`, unless a different directory was used when installing (in which case it will be there).

**Comment by megagerzog** [comment]
Thanks for the answer! Not in the folder either %AppData%\Dogecoin  wallet.dat

**Comment by jeremiahisaacson** [comment]
@megagerzog Search your file system for "*.dat" -> it will search for any files with a .dat file extension (on Windows).

**Comment by megagerzog** [comment]
Thanks for the advice! Everything worked out!
