### ISSUE TITLE
Feature Request Discussion: Fraud Protection Mechanism

### ISSUE THREAD

**Issue by finate-tech** [dogecoin/dogecoin#1911]
### Describe the issue
The network doesn't have sufficient fraud protection in place to facilitate wider payment system adoption. Combining an algorithmic fraud detection mechanism and community-driven fraud prevention volunteers paid in Doge (like mining for node operators) would protect consumers while maintaining a de-centralized system. 

### Expected behaviour
Wallet holders intending on accepting Doge for payments for goods/services should have a means to be KYC validated by the network so consumers sending transactions to those merchants can have confidence of the legitimacy of the merchant. It is possible to be de-centralized while also safer.

### Actual behaviour
Fraudulent entities take advantage of consumers with no means of consumer recourse. There is no basis for consumers to have trust in the entity they are sending coins too.

### What version of Dogecoin Core are you using?
Latest Release

### Discussion Points
Long-article context: https://www.reddit.com/r/dogecoin/comments/n9oyas/the_doge_card_day_2_a_21st_century_payment/

High-Level Feature Implementation Approaches:
1. Wallet Wrappers - companies that provide wallet services are solely responsible for this
This is where we are today. It is inefficient and centralized. Entities have the authority and incentive to act in their best interest not in wallet holders such as increasing profits/revenue and reducing cost even if that means taking short cuts or charging for security/fraud protection features.

2. Federated Nodes - the network provides implementation across disparate, independent solutions
This is perhaps a middle-ground stepping-stone solution. It would allow auxiliary nodes to enhance the core nodes functionality and follow a more micro-service based architecture. It would require core support in allowing the auxiliary nodes to issue rewards or charge increased transaction fees and so a mechanism would need to be in place for that. The drawback is cohesion. In a federated sense, it doesn't take much for there to be vast chaos, repetition/duplication of work, and conflict. This most aligns with decentralization though.

3. Core nodes - the network provides a core implementation / process 
This is the hardest level of effort and would solve some challenges but create others. It would help facilitate an adoption model through a centralized process providing sufficient consensus, but it would also likely be very slow and increase the amount of technical work to manage within the core client.

Given the ability for the micro-service architecture, I would promote federated nodes to implement network enhanced features and look for input on ideas of how the nodes could be accepted and authorized to issue Doge rewards or charge higher transaction fees for their work (likely the later). The RPC mechanism would also need to modified to support interaction with the auxiliary nodes.

**Comment by klawdarza** [comment]
I agree with this totally.Thats the address I instructed Binance to send  my Doge to . I don't know what wallet Binance used because I don't have a Doge wallet . Now this site promised to double my Doge . How can he send me my Doge back of I never had a wallet in the first place and second the website doge-snl.com disappeare

They kept instructing me to connect my trust wallet to binance and to transfer all my other coins and then give them the address. 

 since I am stupid , I didnt know how to connect and when I went to chat .. the site was gone and I want to track the address. 

In some sites .. the address is not valid .. in other sites it states there is 1.6 mil dollars  . ![image](https://user-images.githubusercontent.com/68105594/118389601-3443bb80-b65d-11eb-95c6-d9ea461c45f1.png)

**Comment by rnicoll** [comment]
Moderation note: I'm going to remove anything that shows an address, in this specific case because the last thing I want is anyone sending more coins to them.

**Comment by rnicoll** [comment]
On the issue itself; identity and KYC for/on a blockchain is something I believe several startups are investigating ( https://consensys.net/ springs to mind), it's not something in scope for Dogecoin Core.
