### ISSUE TITLE
Compiler warnings when building Dogecoin.

### ISSUE THREAD

**Issue by CosmoRied** [dogecoin/dogecoin#1912]
### Describe the issue

When compiling dogecoin I get a tonne of warnings related to the "tinyformat.h" header and fallthrough of switch statements. Looks like someone removed the break statements from this header, or they are just improperly left off. 

Everytime the codebase refers to this file when compiling gets this message:

```
./tinyformat.h:707:21: warning: this statement may fall through [-Wimplicit-fallthrough=]
  707 |             out.setf(std::ios::uppercase);
      |             ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
./tinyformat.h:708:9: note: here
  708 |         case 'x': case 'p':
      |         ^~~~
./tinyformat.h:713:21: warning: this statement may fall through [-Wimplicit-fallthrough=]
  713 |             out.setf(std::ios::uppercase);
      |             ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
./tinyformat.h:714:9: note: here
  714 |         case 'e':
      |         ^~~~
./tinyformat.h:719:21: warning: this statement may fall through [-Wimplicit-fallthrough=]
  719 |             out.setf(std::ios::uppercase);
      |             ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
./tinyformat.h:720:9: note: here
  720 |         case 'f':
      |         ^~~~
./tinyformat.h:724:21: warning: this statement may fall through [-Wimplicit-fallthrough=]
  724 |             out.setf(std::ios::uppercase);
      |             ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
./tinyformat.h:725:9: note: here
  725 |         case 'g':
      |         ^~~~
```

Is this intentional? Break statements are used elsewhere throughout? I can create a PR to fix if not intentional.

#### If so, please list the steps to reproduce below:

1. Yes. Dogecoin download -> ./configure && sudo make && sudo make install

### Expected behaviour

There should be no warnings when compiling. 

### Actual behaviour

Tonnes of warnings when tinyformat.h is referred to, which is like thousands of times. 

### Screenshots.

N/A

### What version of Dogecoin Core are you using?

v1.14.3

**Comment by chromatic** [comment]
I think that's deliberate behavior. [Bitcoin's similar code](https://github.com/bitcoin/bitcoin/blob/master/src/tinyformat.h#L798-L807) has comments that call out passthrough behavior.

**Comment by shibe2** [comment]
C++17 has `[[fallthrough]]`. GCC has `__attribute__((fallthrough))`. We can create a conditional macro and add it where false warnings are produced.

**Comment by chromatic** [comment]
@CosmoRied I ran into this again today. Can you fork this repo and submit a PR against the `1.14.5-dev` branch? That'll make it easy for a reviewer to review and test. Thanks!

**Comment by CosmoRied** [comment]
@chromatic I have submitted a PR with the required changes. Additional ignore statements can be added to support the cleanliness of compiling such as -Wunused-function, -Wreturn-type & -Wunused-variable...

**Comment by ReverseControl** [comment]
Issue addressed. See #2497.
