### ISSUE TITLE
Doge wallet Multidoge 

### ISSUE THREAD

**Issue by bunkerWHz** [dogecoin/dogecoin#1918]
Hi fellow Shibes, 
can't run Multidoge wallet on macos 10.15.7. It says I need legacy Java, but when I try to install it, Java says I have a newer version already.
![Screen Shot 2021-05-12 at 22 18 52](https://user-images.githubusercontent.com/11806219/118033156-2813e180-b371-11eb-8f2a-6eb097563fa6.png)

**Comment by shibe2** [comment]
https://github.com/langerhans/multidoge/issues

My MultiDoge seems to work with the latest version of Java.

**Comment by ReverseControl** [comment]
@patricklodder @rnicoll  @michilumin I think we can close this one.
