### ISSUE TITLE
We need an actual main site for dogecoin in this repo.

### ISSUE THREAD

**Issue by okabrionz** [dogecoin/dogecoin#1922]
### Main Site URL
I'm not seeing the official site of this repository. That why I just add the homepage URL to this repo.

**Comment by jeremiahisaacson** [comment]
@okabrionz https://github.com/dogecoin

What more are you interested in finding?

**Comment by rnicoll** [comment]
https://github.com/dogecoin/dogecoin.com I think is what you're wanting?
