### ISSUE TITLE
Dogecoin SNL giveaway scam and wallet issue

### ISSUE THREAD

**Issue by klawdarza** [dogecoin/dogecoin#1940]
Did anyone send Dogecoin to dogecoin-snl.com and this address D6Sb98cbaDyQpYbHCMQmpaLxZe6LctqAj3 ? 
 ![image](https://user-images.githubusercontent.com/68105594/118363714-4e7f8a00-b5c8-11eb-988a-fa60d98043ec.jpeg)

**Comment by roman-rr** [comment]
@klawdarza It is not correct place in CODE repository to post it. Don't waste repository please, and learn about question marks.

**Comment by klawdarza** [comment]
Sorry I don't know anything about tech and I am just trying to get help . I wish there was a hotline for stupid people like me to ask for help . Thank you

**Comment by fastcoin-project** [comment]
You are the bank.  If you fall for scams, you deserve to be scammed.   Do your research before sending anything to anyone.  Better luck next time.

**Comment by klawdarza** [comment]
Not many people are smart to be a bank . Yes I deserve to be called stupid and scammed.

**Comment by klawdarza** [comment]
Thank you for taking the time to comment, by the way. 

Forgive me for my grammatical errors. English is my second language and I was careless.

I think crypto is only for super smart people . 

I am not smart and I don't have high IQ .


Thank you .

**Comment by roman-rr** [comment]
@klawdarza Ok, but please ask such type of questions on [Reddit community](https://www.reddit.com/r/dogecoin/).

**Comment by xjuanc** [comment]
@klawdarza, don't worry it's okay to be a bit lost, use Reddit or Discord next time for this kind of things.

Anyway guys, I don't think being rough with new people around is the best way to follow DOGE's main mission. I understand this is getting kind of out of control because of the whole hype but try to stay calm or simply ignore it.

**Comment by klawdarza** [comment]
I am so sorry.. please just ignore my problem. I learned my lesson .

I was wrong to even think that I can join crypto.

I am too stupid .

Thank you for your time.

I hope one day there will be a crytpo for stupid people like me and peopel
who want transparency in all transactions .

I thought that a blockchain was a group of people verifying the transaction.

I just wanted to trace who the address is because I give my name and email
when I bought in binance and so I don't know why they ask for name and
email if no one can be traced.

I am too stupid to understand . So I really apologize for bothering this
group.

Thank you .

Sincerely,
Kathy

**Comment by roman-rr** [comment]
@klawdarza It is not about crypto and intellectual level. Just here must be code related issues to keep repository clean. That how we can easy improve doge codebase.

**Comment by klawdarza** [comment]
Iam sorry again but I was looking for someone who could explain the point of pubhashkey and null or hex on the dogechain so I could track my money.

Have a good day. I wanted to ask insiwcord but I have to invite or something .. it's too complicated . I tweeted ..I tweeted the developer and even Elon mMusk .

So it's ok. 

I will stick to paper checks or debit cards . 

God bless.

**Comment by klawdarza** [comment]
Roman , I posted everything and tried everything to get help ..I posted
GitHub 1903 1938 1940 ...please don't laugh if you see the numerous posts
and numerous pictures .

**Comment by klawdarza** [comment]
How does one send email to Dogecoin developer ?
