### ISSUE TITLE
how I can help to translate in THAI language

### ISSUE THREAD

**Issue by wutwooddy** [dogecoin/dogecoin#1951]
This issue tracker is only for technical issues related to Dogecoin Core.

For general questions about Dogecoin or wallet recovery please use one of the various communities:

* [Dogeducation on reddit](https://www.reddit.com/r/dogeducation/)
* [Discord](https://discord.com/invite/dogecoin)

#### If so, please list the steps to reproduce below:
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of Dogecoin Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by haxpor** [comment]
What what I understand, mainly you do the following

1. Copy `src/qt/locale/bitcoin_en_GB.ts` file (could be other files, but this one is ease to work on top) into a new Thai translation file e.g. `src/qt/locale/bitcoin_th.ts`.
2. See [example](https://github.com/dogecoin/dogecoin/pull/1871/files) of Chinese translation changes. In short, make changes by providing Thai translations into those `<translation>...</translation>` according to its associated English keys.
3. Add a line of "`<file alias="th">locale/bitcoin_th.qm</file>`" (without quotes) into `src/qt/bitcoin_locale.qrc` file at the end of last line of `<file alias.....>`
4. Add a line of "`qt/locale/bitcoin_th.ts`" (same without quotes) into `src/Makefile.qt.include` file after the last line of `QT_TS = \`, also don't forget to add prior `\` before a new line.

Optional notes:
* there is `.qm` as from my understanding, no need to worry as it's as part of build process related to QT to generate that.
* step no.3 can be done via QT's related tool, but we can also directly modify it here for ease of providing new translation text, and to not complicate things further
* mainly focus on adding relevant translated texts into `src/qt/locale/bitcoin_th.ts` file then make a PR, if there's things need to be handled or fixed, I believe community will help you out :)

**Comment by wutwooddy** [comment]
ohhhhh thank you krub.

**Comment by rnicoll** [comment]
Thanks for writing that up @haxpor
