### ISSUE TITLE
Dogecoin Docker on Photon OS for scaleabilty

### ISSUE THREAD

**Issue by helleflo1312** [dogecoin/dogecoin#1957]
This issue tracker is only for technical issues related to Dogecoin Core.

For general questions about Dogecoin or wallet recovery please use one of the various communities:

* [Dogeducation on reddit](https://www.reddit.com/r/dogeducation/)
* [Discord](https://discord.com/invite/dogecoin)

#### If so, please list the steps to reproduce below:
1. When I restart the docker the progress goes to 0. Are there plans to make it useable for docker containers because of scalabilty. I used photonOS for VMWARE

### Expected behaviour
State should be saved
### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of Dogecoin Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by helleflo1312** [comment]
Thinking about running it in datacenters with scalabilty on docker swarms.
Much scaleabilty, lightweight OS and effeciency improvement.
Toughts on Kubernetes?

**Comment by incognitojam** [comment]
Docker containers aren't persistent, you should attach a volume to the container. I don't think isn't an issue with Dogecoin Core.

**Comment by helleflo1312** [comment]
Okay thanks makes sense. So for my understanding It just would be a transaction node ?

**Comment by rnicoll** [comment]
We can't handle deployment queries, sorry. Please try https://www.reddit.com/r/dogeducation/
