### ISSUE TITLE
Fix magic numbers

### ISSUE THREAD

**Issue by geekwisdom** [dogecoin/dogecoin#1968]
Pubkey.cpp and Key.cpp contain 'magic numbers' mainly 33 and 65 representing the size for the signature (vch) COMPRESSED AND UNCOMPRESSED.

Suggest replaching these with constants for easier future maintaince

 static constexpr unsigned int SIZE                   = 65;
static constexpr unsigned int COMPRESSED_SIZE        = 33;

Also add a function that can verify the size

**Comment by rnicoll** [comment]
I'm doing a refresh of the code based on Bitcoin Core 0.21, and I _think_ they've moved those to constants in that release. If not, best thing to do would be to raise a PR upstream (against Bitcoin Core), and we'll pick it up through our normal update cycle.

**Comment by geekwisdom** [comment]
Oops Sorry, was in the middle of PR when you submitted your comment :-)

**Comment by rnicoll** [comment]
Oops, I've reopened :)

**Comment by ReverseControl** [comment]
@patricklodder Close this one.

**Comment by patricklodder** [comment]
Fixed with #2249
