### ISSUE TITLE
Trivial contributing.md references Bitcoin (not dogecoin)

### ISSUE THREAD

**Issue by geekwisdom** [dogecoin/dogecoin#1992]
# Bug Report

**Current behavior:**
Dev;s trying to learn  how to contribute to dogecoin, are greeting by a contributing.md that tells them all about how to contribute to bitcoin.

**Expected behavior**
Would expect this file to tell me the rules/behaviors if I want to contribute to dogecoin.

**Steps to reproduce:**
Read the contributing.md file

**Screenshots**
N/A - Not GUI - Trivial Update 
**Dogecoin Core version**
main

**Machine specs**
N/A

**Extra information**
This is just one of those trivial text updates, nothing too special, replace words 'bitcoin' with 'dogecoin' like has been done already in various areas of the the source.

**Comment by chromatic** [comment]
This file has been modified for the upcoming 1.14.4 release: [contributing.md in 1.14.4-dev](https://github.com/dogecoin/dogecoin/blob/1.14.4-dev/CONTRIBUTING.md). Does that look like what you would want to see?

**Comment by geekwisdom** [comment]
Shoot, I never noticed it.  Need to get better at looking in active branches.
