### ISSUE TITLE
[feat]  PONW & POE to replace POW Increasing speed and energy efficiency while keeping miners happy

### ISSUE THREAD

**Issue by Planet-Zuda** [dogecoin/dogecoin#1996]
# Feature Request  PONW & POE Increasing the speed and energy efficiency of Doge while keeping miners happy

 
**Describe the Feature Request**
   Dogecoin currently uses proof of work or POW, this is the opposite of how most POW works, so I've named it proof of non work or PONW combined with proof of  efficiency or proof of energy POE, whichever name people like the most. 

**Describe Preferred Solution**
What is proof of non work? 
Proof of non work rewards miners whose system  finds the solution, the fastest while also using the least amount of energy for the doge network, so the most efficient discovery and fastest solutions result in the biggest rewards for miners. 
This adopts multiple ideas from existing solutions and open issues into one concise solution. 

Rather then having these machines look for the answer 24/7 thus using the most energy, the network would be designed to  give any machine running 24/7 a net of 0 rewards, if it is a node pool one may consider sending them a charge for running 24/7 and any fee to them would be sent to a company that offsets carbon footprints.

How this would work is two fold, one the current POW setup would be an emergency fail-safe, so a POW set-up or something more efficient should always be in place, but not running unless the first method of relying on others networks power fails.

What do you mean other networks power?
Twitter, for example lets some people access their firehose, which is every tweet being sent every second of the day and millisecond.  Proof of non work would not use scrypt or hashcat as is, if at all. It would run on a series of apis from large companies, such as youtube api, twitter api, etc.  The goal for the miners would rather then using scrypt, would be working with a Proof of non work script that  randomly generates strings of letters or words that the miners machines must find amongst the data they have access to in the fastest amount of time possible. If the majority of machines are connected per usual and they aren't able to find anything within 60 minutes, then the random letters or words are changed and possibly lowering the difficulty to adapt to the amount of machines connected. It is unlikely there is a string of letters in any form of an alphabet that hasn't been written on twitter or youtube. 

Now having scrypt as a fallback is in case something goes wrong with access to the apis, so there is no downtime, but it would be just that -- an emergency fallback.

Proof of energy would need multiple things known, is this machine using renewable energy? How fast did the machine find the answer? Every minute it takes longer to find the answer, there will be a decrease in reward. This is designed so machines will find the letters and or words at the fastest amount possible at a recurring time or times per day.  but not more then 6 events per day where the machines try to find out what random string or word was generated.   if the random set of letters or words occur in the first hour of each event, being 6 total hours, then that is it for the day. This means the reward incentive generally found in a 24 hour period, would now be given out within a 6 hour period, so the amount of energy used by miners is decreased, the connection time .

If we find the machine having to reset the letters or words because no machine found them in the first sixty minutes of an event, then there would be an extra half hour given with a maximum amount of this occurring 4 times in one day. This means the maximum amount of time the machines would be running is 8 hours a day with 6 events in one day instead of 24/7.

Machines using dirty energy would either be completely rejected or get the smallest amount of reward to incentivize the network owners to upgrade to renewable energy.

By doing this Dog coins engine would be using a very small amount of energy, woof very green! 

**Describe Alternatives**
I don't have the alternatives thought through at this point, but it would be similar to above, but instead use a script that is far easier to find the solution and only run 8 hours per day.

**Additional Context**
This is my first time contributing to dogecoin, so if you find it absurd, I apologize, however i've been coding over 20 years and I know this would work.

**Comment by patricklodder** [comment]
Got code?

**Comment by Planet-Zuda** [comment]
> Got code?

If you're interested, I will whip up a prototype for you.

**Comment by sony2pl** [comment]
How would a miner distinguish and recognize a power source ?
"Proof of energy would need multiple things known, is this machine using renewable energy?
Machines using dirty energy would either be completely rejected or get the smallest amount of reward "

**Comment by Planet-Zuda** [comment]
> Got code?
This is only the computers side of choosing a random string of letters, I ultimately will be adding in a dictionary and miner interaction, but this is how far I got this evening. I will work on it more when I wake up. This is meant to be the fail-safe script as this won't include the api keys I would need, as getting access to the firehose isn't the easiest thing to do.

``#include <iostream>
#include <string>
#include <stdtime>
#include <time>
#include <random>
using namespace std;
// this code shouldn't result in doing anything that you see right now. This currently is just what the computer does, it sets a randomized string of letters. I am going to write the mining part next, but wanted to show what a fail-safe script would look like since I don't have API keys for the twitter firehose yet. Those aren't easy to get.
// even writing the miner part for this will take me sometime.
// I would like the finished version to not just use randomized letters, but also have a much big, many words dictionary so the words are chosen at random in the script or the words are chosen from a tweet via the api....
// copyright Planet Zuda
int main()
{
    string randomize(length)
    {

    string randomalfie;
    srand(time(0));

  int n = rand() % 52;
    char setalfie = (char)(n+65);
    const char alfiebet[] =
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
     // decided to add some uniqueness to the naming variable for alphabet.

    for (int i = 0; i < length; ++i) {
        randomalfie += alfiebet[rand() % (sizeof(alfiebet) - 1)];
    }
    alfiedog = randomalfie; // the shiba inus name should be alfie.

    }

}

 `"

**Comment by Planet-Zuda** [comment]
> How would a miner distinguish and recognize a power source ?
> "Proof of energy would need multiple things known, is this machine using renewable energy?
> Machines using dirty energy would either be completely rejected or get the smallest amount of reward "

There are currently 3 possible routes on that, any suggestions are more then welcome:
1. There is an aerial AI tool that detects what buildings use solar, that we might be able to use and map to the approximate address of the miner.
2.  Depending on what type of miner we are dealing with, say a computer that isn't purely designated for mining, there may be files on the system that would show if they're solar.
3.  The honor system with a fine if caught lying, where any and all rewards are paid back, even if you spent it plus a $10,000- $100,000 fine they would have to pay to a carbon offset company. We would know if they paid the fine because we would want to set it up in a way we would be notified when they paid and they would get an automatic thank you for paying your fine after they paid.

If you have any suggestions, please comment.

**Comment by ingokpp** [comment]
How would you recognize machines that pretend to be something else just for the profit?

**Comment by GiverofMemory** [comment]
> Got code?

The issue is that without a roadmap or a "what is dogecoin" design document no one is sure if it is worth writing code because they don't know who would be responsible for accepting or merging it, and if that person would even do that after the code was written.  Basically to get something accepted we have to convince Patrick, is that how this works?  Or does the community need consensus?

**Comment by patricklodder** [comment]
>  I will work on it more when I wake up. [..] I have the very basic beginning of the code [..]

Awesome! I've subscribed to [your repo](https://github.com/Planet-Zuda/doge-update) and will file some issues with you there to explore the concept. [Created a first issue which I think is the most fundamental question to think about.](https://github.com/Planet-Zuda/doge-update/issues/2)

We can open a new issue/PR here once your proof protocol has been audited and field-proven. Until then, let's discuss on your repo.

**Comment by GiverofMemory** [comment]
Patrick you have one job...and it isn't to close all the fun ideas lol.
