### ISSUE TITLE
Rework of contribution guideline

### ISSUE THREAD

**Issue by AbcSxyZ** [dogecoin/dogecoin#1999]
I suggest updating the entire contribution guideline, at least content of `README.md` & `CONTRIBUTING.md`, to facilitate contributor path.

## Current state of contributor documentation

It seems that an important part of the current documentation is old and coming from bitcoin/Litecoin fork, I think both
**content** & **user-friendliness**/**organization** could be improved for technical contributors, and address guidelines for **other types
of contributor** who could come to this repo : translator/corrector, curious, miners, academics, etc.

I think the current content focus a lot on technical information, but lack of practical info.
For example, having as entry point the `version strategy`, `branches`, speaking directly for `test`, `git` process,
but do not have a lot of information about tools used (reddit or github purposes), decision process, current project state and milestones.

Dogecoin is reaching a larger public than dev, and they also come here. For them in the actual documentation, there is the FAQ, but a bit hidden between technical information, the accessibility is possibly not so great. It's harder for some people to know which information they can get or what can they do here.

## Goals

Having a better documentation for contributors could have a variety of purpose :
- Increase number of contributors & code reviewers
- Reduce entry barrier, reduce contributor struggle
- Reduce duplicate/irrelevant issue
- Improve contributor trainings + project memory
- Get more informed public [avoid things like there is no dev !]
- Save everyone time
- ...

In overall, facilitate developers and contributors works.
  
*Let doge repo be more friendly <3 ! Such fun, wow !*
> Dogecoin is a cryptocurrency like Bitcoin, although it does not use SHA256 as its proof of work (POW). Taking development cues from Tenebrix and Litecoin, Dogecoin currently employs a simplified variant of scrypt

**Comment by EverythingWillBeCode** [comment]
Good idea!

**Comment by rnicoll** [comment]
I've raised #2111 which includes some earlier work as well, hopefully that's a step in the right direction.

**Comment by rnicoll** [comment]
Refreshed guide: https://github.com/dogecoin/dogecoin/blob/1.14.4-dev/CONTRIBUTING.md

**Comment by AbcSxyZ** [comment]
As I said in the issue cited just above, the rework is incomplete from my pov.

What comes in my mind actually :

- No translator/typo corrector guideline
- No guideline for non-dev (like give discord/easy issue support or whatever) (?)
- Suggest to check "help wanted" issues/PR. See #2170 (partially done)
- Quick explanation of tool utility (for example in which case use r/dogecoindev or github)
- `CONTRIBUTING.MD` not linked in `README.md`.
- r/dogeducation link ?

It's immediate and defined improvement, probably possible to find more. Personally I think there is some work to do in the overall organization and clarity, even more when adding other type of contributors like translators.

I would like to help, I wait on https://github.com/rnicoll/dogecoin/pull/17 to move on, to see if important docs change is something you're considering and if my work is useful.
