### ISSUE TITLE
[feat] Eliminate unlimited supply of Dogecoin

### ISSUE THREAD

**Issue by Abstract45** [dogecoin/dogecoin#2003]
Preface:

Currently, the biggest issue in my mind is the fact that the number of dogecoins is unlimited and there is no dev fund to allow for developers to keep working on this project and get rewarded in the process. 

Proposal:

Have a mechanism to burn x% of coins (the community can decide on this) where some percentage of that goes to a dev fund and then people are rewarded from that dev fund when they complete tasks. The purpose of this is to eliminate the unlimited amount of doge coins that are minted by burning a portion of the coins and allowing a dev fund to be made so that the coin can thrive.

Next steps (if accepted):
* Discuss the % of coins that we want to burn on transactions to offset the number of coins that are minted.
* Create a dev fund wallet with an entity in charge of that fund to give out funds when tasks are completed.
* Create a burn wallet where coins can be burnt

**Comment by incognitojam** [comment]
Limiting the supply has been discussed many times.
[1] https://github.com/dogecoin/dogecoin/issues/1674
[2] https://www.reddit.com/r/dogecoindev/comments/la1hk3/continuation_of_1674/

There is in fact a developer fund: https://chain.so/address/devfund

**Comment by patricklodder** [comment]
> Create a burn wallet where coins can be burnt

This is a classic utxo chain. You don't burn to a wallet here. You. burn. for. real. It's built into our protocol..

Thank you for your suggestions!!! I'm closing this :-)
