### ISSUE TITLE
p2p sharing for initial blockchain downloads [feat] 

### ISSUE THREAD

**Issue by tuntinski** [dogecoin/dogecoin#2005]
# Feature Request
p2p sharing for initial blockchain downloads 
**Describe the Feature Request**
peer to peer download of the blockchain to speed up dogecoin core setup times

**Describe Preferred Solution**

option for peer to peer download for the first dogecoin core setup
**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by patricklodder** [comment]
The initial download is p2p? :-/
