### ISSUE TITLE
[feat] Decentralized Identifiers based on the Dogecoin blockchain

### ISSUE THREAD

**Issue by wyc** [dogecoin/dogecoin#2007]
# Feature Request

**Describe the Feature Request**
We wish to implement W3C Decentralized Identifers and Verifiable Credentials based on the Dogecoin blockchain, for use with the Dogecoin blockchain. They would help you understand who you are transacting with, allowing for things like standardized association from social media or other blockchain accounts, such as [Tezos Profiles](http://tzprofiles.com/) and [Uniswap Sybil](https://uniswap.org/blog/sybil/). This has potential to reduce the incident of fraud because it helps establish identity. With decentralized technologies, we can do so in a way that users can control, therefore preserving their privacy as well.

**Describe Preferred Solution**
Use did-pkh's Dogecoin profile to build credentials built on global data standards imported from from other blockchains.

**Describe Alternatives**
You could build your own system based on Dogecoin PKI, but it wouldn't necessarily be compatible across other blockchains and networks such as X.509-based, whereas the Decentralized Identity ecosystem has a large community including [governments](https://www.dhs.gov/science-and-technology/svip), enterprises such as [Microsoft](https://www.wired.com/story/microsoft-decentralized-id-blockchain/) + [Workday](https://www.workday.com/credentials).

**Related Code**
Specification: https://did-doge.spruceid.com/
Reference implementation: https://github.com/spruceid/did-doge
DID-PKH implementation: https://github.com/spruceid/ssi/blob/main/did-pkh/src/lib.rs#L258

**Additional Context**
https://www.w3.org/TR/vc-data-model/
https://www.w3.org/TR/did-core/

**Comment by patricklodder** [comment]
Isn't this already implemented? Why do you want it to be a feature in Dogecoin Core?

**Comment by wyc** [comment]
We could extend the RPC in a similar fashion proposed with [EIP-2844](https://eips.ethereum.org/EIPS/eip-2844) to handle decentralized identifiers, specifically resolution of `did-doge` DIDs to avoid reliance on an external indexer while granting users PKIs with key/service endpoint rotation. This could live in a separate module--the architecture would be a lot like the [walletdb](https://github.com/dogecoin/dogecoin/blob/master/src/wallet/walletdb.cpp) to build an index.

**Comment by rnicoll** [comment]
Presuming you've approached Bitcoin Core, how did they respond? If they can adopt it and we pick it up as part of regular updates, that might be simpler.

**Comment by wyc** [comment]
I have not, and I further suspect they may view the changes as non-core to the objectives of the project as per their [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) and historical PR review outcomes.

With the recent surge of interest in improving Dogecoin, I think it's an amazing opportunity to further define the objectives of the project itself, and I think this direction is a worthwhile consideration, so I made this issue. Happy to follow-up on a Dogecoin Improvement Process or similar if that's a better place for this discussion. If the maintainers have no interest in supporting this at the core level then that's fine too and it could continue to play in "userland" for a while.

**Comment by ReverseControl** [comment]
I am closing this issue as it belongs in the discussion (https://github.com/dogecoin/dogecoin/discussions) section. @wyc Should you wish to continue discussing your proposal, which is important, the discussion section is the proper place to have this conversation.
