### ISSUE TITLE
[feat] Recreate dogecoin for substrate framework

### ISSUE THREAD

**Issue by RoryShively** [dogecoin/dogecoin#2008]
Can we use substrate to help future development of doge? I know this is a longshot but I would be onboard to help development if that was the case. Looking to gauge general interest in the idea

Substrate would help in providing additional tooling, help get new features out the door more quickly, and help weed out bugs

https://github.com/paritytech/substrate

**Comment by langerhans** [comment]
This seems a bit like proposing to re-write Dogecoin Core in another language. Which problems does this framework solve for an existing blockchain?

**Comment by RoryShively** [comment]
Yes thats the proposal. Definitely a long shot.

- substrate is the best blockchain framework out there to date
- larger talent pool as far as devs go
- all the memory safety and tooling that comes with rust
- forkless upgrades since the runtime is compiled to wasm and stored on chain
- plenty of existing pallets (modules) to choose from or start as a jumping off point for new features like contracts

I think this would lead to faster development in the long run. Doge needs a major overhaul and this may be a good starting point

**Comment by RoryShively** [comment]
That being said I dont follow this project so feel free to critique the proposal. I'm not close to the project or community, just wanted to have the conversation

**Comment by langerhans** [comment]
Well I'm looking at this from a long term maintenance perspective. Making ourselves dependent on a third party basis could lead to all kinds of problems in the long run. Who can guarantee that the framework will see continued development for the coming ten years? Dogecoin exists for over seven years now, so I'm not even exaggerating here :D  Just something to keep in mind when thinking about any kind of re-write.

**Comment by RoryShively** [comment]
Thats a valid concern but I would say substrate is here to stay. It's the framework polkadot and kusama are built off of and I personally have the utmost confidence they will be maintained far into the future.

**Comment by RoryShively** [comment]
What indicators would you want to see to consider using a 3rd party framework? Funding behind companies developing substrate, active contributor count exceeding some amount? I think if we look into the numbers and effort behind the project your concerns might be alleviated

**Comment by alekcunn** [comment]
I would like to second, adopting substrate as a core. Substrate allows upgrading node runtime on-chain. 
If not adopt substrate, add a similar feature to the core for on-chain upgrading through voting on changes.

**Comment by patricklodder** [comment]
Closing per #2110, item 4.
