### ISSUE TITLE
[bug] 1.21 Travis timeouts

### ISSUE THREAD

**Issue by rnicoll** [dogecoin/dogecoin#2009]
Currently the time to complete tests on CI (Travis) is too long, or the timeouts too short, or potentially both.

We need to identify a path to maintaining test quality while identifying opportunities to improve reliability of the tests. A paid Travis subscription is one potential option, but this would still mean others would struggle to get Travis to pass on personal repos.

Acceptance criteria:

* Where CI passes successfully on system without timeout (developer machine), it passes on Travis, excluding infrastructure failures.

**Comment by mmicael1** [comment]
@rnicoll need help? might be a good idea to dockerize it!

**Comment by rnicoll** [comment]
@mmicael1 It's Dockerized, take a look at https://github.com/dogecoin/dogecoin/tree/1.21-dev/ci/test . I thought the problem was that for Dogecoin we have faster blocks, so we have more blocks for coinbase maturity, so as a result we need more blocks when doing tests.

I had a trial on https://github.com/rnicoll/dogecoin/tree/1.21-travis-timeouts of using more flexible coinbase maturity values, however for the functional tests it seemed to make no difference at all. I might re-evaluate with a focus on the unit tests (under https://github.com/dogecoin/dogecoin/tree/master/src/test ) though, perhaps I was looking in the wrong place.

**Comment by mmicael1** [comment]
IMO, you should 1st create a pre-image already built which will save about 5mn of install.  (cf https://travis-ci.com/github/dogecoin/dogecoin/jobs/507022866)
Also maybe it would be better to use Dockerfile instead of having to install local dependencies on computers and benefits of caching.
Currently I m not even able to launch it locally (I’m sorry, 'getopt --test' failed in this environment. Please load GNU getopt.
) 😢 
I know I have a MAC :trollface:
Maybe it would be the 1st step for a lot of new developers to help here...

**Comment by rnicoll** [comment]
@mmicael1 Is that something you can tackle trying? Although eying https://travis-ci.com/github/dogecoin/dogecoin/jobs/507937592 and thinking maybe I've got it down to a single unstable test, and if I can fix that, a bigger change would be unnecessary, so if it's likely to be a massive time sink for you, maybe see if I can fix that test instead.

**Comment by ashu0801** [comment]
Include me in the Doge development as well.. I want to contribute and having 7 years of working experience as a software engineer

**Comment by mmicael1** [comment]
@rnicoll I think this issue is fixed now that the CI is way faster thanks to this PR: https://github.com/dogecoin/dogecoin/pull/2224

**Comment by rnicoll** [comment]
Yup, Scrypt now passes reliably and was the major time sink, so I think this is resolved, thanks all.
