### ISSUE TITLE
[feat] Native iOS and macOS SwiftUI app

### ISSUE THREAD

**Issue by Cyclic** [dogecoin/dogecoin#2011]
# Feature Request
A native iOS and macOS client in SwiftUI.

# Much Deets
The team at Neutrino Labs would like to offer up resources to assist with and lead development effort on a native iOS and macOS client for DOGE — the wallet of future money.

# Very Epics
 - Buy DOGE
 - Non-custodial — cold wallet
 - List of partners and marketplaces where DOGE is accepted with ability to add more
 - DOGE do gooders rewards
 - Apple Pay integration
 - Apple Wallet integration
 - Buy ticket to moon feature?
 - DOGE NFT minting
 - DOGE ledger
 - Pay bills with DOGE automagically
 - Partner rewards
 - Financial health and wellness tab
 - Life goal planners
 - Available in App Store

**Comment by langerhans** [comment]
Some good ideas there. It seems to me most of this can be built with existing technology. How does this relate to Dogecoin Core or the underlying protocol? Are you proposing changes to that as well?

**Comment by Cyclic** [comment]
Possibly to core as well since Apple has indicated Swift 6 has a focus on cross platform development.

**Comment by ingokpp** [comment]
Make it open source and i'll contribute as much as i can. Let's build something awesome!

**Comment by itsalb3rt** [comment]
> Possibly to core as well since Apple has indicated Swift 6 has a focus on cross platform development.

exactly what do you mean by "cross platform development" according to its definition swift is native to iOS and macOS

**Comment by langerhans** [comment]
Hm, Qt is a well established and maintained cross platform toolkit. I'm hesitant to switch to a new UI framework that may or may not see continued development. Especially one that has a primary focus (probably?) on macOS and might end up making other systems a second-class citizen. Qt seems less "biased" in that sense.

**Comment by Cyclic** [comment]
> Hm, Qt is a well established and maintained cross platform toolkit. I'm hesitant to switch to a new UI framework that may or may not see continued development. Especially one that has a primary focus (probably?) on macOS and might end up making other systems a second-class citizen. Qt seems less "biased" in that sense.

The BofA app has roughly 26M users, currently. We must aim for a similar feature set, available in the App and Play store. We will need to ship the apps with signed libraries, which will be a very big lift with the current core. Imagine the energy and performance on the ARM core and M1 chips. The cross platform code will need to be WIP and remain in QT for some time, so would not be a replacement for other platforms. 

I understand your concerns completely. First pass will need to focus on App Store version.

**Comment by Cyclic** [comment]
> Make it open source and i'll contribute as much as i can. Let's build something awesome!

That’s the idea — MIT license.

**Comment by ingokpp** [comment]
> > Make it open source and i'll contribute as much as i can. Let's build something awesome!
> 
> That’s the idea — MIT license.

Yeah, it first sounded like that he/they want to create an app outside of this repository (Nothing related to dogecoin core) :)

**Comment by Im-Mr-Chris** [comment]
> > Hm, Qt is a well established and maintained cross platform toolkit. I'm hesitant to switch to a new UI framework that may or may not see continued development. Especially one that has a primary focus (probably?) on macOS and might end up making other systems a second-class citizen. Qt seems less "biased" in that sense.
> 
> The BofA app has roughly 26M users, currently. We must aim for a similar feature set, available in the App and Play stores. We will need to ship the apps with signed libraries, which will be a very big lift with the current core. Imagine the energy and performance on the ARM core and M1 chips. The cross platform code will need to be WIP and remain in QT for some time, so would not be a replacement for other platforms.
> 
> I understand your concerns completely. First pass will need to focus on App Store version.

Would Apple even allow this?  Is it safe to assume these apps will eventually turn into full dapps? Is there anything fully decentralized as of this moment other than eth btc defi and icp?

Apologies if this is the wrong space for these questions.  It's so difficult to find anything concrete or reliable outside of github.

**Comment by kitcateleven** [comment]
![Buckeye_LakeIz](https://user-images.githubusercontent.com/79618575/119410392-cb8cbc80-bcb6-11eb-9161-6af4d623582d.jpg)
Can we add this Doge who will also leave earth on a rocket this week, she's sat w me the entire time I've been on this project.  I'd love a wallet w the name Isabella - added to projects for adoption of old dogs.  Apple should like that

**Comment by kitcateleven** [comment]
And please forgive me guys - I'm old - really only know how to type on the keyboard and press buttons - but these messages are very clear, I will obey and validate

**Comment by miwandn** [comment]
> > > Hm, Qt is a well established and maintained cross platform toolkit. I'm hesitant to switch to a new UI framework that may or may not see continued development. Especially one that has a primary focus (probably?) on macOS and might end up making other systems a second-class citizen. Qt seems less "biased" in that sense.
> 
> > 
> 
> > The BofA app has roughly 26M users, currently. We must aim for a similar feature set, available in the App and Play stores. We will need to ship the apps with signed libraries, which will be a very big lift with the current core. Imagine the energy and performance on the ARM core and M1 chips. The cross platform code will need to be WIP and remain in QT for some time, so would not be a replacement for other platforms.
> 
> > 
> 
> > I understand your concerns completely. First pass will need to focus on App Store version.
> 
> 
> 
> Would Apple even allow this?  Is it safe to assume these apps will eventually turn into full dapps? Is there anything fully decentralized as of this moment other than eth btc defi and icp?
> 
> 
> 
> Apologies if this is the wrong space for these questions.  It's so difficult to find anything concrete or reliable outside of github.

I am doubtful of the purchasing of the coins with Apple Pay.

**Comment by Im-Mr-Chris** [comment]
> > > > Hm, Qt is a well established and maintained cross platform toolkit. I'm hesitant to switch to a new UI framework that may or may not see continued development. Especially one that has a primary focus (probably?) on macOS and might end up making other systems a second-class citizen. Qt seems less "biased" in that sense.
> > 
> > 
> > > 
> > 
> > 
> > > The BofA app has roughly 26M users, currently. We must aim for a similar feature set, available in the App and Play stores. We will need to ship the apps with signed libraries, which will be a very big lift with the current core. Imagine the energy and performance on the ARM core and M1 chips. The cross platform code will need to be WIP and remain in QT for some time, so would not be a replacement for other platforms.
> > 
> > 
> > > 
> > 
> > 
> > > I understand your concerns completely. First pass will need to focus on App Store version.
> > 
> > 
> > Would Apple even allow this?  Is it safe to assume these apps will eventually turn into full dapps? Is there anything fully decentralized as of this moment other than eth btc defi and icp?
> > Apologies if this is the wrong space for these questions.  It's so difficult to find anything concrete or reliable outside of github.
> 
> I am doubtful of the purchasing of the coins with Apple Pay.

As much as I fantasize about the idea, I also don't believe ARM and M1 can be used rn. At least not for a while.  Like, a long while.  I've been day dreaming about running this currency fully on icp.  I'm absorbing Motoko atm. I really believe doge can outperform btc by use of the containers the icp protocol uses.  

If doge is going to be the currency of the future, it needs to be secure and full blown decentralized.  I may be out of my reach on this next part, but it adds more utility imo.

The concept of defi would be really cool to implement with doge and smart contracts.  Let's say I get killed in a car accident, IF I have children, IF they are of age, IF, etc. other conditions such as anything that is used as leverage by the courts (think will and testaments), if all these conditions are met, then funds (doge) would then be dispersed to whatever assigned hashes instantaneously; cutting out the middle man, the courts, banks, anything that has power to take assets away from loved ones.

**Comment by freethe3rdworld** [comment]
This is fantastic. It's addresses problems some new adopters (and future adoptees) face when geting into crypto. The more solutions we can create, the better we can protect the community and accalerate adoption.

We must aknowledge we're all different - that the majority of society does not have time, or the education, (or interest) to aquire the knowldge thats been accumulated by you genuises over 10+ years. But they're buying into a Dogecoin vision.

To providing more holistic solutions within the Dogecoin core 'eco system', fending of external preditors, and creating a better on ramp experience would be appreciated.

I'll follow this project and contribute if any design, branding, UI/UX, content, strategy, marketing, testing is needed.

**Comment by patricklodder** [comment]
Please build this! We can use better wallets! Let's discuss on reddit once you've got something going! https://www.reddit.com/r/dogecoindev/

**Comment by riverbaymark** [comment]
I'll admit my naiveté here but think developing SDKs for Swift (also for Kotlin and other languages) to interact with the Dogecoin blockchain would bring in a lot of developers who love Doge and want to help make it easier to utilize.  As an iOS developer and clinician I think this could open a world of opportunity for healthcare applications.  I would gladly accept it any clinic I was involved with.

**Comment by Im-Mr-Chris** [comment]
> I'll admit my naiveté here but think developing SDKs for Swift (also for Kotlin and other languages) to interact with the Dogecoin blockchain would bring in a lot of developers who love Doge and want to help make it easier to utilize. As an iOS developer and clinician I think this could open a world of opportunity for healthcare applications. I would gladly accept it any clinic I was involved with.

Again, I've mentioned this.  
Dogecoin is centralized. Accept it or not, but I'm sure the majority of the community has this currency on AWS or whatever else big tech runs the internet rn.

I'm suggesting icp again.  If doge devs later discover something or make a mistake years from now, we can't just "update" and transition.  I'm not bashing here but raising the block size for example.  We make mistakes.

Sorry, to my point.  Motoko allows for nearly any language to be used.  So literally any dev can code through a web browser or a laptop, etc. without needing anything such as additional libraries, sdk's, etc.  I also need to add that icp containers allow for "updates". It's too complicated for me to put into words, just look up dfinity.

This also would allow us to fully get off the current internet.  Not even Ethereum is close to being decentralized.  The next best thing is #btc.  But obviously we can't build on that.
