### ISSUE TITLE
[feat] introduce sybil-resistant identity

### ISSUE THREAD

**Issue by ubiubi18** [dogecoin/dogecoin#2013]
I propose to introduce sybil-resistant identity to doge to enable community to set up democratic governance and oracles.

There is no secure governance possible where billionaeres like elon are able to buy or sell control with a blink of an eye. To stay decentralized, Doge needs a way for the community to reclaim control. T o introduce democratic voting that can't be monopolized that easy I propose to take a look at how idenanetwork does it. They connect unique human identity to adresses. It does not require the disclosure of any personal data (no KYC). You just have to appear online when the validation ceremony starts and solve a series of community-made flip-tests (CAPTCHAs), that is all. 

I think community of doge is strong enough to establish something similar or even use idena itself.

https://github.com/idena-network

**Comment by Arcurus** [comment]
Yea would be great to have a strong identity verification, then we could give out an basic income / universal dividend on it. Here a suggestion for that. Also described there how a decentralized identity verification could look like with using a web of trust: 

https://github.com/dogecoin/dogecoin/issues/2028

**Comment by Drael64** [comment]
In the event that dogecoin did become a global reserve current, some form of resilient voting system isn't a terrible idea. Ultimately it's people that make a thing democratic, and it would give a way for devs to float major changes to the public without it being able to be gamified. 

Might be a little ahead of where we are right now.

**Comment by patricklodder** [comment]
A couple of months ago I spoke to people at nomic.io attempting to work on a DAO side chain for Dogecoin! Could be interesting to have a discussion with them about this!

Please let us know if there are any obstacles in Dogecoin Core or the protocol to achieve this! 

I'm closing this issue for now.
