### ISSUE TITLE
[feat] ARM or any energy efficient cpu Feature to be able to run doge blockchain on DOGE-1 sat

### ISSUE THREAD

**Issue by Nirad** [dogecoin/dogecoin#2014]
# Feature Request
ARM or any energy efficient CPU addition to be able to run Doge blockchain on DOGE-1

**Describe the Feature Request** we need to find a way to use as low possible CPU resource because of the need for solar or nuglaire energy for DOGE-1.
Or Is this is the part of SPACE-X?

**Comment by patricklodder** [comment]
We already build for arm. See https://github.com/dogecoin/dogecoin/releases/tag/v1.14.3

**Comment by Nirad** [comment]
oh thx
