### ISSUE TITLE
Im a programmer with 15yrs some c++ exp how can I contribute for betterment of dogecoin. pls guide

### ISSUE THREAD

**Issue by Maverick5675** [dogecoin/dogecoin#2017]
# Feature Request

**Describe the Feature Request**

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by aminbadshah** [comment]
Hi same here well not 15 years hut 5 years for me.. Yeah i guess we have to figure out how to setup the dev enviroment. C++ eh lets do this..

**Comment by alamshafil** [comment]
Hey there! I only have 1 month of C++ experience, but I can get you started with setting up the dev environment.
If you are Linux (Ubuntu, Arch Linux, etc..) follow these instructions: [doc/build-unix.md](https://github.com/dogecoin/dogecoin/blob/master/doc/build-unix.md) 
If you are Windows 10, follow these instructions: [doc/build-windows.md](https://github.com/dogecoin/dogecoin/blob/master/doc/build-windows.md) 

To download the Dogecoin code, you will need to install Git on your system. Run the command in your terminal to download the code:
```
git clone https://github.com/dogecoin/dogecoin.git
```

Hope I could have helped you!

**Comment by rnicoll** [comment]
There's a project board at https://github.com/dogecoin/dogecoin/projects/4 with a heap of open issues, and I'll be looking at the contribution guidelines tomorrow ( https://github.com/dogecoin/dogecoin/issues/1999 )

**Comment by aminbadshah** [comment]
Hi Guys thanks.. ok yeah let me figure out how to get the Dev environment setup.. I saw a ticket on the web side to fix small issues using PHP, so yeah maybe i can help on that side too Fix up the website a bit??

**Comment by aminbadshah** [comment]
> Hey there! I only have 1 month of C++ experience, but I can get you started with setting up the dev environment.
> If you are Linux (Ubuntu, Arch Linux, etc..) follow these instructions: [doc/build-unix.md](https://github.com/dogecoin/dogecoin/blob/master/doc/build-unix.md)
> If you are Windows 10, follow these instructions: [doc/build-windows.md](https://github.com/dogecoin/dogecoin/blob/master/doc/build-windows.md)
> 
> To download the Dogecoin code, you will need to install Git on your system. Run the command in your terminal to download the code:
> 
> ```
> git clone https://github.com/dogecoin/dogecoin.git
> ```
> 
> Hope I could have helped you!

Yes you did help Thank you so much appreciate your help..

**Comment by alamshafil** [comment]
@aminbadshah Glad I could help! Keep in mind when you do the `git clone` command, it clones the master branch. To the change the branch use `git checkout <branch name>`.

**Comment by aminbadshah** [comment]
Hi so i got wsl linux bash setup on my windows environment

I did a Git clone on the master got the source code.

ran through the commands for win64 as per the link in doc/build-windows.md

So i'm using Code Blocks for the IDE, is there a main project file that I open up and then compile? I'm assuming we are compiling the wallet? right.. Any help will be appreciated..

**Comment by aminbadshah** [comment]
Hi,

So these are the steps i've taken.

Installed WSL

I'm able to run dogecoin core through VS Code, by going to the directory through powershell and then $code . it is opening it Ubuntu Terminal in VS Code i can see a connection there.

It opens up the project. here is where I can't really find any documentation, is there a main .cpp file that i have to run and compile? Usually there's a main project file that is compiled and then the project is run.

Do i need any specific launch json params?

**Comment by alamshafil** [comment]
Hey there! You should follow the instructions stated in Cross-compilation [doc/build-windows.md](https://github.com/dogecoin/dogecoin/blob/master/doc/build-windows.md).
Here are the commands you can type in the Ubuntu terminal
```
sudo apt-get install build-essential libtool autotools-dev automake pkg-config bsdmainutils curl g++-mingw-w64-x86-64 mingw-w64-x86-64-dev git
```
then
```
cd depends
make HOST=x86_64-w64-mingw32
cd ..
./autogen.sh
CONFIG_SITE=$PWD/depends/x86_64-w64-mingw32/share/config.site ./configure --prefix=/
make
```
Keep in mind the first compile will take a long time to compile, depending on your hardware.

The `dogecoind` and `dogecoin-cli` will be found in
```./src/dogecoind.exe and ./src/dogecoin-cli.exe```

Core wallet will be found in
```./src/qt/dogecoin-qt.exe```

**Comment by fmhc** [comment]
Can we somehow put these things in a "how to start" wiki page or sth?

**Comment by alamshafil** [comment]
There is `docs/` folder which contains lots of helpful information for developers.

**Comment by aminbadshah** [comment]
Hi had some success compiling it, however am getting this error.. 

However after it compiles, and i enter Make it is giving me a few errors, am i missing a library or something? I got the source from Master.. Do i need to change the branch or something? Seems to have issues with alert.cpp 

![image](https://user-images.githubusercontent.com/11451980/119706696-29341c80-be0f-11eb-9a93-88ec668485b4.png)

**Comment by alamshafil** [comment]
That is weird, I never got that error. You should follow the error and add all the "#include (get from error)" to the top of the alert.cpp file

**Comment by intarpit** [comment]
Hi all,
I am a python developer. Is there any way I can contribute?

**Comment by sabotagebeats** [comment]
> Hi all and @rnicoll,
> I am a python developer. Is there any way I can contribute?

I believe unit testing is in python, you could help there. https://github.com/dogecoin/dogecoin/search?l=python

**Comment by rnicoll** [comment]
I have created a discussion board specifically to help give some guidance: https://github.com/dogecoin/dogecoin/discussions/categories/help-needed

**Comment by rnicoll** [comment]
> 
> 
> Hi all and @rnicoll,
> I am a python developer. Is there any way I can contribute?

Trickier, but some of the RPC tests are in Python. I think we've got most of the work on them in, for 1.21, but worth reading over https://github.com/dogecoin/dogecoin/tree/1.21-dev/test/functional at least to understand what's there and what they do, for when we do have more tests to work on.

**Comment by liu-xuewen** [comment]
Why not restore the number of dogecoins to a limited number?

**Comment by etherx-dev** [comment]
Fix whatever the malicious developer did here  https://github.com/dogecoin/dogecoin/pull/52/files And post a donation address if it helps recover wallet issues your in for a treat

**Comment by patricklodder** [comment]
@etherx-dev that code has not been used in 7 years...

**Comment by ReverseControl** [comment]
Given the help provided here on how to get started and the discussion board opened by @rnicoll to help guide new folks wanting to help the project, I am closing this one.
