### ISSUE TITLE
Dogecoin Network Improvement Proposal

### ISSUE THREAD

**Issue by morciego** [dogecoin/dogecoin#2018]
Dogecoin Network Improvement Proposal

To cut it sweet and to the point, below are my thoughts on how the Dogecoin network could be improved. I don’t know how probable this proposal is but I hope it could, in some way, serve as a template for innovative ideas.

To begin, a new consensus model would have to be created which would run as followed:

First, what if the Dogecoin network could automatically mint a fixed amount of coins on a fixed schedule.

Second, because the network is producing the coin on its own at a fixed schedule, the need for miners is eliminated. This will cut down on electrical consumption and electronic waste as the incentive for buying dedicated equipment to mine Dogecoins will be gone.

Third, when the network produces the coins, 51% of those coins that enter existence are immediately locked away forever by the Dogecoin network itself. Similar to staking but no human is involved. These coins will never be touched or withdrawn. Essentially the network becomes the “whale.” Because the network will always be the majority holder of the coins that come into existence, it will always be able to handle whatever volume of transactions run through it without being overwhelmed, hence resistant to spam attacks. The remaining 49% of the coins will enter circulation and become available for buying, selling etc. 

Fourth, because the network automatically locks up 51% of all coins that come into existence, and eliminates miners, no transaction fees will need to be paid when sending funds because the network pays itself to verify the transactions through its “auto-staking” method during each release cycle.

Fifth, the network is completely transparent with the growing amount of coins that it is holding. These holdings can be verified by anyone by searching the network’s unique address.

I found it appropriate to call the new consensus model “Proof of HODL”  as it still remains in line with the meme aspect but also since the network is pretty much HODLing the coins it produces and doesn’t give them up. However, this can be debated. I am excited to see how the Dogecoin network will develop as time passes and I hope it could, one day, become a real universal currency that transcends boundaries. To everyone working on the project, keep up the hard work and stay safe!

**Comment by kitcateleven** [comment]
I'm good with proof of HOD'L but, because of COVID and hurricanes some of us had to sell doge to pay bills, then re-buy in.  This was hard to do bc whales have all of the doge and, when they dump on little guys after we've had to sell doge for food , our number of doge was depleted.  Could there be some math involved to account for those that showed a level of dedication to the mission (Starlink, energy, and re-loads) but may not have the 2 million doge they had last July?

**Comment by vertiond** [comment]
Got code?

**Comment by morciego** [comment]
No, unfortunately I don't have a code. I have no experience in coding but I figured I'd give my thoughts on how an improvement could be made. Sorry for any letdowns.

**Comment by JushBJJ** [comment]
How would a person say Alice get x amount of dogecoins? How would we know she has x amount of doge?

**Comment by bbcmpc** [comment]
>The remaining 49% of the coins will enter circulation and become available for buying, selling etc.

How? To whom? You haven't thought this through at all, none of your idea makes any sense 🤦

**Comment by morciego** [comment]
@kitcateleven I see your concern. It's hard to be able to hold on to something when a simple dump by a big whale holder could easily manipulate the price. The proposal is one that is definitely not set in stone and could be tweaked in order to address any issues that way arise throughout development. You do bring up a valid point though and the way I see it, the more one account begins to hold the less incentivized people would be to buy or get paid with Doge. That being said, big corporations would have to buy more in order to pay their employees, assuming they choose to use it. The amount of Doge the network would produce might also have to be much greater than the 14.4 million/day that is currently mined in order to make it more available.

**Comment by bbcmpc** [comment]
this entire thread is hilarious

**Comment by kitcateleven** [comment]
Thanks so much for your response. I appreciate you all looking after the little guys who want to do big work

**Comment by kitcateleven** [comment]
I'm sure I'll end up at the principals office for driving outside my lane, and by lane I mean rocket. But, grandmas coming you guys - good luck w the next step!

**Comment by morciego** [comment]
@JushBJJ They can get the Doge either as payment from their jobs or through exchanges. If Doge really does become the universal currency then maybe somewhere along the lines a connection can be made to the Dogecoin network directly where employers and people alike can create "smart contracts" with each other and the network can see this as proof that a payment should be made to a particular party. The use of wallet address is still very valid just like it is now. That doesn't have to change. Also, no one needs to know how much you really have because the wallets are still private. The only time when that info is directly tied to you is when doing taxes or applying for a loan etc, and you can choose via a smart contract, that only you and the recipient will have access to that information and it cannot be shared.

**Comment by morciego** [comment]
@bbcmpc at this point in time, it will be available on exchanges or creating a direct access to the dogecoin network itself. The network itself could be the exchange. My proposal is just a draft so I don't doubt that some things still need to be addressed.

**Comment by morciego** [comment]
@kitcateleven You're welcome. I am a little guy so I have definitely been affected by whales selling too. Please voice your thoughts. The more we all contribute, the more ideas the developers have to work with.

**Comment by bbcmpc** [comment]
@morciego you're using words, but not in a way that makes any sense

your proposal is not a "draft", it's pure gibberish since you clearly don't even understand how blockchains actually work

**Comment by morciego** [comment]
@bbcmpc if you say so.

**Comment by thooton** [comment]
@morciego, for an introduction to how Proof-of-Work based cryptocurrencies function I recommend [But how does Bitcoin actually work?](https://www.youtube.com/watch?v=bBC-nXj3Ng4) by YouTuber 3blue1brown.

**Comment by morciego** [comment]
@thooton this concept wouldn't be related to PoW as it would be something somewhat different but thank you for the link. I will definitely check it out and hopefully I learn something new.

**Comment by kitcateleven** [comment]
There some great tools I was able to use - thanks so much

**Comment by Drael64** [comment]
I'm not clear on how any of this would work. The current dogecoin network is made up of people - people who mine, and run nodes. How would the money held be stored in the network without being able to be stolen? How would new coins be produced without security issues? 

Maybe do a little more research on how consensus systems, and decentralized block chains work?

**Comment by kitcateleven** [comment]
Thank you!

**Comment by m-luck** [comment]
Just wanted to chime in here. @morciego should be encouraged to post here, as we do not know their age, location, or native language. Good job morciego.

The pseudonymous nature of a decentralized ledger prevents their idea from fully working (proof of HODL). Additionally, the project probably wants to stick with feasible yet impactful short term improvements. But I think within a few weeks, they can get up to speed, and this thread can incorporate some of their ideas more equitably. 

I encourage them to keep posting as they learn more!

**Comment by patricklodder** [comment]
Hi! Please move this discussion to reddit: https://www.reddit.com/r/dogecoindev/
