### ISSUE TITLE
[feat] Algorand of Oborus blockchains?

### ISSUE THREAD

**Issue by fatherGIGA** [dogecoin/dogecoin#2019]
Hey guys!

Why don't we consider to transact long term to Algorand or Oborus blockchains? They are Proof of Stake blockchains that seems very good.

**Comment by m-luck** [comment]
Care to elaborate a bit more? In some other threads, we confirm that proof of [any energy expenditure] is what grounds cryptoassets. Stake or work, it is best to hear the first principle reasons for your suggestion! 

Thank you!

**Comment by patricklodder** [comment]
Closing per #2110, point 4.
