### ISSUE TITLE
[bug] Repetitive header requests from 1.14.x nodes.

### ISSUE THREAD

**Issue by patricklodder** [dogecoin/dogecoin#2021]
# Bug Report

**Current behavior:**

1.14.x clients sometimes send many repeat requests for the same headers, which then get sent out to the peer but somehow ignored. This causes some clients to download multiple hundreds of GB of headers. Behavior is spotted 20-30 times per day across 15 of my 1.14.3 nodes.

Example:

```
{
  "id": 255151,
  "addr": "xx.xxx.xxx.xx:36597",
  "addrlocal": "xx.xx.xx.xx:22556",
  "services": "0000000000000005",
  "relaytxes": true,
  "lastsend": 1621427090,
  "lastrecv": 1621427089,
  "bytessent": 237311632324,
  "bytesrecv": 206818992,
  "conntime": 1621365890,
  "timeoffset": 509,
  "pingtime": 0.392223,
  "minping": 0.258712,
  "pingwait": 227.254694,
  "version": 70015,
  "subver": "/Shibetoshi:1.14.3/",
  "inbound": true,
  "addnode": false,
  "startingheight": 21500,
  "banscore": 0,
  "synced_headers": -1,
  "synced_blocks": -1,
  "inflight": [],
  "whitelisted": false,
  "bytessent_per_msg": {
    "addr": 59372,
    "block": 425475202,
    "feefilter": 32,
    "getheaders": 1117,
    "headers": 236884958826, <---- THIS
    "inv": 1114301,
    "ping": 11648,
    "pong": 11616,
    "sendcmpct": 33,
    "sendheaders": 24,
    "verack": 24,
    "version": 129
  },
  "bytesrecv_per_msg": {
    "addr": 36155,
    "feefilter": 32,
    "getaddr": 24,
    "getdata": 968072,
    "getheaders": 205791203, <---- THIS
    "ping": 11648,
    "pong": 11648,
    "sendcmpct": 33,
    "sendheaders": 24,
    "verack": 24,
    "version": 129
  }
}
```

**Expected behavior**

Don't send multiple requests for the same headers that often.

**Steps to reproduce:**

Start a fast node, check your peers from time to time.

**Dogecoin Core version**

1.14.3

**Machine specs**
- OS: Ubuntu 20.04 LTS
- CPU: 4 vCores
- RAM: 16Gb
- Disk size: 200Gb
- Disk Type (HD/SDD): SSD

**Extra information**

[debug.log with debug=net for affected peer](https://github.com/dogecoin/dogecoin/files/6535141/255151.txt.gz)

**Comment by pouriya73** [comment]
To solve this problem, a time-varying internal variable can be defined that is unique. This manages the value of the queue variable formed and prevents the repetition of similar tasks

**Comment by kitcateleven** [comment]
Thank you

**Comment by p-j01** [comment]
@patricklodder Can you elaborate more on the steps to reproduce?

**Comment by mmicael1** [comment]
@patricklodder does it feel similar? https://github.com/bitcoin/bitcoin/issues/6755

**Comment by patricklodder** [comment]
@mmicael1 thank you so much!

**Comment by mmicael1** [comment]
@patricklodder here is the PR: https://github.com/dogecoin/dogecoin/pull/2332 ;)

**Comment by pouriya73** [comment]
> @patricklodder does it feel similar? [bitcoin/bitcoin#6755](https://github.com/bitcoin/bitcoin/issues/6755)
> Potential fix: https://github.com/bitcoin/bitcoin/pull/8054/files

Needs closer scrutiny

**Comment by patricklodder** [comment]
> Needs closer scrutiny

Agreed. We're doing this together with #2306 though, which MAY make this better than it was in the original bitcoin case.

**Comment by pouriya73** [comment]
> > Needs closer scrutiny
> 
> Agreed. We're doing this together with #2306 though, which MAY make this better than it was in the original bitcoin case.

It certainly will.
Together we can make good changes in this direction. Bitcoin has fully revealed its weaknesses in coding. That could be an opportunity for us to improve #Dogecoin
