### ISSUE TITLE
[feat] NFC Payment for mobile wallets

### ISSUE THREAD

**Issue by HypernovaTX** [dogecoin/dogecoin#2023]
Would it be possible to implement NFC Payment for mobile Doge wallets?

For example: https://developer.apple.com/documentation/corenfc
https://developer.android.com/reference/android/nfc/package-summary

I am not sure if this feature exists. If it do, please close it.

**Comment by m-luck** [comment]
Yes, correct me if wrong, but that is actually more up to the wallet app designers. I would search if there any open source wallets and post here so people can help (I would be excited to see some). Good idea though!

**Comment by patricklodder** [comment]
This can be done regardless of Dogecoin Core. Please feel free to discuss further on reddit: https://www.reddit.com/r/dogecoindev/
