### ISSUE TITLE
Ideas to developing Dogecoin

### ISSUE THREAD

**Issue by tepan024** [dogecoin/dogecoin#2025]
I agree with this, and i need dogecoin fans to make this dreams come true.
_For Elon musk and doge developer._
from **Charles Hoskinson**
watch it.
TO THE MOON!

How to Fix Doge (For Elon Musk)
https://www.youtube.com/watch?v=iQd9XjEm8EE&t=181s

**Comment by mnyallen11** [comment]
When I say interoperability, I'm referring to the blockchain having the capabilities to interact with other blockchains. Protocols from the ethereum blockchain could interact on doges faster blockchain. Also if bitcoins blockchain could interoperate with doge blockchain then maybe we could actually use it for payments. This is what I mean by we need interoperability.

**Comment by bbcmpc** [comment]
> When I say interoperability, I'm referring to the blockchain having the capabilities to interact with other blockchains. Protocols from the ethereum blockchain could interact on doges faster blockchain. Also if bitcoins blockchain could interoperate with doge blockchain then maybe we could actually use it for payments. This is what I mean by we need interoperability.

You're replying to the wrong issue, buddy

**Comment by Drael64** [comment]
A very overcomplicated solution, that was not given in good faith nor understands what dogecoin is.

**Comment by tepan024** [comment]
> > When I say interoperability, I'm referring to the blockchain having the capabilities to interact with other blockchains. Protocols from the ethereum blockchain could interact on doges faster blockchain. Also if bitcoins blockchain could interoperate with doge blockchain then maybe we could actually use it for payments. This is what I mean by we need interoperability.
> 
> You're replying to the wrong issue, buddy

yeah, he need some milk, ADA just give the option about to make more bigger transaction, and fixing the algortihm doge was used before, it's lame btw...

**Comment by patricklodder** [comment]
Thank you for your contribution, closing per #2110 point 8.
