### ISSUE TITLE
Doge card

### ISSUE THREAD

**Issue by Fs555** [dogecoin/dogecoin#2026]
To have a special credit card for the currency of the dog only through which we can buy from the Internet, we get special discounts for fesses and collect points by paying them (transfer these points to serve the entire community, and develop the currency) and work on a special platform (electronic marketing) in which companies display their products  At lower prices than the market, we attract all companies in the world to offer their products to us, with small commissions.  Provided the payment is in the currency of the Doge

**Comment by bbcmpc** [comment]
uwotm8?

**Comment by thooton** [comment]
https://bitinfocharts.com/comparison/dogecoin-transactionfees.html

Doge is not viable as a currency.

**Comment by incognitojam** [comment]
@Fs555 I don't think this is related to the dogecoin wallet. A separate group could go ahead and organise this without permission from anyone or modification to dogecoin.

**Comment by rnicoll** [comment]
I don't want to call out a specific service provider because I haven't accredited them, but there is at least one that offers this, and as incognitojam points out, this repository is limited to things we implement in Dogecoin Core.
