### ISSUE TITLE
[feat] Make doge 1000x faster, 1000000x cheaper, and 1000000x smaller in size, and 100000x more sustainable

### ISSUE THREAD

**Issue by billbai0102** [dogecoin/dogecoin#2027]
idk daddy elon said so, so get your ass back to your desk and start working on it

**Comment by qwahzi** [comment]
Already done by another memecoin (Banano), and proposed here :)
https://github.com/dogecoin/dogecoin/issues/2024

**Comment by AbcSxyZ** [comment]
His current suggestion is not so easily feasible, see #1947. You can also read [Vitalik Buterin](https://vitalik.ca/general/2021/05/23/scaling.html) article on the question.
Some major technical improvement are needed before going to the moon !

To finish, the way you ask for things to get done won't help (the opposite could occur). All devs are volunteer, please be respectful, Do Only Good Every Day :)

**Comment by rorcores** [comment]
We could achieve all of the above by changing the Dogecoin color to a nice shade of red. Red is the fastest color.

**Comment by rnicoll** [comment]
Red's an interesting idea :)

**Comment by PapauloGamerOfc** [comment]
Interesting idea, issue #2024 seems to solve it.
