### ISSUE TITLE
[feat] [SoftFork] Use a part of the block reward to give out an basic income / universal dividend 

### ISSUE THREAD

**Issue by Arcurus** [dogecoin/dogecoin#2028]
Use a part of the block reward / fees to give out an basic income / universal dividend.

**Why?**
This would reduce the environmental impact of dogecoin while on the same time help to make a true currency from the people for the people.

If the amount of your basic income / universal dividend depends on the participation in the doge economy  this would also help drastically to increase adoption of doge since you are incentivized to use doge.

**How?**
This could be implemented as a soft fork in a second layer like for example dash did it with the master nodes rewards.

Layer one would still be the good old dogecoin like now and can be slowly improved.
Layer two can be activated in a soft fork. The fall back would always be layer one.

As basis for implementation the cosmos technology could be used, which should right now provide a big chunk of the needed features.

**Comment by thooton** [comment]
How are you going to defend against Sybil attacks?

**Comment by Arcurus** [comment]
**"How are you going to defend against Sybil attacks?"**

First of all in worst case, if all try to cheat, the fall back would be like with proof of use / proof stake. In this case the more you use / stake the coins the more you get. Which would be better then now burning all for POW.

But now back to the question:

There are mainly two solutions that can be combined (bottom up / vs top down)

**Bottom up - Web of Trust:**
At best we would make "doge parties" around the world, where people can verify each other, same way like they do already now with PGP, but with a "little" bit more fun.

A currency that implemented already a web of trust plus basic income is Duniter:
https://duniter.org/en/

In short they use a web of trust where you need to have a max distance to X% to the sentries. 

While a sentry has certain conditions like being connected to X% of the sentries over a max distance.

It would start with an initial web of trust and then be extend with time (the possible verifications per time per member are limited).

**Top down - Verificators**
Additionally / Alternatively we could require to be verified through verificators.
The verificators could be voted in / out using blockchain based liquid democracy techniques.
If needed each new person could be assigned two random chosen verificators (4 eyes principle). 
 
Both methods could be combined. For example we could use a web of trust between sentries, which then have the task to vote in / out verificators.

**Dividing in Groups / Regions**
Optionally we could also divide people in groups / regions to optimize verification process / and or the web of trust.

**Economic Incentives:**
Additionally we could give an economic reward for finding double accounts.
We could also require that you need to have people which pledge for you, which then have to pay the penalty if you cheated.

In short: We don't need to find all double accounts, we needs to find most of the double accounts in an acceptable time period. Which method (top down or bottom up or a combination of both) is best for that time will tell.

**Comment by Arcurus** [comment]
By the way here are some suggestions of how to secure the network in layer two:
1. (Master Nodes) Do it like dash does it. Each master node needs a certain amount of doge. 
2. (Proof of Stake) Use proof of stake like cosmos does
3. (Proof of Members) Use instead of the staked coins the people who are verified and participated with at least X coins

**Comment by Arcurus** [comment]
I think a nice way of solving the Sybil problem would be to to make a competition between different member verification projects. The one with the best outcomes (number of double accounts that managed to sneak in / vs growth grate / ease of use) can then be used. Or even better a continues competition could be allowed while economically incentivizing projects that manage to have more active participants with less double accounts.

**Comment by m-luck** [comment]
Interesting. What numbers / percentages are you thinking? Is it a nontrivial amount, and does it change over time? 

I think this is actually an intriguing idea. Let's engage with actual present numbers if possible. 

After that, can discuss if incentives line up.

**Comment by Arcurus** [comment]
> Interesting. What numbers / percentages are you thinking? Is it a nontrivial amount, and does it change over time?
> 
> I think this is actually an intriguing idea. Let's engage with actual present numbers if possible.

I think the actual amount depends very much on many factors that are not yet known. Ideally there should be a system the community can vote on the parameters.
 
As a roadmap I would suggest to go the following way:
1. Do a prototype to see which functions / parameters are needed. I did already a very very basic one just to get a feeling. Its super basic, no crypto in it yet / no server nothing, just a simple program to test how it would look / feel.
2. Use something like Cosmos or Cardano to implement a first "functional" prototype which allows to add / verify multiple people. With this the first test could be run. (bringing this to run I could need some help)
3. Run it in a second layer with a one way peg to doge. For example by donating / burning some doge you can create doge X in the second layer.  This can already run on its own without the need of any change to doge core or core devs.
4. Once it proofs to work and has the acceptance of the community a certain % of the blockreward / fees can be additionally distributed as basic income through a soft fork.

How big this % would be depends very much on how much is still needed for POW once there is a second layer securing the chain is in place. I think here we can learn from how dash did it with the second layer master nodes, which use a kind of softfork to use a part of the block reward for their treasury and master node reward.   

If you are interested, i wrote a more detailed early draft doc with some basics (mainly about economics) how it could look. If you are interested just write me at martin_auer (at) gmx.net

**Comment by ubiubi18** [comment]
Sybil resistant identity is a non-trivial effort. It is like the holy fail of blockchain. If we have sybil-resistant identity, we won't even need PoW anymore. But it is really hard to achieve. As much as I love duniter (trying to join for several years, but it is restricted to france) I think it is not sybil-resistant at global scale. Web of trust works only locally. 

And even centralized verification doesn't work that well and is risky.  Id-card fraud, registering accounts with stolen or abused documents is quite common in blockchain-sphere. 

I think the most realistic option so far is idena.io, as much as i would love it to be duniter (which has more sustainable cryptonomics than any other project)

**Comment by Arcurus** [comment]
> Sybil resistant identity is a non-trivial effort. It is like the holy grail of blockchain. If we have sybil-resistant identity, we won't even need PoW anymore. But it is really hard to achieve. As much as I love duniter (trying to join for several years, but it is kind of restricted to France) I think it is not sybil-resistant at global scale. Web of trust works only locally.

Great to have one from Duniter! Also loved it very much (helped to find some bugs), then suddenly they dropped all Englisch... always these French :/ Also i was missing some economic incentives there like connecting the amount of basic income you get with the amount of participation.

Yea its the holy grail, but as said, I dont think that it needs to be 100% perfekt. The worst fall back would be something similar to proof of stake / use, since my plan is to connect the amount of basic income / universal dividend you get with how much you use the coin.

Also I think giving the right economic incentives could help a big deal to find double accounts, so that they wont take over.

On a global scale dividing the network of trust in different regions could help a lot. These regions could then be tested / people can try to create double accounts. The more double accounts a certain region lets in the less high their basic income could be relative to the other regions.

**Comment by ubiubi18** [comment]
I think if sybil resistance is not 100% secure, it will fail to provide value. I like the idea of regional shards, but again you would need to be able to prove which region people do come from. It is pretty easy to use VPN and claim to be from whatever Continent you like.

Until last year I was following a project that did try  to make use of official passport-certificates. Ubic.app 

The dev made it secure and the tech is just fine, but no matter that at some point suddenly a unknown Player started to register thousands of passports within short time, with no community growth behind it. Probably stolen data or abused passports of people in a travel agency. It turns out even KYC is vulnerable without additional security measurements, if you try to decentralize it. 

Here is another hint at KYC-data beeing leaked and traded all the time
https://e.vnexpress.net/news/news/personal-data-leak-affects-thousands-of-vietnamese-4279503.html

An argument against web of trust approaches on the other hand is the lack of privacy protection. People at duniter wot are mostly known with their faces or at last easy to track. 

But I hope someone finds a way. It is really worth trying out. 

I strongly recommend you to really look into idena.io  

The downfall of that idea is, that it consumes a lot of time and effort to verify your anonymous unique identity, but at last it seems sybil resistant in opposite to WoT or KYC-solutions

**Comment by patricklodder** [comment]
This would be perfect for another coin! Closing this per #2110 point 4.

**Comment by Arcurus** [comment]
This proposal is a protocol change (soft fork) with use case "basic income / universal dividend".  This proposal is not about a hard fork or an new coin. A possible solution to implement it would be to have in the end a two way peg to a layer two who can handle the needed complexity. So one doge would be one doge. Looking at the updated issue submission rules it would be a "grey" area (none of 1-8). Maybe add a point 9, protocol change too big / complex to discuss here and provide some clear rules where to discuss these (don't think that reddit is a good place for that).
