### ISSUE TITLE
[feat] Store arbitrary data along transactions (e.g. for NFT)

### ISSUE THREAD

**Issue by maierfelix** [dogecoin/dogecoin#2032]
# Feature Request

**Describe the Feature Request**

Projects like Polkadot allow to store arbitrary data along transactions (see [here](https://polkadot.js.org/docs/substrate/extrinsics/#remark_remark-bytes)). Compared to smart contracts, this is a considerably lightweight feature without adding too much overhead to the network. At the same time, this would open the door to a lot new interesting things. An example use case are NFTs (see the [RMRK protocol](https://docs.google.com/document/u/1/d/e/2PACX-1vToDf7FmFbNwnIvXJeCvWvXscG7HwL638eeuAlV3-692vExzpzoHJNAmqc-jEu2IeOEyYgJuN_Fn4th/pub) on how a NFT system can be put on top of this).

**Describe Preferred Solution**

Consider allowing to add arbitrary byte-based data along transactions (a limit of 8kb could be enough). The additional transaction fee could be determined based on the size of the data.

**Additional Context**

I'm relatively new to blockchain development, but in case anyone thinks this a considerable feature request, then I'll do my best to discuss this further!

**Comment by IndianBoy6** [comment]
@maierfelix  I've never done any blockchain stuff and I'd have to do a lot of research but I would be willing to help out where I can on this.

**Comment by m-luck** [comment]
This is a fine idea. I would research how ether tokens do it and perhaps propose some pseudo-code.

In a realer sense, to attach a note or real world SKU or ID to a transaction is useful. Purchasing of property, Snickers, etc, all using in currencies. These IDs/notes could be hashed so only the parties involved in that purchase can read them.

Other than that, I don't believe there's much utility. The main thing you want is ability to provide proof of purchase upon request, if you think based in the real world with real goods.

**Comment by patricklodder** [comment]
Hi! Storing arbitrary data will reduce capacity for actual transactions. I would recommend building NFTs on a side-chain, or utilize a cross-chain token bridge. Let's discuss further on https://www.reddit.com/r/dogecoindev/
