### ISSUE TITLE
[feat] Stick to cars and rockets

### ISSUE THREAD

**Issue by mixtmick** [dogecoin/dogecoin#2034]
Elon Musk want to do crypto but is only making it look ridiculous....

**Comment by Cyclic** [comment]
You mean finance (PayPal, also has an MBA from Stanford), solar (Solar City), battery tech (Tesla), AI (SpaceX, Tesla), rockets (SpaceX), Neuralink (organic intelligence, machine/human integration), crypto (large whale in BTC).

Stop beclowning yourself. So many people like you are on here trolling, like they've done anything helpful for humanity. Just clown at the circus, not on here, please. We are here to GSD, if you even understand what that means.

**Comment by greboide** [comment]
I think we need more stickers of cars and rockets and doges to the moon and beyond, it can even be ridiculous!!!

**Comment by rnicoll** [comment]
We are not in control of Elon.
