### ISSUE TITLE
Multi chain identification

### ISSUE THREAD

**Issue by Aivolt1** [dogecoin/dogecoin#2035]
Help me build a Multi-chain HTML platform which will enable users to identify any txn, block or wallet associated to transactions taking place on the blockchain. This will eliminate the struggle for user to search and identify a block produced by searching on several chains. This project needs to have compiled all solidities under one HTML platform registered on the Doge chain as multi sig confirmation API interconnecting the Internet of Blockchain.

**Comment by thooton** [comment]
Why search on several chains when the transaction is only on the DOGE chain?

**Comment by Aivolt1** [comment]
Is it possible to creat a HTML site which identifies transactions taken place on any chain but the individual trying to identify the source of the transactions must contribute in Dogecoin in order to access various transaction and  identifying the source of the transactions.

**Comment by thooton** [comment]
There is no point, firstly because nobody would pay $1 DOGE fees just to look up their transaction and secondly because I cannot think of a situation where you would need to use an explorer to find a transaction on multiple chains, when you make a transaction (perhaps a withdrawal or deposit from an exchange, or using the wallet itself) you already know which blockchain you made it on, so you can just use the relevant block explorer

**Comment by rnicoll** [comment]
Isn't that https://chain.so/ ?

**Comment by Aivolt1** [comment]
What if for instance in my case, I have access to the wallets private key, TX hash, block number yet I can't not remember the platform I registered on or the crypto I have purchased searching on the main chain like ETH, BTC , LTC , Doge and via the EVM I'm able to identify the funds yet can't seem to locate the platform used. Also there will be no fee ! As the payment will be made via a doge NFT raffle or the garlicoin project?

**Comment by Aivolt1** [comment]
Https://chain.so currently showing error

**Comment by m-luck** [comment]
chain.so loading for me. Believe this can be closed. Nothing preventing a third party from making a searchable, read-only web app sourcing from the data of a full node. 

As for accessing wallets where you have forgotten the platform, that's a lot like accessing a physical bank vault if you have forgotten the location. Impenetrable, and arguably, good for keeping active coin supply less abundant (over generations).
