### ISSUE TITLE
[feat] Make DOGE the Worlds's Currency

### ISSUE THREAD

**Issue by bernieblume** [dogecoin/dogecoin#2036]
# Make DOGE the World Currency

First thing we need to do is transition from PoW to PoS or more specific DPoS. Will drastically speed up TPS and all but eliminate carbon footprint. Lots of research & previous work out there for DPoS to pull ideas and code from, to incorporate into Doge. Transition current DOGE chain to new DPoS chain so current holders & HODLers keep their assets.

Nano (the blockchain) won't cut it, we need fees in order to be secure and resilient enough to become (and stay) the world's currency.

I like Cardano, but it's a bit heavy on academics (this can be a disadvantage) and Hoskinson's demeanor these days doesn't radiate a lot of confidence imho. Can use some of their ideas, though.

Ethereum 2.0 is absolutely great and Vitalik is a truly awesome guy, in so many (if not all?) respects. However, Eth doesn't feel like "ours", feels more like the established "big guys" these days, very serious. Want some more lightness & approachability in the brand: Doge :-)

Key for longterm adoption, security & scalability is EXTREME decentralization. Everyone needs to be able to run a block producing node on a Raspberry Pi!

Just pull the bare necessities from existing projects, so that a Doge node can run on 2GB RAM.

This ^^^ is the MVP, let's get started. At this stage, we have a high-throughput, low-fee, secure & resilient crypto that is very fun, too.

Then vvv the roadmap.

Implement smart contracts. If we don't do that, some other crypto WITH smart contracts will become the world's currency and kick us out of the market.

To be both scalable and and decentralized, we will introduce hyper sharding. With regular sharding, a single node will always be on its own to run the smart contracts contained in the block. This limits scalability in micro nodes such as Raspberry Pi's.

With hypersharding, even smart contract execution is distributed.

That way, everyone can help run the network (and get compensated for it) by running a fanless, silent and cheap device from their home. Few people will leave their laptop running day and night. Different story for Raspberry Pi or devices like an Antsle One (antsle.com).

With this roadmap, Doge will take over the earth. And moon. And ...

I run a small company (Antsle) with a few thousand customers who run Antsle's server virtualization software, mostly on Antsle's silent server devices.

I personally (as well as Antsle) would love to help push Doge forward along the lines outlined above. Many Antsle customers have voiced the wish to help run blockchains with our server appliances. I'm sure we'll have the first 1,000 enthusiastic node operators virtually from day 1.

More detailed plan and capital requirements / timeline on request (not in public please).

**Comment by alanconrad** [comment]
From my view, it's imperative that a digital currency meant for the transfer of value should not have smart contracts. A monetary protocol should only have one demand curve - using the network for money transfers. Any additional features would lead to less efficient value transfers due to larger transaction sizes and individuals using the network for other means.

**Comment by angelcervantesa** [comment]
damn.

**Comment by thooton** [comment]
> we need fees in order to be secure and resilient enough to become (and stay) the world's currency.

If you are aiming for world currency status, fees are simply not an option psychologically. If I feel that I am losing something when I perform a simple transfer, I will avoid using the cryptocurrency whenever possible and will likely stick to cash, where its value is not depleted simply because I hand it to someone else and they hand it back.

Block time is also an issue. If I wish to make a purchase and have to wait for two minutes, one minute, or even fifteen seconds longer than usual, there is simply no point in not using a conventional option.

**Comment by bernTOAST** [comment]
You get fees all the time and pay them with no mind. Majority of populations use digital currency already just in state backed fiat form. Fees are fine. How and what those fees should do and who they should go to is a contentious issue. I think there should be some sort of air drop of collected fees every month or something or the sorts.

**Comment by bernieblume** [comment]
> From my view, it's imperative that a digital currency meant for the transfer of value should not have smart contracts. A monetary protocol should only have one demand curve - using the network for money transfers. Any additional features would lead to less efficient value transfers due to larger transaction sizes and individuals using the network for other means.

In my view, that is only conditionally true. Concerns (transfer of value vs smart contracts) can be separated, we can use UTXO (or an extension thereof) for transfer of value, without invoking any smart contract functionality.

Let's do one step after the other. Start without smart contracts. I just feel if there is a GOOD smart contract blockchain out there, that can handle payments as well (which it eventually will), there will be no place in the world (at least not as the leader) that does "only" payments. Both are interconnected, and the one with the least friction wins.

**Comment by bernieblume** [comment]
> > we need fees in order to be secure and resilient enough to become (and stay) the world's currency.
> 
> If you are aiming for world currency status, fees are simply not an option psychologically. If I feel that I am losing something when I perform a simple transfer, I will avoid using the cryptocurrency whenever possible and will likely stick to cash, where its value is not depleted simply because I hand it to someone else and they hand it back.
> 
> Block time is also an issue. If I wish to make a purchase and have to wait for two minutes, one minute, or even fifteen seconds longer than usual, there is simply no point in not using a conventional option.

It will cost a lot of resources (equipment, time, ...) to run a huge blockchain securely over time. We want to make sure it stays that way. Asking people to donate their time and equipment is not sustainable. Also, Byzantine Fault Tolerance requires some sort of resources (as in PoW) or proxies for resources (as in PoS) to be put on the table or "staked". Otherwise, bad guys (think nation state actors) have too easy a time to attack and possible take over the network.

**Comment by Arcurus** [comment]
> If you are aiming for world currency status, fees are simply not an option psychologically. 

Fees could be paid by the one accepting the transaction. Business are used to pay fees already.
Technically it is simple, the one who accepts the payments adds a second transaction and pays the fees for both. Or alternatively the payment providers pays miner directly to put the transaction in.
Or just use something like lightning network.

 
> Block time is also an issue. If I wish to make a purchase and have to wait for two minutes, one minute, or even fifteen seconds longer than usual, there is simply no point in not using a conventional option.

For most if replacing of transactions is deactivated and the blocks are not full, you can accept most transactions with 0 confs without much risks. Additionally it should not be too difficult for bigger payment providers to make an agreement with 60% of the mining pools to not include a double spend transaction. Or use lightning.

**Comment by Arcurus** [comment]
> From my view, it's imperative that a digital currency meant for the transfer of value should not have smart contracts. A monetary protocol should only have one demand curve - using the network for money transfers. Any additional features would lead to less efficient value transfers due to larger transaction sizes and individuals using the network for other means.

Should be possible to add smart contracts through a soft fork in a layer two.
As base something like cosmos tech could be used.

Layer one would be still simple proof of work with simple transactions, while layer two could be proof of stake plus smart stuff.

It could be done similar like dash added the master nodes. Coins moved to layer two could only be moved if X% of the master nodes (stakers) approve. 

Seen from layer one coins moved to layer two could be spent by all, but technically cannot because through a soft fork X% of master nodes must agree to the transactions moved to known layer two addresses.

**Comment by Drael64** [comment]
Proof of stake is less democratic, in that it favors the rich. ADA has an approved node list (ie is centralized). Smart contracts can be run multichain, there's no real need to have them native.

**Comment by Drael64** [comment]
> > we need fees in order to be secure and resilient enough to become (and stay) the world's currency.
> 
> If you are aiming for world currency status, fees are simply not an option psychologically. If I feel that I am losing something when I perform a simple transfer, I will avoid using the cryptocurrency whenever possible and will likely stick to cash, where its value is not depleted simply because I hand it to someone else and they hand it back.
> 
> Block time is also an issue. If I wish to make a purchase and have to wait for two minutes, one minute, or even fifteen seconds longer than usual, there is simply no point in not using a conventional option.

And yet people use paypal, pay credit/debit card convenience fees, card fees and so on. Basically any existing fiat option has fees everywhere. 

I agree on the time element. It's not however easy to solve whilst keeping things decentralized. Long term this should be solvable IMO, by using offchain, and onchain scaling methods. Existing payment methods are fast because they are centralized. Catching up to that is a long term technical project.

**Comment by bernieblume** [comment]
> Proof of stake is less democratic, in that it favors the rich. At a low barrier to entry one can meaningfully participate in dogecoin mining, but it takes MUCH more money to meaningfully participate in staking. ADA has an approved node list (ie is centralized).
> 
> Smart contracts can be run multichain, there's no real need to have them native. Flare, thorchain, cosmos and others will provide this. The lowest friction option will rise to the top.

Whether the rich pay for coins or for mining equipment/electricity -> same thing. Compared to proof of work, proof of stake does NOT favor the rich. To the contrary: Proof of work favors the ones who are [1] to buy equipment and pay for electricity and other operating costs AND [2] have good connections to be able to get their hands on mining equipment at all! There is simply ZERO merit to PoW, imho.

**Comment by Drael64** [comment]
> > Proof of stake is less democratic, in that it favors the rich. At a low barrier to entry one can meaningfully participate in dogecoin mining, but it takes MUCH more money to meaningfully participate in staking. ADA has an approved node list (ie is centralized).
> > Smart contracts can be run multichain, there's no real need to have them native. Flare, thorchain, cosmos and others will provide this. The lowest friction option will rise to the top.
> 
> Whether the rich pay for coins or for mining equipment/electricity -> same thing. Compared to proof of work, proof of stake does NOT favor the rich. To the contrary: Proof of work favors the ones who are [1] rich to buy equipment and pay for electricity and other operating costs AND [2] have good connections to be able to get their hands on mining equipment at all! There is simply ZERO merit to PoW, imho.

No, it's not. For 3k USD you can buy a miner and get meaningful passive income. Staking the same amount will buy you a coffee a year.

**Comment by bernieblume** [comment]
> > > Proof of stake is less democratic, in that it favors the rich. At a low barrier to entry one can meaningfully participate in dogecoin mining, but it takes MUCH more money to meaningfully participate in staking. ADA has an approved node list (ie is centralized).
> 
> > > Smart contracts can be run multichain, there's no real need to have them native. Flare, thorchain, cosmos and others will provide this. The lowest friction option will rise to the top.
> 
> > 
> 
> > Whether the rich pay for coins or for mining equipment/electricity -> same thing. Compared to proof of work, proof of stake does NOT favor the rich. To the contrary: Proof of work favors the ones who are [1] rich to buy equipment and pay for electricity and other operating costs AND [2] have good connections to be able to get their hands on mining equipment at all! There is simply ZERO merit to PoW, imho.
> 
> 
> 
> No, it's not. For 3k USD you can buy a miner and get meaningful passive income. Staking the same amount will buy you a coffee a year. 

That seems more a statement about returns on PoW or PoS, which depends (and fluctuates massively) between various cryptos, times in their lifecycles, market conditions and much more. It seems less a statement about PoS or PoW being more "democratic" or decentralized.

**Comment by Drael64** [comment]
> > > > Proof of stake is less democratic, in that it favors the rich. At a low barrier to entry one can meaningfully participate in dogecoin mining, but it takes MUCH more money to meaningfully participate in staking. ADA has an approved node list (ie is centralized).
> > 
> > 
> > > > Smart contracts can be run multichain, there's no real need to have them native. Flare, thorchain, cosmos and others will provide this. The lowest friction option will rise to the top.
> > 
> > 
> > > 
> > 
> > 
> > > Whether the rich pay for coins or for mining equipment/electricity -> same thing. Compared to proof of work, proof of stake does NOT favor the rich. To the contrary: Proof of work favors the ones who are [1] rich to buy equipment and pay for electricity and other operating costs AND [2] have good connections to be able to get their hands on mining equipment at all! There is simply ZERO merit to PoW, imho.
> > 
> > 
> > No, it's not. For 3k USD you can buy a miner and get meaningful passive income. Staking the same amount will buy you a coffee a year.
> 
> That seems more a statement about returns on PoW or PoS, which depends (and fluctuates massively) between various cryptos, times in their lifecycles, market conditions and much more. It seems less a statement about PoS or PoW being more "democratic" or decentralized.

Well effectively the incentive for participation, and actual participation are the same thing. Dogecoin being merged mined means that market conditions effect it less than other coins.

**Comment by patricklodder** [comment]
Closing this per #2110 point 8
