### ISSUE TITLE
Idea lava lamps as cpsrng

### ISSUE THREAD

**Issue by guccizilla** [dogecoin/dogecoin#2037]
# Feature Request

**Describe the Feature Request**
  Use lava lamps as cpsrng system like cloud flare 

**Describe Preferred Solution**
Lava lamps move in random patterns cloud flare creates crypto keys using it already I would like to see lava lamps integrated into the cpsrng system You could have walls of lava lamps using a camera as input into the CSPRNG
Possible environmental benefits? I’m not sure but maybe 
<!-- A clear and concise description of what you want to happen. --

**Comment by thooton** [comment]
This would require centralization

**Comment by guccizilla** [comment]
> This would require centralization
Control would be transferred to lava lamp authorities ie decentralized excuse me if I’m confused

**Comment by guccizilla** [comment]
> This would require centralization



> This would require centralization

Also see league of entropy they say other organizations can join their already decentralized lava network

**Comment by guccizilla** [comment]
Plus dogecoin value already increases off a meme  it would add another niche, randomness is also an iconic staple of the internet

**Comment by RichDevX** [comment]
You can do that with video-entropyd on linux systems.
https://web.archive.org/web/20210323190233/https://www.vanheusden.com/ved/

It's mainly used by servers that establish a lot of encrypted connections and quickly run out entropy, it isn't really an issue for personal computers.

**Comment by m-luck** [comment]
I do not think this is immediately relevant. If you wanted to do something for synergistic marketing purposes, you could probably use source signals from a Neuralink chip of an unknown pig. Source: have a neuroscience degree, and at time of writing eat bacon.

**Comment by RichDevX** [comment]
@m-luck you could probably do that by modifying audio_entropyd
https://web.archive.org/web/20210323190233/https://www.vanheusden.com/aed/

**Comment by patricklodder** [comment]
Sounds interesting. Please let us know when you have an implementation done!
