### ISSUE TITLE
[feat] Use Elon Musk's connections to gain widespread political support

### ISSUE THREAD

**Issue by elonissocool** [dogecoin/dogecoin#2039]
There is no global currency or currency of the people without the support of governments, for better or worse. An opportunity has fallen into this community's collective lap, it should not be wasted.

**Comment by m-luck** [comment]
Bit out of scope for GitHub. I think this is well underway, but the work we should do is learning the technical knowhow and making the product the best it can be. The publicity will follow. 

I encourage learning the ropes of GitHub and to start contributing code!

**Comment by rnicoll** [comment]
Appreciate the enthusiasm, we're just the Dogecoin Core maintainers, bit out of scope for us as m-luck says.
