### ISSUE TITLE
[feat] marketing?

### ISSUE THREAD

**Issue by aggy96** [dogecoin/dogecoin#2040]
Disclaimer idk shit about crypto, I’m learning, I mostly just like to see my portfolio go up in value and know 0 about fundamentals rn so I may sound like an idiot. 

But doge seems to me like it is a marketing goldmine for many businesses that are trying to differentiate themselves in the market and I think it’s one of the major appeals that this coin has because it can relate to such a wide audience and demographic because of its branding.

The idea would be to try and promote the coin to businesses and essentially manufacture a deal where we can get them to accept doge as a currency with the stipulation that they have to hold on to their doge that they accumulated for at least one year, having many businesses agree to this model on a wide scale would allow the coin to build up and not be used in a way where the companies will quickly liquidate but rather hold on and see their total value increase as the coin continues to rise in value and hence their previous sales would accumulate more value. Doing this on a wide scale would quickly dispel the notion that the coin has little use case and really push it into the mainstream world.

There’s definitely flaws in this but I didn’t really take too long to look to see every potential pitfall but I thought about a few, I would assume someone (prob Elon) would have to fork up money to entice this form of deal to be accepted by businesses, like an up front payment to the company to take this coin on. Because outside of it there is little incentive for a business to just not make the decision on their own to accept doge and feel free to hold/sell their coins at their own desire and need. But the stability formed and the launching pad that would be created from that would be interesting to see. I could also see how whatever money was spent trying to get doge through the door on a wide scale for businesses would not look like money terribly spent if the coin can essentially be used for stores that are heavily frequented. Like Starbucks/Dunkin, McDonald’s or other common fast food shops, Stores, Gas Stations, etc.. Basically any place that is heavily frequented and really holds a grip on almost every citizen, this would put doge basically everywhere people go and again massively increase the use case of the coin. Another pitfall I see is the amount of damage that could be caused if the coin were to be collectively dumped by every or a lot of the businesses when the stipulation for the 1 year holding period ends. I can’t really see a 2 year holding period being even conceivable because no business would not take their profit that quickly and it would just put on a bandaid on the problem. Another pitfall that I may just be an idiot for overlooking until now is that some companies may be unwilling to do this because they need to pay for their employees to work, big shocker, and they may not want to fork over some of their reserve cash to hold on to their incoming, recent, and past sales revenue. This would probably be a problem for companies who do not operate on a really high scale so their sales revenue may be of more importance. I would say if that is the case then there could be another stipulation that the employer was in this position they could then distribute the doge from their wallet to their employees directly who would be free to liquidate to and receive their salary in that way if they choose. One benefit to this is that it would increase more people having crypto wallets and becoming more introduced to the world of crypto as well because their basically getting paid in crypto.  

Idk it’s a rough draft of an idea that I don’t even know if I’m supposed to put in here or in the doge subreddit but w/e if y’all are viewing this I pulled the trig and posted

**Comment by m-luck** [comment]
I understand. However, that's not the scope here on GitHub. Here, code and product will be developed -- the marketing is ancillary. 

Good product practices will lead to adoption. Just need to put in the time. Once the product is able to be adopted by heavy hitters, everyone else will follow. For now, let's put the horse before the cart.
