### ISSUE TITLE
[feat] Proof of D.O.G.E. 

### ISSUE THREAD

**Issue by LTCO-USA** [dogecoin/dogecoin#2041]
I saw Elon's Tweeter and would like to help develop Doge.

I have an idea. I propose to develop a mining system/software to cluster all miner's devices as a cluster computing supercomputer(s) to solve human's current computing challenges. Scientists, engineers, mathematicians, and others can use computing power for their researches to save the world, such as renewable energy, space science, electric vehicle, and etc. It will reduce the cost to develop supercomputers and put all mining energy to good use as the DOGE's spirit, Do Only Good Everyday!! Using the proof of D.O.G.E. to get the reward. 

1 Dogecoin = 1 Dogecoin. To the moon!!!

Best Regards,
LCo

**Comment by greboide** [comment]
Somehow that is how I see a cryptocurrency now, instead of a ponzi scheme. I see it as a pool of dog money that you can take it when you need, like you lose 1 DOGE and get a low valued fiat to buy groceries and stuff. But regarding your idea this is something too hard for us to develop, not that it is a bad idea, just a bit out of scope i think.

**Comment by IndianBoy6** [comment]
Things like [BOINC](https://boinc.berkeley.edu/) already exist. I'm not sure that we would be adding anything new and in the end, we would just be dividing the computing we have.

**Comment by nullbio** [comment]
This is already being done by the Banano meme coin. You can Fold@Home to earn Banano (reddit.com/r/banano if you're curious).

**Comment by LTCO-USA** [comment]
Thank you for all your inputs. I did not know those exist already. Those are great and hope they will succeed. I learned a lot today.

BOINC doesn't have a cryptocurrency as rewards to motivate people, and Banano is focusing on medical research, which is wonderful. I will look into that for sure.

I am thinking maybe Dogecoin can focus on ML (ex. auto-pilot), big data or a specific computing area? There are massive needs for computing power I can see, and many of them can help our world become better.

**Comment by simonmadsen** [comment]
how about cure and folding at home, also similar perhaps

**Comment by rnicoll** [comment]
Would https://www.dogecoinfah.com/ be a close enough match to what you're trying to achieve?

**Comment by simonmadsen** [comment]
> Would https://www.dogecoinfah.com/ be a close enough match to what you're trying to achieve?

oh yea, probably

**Comment by LTCO-USA** [comment]
Yes! Thank you for spending time to react to all of our crazy suggestions. DOGE is great because of people. Thank you again, Ross and your team for keeping DOGECOIN strong and great.

To the moon!

best regards,
LCo
A Doge Hodler since 2018.

**Comment by LTCO-USA** [comment]
By the way, dogecoinfah.com and fold @ home are great. I love their ideas. However, it is relying on donations (100 doges per week for all contributors). Is it possible to have DOGECOIN-Official to support that program, so it becomes a more "mining-like" work for D.O.G.E. and a long-term contribution to the world? Thank you again. :)
