### ISSUE TITLE
[project-idea] creating a new system for life using dogecoin

### ISSUE THREAD

**Issue by C93M** [dogecoin/dogecoin#2043]
Development of a massive multi-user online system, using an cryptocurrency DOGECOIN  and blockchain technologies.

If you plan to consider the future use of cryptocurrency in our life, then our project is just right:
[LIFE SYSTEM .pdf](https://github.com/dogecoin/dogecoin/files/6535808/LIFE.SYSTEM.pdf)

**Comment by m-luck** [comment]
I read through your slides. Interesting. Not sure I understand a lot of them, but looks like you put in a lot of effort. 

I think with the professional development of this repo, what you picture in your slide can be attained in some capacity. Care to discuss more, or talk about any technical terms in English? (Most of the slides were just diagrams)

**Comment by C93M** [comment]
> Привет! Вы можете использовать Dogecoin в своих боковых цепях и в своих приложениях уже сегодня. Пожалуйста, обсудите это на Reddit: https://www.reddit.com/r/dogecoindev/

well thank you. I'll open a topic in reddit
