### ISSUE TITLE
[idea] Integration of Neural Net and Search Engine for Proof of Work

### ISSUE THREAD

**Issue by CuttyFlam-Franky** [dogecoin/dogecoin#2045]
There is a Memory-Based Neural Network framework I would like to tinker to speedup / reduce the necessary computation for Proof of Work.

Main idea of the framework is based on these two papers:
https://arxiv.org/abs/2005.11401
https://arxiv.org/abs/1910.13406

Short Summary:
Query a database to retrieve relevant blocks of data, use the retrieved blocks as additional input to train a neural net.
The neural net is trained to predict sequential input and output.

I would like to work on this side project to see whether there is any merit to integrate a search engine function on the blockchain. And whether there is a possibility to integrate neural net to map the Proof of Work.

Hope that any performance gain can benefit the efficiency of the miners.

I want to start by building a search engine on all input / output pair

 - What would be the best way to stream / download all the existing input / output that a miner would see?

Thanks
- Super Franky

**Comment by rnicoll** [comment]
Proof of work exists to make it impractical for anyone to have enough processing power to control the ordering of blocks. The complexity is (and has to be) automatically rescaled based on how much computation is on the network, so even if the community would adopt an algorithm change, the complexity has to remain high enough that it's impractical for any single entity to control more than 50% of the computation used on the network.

What I mean is, we can't make it less computationally intensive and it still be functional proof of work.

**Comment by CuttyFlam-Franky** [comment]
One part makes sense.

The other part...
We do want decentralized mining, but with the rescaling algorithm, the more people adopt, the less efficient Dogecoin becomes (both mining and transaction)

Seems rescaling algorithm will eventually be phased out.

Will be back and integrate the AI components when that happen.

- Super Franky
