### ISSUE TITLE
[feat] ARM port and ARM assembly optimization for energy savings

### ISSUE THREAD

**Issue by smartops-main** [dogecoin/dogecoin#2046]
Was thinking about the energy efficiency aspect of recent comments/commentary.  Was considering doing a port to ARM and then profiling the code and finding a short (maybe long) list of routines that would benefit from conversion to ARM assembly code.  New to the codebase, so maybe this has already been done in part or attempted?  Also, I found a few vendors that have ARM server boards/systems but obviously, the vastly smaller ARM server chip supply over x86 ecosystem is a risk.  

But, I was just thinking about best case 'how do we make the code as energy efficient as possible' and therefore thought of ARM port and then assembly optimization.  And if anyone really wants to get into a discussion about energy efficiency, I'd share some plans/thoughts I have about a solar/wind sustainable data center design I've been kicking around for awhile.  But, that's down the road and would have application not just for Doge.

Anyway, I'll keep plugging along and learning the code and see what I can do...  cheers to the devs, best of luck

UP BOY, UP!!!!!

**Comment by vertiond** [comment]
An ARM build exists: https://github.com/dogecoin/dogecoin/releases/download/v1.14.3/dogecoin-1.14.3-arm-linux-gnueabihf.tar.gz

I've compiled and run Core on a Pi Zero with no problems.

**Comment by smartops-main** [comment]
> An ARM build exists: https://github.com/dogecoin/dogecoin/releases/download/v1.14.3/dogecoin-1.14.3-arm-linux-gnueabihf.tar.gz
> 
> I've compiled and run Core on a Pi Zero with no problems.

Thanks, I'll give it a look!!
