### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by Ashjo80** [dogecoin/dogecoin#2047]
When will Dogecoin developers will start control and mentor the prices overall the platforms which are playing on selling and buying the coin not in the rightprice? Seems like the coin not supported to stop this kind of issues. The reputations is important in the markets to build the trust for long term. at least  issue a warnings and Giving fines for non-recurrence.  To control these acts.

**Comment by vertiond** [comment]
Please elaborate.

**Comment by vertiond** [comment]
Price discrepancies between exchanges are up to market makers to resolve, not dogecoin developers.

**Comment by Ashjo80** [comment]
Indeed, that's why no one can play with Bitcoin  because they control. All the best

**Comment by rnicoll** [comment]
The prices are set by the market, we do not set them. It's important to remember here that Dogecoin is decentralised, the vast majority of the coins have been mined already and are in the hands of individuals (who are free to determine their price to sell to you), and new mined coins go to the miners.

**Comment by Ashjo80** [comment]
Rnicoll thank you for your prompt response, i understand this, i think you get me wrong, the prices are stable in the markets, except one platform called HitBTC, which we  buy half million Dogecoin from them. The price in this platform at this moment. 12 cents. Globally 35 cents. I know you cant assist.
