### ISSUE TITLE
Limit Dogecoin supply, Make it a erc20 token, use doge as a governance token to make it a DAO

### ISSUE THREAD

**Issue by ChaituVR** [dogecoin/dogecoin#2048]
https://www.reddit.com/r/dogecoin/comments/i3o0ne/erc20_token_for_dogecoin/?utm_medium=android_app&utm_source=share

**Comment by kumikumi** [comment]
It makes no sense for a currency to have a limited supply

**Comment by rnicoll** [comment]
Isn't that reinventing ourselves as Shiba Inu?
