### ISSUE TITLE
[feat] Practical Smart Contracts

### ISSUE THREAD

**Issue by azhtom** [dogecoin/dogecoin#2050]
Maybe Doge could implement FASTKITTEN (https://www.usenix.org/system/files/sec19fall_das_prepub.pdf) to support Smart Contracts. 

Who wants to do it?

**Comment by m-luck** [comment]
Can you propose what this means for the community and how it feeds into the goal to make this the Milky Way's currency? ;)

It would be nice, but tasks ought to be ordered by tractability and impact. It sounds like you want this to happen, so perhaps you should put forth a little development roadmap that the community can vote and discuss on. Genuinely excited if you do!

To answer your question, I and many others probably want to do it, but days have limited time in them!  Let's choose the best things to actually make this the world's currency. From newcomer to newcomer!

**Comment by patricklodder** [comment]
Have code?

**Comment by azhtom** [comment]
Not yet sir

**Comment by patricklodder** [comment]
Alright! So I'm going to close this for now. Please let us know when you have some code and you run into protocol issues!
