### ISSUE TITLE
More Possible Transactions per Block

### ISSUE THREAD

**Issue by m971668** [dogecoin/dogecoin#2051]
It would be nice for the blocksize limit to be removed (like BSV has done...sorry) and all non-monetary transactions be blocked....just debits and credits....

Multisig transactions where the receiver pays the transaction fee.

Enable a monetary transaction "rewards/rebate" where the sender gets a portion of the transaction fee for using Dogecoin as a payment system.

Increase default maximum ancestors count for monetary transactions to 1000.

Eliminate zero transaction fees.   x satoshi/inputs#output#.  Minimum transactions per block requirements.

 Implement MinerId in the coinbase block.

**Comment by gewure** [comment]
there are a lot of duplicate issues like this already

**Comment by m971668** [comment]
Right.  Without actual code this is meaningless.  Hopefully Elon Musk will sponsor developers to address these times and get them into the official roadmap.

**Comment by Drael64** [comment]
We had a pretty productive conversation about all this scaling stuff here:

https://github.com/dogecoin/dogecoin/issues/1849

**Comment by rnicoll** [comment]
You realise we're running at a fraction of maximum capacity right now? I'm not saying we can't hit scaling issues, just that to my mind this is something to tackle after we get increased adoption.

**Comment by m971668** [comment]
I am sorry.  I think you have it backwards, fix the scaling issue, get more adoption.   After realizing why Elon Musk chose to promote Dogecoin, and he isn't actually sponsoring Dogecoin developers, nor is there a Linux Foundation style trade consortium for Dogecoin; this is not a project I will contibute to.  Given the expectation that Dogecoin will fail to scale, on-chain, without breaking the chain of signatures, with increased usage just like BTC and Ethereum; in that one risks a transaction getting "stuck" in the mempool, which after enough interest/transaction-volume fails to process more and more transactions into the next block.  Bitcoin Satoshi Vision (https://github.com/bitcoin-sv/bitcoin-sv) claims their changes will fix this and they have really low fees.  Problem is most of there transactions are non-monetary and a lot of non-financial data is getting "spammed" into the BSV blockchain making it ridiculously bloated.  Also as the fiat price of BSV grows and the block reward alone is enough monetary incentive to mine more merge mining pools will mine blocks with very few transactions.  Transaction fees on BSV are quite low though ( $0.0001 compared to $0.33 ), so most probably won't care the emense disk storage the full node will need as usage grows, just that their transaction gets into a block quickly and will a fraction of a penny transaction fee.
