### ISSUE TITLE
Dogecoin is going to have Segwit and CSV, a must-have feature for Lightning Network.

### ISSUE THREAD

**Issue by JohnChan1017** [dogecoin/dogecoin#2052]
**Dogecoin is going to have Segwit and CSV, a must-have feature for Lightning Network.**

**Comment by Cyclic** [comment]
Just to clear the air about the importance of Lightning Network, check out this job description posted with Visa about 12d ago. If DOGE is to compete with the likes of the big banks, it must be compatible with some of the large POS implementations.

"Good understanding of 2nd layer scaling solutions (Lightning Network), and experience authoring smart contracts to tokenize fiat currencies (Solidity, Rust, Move or other competing technologies)"

[Visa Crypto Role](https://www.glassdoor.com/job-listing/lead-software-engineer-visa-crypto-program-visa-JV_IC1163997_KO0,42_KE43,47.htm?jl=4061777552&pos=311&ao=4134&s=58&guid=00000179a1e4b554ae910d82030dae73&src=GD_JOB_AD&t=SR&vt=w&uido=DB1D3CAC991522EBF4C055F6794D3EEC&cs=1_24855dae&cb=1621918791395&jobListingId=4061777552&ctt=1621919122481)

**Comment by patricklodder** [comment]
Please see #1798
