### ISSUE TITLE
[feat] Use Satrlink Network for doge transaction 

### ISSUE THREAD

**Issue by AlisterTA** [dogecoin/dogecoin#2055]
1) Use Satrlink Network for doge transaction.
2) People who owns your Starlink internet, can pay for internet bill through doge

**Comment by m-luck** [comment]
External tag warranted

**Comment by rnicoll** [comment]
My (extremely limited) understanding is once Starlink is available, it will be a standard Internet platform, as in everything could run over it. So... hopefully this will just happen, but it's not something we can directly control.
