### ISSUE TITLE
[Limit the Dogecoin ]

### ISSUE THREAD

**Issue by Mrbiggbull** [dogecoin/dogecoin#2057]
limit the dogecoin,tesla invest in dogecoin, sell bitcoin --- simple and effective and that's how  it goes to the moon

**Comment by LTCO-USA** [comment]
Then people cash out, and Dogecoin crashed. It is not a real long term plan for Doge development but a Ponzi scheme.

**Comment by Drael64** [comment]
Where do you guys think you are exactly?

**Comment by Darkstarcracker** [comment]
you just want Doge to Fiat value to go up MUCH MUCH higher. but the case in doge coin is to be use in exchange of fiat like USD. But if you think about it if people change their preferred mode of payment to be dogecoin than Fiat then Dogecoins value will truly rise.

**Comment by rnicoll** [comment]
This isn't something the current contributors are willing to do, and notably despite arguments it can't go up as-is, it has gone up around significantly in the last year.
