### ISSUE TITLE
[feat] Development Guideline & Documentation and Development Environment in VM

### ISSUE THREAD

**Issue by ch4meleon** [dogecoin/dogecoin#2061]
# Feature Request

**Describe the Feature Request**
There are many good C/C++ programmers out there but setting up the development environment is always the tedious stage. There is need to provide good documentation and environment VM to speed up the adaptation to let developers jump into development in a quicker way.

**Describe Preferred Solution**
-Provide step-by-step: how to start the dev,  how to setup the development environment
-Use good documentation website such as https://readthedocs.org/
-Provide a development VM that pre-setup and configured for Dogecoin development use.
-Use of docker, etc.
-Medium post for quick start with the development.

**Comment by chromatic** [comment]
Writing a Dockerfile for a bare-bones Linux image wouldn't be too bad and could provide some value. That might leave Windows and Mac developers out, but it's a start.

**Comment by vertiond** [comment]
https://github.com/vertiond/DockerDOGE

**Comment by n0nimouse** [comment]
It would be helpful to have the blockchain/bdb files as a mountable directory from your local filesystem, or have a sidecar image that isolates state from the main wallet container. This would greatly benefit people who want a simple way to run their doge node and update it without having to re-download the chain / backup their keys etc..

**Comment by ch4meleon** [comment]
> https://github.com/vertiond/DockerDOGE

Thanks for the info. Glad to know there is such there.

**Comment by ch4meleon** [comment]
> Writing a Dockerfile for a bare-bones Linux image wouldn't be too bad and could provide some value. That might leave Windows and Mac developers out, but it's a start.

Totally!

**Comment by ch4meleon** [comment]
> It would be helpful to have the blockchain/bdb files as a mountable directory from your local filesystem, or have a sidecar image that isolates state from the main wallet container. This would greatly benefit people who want a simple way to run their doge node and update it without having to re-download the chain / backup their keys etc..

This is an issue with these traditional blockchain design. The files got bigger every time. Need a more efficient way to handle this to be more sustainable.
