### ISSUE TITLE
Tesla can hasten adoption of DOGE like this

### ISSUE THREAD

**Issue by CryptoCooked** [dogecoin/dogecoin#2062]
Tesla buys $5 billion worth of DOGE at current price of $0.35

Tesla announces vehicles will be sold on the basis of 1 Dollar = 1 DOGE for a limited period of time

Thousands of people rush to buy DOGE at sub $1 price, in order to use the DOGE (which they bought at under $1 to buy Tesla on the basis of $1 = 1 DOGE.

Tesla Buyers will always buy DOGE if it falls to sub $1 pricing so that they can get a discount on the Tesla price.

Tesla uses the $5 Bill DOGE (now worth closer to $12bill), to subsidize any (unlikely)shortfall in DOGE to USD conversion value.

This pegs / stabilises the value of DOGE, increasing market cap and improving adoption and use case,  until the next ....

**Comment by bbcmpc** [comment]
How does this benefit Tesla or their investors? What incentive do they have to do this?

**Comment by CryptoCooked** [comment]
Tesla's customers get a discount on the price of Tesla, if the price is lower, then more Tesla's are sold. More sales is good for shareholders. The initial $5billion dollars becomes worth closer to $12billion due to the announcement and the $7 billion surplus can be used to offset any shortfall on the sale of DOGE into $

**Comment by CryptoCooked** [comment]
Development of DOGE encompasses adoption of it?

**Comment by bbcmpc** [comment]
>if the price is lower, then more Tesla's are sold

Yes, and if you sold Teslas for only $1k each, you could sell tons more of them

>More sales is good for shareholders

Assuming the sale value is greater than the production cost.

If they can sell all their DOGE (initial investment and amounts from vehicle sales) for $1 each, yes, they've made a profit. But that is assuming there is enough liquidity in the market willing to buy billions of dollars worth of DOGE at $1 each. It's a pretty crazy scheme that could easily just lose them billions of dollars for nothing.

Also, GitHub is entirely the wrong place for a discussion that has absolutely nothing to do with Dogecoin software development.

**Comment by CryptoCooked** [comment]
You're not following what I'm saying. Sell Tesla's for $39 000 or D39 000 customer can chose, but if they pay in DOGE then they have a chance of buying DOGE for less than $1, thereby getting a discount on DOGE. Tesla can sell the DOGE at $1 or less, if less they can supplement the shortfall with the massive gain / pump on the initial $5 billion which would amount to a surplus of $7 billion. It's a lot of room for a lot of discount for a lot of Tesla's while causing mass adoption. Tech issues are one thing mass adoption is more important.

**Comment by rnicoll** [comment]
People we're not Elon's boss, this is outside of our control.
