### ISSUE TITLE
[feat] On-Chain Programming Language

### ISSUE THREAD

**Issue by geoffwalmsley** [dogecoin/dogecoin#2064]
# Feature Request

**Describe the Feature Request**
To be a central cryptocurrency Doge needs to be fully programmable. The primary way to encourage meaningful engagement with doge (the memes are valuable but not functional) is to build an active and enthusiastic developer community. This will unlock use-cases of doge in millions of possible applications.

**Describe Preferred Solution**
An On-Chain Programming Language should not permit side-effects and also be able to evaluate sections of its own code. These are the two principles guiding chialisp and are important adaptations for programmable money. 

**Describe Alternatives**
The solidity language is the most popular OCPL, introduced by ethereum. It is terribly insecure and unsafe. Even the ethereum devs couldn't make a secure smart contract without needing to make a hard fork when it went wrong. 

**Related Code**
https://chialisp.com/

**Additional Context**
Lisp is a very hard language to learn. However it is to be expected that the language and syntax of programmable money shouldn't look that familiar to modern developers. Therefore a suite of tools, docs, examples, are needed to enable and support a thriving developer community.

**Comment by m-luck** [comment]
Sure, this is totally possible. I read somewhere else that allowing Turing complete operations may take away from the simplicity and understandability of the asset (e.g. ETH). But I think we may be at a good point where the public would openly volunteer to learn more about it. 

I do think having a potential layer that allows some sort of contract would definitely beef up the robustness. At the same time, I would say focus on adoption -- however, your very post addresses that, and claims it as beneficial to professional developer adoption. 

Therefore, I support your claim. I do think it should come after simpler (yet non-trivial) optimizations, instead of spreading too thin. Twitter: michael_lukiman

**Comment by geoffwalmsley** [comment]
Thanks for the feedback! 

I think the turing completeness is a red-herring. The problem is that by allowing functions with side-effects (i.e. the function can change things outside itself) you introduce a lot of potential for unwanted behaviour in the execution of smart contracts. This has been the problem with solidity. It's not so much that allowing loops introduces unwanted complexity, it's that allowing loops to do whatever they want introduces dangerous complexity. So having restrictions like no side-effects gives you the innovation and extension benefits of an OCPL without risking chain integrity. 

In terms of developing an OCPL for doge, it could take place in parallel with the much needed optimizations. It would also be an incredibly cool project to be part of :)

**Comment by m-luck** [comment]
Also, very interesting point regarding the red herring. I suppose creating a simpler non-looping OCPL reduces the scope a little

**Comment by geoffwalmsley** [comment]
> As Ross tags, this would be a major rework. Geoff would you want to take point on such an endeavor? You may find yourself leading a team of very passionate dilletantes. Like you said, could be very exciting.

I would freaking love it :)

**Comment by AadiPapp** [comment]
Would Rust with its Ownership model be helpful here? Or do we need to write a new OCPL?

**Comment by geoffwalmsley** [comment]
Rust is a very interesting possibility, and I think using monads could be helpful here.... I will read up on it a bit.

**Comment by AadiPapp** [comment]
> Rust is a very interesting possibility, and I think using monads could be helpful here.... I will read up on it a bit.

Thanks Goeff, this is first time I am trying open source development and would love to be part of Doge team

**Comment by rnicoll** [comment]
I think it's fairly well known I favour making Dogecoin-equivalent tokens on smart contract chains, rather than trying to reinvent the wheel as it were.

That said, throwing some advice in as someone who's worked with a few smart contract platforms; if you use an existing language (such as Rust), remember that any on-chain calculation must be deterministic (it cannot use inputs which are not on chain, for example current time, because the calculation must always be exactly the same when validated later). That can be confusing for developers, as it affects quite large parts of the existing language infrastructure. One of the advantages of specialised smart contract languages is that the engineers don't come in with pre-existing expectations, so elements which have to be disabled for a blockchain aren't "missing" from their perspective.

**Comment by geoffwalmsley** [comment]
@rnicoll I totally agree - you have to build the language for the blockchain. 

So, in general it seems like the main options being considered are to either make doge tokens on another chain, or to change the consensus algo to proof of stake (RIP). Solving the environmental problem is easily doable by issuing doge as tokens on the chia blockchain, and brings all the environmental and functional benefits of Chia. 

But I think there is a lot to be said for pushing hard innovation in doge, especially in protecting the integrity of the consensus model. The fact is that PoW is a good consensus model, but it is environmentally expensive. Instead of killing the protocol it just needs to have a point of integration between miners and their energy sources. In much the same way as Chia uses a verifiably delay function, Doge could implement a method to verify miners' energy sources - Proof of Source. 

So hypothetically it work like:
- a miner submits a proof, and a 'token' containing their claim of energy source
- the 'token' is some kind of NFT registered by a power provider, which they verify when it is submitted with a proof
- the coin reward is paid out to a smart contract which splits the value according to the verifier token. So a low-renewable token pays out less than 100% of the reward
- Unpaid rewards are pooled into a DAO which provides services to the community (environmental audits, nascar sponsorships etc)

By making it unprofitable to mine from unverified energy sources, it breaks the energy centralisation issue, improves the environmental footprint, and welds crypto into the framework of energy grids for future development. And a side bonus, it will create a pool of funds that can be used to support community projects.

I don't know whether this seems a bit...mad? I just don't want crypto (and especially doge) to develop into an abstract asset class to be manipulated...So to me it's worth trying to tackle the hard problems of integrating crypto with physical reality, and mining seems a good place to focus the effort. Sorry for the rant, and keep up the good fight :)

**Comment by patricklodder** [comment]
Closing this per #2110 item 4.

**Comment by geoffwalmsley** [comment]
> As Ross tags, this would be a major rework. Geoff would you want to take point on such an endeavor? You may find yourself leading a team of very passionate dilletantes. Like you said, could be very exciting.

@m-luck Would you be interested working on something? Looking at your profile I think we could potentially make a good team...

**Comment by m-luck** [comment]
> > As Ross tags, this would be a major rework. Geoff would you want to take point on such an endeavor? You may find yourself leading a team of very passionate dilletantes. Like you said, could be very exciting.
> 
> @m-luck Would you be interested working on something? Looking at your profile I think we could potentially make a good team... 


Totally possible! My plan is to set up the environment by this weekend, see what problems and potential improvements are in motion (after grokking through the codebase), and apply myself in the capacity that best fits my schedule (day job SWE, 3d printing, some side businesses, food, and still want to enjoy some time outside as summer rolls around haha). 

Would put in more hours if each dev can clock in hours voluntarily via a charitable entity i.e. if we start being bankrolled benevolently ;) -- which core devs have already declined (in public)

In short, I don't want to over-commit given other uses of my time! For example, right now I'm chugging away at my current job's tasks, and it's 10pm at night haha (more productive at night). However, in a vacuum yes, I would love to research and tackle this intellectual and perhaps utilitarian project with you. 

If there is any full time person you can find, that'd be great, as I will probably be in and out days at a time. I would wait one or two weeks for the influx of well-meaning but lacking in technical knowhow participants to level out. 

Action items: 

- I need to read up more on the Chia white paper
- We should create some milestones that would realistically implement this project, and time estimates
- We should see if other repos have licenses that we can base this off of
- I need to see how the current repo is structured, so we know where this plugs into the file hierarchy 
- We should generate all this in a technical design document that sets a good process for documentation and onboarding 
- Last reiteration, I'm a busy bee! But I support making this happen
