### ISSUE TITLE
[IDEA] move to proof of stake this year - move will be very possible with existing stakers on other chains

### ISSUE THREAD

**Issue by simonmadsen** [dogecoin/dogecoin#2066]
DOGE needs to go green and this will make it more decentralized as well.
Proof of Stake (PoS) will achieve this.

I stake ethereum, but will gladly stake DOGE also and this is possible on the same machine without even using all it's resources (intel Nuc 10 from 2019)

There will be a lot of support from DOGE lovers to help stake and secure the network.
I am thinking that around 10000 DOGE should be needed to stake, but that number might need to be higher.
It is actually one of the big benefits of PoS, i.e. that you can support multiple chains on a relatively simple machine and network connection (say intel nuc 10 on a 25/25 Mbit connection)

Several other PoS chains share their knowledge and coding on github.
The PoW improvements Hoskinson suggested are just bait as I see it.
I recommend not doing much more PoW (proof of work) improvements. Focus on migrating to PoS as soon as possible.

**Comment by wallacewd** [comment]
> DOGE needs to go green and this will make it more decentralized as well.
> Proof of Stake (PoS) will achieve this.
> 
> I stake ethereum, but will gladly stake DOGE also and this is possible on the same machine without even using all it's resources (intel Nuc 10 from 2019)
> 
> There will be a lot of support from DOGE lovers to help stake and secure the network.
> I am thinking that around 10000 DOGE should be needed to stake, but that number might need to be higher.
> 
> Several other PoS chains share their knowledge and coding on github.
> The PoW improvements Hoskinson suggested are just bait as I see it.
> I recommend not doing much more PoW (proof of work) improvements. Focus on migrating to PoS as soon as possible.

I don't think you understand what kind of overhaul that would take.

**Comment by simonmadsen** [comment]
> > DOGE needs to go green and this will make it more decentralized as well.
> > Proof of Stake (PoS) will achieve this.
> > I stake ethereum, but will gladly stake DOGE also and this is possible on the same machine without even using all it's resources (intel Nuc 10 from 2019)
> > There will be a lot of support from DOGE lovers to help stake and secure the network.
> > I am thinking that around 10000 DOGE should be needed to stake, but that number might need to be higher.
> > Several other PoS chains share their knowledge and coding on github.
> > The PoW improvements Hoskinson suggested are just bait as I see it.
> > I recommend not doing much more PoW (proof of work) improvements. Focus on migrating to PoS as soon as possible.
> 
> I don't think you understand what kind of overhaul that would take.

probably not, but what im thinking is:
1 you have a lot of support for doge and many will jump right in on staking, hundreds of thousands in months
2 copy other open source projects, which many of them won't oppose

can you elaborate?

**Comment by freethe3rdworld** [comment]
Does PoS make Dogecoin a more centralised project? As in barrier to entry for mining and rewards.

How do we keep this project 3rd world friendly. Mining on a laptop chould change someones life in Somalia, Afghanistan, Sierra Leone, etc.

**Comment by simonmadsen** [comment]
> o entry for mining and rewards.
> 
> How do we keep this project 3rd world friendly. Mining on a lapto

true, later there will be stateless proofing, just like eth 2.0
in fact i suggest doge follows the footsteps of eth and perhaps even jump before them to release PoS this year
well i think eth foundation will also launch PoS this year due to provocation from elon now towards buterin ; )

**Comment by JushBJJ** [comment]
> Does PoS make Dogecoin a more centralised project? As in barrier to entry for mining and rewards.
> 

Cardano is almost 100% decentralized if it hasn't already.


> How do we keep this project 3rd world friendly. Mining on a laptop chould change someones life in Somalia, Afghanistan, Sierra Leone, etc.

Proof of Stake in this case, or better yet Proof of Interaction.

**Comment by freethe3rdworld** [comment]
> > Does PoS make Dogecoin a more centralised project? As in barrier to entry for mining and rewards.
> 
> Cardano is almost 100% decentralized if it hasn't already.
> 
> > How do we keep this project 3rd world friendly. Mining on a laptop chould change someones life in Somalia, Afghanistan, Sierra Leone, etc.
> 
> Proof of Stake in this case, or better yet Proof of Interaction.

What are the main trade offs?

I like the idea of reduced threat of 51% attack, but think with a huge grassroots community and good culture it shouldn't be an issue.

Will this require pool mining to be viable? How do poor people participate with fairness?

And will need a bag of coins already to be able to stake? My understanding is that if you start with moe you'll end up with much more.

**Comment by JushBJJ** [comment]
> > > Does PoS make Dogecoin a more centralised project? As in barrier to entry for mining and rewards.
> > 
> > 
> > Cardano is almost 100% decentralized if it hasn't already.
> > > How do we keep this project 3rd world friendly. Mining on a laptop chould change someones life in Somalia, Afghanistan, Sierra Leone, etc.
> > 
> > 
> > Proof of Stake in this case, or better yet Proof of Interaction.
> 
> What are the main trade offs?
> 
> I like the idea of reduced threat of 51% attack, but think with a huge grassroots community and good culture it shouldn't be an issue.
> 
> Will this require pool mining to be viable? How do poor people participate with fairness?
> 
> And will need a bag of coins already to be able to stake? My understanding is that if you start with more you'll end up with much more.

Thats the problem with PoS, it rewards the rich more. A person that stakes say 10 Ada won't get a bigger return than a person who staked 100000 Ada in both short and long term.

**Comment by simonmadsen** [comment]
> > > > Does PoS make Dogecoin a more centralised project? As in barrier to entry for mining and rewards.
> > > 
> > > 
> > > Cardano is almost 100% decentralized if it hasn't already.
> > > > How do we keep this project 3rd world friendly. Mining on a laptop chould change someones life in Somalia, Afghanistan, Sierra Leone, etc.
> > > 
> > > 
> > > Proof of Stake in this case, or better yet Proof of Interaction.
> > 
> > 
> > What are the main trade offs?
> > I like the idea of reduced threat of 51% attack, but think with a huge grassroots community and good culture it shouldn't be an issue.
> > Will this require pool mining to be viable? How do poor people participate with fairness?
> > And will need a bag of coins already to be able to stake? My understanding is that if you start with more you'll end up with much more.
> 
> Thats the problem with PoS, it rewards the rich more. A person that stakes say 10 Ada won't get a bigger return than a person who staked 100000 Ada in both short and long term.

true, but it must be nice for a foundation or a network to know that there are some stakers.

PoS is already a big / huge leap, and as I understand those who do PoS are already looking into PoI.
It is just the next step, but it might not exclude PoS (immediately) you might still need PoS.
PoI / stateless is going to be cool. All devices participating. I expect iphones will before we would think it. 
Within 2025 maybe before

**Comment by wallacewd** [comment]
> > > DOGE needs to go green and this will make it more decentralized as well.
> > > Proof of Stake (PoS) will achieve this.
> > > I stake ethereum, but will gladly stake DOGE also and this is possible on the same machine without even using all it's resources (intel Nuc 10 from 2019)
> > > There will be a lot of support from DOGE lovers to help stake and secure the network.
> > > I am thinking that around 10000 DOGE should be needed to stake, but that number might need to be higher.
> > > Several other PoS chains share their knowledge and coding on github.
> > > The PoW improvements Hoskinson suggested are just bait as I see it.
> > > I recommend not doing much more PoW (proof of work) improvements. Focus on migrating to PoS as soon as possible.
> > 
> > 
> > I don't think you understand what kind of overhaul that would take.
> 
> probably not, but what im thinking is:
> 1 you have a lot of support for doge and many will jump right in on staking, hundreds of thousands in months
> 2 copy other open source projects, which many of them won't oppose
> 
> can you elaborate?

If that is what you want to do, go make a fork of any other coin as that would be easier. Look how long it has taken ETH to make the switch from proof of work to proof of stake. This is not simply a "change the variable from PoW to PoS" solution. If you want staking, go make a ERC20 or BEP20 token and create liquidity pools for them. People have already created wrapped doge that you can stake on binance smart chain. Doge itself is a network without any major developer support. Look at this github repo. There have hardly been any updates/dev support for the past 4 years.. the only people commenting were sent here from a Elon tweet. 

This repo has turned into a twitter comment thread full of people who don't understand the tech... No one could develop like this.

**Comment by simonmadsen** [comment]
are you joking?

because it is definitely not true that there has only been activity here since elons tweet

sorry but that sounds like you have an agenda

________________________________

**Comment by patricklodder** [comment]
Closing this per #2110 point 4
