### ISSUE TITLE
[bug] Remove Elon Musk

### ISSUE THREAD

**Issue by SoloJr** [dogecoin/dogecoin#2067]
# Bug Report

**Pump and dump:**
Musk writes a twitter and manipulates the market.

**Current behavior**
Musk uses his network to make himself richer based on people.

**Expected behavior**
Musk should NOT be able to create such a big fuss on the market. 

**Steps to reproduce:**
Write a tweet and see madness.

**Comment by CryptoCooked** [comment]
He's not trying to make himself richer dude. He's trying to make the world a better place. Currency adoption is an extremely complex issue, like changing automobiles from combustion to electric, like starting a civilisation on Mars.

**Comment by djdennis91** [comment]
Stop looking at what 'looks' obvious for you on the surface and start thinking about the big things that are happening and the reason why this is happening. If you don't want to look that far, this is not a problem but then stop interfering

**Comment by Testfortest4** [comment]
Mr Elon is trying to help...

**Comment by GregLukosek** [comment]
Why is this even here, anyone managing the bug reports? Please clean this up

**Comment by freethe3rdworld** [comment]
He can't change his level of fame or influence. (Which he's earned)

His intentions seem noble and honest, yours seem to have an agenda.

There are many people working on this project who have conflicts and personal interests.

**Comment by rnicoll** [comment]
Points for "Write a tweet and see madness."

We're not his boss, though, this is something which occurs because of the public perception of him.

Closing as well out of our ability to affect as open source contributors.
