### ISSUE TITLE
[feat] Virtual bank

### ISSUE THREAD

**Issue by diamondskiller** [dogecoin/dogecoin#2068]
YOOOOOOOO DOGE PEOPLE
I think we can agree that dogecoin should be the first crypto coin with a virtual bank!
I mean, think about the future of not needing to use an exchange when you want to travel. For example, if I live in the US, I need to change my USD into Pounds if I am going to the UK. They will take a conversion fee, and even if it's a small amount, that's still money lost.
Imagine a world where you travel everywhere, and you have one bank card, which is the dogecoin card and buys everything on it. If Elon succeeds in going to mars, what are the chance we will use actual currency its 0. We will most likely use cryptocurrency to don't waste paper. We know that Elon likes dogecoin, so #dogetomars, not the moon.
People put in their details where they live, and the cards get shipped within 7 business days, or even better, just send them a virtual card.
I feel like this idea will 100% get doge to over 1$. Please do this.
If anyone wants to improve the idea, even more, do it lets work as a team and improve the coin; we love #doge4life
Also, sorry for my English its, not my first language

**Comment by JushBJJ** [comment]
That makes dogecoin more centralized.

**Comment by rnicoll** [comment]
We're not in a position (we are not an organisation, to start with) to run a financial services company, but several companies (I note Coinbase, PayPal and Revolut) all have cryptocurrency offerings and Coinbase is expected to adopt Dogecoin ( https://www.forbes.com/sites/billybambrough/2021/05/15/coinbase-reveals-dogecoin-bombshell-as-bitcoin-and-crypto-price-fears-grip-the-market/?sh=25befad254fe ). I think makes more sense to have an established company do this.
