### ISSUE TITLE
Mine doge using tesla

### ISSUE THREAD

**Issue by raghu999** [dogecoin/dogecoin#2069]
# Idea

**Describe the Feature Request**

This is an idea for Elon and tesla to use the gpu’s and connected network in tesla cars to mine doge. Since tesla cars are ecofriendly mining using tesla cars will also become ecofriendly.

This is a self sustaining idea where the customer only needs to put downpayment and rest of the payments can be paid by mining using tesla. So the longer a customer drive the more the profits.

This also opens up tesla to become an exchange and charge transaction fees when user convert thier doge to fiat or other cryptos.

**Additional Context**

https://twitter.com/elonmusk/status/1396916392629137409?s=20

Submitting an idea which I see is possible and align with Tesla and Elon’s ideologies

**Comment by segfaultdoc** [comment]
Hey this is a really cool idea

**Comment by xilopaint** [comment]
haha this is cool. Waiting for Mr. Elon tweet this thing. 🚀

**Comment by danielkp1234** [comment]
This is a fun idea. But I don't really think that a tesla would be very profitable for mining. And this really depends on tesla to implement it

**Comment by mmod-max** [comment]
Yes, winter mode, use ASICs instead of heating elements, and mine!

**Comment by patricklodder** [comment]
Please file this issue on the Tesla GitHub :-)

**Comment by raghu999** [comment]
@patricklodder Posted here since Elon asked to share ideas in doge github. The dev’s should really confront Elon as he is creating an impression that somehow he owns and controls doge ☮️
