### ISSUE TITLE
Doge Auction[feat] 

### ISSUE THREAD

**Issue by Darkstarcracker** [dogecoin/dogecoin#2070]
have a built-in verification for Auctions/Bids ex.
* Do the bidder have enough doge to make the bid.

* Both wallet should know that The bidder and auctioneer have enough money to do the transaction without the wallet owners knowing (for Privacy Reasons).

* Do Unsuccessful Bid have lower to no transaction fee.

I think this is a neat idea and should be implemented cause auctions like in ebay is a way to use a currency.

**Comment by patricklodder** [comment]
You can build this on top of Dogecoin today. Please let us know how your implementation progresses on https://www.reddit.com/r/dogecoindev/
