### ISSUE TITLE
[feat] Switch codebase from core to libbitcoin

### ISSUE THREAD

**Issue by narodnik** [dogecoin/dogecoin#2073]
We've been working since 2011 on a rewrite of the Bitcoin implementation. It actually has the fastest blockchain speed since it uses memory mapped databases specifically custom designed for blockchain (dropping durability and optimized for append ops). There is an Electrum backend and they're in the process of migrating to the new infra.

The codebase is actually much better written and understandable than core so it's easier to build applications on top of and extend the code.

https://github.com/libbitcoin/

By adopting this codebase, you automatically gain a team of committed & experienced long term Bitcoin developers.

Our project is also working on a new anonymization system using ZK, which we already have anonymous payments working:

https://github.com/darkrenaissance/darkfi/blob/master/src/bin/tx.rs

If desired this is something we can work to integrate directly into doge.

**Comment by patricklodder** [comment]
Hi, thank you. We'll have a look at some point. Let's talk on reddit: https://github.com/dogecoin/dogecoin/issues/1999
