### ISSUE TITLE
DogePay App for Android/iOS with free internal wallet transfers

### ISSUE THREAD

**Issue by mihirgates** [dogecoin/dogecoin#2076]
To increase the use of Dogecoin for everyday transactions, an Android/iOS app is essential which can provide free internal wallet transfers just like Binance provides free internal wallet transfers for every crypto.

**Comment by freethe3rdworld** [comment]
Check out this cool thread https://github.com/dogecoin/dogecoin/issues/2011

**Comment by CoolxIdea** [comment]
Like this Idea! Would be very convenient and it prevent people from downloading apps that’s trying to steal people’s passphrase

**Comment by alamshafil** [comment]
I believe there already is a Dogecoin android wallet: [https://play.google.com/store/apps/details?id=de.langerhans.wallet](https://play.google.com/store/apps/details?id=de.langerhans.wallet)
