### ISSUE TITLE
Website for doge for future use.

### ISSUE THREAD

**Issue by hiphopsid** [dogecoin/dogecoin#2078]
We could make a website with best UI?UX designers so that it could be easily accessible by others. And, also it would be very beneficial for the growth of DOGE in future. Help, to understand about the holdings, sells, buys and etc in the near future

**Comment by hiphopsid** [comment]
Could also build a payment gateway for tesla and for coming projects.

**Comment by freethe3rdworld** [comment]
Could we just develop dogecoin.com further?

What are some ideas you would like implimented?

**Comment by little-buddy** [comment]
I want to join，it's so cool~🙋

**Comment by hiphopsid** [comment]
@freethe3rdworld you have done amazing work buddy. Let's try to make it more user friendly and easily accessible by others. And can also link the exchanges on the same.

**Comment by freethe3rdworld** [comment]
> @freethe3rdworld you have done amazing work buddy. Let's try to make it more user friendly and easily accessible by others. And can also link the exchanges on the same.

This is not my project, it's the official Dogecoin website. 

So I suggest coming up with a list of features and products and ways to achive it.
