### ISSUE TITLE
Cheap Energy Source

### ISSUE THREAD

**Issue by baba-rj** [dogecoin/dogecoin#2079]
**Cant we use data centers unsused computational powers if we use multiple data centers we can also make a pool from it, as every data center has surplus computational power ?**
<!-- A clear and concise description of what the feature request is. Please include if your feature request is related to a problem. -
**Describe

**Comment by RichDevX** [comment]
Not only that, the servers waste energy when they are idle doing nothing. giving them alternative tasks wouldn't be a bad idea if they don't plan to place the servers in a low power state. It's not something that can be implemented in dogecoin core, but as a society it might be worth doing assuming the workload isn't above the idle power usage, or if the heat can be used.

**Comment by rnicoll** [comment]
Decentralisation means miners are independent of the core maintainers, rather than something we (as open source software maintainers) control, as much as yes it would be great if they used more renewables.

The better news is others are trying to encourage more responsible practices httpswww.theverge.com202152422451900elon-musk-bitcoin-miners-council-sustainability

**Comment by baba-rj** [comment]
Yes thats for sure that they have surplus energy even if servers are on
idle and they are using less energy but still that less energy is in large
amount if considered cumulatively and for now i think we can use that as
they havw perfect infrastructure which they put for maintaining the temp
and everything which is also surplus. I am not saying that we can go
through 1 or 2 data centers but if we try to make a big pool from it then
even if they (data centers) provide us low computing power even then we can
have huge power with lesser fossil waste.

I dont think we have to setup any special data center for this as that will
not be enough for us, not now and not even in future.
And this is not like we are using that service for longer run bu we can use
that for immediate effect and besides we can go for another alternative
options.
