### ISSUE TITLE
FareShare Mining Idea - replying to Musk

### ISSUE THREAD

**Issue by climpinho** [dogecoin/dogecoin#2080]
# Feature Request

**Describe the Feature Request**

New miners should have priority in receiving blocks rewards independently of the hardware the wallet core is installed at.

**Describe Preferred Solution**

Create a queue in the blockchain based on some variables ( maybe more): 
- hardware - some hash of the characteristics 
- coins in wallet - could give priority in the queue to promote holding coins

This will end with large mining rigs and dis-centralize mining from large rig's. 
To prevent a rush of new wallets the block-reward should be limited to a max of 10 block for a new wallet mining for the first time. The value could be calculated base on the count of new miners and length of the queue.

 
**Describe Alternatives**

none
**Related Code**

none
**Additional Context**

Some feature to help all type of hardware to be participate in the network.
Button to mine in the wallet; 
Possibility do choose percentage of CPU usage for the network to use in mine;
Possibility to choose bandwith usage , upload speed control;

**Comment by m-luck** [comment]
This is sound, except how do we hash the hardware? If it's ingestible machine code is Turing complete with a non-transparent ID from the manafacturer (and even then makeshift ones can exist), it's difficult to apply a one-to-one atomization of hardware.

**Comment by climpinho** [comment]
Could be something similar to to building a block. gather some information ( cpu serial, memory, a result of lsof) and hash it.

**Comment by climpinho** [comment]
Sorry can help more...

**Comment by patricklodder** [comment]
I think you need to study this a bit in terms of sybil attacks. Please let us know when your white paper is ready on reddit: https://www.reddit.com/r/dogecoindev/
