### ISSUE TITLE
A device which mines using solar power 

### ISSUE THREAD

**Issue by AadityaMunjal** [dogecoin/dogecoin#2081]
# Feature Request

**Describe the Feature Request**

A one-piece device that sits under the sun (maybe in your yard, or on your roof) and mines dogecoin. This will encourage dogecoin and renewable energy.

**Comment by danielkp1234** [comment]
What does this have to do with dogecoin as a project. This is just a change in the way you mine doge.

You could power your pc off solar energy and mine dogecoin with that.

**Comment by m-luck** [comment]
I encourage someone (maybe you, the original poster) to start a side business to make little mining rigs for perhaps quasi-confused parents to buy for their children under the proposition of teaching them for the future (which is genuine). 

That would be lucrative, and would achieve what you've outlined, even if not directly applicable to the codebase.

Heck, maybe I'll do that. I would be happy if someone reads this and I see news of it happening. 

External tag warranted

**Comment by AadityaMunjal** [comment]
@m-luck Thanks I got your point.

**Comment by m-luck** [comment]
Genuinely encouraging this! I see you're a programmer that is at least capable of some adequately hard things (Arch). ;)

Thanks for posting!

**Comment by delbonis** [comment]
>A one-piece device that sits under the sun (maybe in your yard, or on your roof) and mines dogecoin. This will encourage dogecoin and renewable energy.

Just get a solar panel and an scrypt miner and plug it into the solar panel.
