### ISSUE TITLE
[feat] USE TESLA CARS FOR MINING. 

### ISSUE THREAD

**Issue by ccj13** [dogecoin/dogecoin#2082]
MINE DOGE WHILE RUNNING TESLA CARS OR WHEN THE CARS ARE SITTING IDLE!

**Comment by m-luck** [comment]
Possible since they already use some form of proprietary ASIC I believe. 

There is probably also something with the Dojo that can happen. 

But, the community has to be prepared when that is ready, by truly making this codebase the best product up to par.

**Comment by AbcSxyZ** [comment]
Doge devs won't have the possibility to achieve that, it's hope to Tesla :)

You will have more luck to achieve this by contacting Elon Musk :smiley: !

**Comment by SirHodlington** [comment]
POT - Proof Of Tesla

**Comment by patricklodder** [comment]
Sounds like you can implement this today! Let us know how you progress on reddit: https://www.reddit.com/r/dogecoindev/
