### ISSUE TITLE
[feat] Build an NFT based Mars Game which uses Dogecoin as universal currrency.

### ISSUE THREAD

**Issue by OpenlakeNFT** [dogecoin/dogecoin#2086]
Doge Planet on Mars is committed to build an NFT based Mars Game which uses Dogecoin as universal currrency, and hopefully this can be listed as an official project in the community.

**Comment by illustriousdoge** [comment]
my comment is similar to this instead of just limiting it to that one game they need a whole entire NFT and/or Full gaming platform to have a wide arrange of stuff.

**Comment by patricklodder** [comment]
Hi! I'd suggest looking at doing this on a side chain so that billionaires don't have to make everyone scared about capacity. Please tell us how you progress in your development on reddit: https://www.reddit.com/r/dogecoindev/
