### ISSUE TITLE
[feat] Make doge accept everywhere like google pay or make doge payment gateway

### ISSUE THREAD

**Issue by harshkush9644** [dogecoin/dogecoin#2089]
# Feature Request

**Describe the Feature Request**

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by rnicoll** [comment]
We're pushing ahead with stability of the codebase to help adoption by payment processors, but ultimately the decision to adopt Dogecoin is theirs, we're just trying to encourage them.
