### ISSUE TITLE
Devs I know you want to make it better.  Consider migrating to Iota  [feat] 

### ISSUE THREAD

**Issue by Roy-export** [dogecoin/dogecoin#2090]
![whyiota](https://user-images.githubusercontent.com/77155712/119480710-8636c080-bd84-11eb-9290-a65ec64c483e.jpg)

# Feature Request

**Describe the Feature Request**
Make doge 2.0 fast, scalable and feeless just build a bridge to Iota .. Iota is ready to work with you.  Please refer to my master plan for Doge 2.0

**Describe Preferred Solution**
Use iota as the underlying layer - you can use smart contracts or you can decide to tokenize.  Security is the same.

**Describe Alternatives**
You can try to fix block chains.. but I think Ethereum and BTC been at it for many many years already.

be good!  Luv ya!

**Comment by NARCO78** [comment]
Why would the Doge devs want to create a token of Dogecoin (a decentralised POW coin) on a centralised network? Makes no sense.

**Comment by Roy-export** [comment]
The brief was to be faster, cheaper and scalable - Iota fits this brief.  Why discount it?  

Doge 2.0 can run on Iota 2.0 which has no coordinator.  Iota 2.0 will be released late 2021 or early 2022.  The Iota 2.0 will have tokenisation, Smart contracts (parallel processing) and node incentives amongst other upgrades.

Development can start now on the soon to be released nectar incentivised testnet (NO COORDINATOR) with smart contracts and tokenisation, so many options - the world is your oyster.  

In terms of a POW why would you want to run POW - It can't give you any of the desired outcomes.  It can't reduce cost 100x it can't speed up 100x it can't increase blocks by 10x.  So if you had a problem and you can solve it and someone has a PEER researched solution perhaps it's worth investigating.

**Comment by NARCO78** [comment]
There's already discussion of Dogecoin forking Nano software and becoming it's own Sovereign network. Why would the devs want to create a token that sits on a 3rd party centralised network that hasn't even been battle tested?

**Comment by patricklodder** [comment]
Hi! Closing this per #2110 point 4.
