### ISSUE TITLE
DAAS: DOGE as a Service

### ISSUE THREAD

**Issue by davidleathers113** [dogecoin/dogecoin#2091]
So many businesses have rewards systems that give you various bonuses for buying their products. In a way, these become their own currency. My college had their own Davis Bucks that you could use around town. This could be an opportunity for DOGE. Every business that has a points system could join the DOGE network, buy up a certain amount of DOGE, and reward it to their customers based on a system that is profitable for the company. More companies buying up DOGE would increase its stability. Here's a list of companies that already use a points system...
- Almost every coffee place
- Most grocery stores
- Colleges for their cafeterias and book stores
- Pizza shops
There's more that I can't think of off the top of my head. 
The opportunity here is for developers to create a template for these businesses to use. Most of them don't come up with their own points system. Some other company made it for them. These businesses would be more apt to adopt DOGE if we fixed these problems...
- Implementation into their business model
- POS Integration
- Exposure to price fluctuation 
The last one is probably the biggest thing that needs to be fixed. There has to be a way to offset this exposure by paying an insurance company. Or maybe we could have a decentralized insurance where the DOGE community can assume this risk temporarily? Someone much smarter than me could come up with a solution here. Let me know what y'all think.

**Comment by freethe3rdworld** [comment]
This is a really cool and inovative idea! Mainstream implimentation has to start somewhere, this could be a great way to cick it off.

You just sparked my memory of an article I read: [Does Starbucks Want to Be Your Bank?](https://www.fool.com/investing/2020/02/04/does-starbucks-want-to-be-your-bank.aspx) Where they had over $1.5 billion in stored value as of a couple yers ago. So this is a huge market to tap into.
