### ISSUE TITLE
Dogecoin for the needy. Doge saves lives.

### ISSUE THREAD

**Issue by nikozor** [dogecoin/dogecoin#2093]
Ideas:

Feature for donating with 1% fee Dogecoin for organizations such as:

- Kids
- Animals
- etc

- Doge exchange for poor countries, where they can change donations to their currency, without any or less fee.

- Special wallet for organizations, easy to use, diagram of revenue that owners can easily share for the public.

- Integrated simple accounting in a special wallet, so that the organizations do not have any difficulties and have a good overview.

- Total donation counter so that everyone knows how much Dogecoin is doing

- "DSL" ( Doge Saves Lifes ) Website for spend Doge for organisations. Optional with PC Power, with 1 % Fee for the Developers.

- Everything should be public so that everyone can control. 

- Simple website where you can quickly find the right organization. Maybe a direct link to Dogewallet

- Maybe find a partner exchange who are willing to work with less fee.

**Comment by patricklodder** [comment]
You can contact miners and ask them to donate their Dogecoin without any protocol changes!
