### ISSUE TITLE
[Discussion] End Goal of Dogecoin

### ISSUE THREAD

**Issue by CuttyFlam-Franky** [dogecoin/dogecoin#2095]
It seems the end goal for Dogecoin is for everyone to be a miner + Dogecoiner.
1. High decentralization
2. Having coin utility
3. High security; improbable to have 51% attack

Yet, the **compute complexity rescaling** of Proof of Work does not seem to incentivize this goal.
The more people join the mining pool, the less reward per miner & higher power consumption per block
It means: The more people join mining, the more inefficient decentralized mining becomes.

Proposed alternative:
**Use non-intrusive identity verification.**

Periodic verification of identity of miner based on: 
1. Data labelling to help the science and engineering community (captcha) or 
2. Monthly Dogecoin spending  
(Selected based on miner's privacy preference)

The verification produce a scaling factor for the block reward for each miner.

How does this drive Dogecoin towards the end goal:
1. Develop Dogecoin utility / adoption in science and engineering community.
2. Promote spending of Dogecoin; centralized hoarding address will receive less block reward.
3. Move away from the complexity rescaling heurstic; block time can scale linearly as more people join

Constructive discussions below

Super Franky

**Comment by CuttyFlam-Franky** [comment]
If there is a Dogecoin spending API (something like OpenBanking API), I can code a lite neural net to produce desired block reward scaling factor

**Comment by patricklodder** [comment]
Hi! Do you have any code towards this?

**Comment by CuttyFlam-Franky** [comment]
> Hi! Do you have any code towards this?

1. Data Labelling tools and library: https://github.com/heartexlabs/awesome-data-labeling
- UI can be copied from Amazon's SageMaker: https://github.com/aws-samples/amazon-sagemaker-ground-truth-task-uis

2. For monthly Dogecoin spending, some codes need to be developed on the wallet app.
 - OpenBanking API can be helpful: https://github.com/adorsys/open-banking-gateway

**Comment by patricklodder** [comment]
All of this can be done without changes to Dogecoin Core? Please develop this, it's awesome! Let us know on reddit how you progress! https://www.reddit.com/r/dogecoindev/

**Comment by CuttyFlam-Franky** [comment]
> All of this can be done without changes to Dogecoin Core? Please develop this, it's awesome! Let us know on reddit how you progress! https://www.reddit.com/r/dogecoindev/

All of these need to be done directly to the Dogecoin Core.
Complexity rescaling needs to be replaced by Data labeling and Dogecoin monthly spending.
This is a direct change to the core of Dogecoin mining algorithm.
