### ISSUE TITLE
DOGE in Gaming/Twitch Community 

### ISSUE THREAD

**Issue by nikozor** [dogecoin/dogecoin#2097]
Looking for partners in the field of gaming, such as:

Blizzard
Riot Games
EPIC Games
ETC...

Using Doge for microtransactions, such as skins.

Trying to contact Twitch. Maybe in the future it will be possible to pay for donations with Doge. Epic Doge memes on Twitch! : D

**Comment by AbcSxyZ** [comment]
A good idea, but it's not related to the development of dogecoin source code :)

You should share this kind of idea on social media like reddit, discord or twitter, it will have more impact !

**Comment by nikozor** [comment]
> A good idea, but it's not related to the development of dogecoin source code :)
> 
> You should share this kind of idea on social media like reddit, discord or twitter, it will have more impact !

Thank u :) I made it

**Comment by patricklodder** [comment]
Hi! You can do this without any change to Dogecoin Core. Please let us know how you progress on Reddit: https://www.reddit.com/r/dogecoindev/
