### ISSUE TITLE
IDEA Multiplanetary

### ISSUE THREAD

**Issue by juanr2001** [dogecoin/dogecoin#2100]
We should make dogecoin multi-planetary. Or design it for the present and for the future.

Imagine if Elon Must sends people to Mars. Now the new martians can make doge transaction from Mars to Earth to buy digital products. Super cool!

**Comment by patricklodder** [comment]
Sounds awesome! Let us know how you progress with your solution on reddit: https://www.reddit.com/r/dogecoindev/

**Comment by michaelni** [comment]
A single classical blockchain would have difficulty when spanning 2 distant places. Consider MrEvil would spend all his wallets contents to download a mars opera while also buying a bottle of milk on earth. He listens to to opera while drinking the milk. There is a delay between distant places so the blockchains would need time to resolve which is "first".  Multiplanetary directly conflicts thus with universally fast transactions.
What you could do is have a blockchain per planet, transfers between these would take additional time before becoming final.

An alternative is something a little more complex than a classical blockchain. I think if each wallet address and node has a location in space known to all you could use the distance to have some variable finality, I think though thats maybe a little complex  at this point ;) It would be some sort of relativity "blockchain". The farther away one is from the wallet location the longer it would take for a transaction to become final.

**Comment by delbonis** [comment]
To safely extend the range of a blockchain usually you need to increase the block time, as all miners (stakers, etc.) need to within a sphere with a radius of the average distance that light travels between each block, and the closer the better to decrease orphans.  This would require a hard fork, and in order to safely reach even Mars the block time would need to be increased to roughly half an hour, 30x what it is currently.

**Comment by michaelni** [comment]
@delbonis , Yes, the "alternative" i suggested is not a blockchain by the classical definition :) it would also probably need a complete  rewrite for a use case not relevant in the near future.
For example a transaction for a distant wallet address would be noted but only become valid after enough blocks passed. I think 2x the light travel time might be the minimum. That way a node "close to a wallet" can quickly reach finality for a transaction while a distant one would need a lot longer. I ve not thought much about this as i dont think anyone will implement this in the near future. The structure this would result in would not be a block chain as distant nodes would generate blocks much faster than they can synchronize.
