### ISSUE TITLE
[feat] Make Dogecoin the currency for use in social media apps

### ISSUE THREAD

**Issue by Dimes84** [dogecoin/dogecoin#2101]
Maybe use Doge as a form of currency inside of social media and gaming apps such as facebook, IG, Bigo, Mico, Clubhouse, ect...  That way users would buy Doge conveniently inside the app to use as currency right then and there to "Gift or Game" with. So instead of purchasing "Diamonds, Coins or Badges" ect with regular money they would buy Doge and use that instead. That would also make it a universal currency that could be used from platform to platform and directly rival traditional "Dollar" purchases.

**Comment by AbcSxyZ** [comment]
It will depend on social media platform, doge devs can't do something about it.
It's the wrong place to ask this kind of things, contact directly the social media or speak about it on reddit, twitter, whatever if you want to bring change :)

Relative to #2097.

**Comment by Antona89** [comment]
BAT literally exists.

**Comment by patricklodder** [comment]
Hi! Sounds interesting. You can do this today without any changes to Dogecoin Core. Please let us know how you progress with this on reddit: https://www.reddit.com/r/dogecoindev/
