### ISSUE TITLE
[feat] 

### ISSUE THREAD

**Issue by Holinhong** [dogecoin/dogecoin#2106]
Hey Elon, 
I have previously dropped some ideas here and there. Since I am typing on hub guess I am more serious than I was. 
I think we are witnessing a new group of fortunes that is currently being conceived by the US stock market. It's just a time manner when we get there. That being said the very first honor after one hits fortune probably would be the taxation. Instead of contribute to IRS it would be more effective if it was utilized in private section. That's why I am thinking about running a charity that accepts dogecoin. Once on truck(stable cash flow), I will further extend the business structure onto investment and finance. In this case, Dogecoin could use the vehicle and smoothly landing into different aspects of finance industry instead of troubling your ceo constantly posting HODL on Reddit/dogecoin. The idea is relatively new and there will be a lot of details to think about. Such as if I shall contact the owner of Reddit and develop them as the partner since I am planning to start with the needs of crew there. But I do see a lot of potentials that will put everyone in a win-win situation (maybe not IRS). So let me know if that's something dogecoin would be interested in participate. 

Thanks.
Regards, 
H.

**Comment by patricklodder** [comment]
Hi! Please discuss this elsewhere!

Closing this, see #2110, point 8.
