### ISSUE TITLE
[feat] PoT (Proof of Thought)

### ISSUE THREAD

**Issue by jonesnoaht** [dogecoin/dogecoin#2107]
Support of "proof of thought."  Find a family of tasks that allow discrimination between human brain activity and adversarial neural networks attempting to simulate human activity. 

Benefits include providing a strong incentive for miners to learn to simulate human thought in silice.

**Comment by wallacewd** [comment]
Much no.

**Comment by patricklodder** [comment]
Hi! Sounds awesome! Please discuss this elsewhere :-)

Closing this, see #2110, point 6.
