### ISSUE TITLE
[feat] Doge as a multi-chain même protocol

### ISSUE THREAD

**Issue by thebalaa** [dogecoin/dogecoin#2109]
The future of blockchain is multi-chain interoperability. 

As Vitalik discusses here:  [Limits of Blockchain Scalability](https://vitalik.ca/general/2021/05/23/scaling.html), in order to remain sufficiently decentralized certain trade-offs must be made. 

There are many blockchain projects working to address the scalability and decentralization issues that plague 1st generation blockchains. Why not re-deploy Doge (via snapshot) across as many chains as possible allowing users to atomically move their Dogecoins to the chain of their choice. 

Taking a snapshot of Doge account balances at a predetermined block then migrating those balances to as many PoS blockchain as possible while allowing for transaction fees to be denominated in this new Doge token on the respective chains is the best technical solution to ensure the long term viability of Dogecoin. 

Users could atomically swap their Dogecoins between any of the backing chains (any chain that with smart contract support and deemed to be sufficiently secure by the Dogecoin community.

**Comment by azhtom** [comment]
It's a great idea! Last night I was researching Polkadot and how it works. This project supports "Bridge" where it can be integrated with another chain. For Doge's case, we could build a parachain and use XCLAIM.

**Comment by patricklodder** [comment]
Do you have any code towards this?

**Comment by thebalaa** [comment]
> Do you have any code towards this?

I have successfully tested atomic swapping of ERC20 token between EVM (solidity compatible) blockchains with this code: [ETH Atomic Swaps](https://github.com/jchittoda/eth-atomic-swap)

Here's what I think are the remaining tasks:

- decide when the snapshots will be taken
- coordinate the deployment of contracts with the participating blockchains
- allow balance holders to decide which participating chain they would like their coins to originate
- cross-chain transfer wallet support

Probably missing a few points here but if this idea can get enough traction I'm willing to contribute the resources needed to make it happen.

**Comment by patricklodder** [comment]
Hi! So why don't we just keep things cross-chain as they are today? You can create a bridge regardless of what we implement in Dogecoin Core. Let us know how you fare on https://www.reddit.com/r/dogecoindev/

**Comment by thebalaa** [comment]
Sorry, I think you're missing the point. 

With this proposal Dogecoin core goes away.
