### ISSUE TITLE
[bug] QR code on Android says invalid Dogecoin URI

### ISSUE THREAD

**Issue by CryptoCooked** [dogecoin/dogecoin#2112]
# Bug Report

**Current behavior:**
When I scan QR code to transfer wallet to wallet on Android to android it gives error attached.

**Expected behavior**
Should have recognised the recipient wallet address after scanning QR code from the senders wallet address

**Steps to reproduce:**
Scan QR on one android device/app to another to transfer coin from one DOGECOIN wallet address to the other on a different phone

**Screenshots**
Attached
![Screenshot_20210525-174025_Dogecoin Wallet](https://user-images.githubusercontent.com/34531579/119528434-75d11680-bd81-11eb-9eab-a2c59d1cc8e2.jpg)

**Dogecoin Core version**

**Machine specs**
Both Samsung android sender and recipient apps downloaded within the last few months

**Extra information**
Strange this hasn't been fixed or detected yet, seems pretty critical issue.

**Comment by incognitojam** [comment]
Sorry but this is the wrong repo to report this issue, unless you believe Dogecoin Core is creating invalid QR codes? It might be better to report it at [langerhans/dogecoin-wallet-new](https://github.com/langerhans/dogecoin-wallet-new) instead.

**Comment by iamthewallrus** [comment]
Ce n'est pas un problème avec Dogecoin, mais plutôt avec l'application de portefeuille

**Comment by rnicoll** [comment]
Yup please raise in the repo incognitojam mentioned above.
