### ISSUE TITLE
Do not follow Bitcoin's development model

### ISSUE THREAD

**Issue by ParashRahman** [dogecoin/dogecoin#2113]
Bitcoin is being for-profit developed to promote transaction verification methods separate from the miners (https://m.youtube.com/watch?v=0BZoKH-hX_o)

The Lightning Network (https://m.youtube.com/watch?v=UYHFrf5ci_g) exists, because BTC sucks, not because it is a good idea. Dont lean on centralization to improve Dogecoin transactions or Doge will end up clunky and require its users to use third parties to avoid volatile and high fees.

Bitcoin cash was made to keep this principle of decentralization. Follow their ideas not Bitcoin, the dinosaur of crypto.

**Comment by patricklodder** [comment]
Thank you for your insights. Noted!
