### ISSUE TITLE
[feat] Suggest to make a mining machine for renewable energy activity used

### ISSUE THREAD

**Issue by LeeWeiZhang** [dogecoin/dogecoin#2114]
# Feature Request

This suggestion is not related to technical side on cryptocurrency, but it would be a great move for making cryptocurrency sustainable.

Renewable energy that depends on wind, water, or solar energy power is highly volatile. During good weathers and usage is low, it will have excessive energy that will be wasted and this is one of the reasons that renewable energy businesses has low profits margin.

If these excessive power can be use on mining cryptocurrency to gain extra profits from mining cryptocurrency, pretty sure there would be more investment on renewable energy businesses.

My suggestion is to create a mining machine for renewable energy companies that only run when there is detection of excessive energy produce.

**Additional Context**
https://www.aljazeera.com/economy/2021/4/22/cathie-woods-ark-says-bitcoin-could-help-fight-climate-change

**Comment by patricklodder** [comment]
Please develop your machine and let us know how you fare on reddit: https://www.reddit.com/r/dogecoindev/
