### ISSUE TITLE
Prevent market manipulation buy whales using tokenomics

### ISSUE THREAD

**Issue by CryptoCooked** [dogecoin/dogecoin#2119]
# Feature Request

Limit wallet size to say 1 420 069 coins to prevent whales from being able to manipulate the price of the coin

**Describe Preferred Solution**
Reduce maximum wallet size to 1 420 069

**Describe Alternatives**
Asking external parties like SEC to prevent market manipulation, which they won't do.

Whales need to buy a lot of coins in order to manipulate the price down by dumping the coins that they bought, if we have a decentralised exchange like metamask where you can swap BTC for DOGE to a maximum wallet size of say 1 420 069 it solves the problem of price volatility to a massive extent. If the volatility is reduced, adoption will follow like a tsunami. Elon will ove this idea because it deals with the price manipulation.

DOGE would absolutely stand out as the peoples coin and solicit mass adoption if the price increase was natural/organic.

Please look at this issue again, getting this sorted is MASSIVE!

**Comment by CryptoCooked** [comment]
It's urgent, this is a great idea, someone might take it and start a new coin, this idea is public now!!!

**Comment by patricklodder** [comment]
> Reduce maximum wallet size to 1 420 069

So one will just spread out 1 420 069 DOGE over 1 420 069 addresses?

> Asking external parties like SEC to prevent market manipulation, which they won't do

You're asking the wrong US regulator. I think the correct US agency to contact is the CFTC.

**Comment by KillerRabbit345** [comment]
Patrick.

On the meta issue of regulation -- wouldn't it be better to build in systems we would like to see into the tokenenomics of the coin itself instead of hoping for / encouraging external regulators to step in?

**Comment by CryptoCooked** [comment]
External regulators are failing us, that's why we have blockchain, if we can figure out how to use tokenmics/programming to limit the manipulation of the price by the whale, s DOGEcoin "wins handsdown" 2x, could even replace the stable coins because then the coin value vs USD becomes more stable on an upward trend as the market cap grows... Market cap grows organically because the manipulation is limited...

**Comment by JushBJJ** [comment]
> External regulators are failing us, that's why we have blockchain, if we can figure out how to use tokenmics/programming to limit the manipulation of the price by the whale, s DOGEcoin "wins handsdown" 2x, could even replace the stable coins because then the coin value vs USD becomes more stable on an upward trend as the market cap grows... Market cap grows organically because the manipulation is limited...

I think it's a bad idea to convert cryptocurrencies back into fiat and so, 1 Doge should equal to 1 Doge. But there are hardly any alternatives to gain dogecoin other than mining and donations.

**Comment by patricklodder** [comment]
I have created this for us to discuss further: https://www.reddit.com/r/dogecoindev/comments/nkv569/continuation_of_2119/

I AM actually sensitive to price manipulation, but we have to assess this from an impact to anonymity / freedom p.o.v. too. Please, let's discuss on reddit!

**Comment by elvisdare07** [comment]
I don't think the idea of limiting whales would be productive. There's a few issues with this:
- Whales can create multiple wallets to overcome the coin limit
- The wallet limit would indirectly affect true investors that are buying and investing

**Possible solution:**
I think if DOGECOIN can have a wallet of burn coins that are locked up with 50% of all minted coins, then that could provide stability. Perhaps another idea would be to somewhat limit transactions, so this limit would be in proportion with their wallet size.

**Comment by CryptoCooked** [comment]
elvisdare07 Please continue discussion on reddit, this is so vitally importnat!
