### ISSUE TITLE
Dogecoin 1.21 QT Wallet UI

### ISSUE THREAD

**Issue by alamshafil** [dogecoin/dogecoin#2123]
# Feature Request

**Describe the Feature Request**
The QT wallet for version 1.21 is missing many elements from the stable release `(1.14.3)`. It still uses the Bitcoin icon and the Comic Sans font is missing.

**Describe Preferred Solution**
I can open a pull request to address this issue for the QT Wallet in 1.21.

**Related Info**
Bitcoin icons is still being used here: [https://github.com/dogecoin/dogecoin/blob/1.21-dev/src/qt/res/icons/bitcoin.png](https://github.com/dogecoin/dogecoin/blob/1.21-dev/src/qt/res/icons/bitcoin.png)

**Comment by patricklodder** [comment]
Hi! The normal process that @rnicoll follows for new major releases is:

1. Protocol implementations
2. Branding
3. Porting Dogecoins-specific UI features

We're currently still at step 1.

**Comment by alamshafil** [comment]
Ok nice to know! Good luck!
