### ISSUE TITLE
[feat] performance improvement by tuning block parameters

### ISSUE THREAD

**Issue by mmahut** [dogecoin/dogecoin#2126]
# Feature Request

Can we try to speed up block time 10X, increase block size 10X & drop fee 100X? This should solve the scaling problem the industry have seen for years. A lot of great minds agree.

**Comment by patricklodder** [comment]
Oh wow. I hadn't thought of that!!!! Thank you so much for your insight 👍

**Comment by ulfox** [comment]
ahhahaha

**Comment by delbonis** [comment]
To elaborate: This only works if block space is contentious.  Dogecoin's default minrelayfee is set at 1 DOGE, which means transactions will only be relayed by other nodes if it pays that minimum fee.  Block space is not contentious so any nonzero fee should be accepted by miners, but there's no way for miners to receive the transaction so it does not propagate through the gossip network.  This is not a consensus rule and is being addressed in the next release.

Doing that *also* increases the amount of effort it requires to run a node by 100x, which would prevent many users from being able to verify the network and shift them to centralized services.  A 6 second block time would also massively increase the orphan rate, decreasing profitability and network security.  No, most experts do not consider that a viable solution.
