### ISSUE TITLE
[feat] My NFT Colletion Buy Dogecoin 

### ISSUE THREAD

**Issue by yurimedeiros** [dogecoin/dogecoin#2129]
Olá time beleza ? tudo bem a todos ?  
Desejo a todos um ótimo ano !

E quero revelar uma coisa muito importante para a comunidade do Dogecoin.

Depois de muitos dias pensando que eu posso agregar aqui com todo carinho e todo cuidado para que essa comunidade possa evoluir cada vez mais eu resolvi revelar aqui a vocês isso.

Devido a muitos  cogitar em que o Dogecoin não é uma criptomoeda sustentável resolve de fato mudar isso!!!!

 Eu quero criar uma plataforma de vendas de nfts com a moeda DOGECOIN para que isso possa desenvolver no mercado e aumentar cada vez os meus mais suas transações mundiais !

Além de mudar e facilitar com que muitos artistas possam Criar e cadastrar os seus projetos e nfts dentro das plataformas para ser vendidas sem cobrar muitas taxas Como é cobrado ultimamente e isso acaba impedindo com que outros artistas acabe se cadastrando e Vendendo as suas artes.

 Por isso mesmo resolver aqui de fato pedir ajuda a todos vocês para gente formar um time agregar valor a cada vez mais esse negócio o nome desse site se chama "My NFS Collection “

Porém ele só está agora não sub-domínio [](http://mynftscolletion.yurimedeiros.net/)
Quero ajuda de todos vocês podiam ter um recurso de lançar o site completo condomínios só e poder configurar todo ele sozinho de um modo seguro onde usuários possam vender e cadastrar tokenizar suas artes dentro do site e também distribuir para outras pessoas comprarem através de Dogecoin.

Assim para ajudar a comunidade agregar mais a moeda no mercado digital não só como é ter um Bitcoin e assim.com também pode comprar nfts 

Meu nome é Yuri Medeiros eu tenho 29 anos moro no Brasil São Paulo e há 10 anos atrás eu fiz um firmamento para mim que eu quero fazer diferença neste mundo,Não quero ir dormir pensando no dinheiro que eu tenho mas quero poder ir de dormir pensando nas mudanças que eu fiz para o mundo melhor assim como eu aprendi com muitas pessoas e também chegou a esses tipos de evolução mental e principalmente Elon Musk que cada vez mais aumenta a nossa e creio que é de todo mundo capacidade de acreditar nos seus sonhos, deixo abaixo o meu e-mail para contato e telefone casos queira tenha interesse em participar desse projeto 

# Feature Request

**Describe the Feature Request**

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by yurimedeiros** [comment]
Hello beauty team? What's up everybody?  
I wish you all a great year!

And I want to reveal something very important to the Dogecoin community.

After many days thinking that I can add here with all affection and all care so that this community can evolve more and more I decided to reveal here to you that.

Due to many cogitating that Dogecoin is not a sustainable cryptocurrency I decided to actually change that!!!!

 I want to create a platform for sales of nfts with the DOGECOIN currency so that it can develop in the market and increase my more and more its worldwide transactions !

In addition to change and facilitate many artists can Create and register their projects and nfts within the platforms to be sold without charging many fees as is charged lately and this ends up preventing other artists end up registering and selling their art.

 That is why I decided to ask for your help to form a team to add value to this business the name of this site is called "My NFS Collection ".

However he is now only without sub-domain http://mynftscolletion.yurimedeiros.net/
I want help from all of you could have a feature to launch the full site condominiums only and be able to configure it all alone in a secure way where users can sell and register tokenize their art within the site and also distribute to other people to buy through Dogecoin.

So to help the community add more currency in the digital market not only as it is to have a Bitcoin and so.com can also buy nfts 

My name is Yuri Medeiros I have 29 years live in Brazil Sao Paulo and 10 years ago I made a firmament for me that I want to make a difference in this world, I do not want to go to sleep thinking about the money I have but I want to be able to go to sleep thinking about the changes I made for the world better as well as I learned from many people and also came to these types of mental evolution and especially Elon Musk that increasingly increases our and I think it is everyone's ability to believe in their dreams, I leave below my email for contact and phone if you want to have interest in participating in this project 


Translated with www.DeepL.com/Translator (free version)

**Comment by patricklodder** [comment]
Hi! This is not the right place for this request, you'll have better luck on reddit: https://www.reddit.com/r/dogecoindev/
