### ISSUE TITLE
The Great RESET - OBJECTIVELY to get it right!

### ISSUE THREAD

**Issue by mobtap** [dogecoin/dogecoin#2133]
1 - The big problem of DOGE today is made by the issue of new currencies, deflationary currencies, so in START the NEWDOGE is done with the problem solved!
2- For exchanges and carriers, DOGE (OLD) exchange pattern for NEWDOGE (without fees) or with automatic due must be added. Not generating losses and making the burning from the new, perhaps defining a portfolio for the burning.
3- Define FINAL, finite amount of NEWDOGE.
4- NEWDOGE will replace. But the name should be the same, making a smart transition!

Matheus Tavares
Systems Analyst
+55 32 98855-6931
mobt.ap@gmail.com

**Comment by patricklodder** [comment]
Thank you. Got code?

**Comment by mobtap** [comment]
Unfortunately not, I have not yet reached this level, this is just an idea, because I believe endlessly in the future of the currency! However, I am interested in translating the entire package to PT-BR | Brazilian Portuguese if it is useful.

**Comment by patricklodder** [comment]
Okay so I'm going to close this one, as that discussion is better had elsewhere.

> However, I am interested in translating the entire package to PT-BR | Brazilian Portuguese if it is useful.

Once we get some more UI work into 1.14.4-dev, I will regenerate the translation files, including for [pt_BR](https://github.com/dogecoin/dogecoin/blob/master/src/qt/locale/bitcoin_pt_BR.ts), but if you already see any bad translations there, feel free to submit now and get some quick wins in. Any changes made now will be carried over into the newly updated set of files.

**Comment by mobtap** [comment]
Thanks! Whatever you need I'm here!
