### ISSUE TITLE
如何解决因为经济危机结束导致加密货币暴跌？

### ISSUE THREAD

**Issue by air0key** [dogecoin/dogecoin#2134]
我们可以看到每次加密货币达到新的高度背后都是全球性的经济危机导致
本次的大幅增长 也是因为 COVID-19 在全球蔓延造成实体经济发展困难所导致
可以预见的未来 当COVID-19结束 加密货币可能会再次崩塌

**Comment by patricklodder** [comment]
我们使用成长期来使全球金融体系更加依赖加密货币并最终取胜。

题外话，我关闭这个:-)
