### ISSUE TITLE
Not necessarily a new feature but anybody know how to post on the reddit when your Karma is too low? 

### ISSUE THREAD

**Issue by illustriousdoge** [dogecoin/dogecoin#2136]
How can we implement new ideas or see who all agrees when our ticket will be closed down here which is OK but if they want the idea to be moved to reddit for a bigger audience it is impossible because of the karma so basically anybody with a good idea and doesn’t have a outstanding account already get their ticket closed and the post is and not seen. Is there any way around it? some type of special way if somebody is bringing over some thing from Github they can post onto the to the doge coin devs/ Main dogecoin page. 

Links are an essential part of displaying evidence, on some accounts I can’t even comment because my karma is too low.

**Comment by patricklodder** [comment]
Finding out how to make this better, please stand by. Also keeping #2128 under consideration for things that could be more on-topic for this repository than the development sub on reddit.

**Comment by fmhc** [comment]
Hello, i had the same issue with my proposal here https://github.com/dogecoin/dogecoin/issues/2120 and now I dont know where to proceed because I have no Karma on Reddit. How can I make my work open to the dogecoin public and find people who are interested in a discussion over that?

**Comment by AAB-Manifesto** [comment]
https://www.reddit.com/r/redditdev/comments/amjj63/how_to_make_a_reddit_bot/
https://www.reddit.com/r/learnmachinelearning/
post some memes to farm some karma :)

**Comment by illustriousdoge** [comment]
![3A160033-E938-417D-8BA2-A8761AD1E33E](https://user-images.githubusercontent.com/84756453/120194147-dd082400-c1e2-11eb-9bfa-a6b3440e47c7.png)

OK everybody needs to spam this

**Comment by ReverseControl** [comment]
@illustriousdoge Your concern has been addressed. You can now start and join discussions: see https://github.com/dogecoin/dogecoin/discussions/2254.
