### ISSUE TITLE
In a Windows environment, running make HOST=x86_64-w64-mingw32 throws various syntax errors

### ISSUE THREAD

**Issue by jimmyt1988** [dogecoin/dogecoin#2138]
# Bug Report

**Current behavior:**

When following the `doc/build.windows.md` on Windows 10, if you run `make HOST=x86_64-w64-mingw32`, the command prompt throws the following error:

```txt
: not foundb: 4:
: not foundb: 6:
: not foundb: 26:
: not foundb: 27:
: not foundb: 34:
: not foundb: 37:
: not foundb: 45:
: not foundb: 52:
: not foundb: 54:
: not foundb: 66:
: not foundb: 74:
: not foundb: 77:
./config.sub: 80: Syntax error: word unexpected (expecting "in")
: not foundb: 4:
: not foundb: 6:
: not foundb: 26:
: not foundb: 27:
: not foundb: 34:
: not foundb: 37:
: not foundb: 45:
: not foundb: 52:
: not foundb: 54:
: not foundb: 66:
: not foundb: 74:
: not foundb: 77:
./config.sub: 80: Syntax error: word unexpected (expecting "in")
/bin/sh: 1: Makefile: not found
/bin/sh: 1: Syntax error: "|" unexpected
/bin/sh: 1: Makefile: not found
/bin/sh: 1: Syntax error: "|" unexpected
/bin/sh: 1: Makefile: not found
/bin/sh: 1: Syntax error: "|" unexpected
/bin/sh: 1: Makefile: not found
/bin/sh: 1: Syntax error: "|" unexpected
/bin/sh: 1: Makefile: not found
/bin/sh: 1: Syntax error: "|" unexpected
/bin/sh: 1: Makefile: not found
/bin/sh: 1: Syntax error: "|" unexpected
/bin/sh: 1: Makefile: not found
/bin/sh: 1: Syntax error: "|" unexpected
/bin/sh: 1: Makefile: not found
/bin/sh: 1: Syntax error: "|" unexpected
/bin/sh: 1: Syntax error: "|" unexpected
/bin/sh: 1: Syntax error: "|" unexpected
/bin/sh: 1: Syntax error: "|" unexpected
/bin/sh: 1: Syntax error: "|" unexpected
/bin/sh: 1: Syntax error: "|" unexpected
/bin/sh: 1: Syntax error: "|" unexpected
/bin/sh: 1: Syntax error: "|" unexpected
/bin/sh: 1: Syntax error: "|" unexpected
make: config.site.in: Command not found
/bin/sh: 1: Syntax error: "|" unexpected
make: config.site.in: Command not found
/bin/sh: 1: Syntax error: "|" unexpected
Makefile:110: builders/.mk: No such file or directory
make: *** No rule to make target 'builders/.mk'.  Stop.
```

**Expected behavior**

When running the make command, the build process should begin.

**Steps to reproduce:**

- Clone dogecoin repository
- `git checkout 1.21-dev`
- Navigate to the `doc/build-windows.md` and follow the build instructions at [commit 21a65756f558a2bd50e71c6dfb04143533e59f76](https://github.com/dogecoin/dogecoin/commit/21a65756f558a2bd50e71c6dfb04143533e59f76)
- When running `make HOST=x86_64-w64-mingw32` note the error

**Screenshots**

![image](https://user-images.githubusercontent.com/4400555/119579933-610f7580-bdb7-11eb-8dd4-314d2b0d735d.png)

**Dogecoin Core version**

The commit at time of writing was `2797a581` on `1.21-dev` branch.

**Machine specs**

- OS: Windows 10

**Extra information**

The issue is due to LineEndings in the `config.guess` and `config.sub` files found in the depends folder and can simply have a note added to the documentation to make clear that this is the problem.

The CRLF option for me stems from the default ticked checkboxes that appear on installation of Git for Windows, therefore core.autocrlf is not set.

![image](https://user-images.githubusercontent.com/4400555/119584827-5d80ec00-bdc1-11eb-9c76-5ed7262307e2.png)

**Comment by aeroc7** [comment]
It doesn't look like Visual Studio builds are supported; you're trying to build with tools that you do not have. As the guide suggests, you need to (preferably) use the WSL to cross-compile the Windows build, or install the [MSYS](https://www.msys2.org/) environment.

**Comment by aminbadshah** [comment]
Hi, 

I couldn't compile either in a windows environment.

Here is what i did, please let me know if i'm missing something..

In a Linux Ubuntu WSL Terminal: I did

git clone https://github.com/dogecoin/dogecoin.git

So i put in a folder called Dogecoin

so then go

cd dogecoin

git clone https://github.com/dogecoin/dogecoin.git

should clone the branch..

Then

PATH=$(echo "$PATH" | sed -e 's/:\/mnt.*//g') # strip out problematic Windows %PATH% imported var 
sudo bash -c "echo 0 > /proc/sys/fs/binfmt_misc/status" # Disable WSL support for Win32 applications.

cd depends
make HOST=x86_64-w64-mingw32
cd ..
./autogen.sh # not required when building from tarball
CONFIG_SITE=$PWD/depends/x86_64-w64-mingw32/share/config.site ./configure --prefix=/
make

I get some compilation errors

![image](https://user-images.githubusercontent.com/11451980/120061858-ff981280-c013-11eb-95f4-a718e18b9daa.png)

I'm I missing a step? any help will be appreciated?

**Comment by ReverseControl** [comment]
As the original issue was resolved I am closing this issue. @aminbadshah, feel free to post your problem as a new Issue.

**Comment by aminbadshah** [comment]
@ReverseControl thanks no worries i figured it out how to compile it I gave the details instructions on another post how to compile it.

**Comment by ReverseControl** [comment]
@aminbadshah If you could post how you resolved your issue to help other shibes that come across this problem in the future, the community would be much thankful.

**Comment by aminbadshah** [comment]
Sure no worries here are the steps i took:

did try this... from https://github.com/dogecoin/dogecoin/blob/1.14.4-dev/doc/build-windows.md
yes this has some good info and i got it to compile... yay...

There are a couple of mistakes on the doc: if you are using Ubuntu18.04 it doesn't support libqrencode4
sudo apt-get install libssl-dev libboost-all-dev qt5-default libprotobuf-dev libqrencode4 libdb++-dev libdb-dev miniupnpc

I think this is for newer versions of Ubuntu..

Had to use libqrencode3 instead for Ubuntu18.04

so

sudo apt-get install libssl-dev libboost-all-dev qt5-default libprotobuf-dev libqrencode3 libdb++-dev libdb-dev miniupnpc
this should work...

apart from that had one issue where it was complaining about virtualization when running the first command in Ubuntu18.04. So i did enable that from the BIOS, however that did not work. what did work was running the Ubuntu Terminal in Admin Mode.. that got rid of the virtualization error...
