### ISSUE TITLE
VERY LOW SPEED 

### ISSUE THREAD

**Issue by keshav1612** [dogecoin/dogecoin#2141]
Visa can do 65k transactions per second whereas DOGE can do only 70 transactions per second . We want doge that it should do 700k transactions  per second

**Comment by yuanoook** [comment]
> Visa can do 65k transactions per second whereas DOGE can do only 70 transactions per second . We want doge that it should do 700k transactions per second

@keshav1612  Visa can ban your account at anytime. Anyway, if you use in platform transfer like binance pay, you get the same speed as visa

**Comment by delbonis** [comment]
@keshav1612

You should read this recent article: https://vitalik.ca/general/2021/05/23/scaling.html

@yuanoook 

>if you use in platform transfer like binance pay

Binance can also ban your account at any time.  The answer is to move off-chain.

**Comment by rnicoll** [comment]
I was sure we had a scaling issue open already, but can anyone find it?

**Comment by patricklodder** [comment]
> I was sure we had a scaling issue open already, but can anyone find it?

The authoritarian dictator in me may have slipped and left one open, perhaps.

Closing this one though.
