### ISSUE TITLE
To limit supply of Dogecoin

### ISSUE THREAD

**Issue by anthonyheng** [dogecoin/dogecoin#2146]
Please try to take over and limit supply of dogecoin

**Comment by RichDevX** [comment]
You're free to fork the code and place a limit on the supply.

**Comment by ice2200** [comment]
Reduce the market cap to 15B.
Once 70% of 15B is utilize, initiate plan to pour 5B coins per year.

**Comment by Aitare** [comment]
What would be the policy behind why we would do this and choose these amounts? Is there a logical way to optimize demand. My brother, Ray was actually talking with me the other day about this. The idea being: Where the demand for a meme's generated by an individual was high and staked against holders doge it would rise in value to the point where it would load balance against demand and issue a new mutual allocation of coins. The new coins would be stalked as a stabilization buffer, for allocation on maturity. The (doge + doge) x steaks held = logarithmic puppies / time

**Comment by patricklodder** [comment]
> Reduce the market cap to 15B.

Sounds like some real thing a government would do. Confiscate all the value out there. And then use it for the benefits of politicians and their buddies. 

Let's not. Closing this.

**Comment by bernTOAST** [comment]
@patricklodder sounds like something doge coin would do.. original cap was 100 bil. You have some fantasy idea of what doge is, not based in reality... No doge will go the way your vision wants because you're a dictator. Even if someone built a perfect fork to do everything needed. You'd shut it down out of spite.
