### ISSUE TITLE
Upgrade Dogeoind daemon 

### ISSUE THREAD

**Issue by PrestonHack** [dogecoin/dogecoin#2147]
I purpose upgrading the daemon so that all platforms can use a local miner on their own ledger for validating transactions.

-- I understand doge merge mines with LTC to prevent a 51% attack this will strengthen the network long term. 

-- It helps to prevent poolers from undermining the mining/magic transaction security.

-- Having lots of wallets with ledgers is not the idea of cryptocurrency security, if mining is pooled by a handful of people then this undermines the whole idea and basically removes the security and places the entire protocol in the hands of the people mining.

This should be the peoples crypto and therefore we should put the control back in the hands of the people this can only be done by securing enough miners and ledgers to prevent an attack so there is a need for pools but there is also a need for individuals to check the pools sadly there are very few. 

I suggest upgrading the daemon, implementing an opensource protocol to handle worker requests like stratum, and providing a opensource miner. It's a tall order it's not impossible I can help when I am not doing my own AI racing drone project. 

As mentioned I can help feel free to DM me on twitter @prest0n1337 I am certified in secure infrastructure.
PS I will work for doge not for free though sadly I have a life

**Comment by rnicoll** [comment]
I believe http://p2pool.in/ is broadly what you want?

**Comment by PrestonHack** [comment]
Right now it's just a trading game more or less.

**Comment by PrestonHack** [comment]
If you want to talk i'll head in to the discord

**Comment by PrestonHack** [comment]
Also the dogecoin guide is garbage no offense it just needs major reworking there isn't a guide that explains much.

**Comment by PrestonHack** [comment]
what is the discord

**Comment by PrestonHack** [comment]
I am willing to help do a rewrite of the core that doesn't break major implementations. It really needs to be done if you understand the history if this software and I am sure you know more than me it is from a broken software that was updated till it finally worked. Bitcoin wasn't the first to use this code it was just the first to do it successfully in my opinion it's not secure it has been undermined and people don't understand that if miners that aren't pooled don't verify their own ledgers then it's pointless. And if you look at how a lot of this software is working now it breaks the nature of how this whole idea is supposed to work so yeah the very idea of crypto in it's current form is not what people thought it would be.

**Comment by PrestonHack** [comment]
I have a degree in digital forensics and have taken courses in cryptography

**Comment by PrestonHack** [comment]
When people layer these software's especially the unexperienced they leave themselves very vulnerable because there are people out here who know a ton about how this software functions.

**Comment by vertiond** [comment]
https://www.reddit.com/r/dogeducation/comments/mtjo6a/solo_merged_mining_doge_and_ltc_local_cpu_and_asic/

This guide details on how to run P2Pool configured with merge mining.  Litecoin does have an active P2Pool network already on mainnet so in this case it wouldn't be solo mining but a matter of connecting to the existing network. One node is here: http://p2p-spb.xyz:9327/static/

9326 is the port to allow connections from other P2Pools to you and 9327 is the port to allow others to mine to your P2Pool.

**Comment by PrestonHack** [comment]
Thanks I will take a look, but the position I am taking is making this user friendly packaging doesn't matter if it's just a simple guide at the very least. The internet spam on this topic is bad and the main site isn't updated with a guide.

**Comment by vertiond** [comment]
More information about what P2Pool is here: https://en.bitcoin.it/wiki/P2Pool

**Comment by PrestonHack** [comment]
I understand what it is on the high level. But I am only getting the same response no one addressing the issue I get it there were over the years several projects to bring this field into maturity. But it's time to package it.

**Comment by PrestonHack** [comment]
It's just a software that implements a RPC json protocol very poorly over a port we can fix that.

**Comment by vertiond** [comment]
Suggesting that 'all platforms can use a local miner on their own ledger for validating transactions' is disingenuous at best considering an ASIC is essentially required at this point to have success.  I'm all for simple mining as being involved in a one-click miner software myself but this approach to allow anyone to mine with their existing hardware doesn't have any merit when they won't be contributing much if anything.  I do agree that it can be made simpler for those who wish to purchase the hardware necessary.

**Comment by PrestonHack** [comment]
Not suggesting all I am suggesting it has a package with it instead of giving people a ledger and them being mislead into thinking it's something else.

**Comment by PrestonHack** [comment]
Okay the reason is not to get lucky and get a reward you get that? It's so that you can validate your ledger which is the point.

**Comment by PrestonHack** [comment]
Otherwise you trust whichever ledger you get

**Comment by PrestonHack** [comment]
So some pools may not even carry a full node for example they might just carry a recent history right and then they pass out smaller less complex hashes to do a certain amount of work then they prove they did a certain amount of work. The whole thing is muddy and it's early right now and I'd have to write it down in detail and follow the path.

**Comment by vertiond** [comment]
> Okay the reason is not to get lucky and get a reward you get that? It's so that you can validate your ledger which is the point.

This is fulfilled by running a node.

**Comment by PrestonHack** [comment]
The full node doesn't validate

**Comment by vertiond** [comment]
Yes, it does.  I think you have some misconceptions on what validation is and how this is different than mining.

**Comment by PrestonHack** [comment]
Your right I do have a misconception when I think about it but there are valid reasons.

**Comment by PrestonHack** [comment]
A lot of the hard reasoning has to do with all of the fact that a lot of the consideration is that everything is done with the assumption that a bad actor is at play. And let me tell you that is conveying the flow of attack meaning you don't go against the grain. Secondly the weakest link in security is people not the appliance. And pooling centralizes you can argue that all day.

**Comment by ReverseControl** [comment]
@PrestonHack For proposals, and topics which merit discussion, please use the discussion tab: https://github.com/dogecoin/dogecoin/discussions.
