### ISSUE TITLE
[bug] Please upgrade ZMQ library: the old one used misses some transactions

### ISSUE THREAD

**Issue by Polve** [dogecoin/dogecoin#2149]
Programs listening to the ZMQ socket to receive real time blocks and transactions sometimes skip some transactions.

I had a similar problem on other nodes (coins), and the problem was due to an old version of ZMQ: the included one is 4.1.x that's very old and full of bugs.

The problem should be fixed by upgrading ZMQ to a recent version.

**Comment by patricklodder** [comment]
Hi! I want to do a depends update anyway. 

Targeting this for 1.14.4 release. Thank you for letting us know!!

If anyone wants to pick this up and PR before I get to it, be my guest! ❤️

**Comment by AbcSxyZ** [comment]
@patricklodder "help wanted" label ;) [can't do that myself]

Can be a good practice, see #2170.

**Comment by patricklodder** [comment]
I decided against that because messing with the depends system isn't easy. But let's do an experiment 😁

**Comment by tuthodien** [comment]
I have just built dogecoin on Ubuntu 20.04 with ZMQ 4.3.2 (libzmq3-dev/focal,now 4.3.2-2ubuntu1 amd64) and It was successful. So what is the problem?

**Comment by patricklodder** [comment]
> what is the problem?

We have a build system that fixates dependencies for tests and for gitian builds, [zmq is listed here](https://github.com/dogecoin/dogecoin/blob/1.14.4-dev/depends/packages/zeromq.mk) and that needs updating for this to pass tests and be included in the actual releases.

**Comment by tuthodien** [comment]
Thank you @patricklodder 
I think I can help resolving this issue. But I don't know where to start. Any guideline sir?

**Comment by sabotagebeats** [comment]
does that look right? ☝

**Comment by rnicoll** [comment]
@Polve Can you test if https://github.com/dogecoin/dogecoin/pull/2236 fixes the issue for you? I'm running checks for stability, but don't have any tooling for ZMQ specifically myself, and if you have the ability to test it, that's probably most practical.

**Comment by Polve** [comment]
The current ZMQ release is 4.3.4, while the 4.1.x (the actual one) is the one buggy.
The changeset you linked "updates" it to 4.1.8, i.e. a very old release, so it doesn't seem to be the right one.

**Comment by sabotagebeats** [comment]
@Polve are you getting the same error that I am in the build process? 
https://github.com/dogecoin/dogecoin/pull/2236#issuecomment-854117638
