### ISSUE TITLE
Mining cryptocurrency on the moon using nuclear energy 

### ISSUE THREAD

**Issue by PetrosS1** [dogecoin/dogecoin#2151]
# Feature Request

The environmental impact of mining cryptocurrencies (and computation in general) is becoming significant.

A way around it could be migrating crypto mining on the moon using nuclear energy and sending the data through. Similarly, other heavy computation could be migrated there. 

A business case could be attached to the proposition as this could also apply to other computation needs currently serviced on earth which already has a massive impact, and also act as a "pilot" to space colonisation
a bit of a "moonshot" idea but can be elaborated

**Describe the Feature Request**

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by fmhc** [comment]
I like your out of the box thinking. do you have more details to that, how to safely transport nuclear fuel to space etc.?
Your post will probably get closed very soon by the mods as this has no dogecoin core code relevance. There are other, already closed issues around these topics. (https://github.com/dogecoin/dogecoin/issues/2120 and linked).
The guideline here is to move the conversation to reddit, but much people dont have Reddit Karma points. See https://github.com/dogecoin/dogecoin/issues/2128 for an idea of workarounding with github discussions, but this is not live yet. Would like to see more discussions around "moonshot" ideas here!

**Comment by PetrosS1** [comment]
there will indeed be multiple engineering challenges however nuclear submarine technologies could be a starting point.
I have tried posting it on reddit and awaiting approval by mod

**Comment by patricklodder** [comment]
https://www.reddit.com/r/dogecoindev/comments/nlmgmd/mining_cryptocurrency_on_the_moon_using_nuclear/
