### ISSUE TITLE
Doge Development

### ISSUE THREAD

**Issue by AfCraft** [dogecoin/dogecoin#2155]
1. Provide good advertising support to Doge.(bloggers, TV, radio) 
2. Enter into contracts with companies, issue cashback in Dogecoin for purchases. 
3. Take an excavator to the moon, and dig up the Doge logo there))) (for the whole world to see) 
4. Place logos on airships and balloons. 
5. Doge should support animal shelters so that the little brothers can find a home thanks to Doge.(if a person picks up a dog, award him a DOGE) 
6. Make a mega promotion to attract investment in the company.

**Comment by patricklodder** [comment]
Dogecoin is whatever the SUM of the community makes of it, not what the development team does. You can do all this without any centralization!

Closing this. ❤️
