### ISSUE TITLE
Multiplanetary cryptocurrency system

### ISSUE THREAD

**Issue by LoganDev** [dogecoin/dogecoin#2156]
As we are planning to make human as multiplanetary, cryptocurrency will be major part on this as per my understanding. It will be perfect idea to have this in transactions. According to this plan, I got an idea that we can have different coin setup based in planets like one for earth, one for mars, and so on. We would need different transaction fee based on planets like one fee for same planet transaction and one fee for different planet transaction. Also, I think we can name the coin based on planet like eDogecoin for earth, mDogecoin for mars and so on.

**Comment by patricklodder** [comment]
🚀
