### ISSUE TITLE
[feat] I need help locating my crypto (doge)

### ISSUE THREAD

**Issue by victoriat31** [dogecoin/dogecoin#2157]
# Feature Request

**Describe the Feature Request**

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by WasabiBeats** [comment]
this unfortunately isnt the best resource to help with this sort of issue.  The best thing you can do is join the discord or reddit groups and provide a detailed summary of the problem. Maybe someone would be able to assist then. Best of luck to you!
