### ISSUE TITLE
Telsa cars sold with doge

### ISSUE THREAD

**Issue by xandee-games101** [dogecoin/dogecoin#2168]
I was directed here by Elon Musk on twitter and I say why don't you add buying of Tesla cars with doge

**Comment by demostanis** [comment]
Elon told me dogs can't drive cars. Maybe Tesla should put a doge on the passenger seat, but dogecoin developers have no power on this.

**Comment by patricklodder** [comment]
Wrong repo: I think you should raise issues in all the repos here: https://github.com/teslamotors
