### ISSUE TITLE
FEATURE REQUEST/DESCRIBE ALTERNATIVE 

### ISSUE THREAD

**Issue by NOVAFARE** [dogecoin/dogecoin#2169]
Hi!
I am just here to share a few ideas for our beloved DOGE.  To be clear, my technical prowess may be less than other people contributing ideas. I do however, inherently understand the massive financial revolution that is in play.
If anyone sees this. Thank you. 
1. Create a Proof of Stake driven model of Doge that is designed to be merged with the original version like what's happening with ETH2.O🌍🌱
2. Create a farmable token called PEDIGREE, design it to have the "best of" features for long term holders. Connect it to the DOGEPAY universe with real life benefits for your reliable blockchain farmers/holders. 🚜🏅
3. Create an internal swap within DOGEPAY, PEDIGREE, or both. Make these easier to access for average people. Reward both business that accept DOGE and customers that use it, with things like PEDIGREE, which could grow in value for the business or customer. 🧭🍭
Would say more. That's me keeping it short. Thank you again to all of DOGE~~~~

**Comment by patricklodder** [comment]
I'm going to close this. Anyone can make a token. When you do, keep it honest, and don't issue to yourself plz. ❤️
