### ISSUE TITLE
Suggest checking "help wanted" issues in CONTRIBUTING.md

### ISSUE THREAD

**Issue by AbcSxyZ** [dogecoin/dogecoin#2170]
It could be a good practice for dev to add this label on issues where they ask for help.
Add it explicitly to the `CONTRIBUTING.md` to suggest contributors to check issues/PR with this label.

**Comment by patricklodder** [comment]
Also has been mentioned here:

https://www.reddit.com/r/dogecoindev/comments/nlryj5/development_update_20210526/

**Comment by tiarebalbi** [comment]
#2111 ^^^

**Comment by AbcSxyZ** [comment]
Done
