### ISSUE TITLE
[feat] Little Rabbit Coin

### ISSUE THREAD

**Issue by georgeartem** [dogecoin/dogecoin#2172]
# Feature Request

**Describe the Feature Request**
Fork for "little rabbit coin" a fork that is modeled after the dollar starting with a circulation of 20 trillion "little rabbit coins" that are set to maximum reproduction and hyperinflation to 11 quadrillion "little rabbit coins" leading to a Night of the Lepus scenario.

**Describe Preferred Solution**
Invest in little rabbit coins at your own risk - they will eventually hyperinflate

**Describe Alternatives**
Don't buy little rabbit coins

**Related Code**
Investigate Litecoin forking

**Additional Context**
Clearly this is a joke. Do not build little rabbit coin.

**Comment by ThisIsMyDogeAccount** [comment]
Haha

But honestly do not spam the GitHub.

Please close / delete this

**Comment by georgeartem** [comment]
Sounds good. Happy you had a laugh 😂
