### ISSUE TITLE
[feat] dont know how it would be done just some ideas

### ISSUE THREAD

**Issue by chrisyouree** [dogecoin/dogecoin#2174]
Making the mining of dogecoin simple so that I can mine it on my chrome book while I'm at work. Make a dogecard (all black with gold trim withe the dogecoin in the middle) . (Doge vault ) if it's the currency of the future people will still need loans, so the vault you can put doge in to gain interest. Dogecoin app/ wallet . (Dogepay) with dogepay you can use any cryptocurrency you have and it will transfer it to Dogecoin for you anyway that accepts Dogecoin as payment. Number of coins able to be mined lower on leap yrs. Add a fee for selling over a certain amount of doge.  

# Feature Request

**Describe the Feature Request**

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**
 

**Additional Context**

**Comment by patricklodder** [comment]
All this can be done with existing tech on top of Dogecoin Core, except for the subsidy change, which is unnecessary anyway.

Please consider putting this on reddit, so that interested 3rd parties may hear of your idea and discuss it.

Closing this now.

**Comment by Haleymiranda79** [comment]
I liked your idea
