### ISSUE TITLE
Dogecoin In Videogames

### ISSUE THREAD

**Issue by CipherDoge90** [dogecoin/dogecoin#2175]
Get Dogecoin to be used in the video game world

Imagine, crypto in an actual game. Is using Crypto directly considered gambling? Online competitive video games could use something fresh. 

• To purchase in game specials on dlc 

• To wager X amount on a match in COD, Battlefield, PUBg, Madden, FIFA. The list could honestly go on and on. You can only wager Dogecoin 🤷🏻‍♂️. Thus creating a need to buy it. 

• Video Game Tournaments based around Dogecoin reward. 

The video game industry has huge money in it. But no crypto has tried to establish itself there.

• The Publicity Dogecoin could receive would be on a whole new level. At the same time, attracting young coming of aged adult to be aware of finances and investing. That would be so crazzzy! and honestly could benefit a lot of people. 

I’m serious about that thought though. I wish something would of grabbed my attention at a young age and pushed me to invest or of at least look into it. I do now, but if I started 10yrs ago I’d be waaay ahead. Lets be honest video games is just a culture thing now.  Imagine how Dogecoin could not only be fun, but effective learning tool for the next generation and so fourth. Because just like the Desire to go to the moon.... or mars, or to Just hang out and play a video game. Their not going anywhere and neither is Dogecoin.... (I’ll take a bow)

**Comment by patricklodder** [comment]
You can do this, today! No need changes to Dogecoin Core either! Let us know how you fare here: https://www.reddit.com/r/dogecoindev/
