### ISSUE TITLE
Ideas for Elon Musk / Tesla regarding Doge mining[feat] 

### ISSUE THREAD

**Issue by charlesb2003** [dogecoin/dogecoin#2176]
I'm a long term HODLer and miner of Dogecoin (I have two Antminer L3++ ASICS) and a future Tesla owner and I have a couple ideas.

I know that Teslas have Nvidia chips in them, would it be possible to use those chips to mine the Scrypt algorithm while the car is parked? I'm sure it wouldn't be as profitable as an ASIC but it would help further decentralize the network, incentivize people to buy Teslas (the car helps pay for itself), and the feature could even be set to only work if the car was charged or is connected to a "green" source of electricity.

Another thought that I had is some kind of incentive for miners to buy a Tesla solar roof and/or Powerwall. This would have the same benefits and incentives as mining in the cars (offsetting equipment cost, "green" energy). This could come in the form of either a rebate on purchasing the equipment if it's paid for in Doge, or some kind of discount or exclusive offer on the ASIC miners themselves if you own a solar roof or Powerwall. Perhaps Tesla or another one of Elon's companies like SpaceX could even start producing Scrypt ASIC miners optimized for Dogecoin mining. I would definitely buy one! Would be great if an American company would produce and sell them domestically so we aren't dependent solely on Chinese producers.

**Comment by AbcSxyZ** [comment]
A car whom pay for herself, a good marketing argument :smile:  !

Sadly, it's the wrong place to expect this kind of change, Github issues are used for trouble with Dogecoin Core software.

As developers [said](https://www.reddit.com/r/dogecoindev/comments/nlryj5/development_update_20210526/) :
> We can’t control external companies, and requests that are for externals are probably better posted to the r/dogecoin subreddit.

You should use any social media or contact the company directly, you will have more impact.

**Comment by patricklodder** [comment]
Please leave your issue at https://github.com/teslamotors
