### ISSUE TITLE
[feat] i would like to develop the RPi4 board with minimal scripts and power consumption

### ISSUE THREAD

**Issue by angakkoq** [dogecoin/dogecoin#2177]
# Feature Request

**Describe the Feature Request**

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by rnicoll** [comment]
You don't need our permission for any of this, we're purely an open source project. I believe it works on Raspberry Pi in theory, although memory usage is high, so you'd want to look at whether you can reduce memory usage while keeping performance high enough.

If it helps the contribution guidelines are being reworked in https://github.com/dogecoin/dogecoin/pull/2111

**Comment by vertiond** [comment]
https://github.com/vertiond/pidohj
