### ISSUE TITLE
Can’t Beat A Win Win! 

### ISSUE THREAD

**Issue by CountingCoins** [dogecoin/dogecoin#2180]
Can’t beat a win win for buyers & sellers!!
This may sound a bit too simple but sometimes we overthink things so I didn’t see what it could hurt to add an idea. I understand this isn’t core development help but who knows it could spark a idea for someone!
In my opinion, creating a safe & secure Dogecoin payment system that has buyer & seller protection (similar to PayPal), that is also easy to use, would likely boost the acceptance of Dogecoin for retailers as well as boost the trust in Doge for investors. Personally when I shop online & a seller does not accept PayPal, I look elsewhere. As a seller I would know that the possibility for that $20 item to end up allowing me to profit even further in a short period of time (if I chose to hold it) why wouldn’t I want to accept Dogecoin as a form of payment. The market is killing companies right now so they have to find a way to recoup the losses from the Pandemic & the market....what better way to do that than accepting Doge. Company financials improve, share price improves, it’s a win win! Buyers are happy because they bought Doge early or on a dip & actually purchased the $20 item for less than $20. I have a bit of a shopping habit but I’m also OCD, which makes me search until I find a item at the absolute lowest price possible (very time consuming!). Never needing a discount code or waiting on the best sale because I would be in control of what price I own/purchased my Dogecoin....it would be awesome for buyers & sellers alike!!

**Comment by metatron1973** [comment]
Good thought nice post

**Comment by CountingCoins** [comment]
Thank you! I’m new to Github so it will take me a minute to figure out how everything works.

**Comment by CountingCoins** [comment]
> Good thought nice post

Thank You! I’m new to github so it might take me a minute to figure out how everything works😁

**Comment by Im-Mr-Chris** [comment]
I've started doing this with bitpay. Idk if it's known out there or not but I actually got a card in the mail. They have Dogecoin listed on there out of bitcoin bitcoin cash, and ether. 

To add on top of this, with all the stuff Apple is publishing, everyone's stuck on using Apple Pay with their 44 million users. 

We're already on bitpay. You can use the card directly with Apple Pay already. They even have the virtual bard. 

Doesn't this give us the utility already? Why speculate on the price action and trying to make everyone else accept us when only our community believe and find value in? 

If the community is only focused on our 1 out 14 placements in the consensus algorithm, we need to imagine our end goal. Right?  

Or was that a bit too far ahead?

**Comment by CountingCoins** [comment]
Apple pay doesn’t have protection for buyers & sellers. Yes, I use it if I’m 
buying lunch but not for big ticket items. I believe Dogecoin is much bigger than some realize, finding someone who hasn’t heard of Doge isn’t easy as you would think. I believe the possibilities for the future of crypto will surpass any form of trade that exists, especially ApplePay. I understand that there is bitpay & using the card on ApplePay but I don’t see the need or why some think that every product needs to be associated with Apple to be successful. I’m looking at going beyond what ApplePay can offer. To be honest Apple isn’t a factor when I’m thinking about the future of crypto. “Don’t put all of your eggs in one basket”...we shouldn’t put all of our eggs in Apple’s basket. What makes crypto unique is that it’s not under anyone’s control like everything else in this world! I’m not saying there isn’t a place for the never ending supply of Apple products, because apparently there is. Following the Apple brick road isn’t where the focus for future use & development of crypto needs to be..in my opinion.

**Comment by Purukitto** [comment]
Wouldn't this be against the fundamentals of how crypto works? You'll have to centralise and track the payments to provide said protection.

**Comment by Sanyam17-beep** [comment]
im new to this can anyone help me contributing
please

**Comment by Purukitto** [comment]
@Sanyam17-beep as a developer or?

**Comment by rnicoll** [comment]
We don't have resources to become a payment processor, but there are existing payment processors for Dogecoin, and obviously with PayPal handling other cryptocurrencies, we hope they will in time handle Dogecoin.

Meanwhile there's a list of existing services for this on https://spendyourdogecoins.cf/

**Comment by CountingCoins** [comment]
If looking at the current standard way of doing things, yes. I’m not a developer but I know there are plenty highly skilled developers who think outside the box. I know there is someone that can figure out a way for Doge to go way outside the box but offer similar benefits. I try not to let anything that is the current way things are done or anything that has ever been done play a role in what the possibilities for Doge could be...unless I’m referencing something current just to help those who are reading my post to somewhat visualize what I’m trying to explain. There are plenty of “isn’t that like...” but that is what this development process is about. Let’s go beyond the imaginable & find a way to do things differently & better. If Elon can create a brain chip I’m certain he can help figure out how to advance Dogecoin to surpass all other crypto.

**Comment by delbonis** [comment]
>If Elon can create a brain chip I’m certain he can help figure out how to advance Dogecoin to surpass all other crypto.

Elon must didn't create the neural implants, bioengineers did.  He also didn't create SpaceX's rockets and engines, an army of other (mechanical, chemical, material, electrical, software) engineers did.  Sure he definitely knows more about most of these projects than 99% of people do, but cryptoeconomic engineers are the ones to talk to about development of cryptocurrencies whose actual job is to do that.

**Comment by CountingCoins** [comment]
Can’t, Don’t, already exist is part of the issue. It’s not about being a payment processing system. Does it seem impossible for Doge to become the new way of trade & most used currency in the world...I guess I must be shooting for the stars. The responses I’ve received have been geared toward being reliant on a system already in place or the current way of doing things, those are old school & need not be apart of our thought process when it comes to Doge. For me, the only obstacle for Doge becoming the currency of the world would be government interference, not another crypto. Like I said previously, Dogecoin is pretty much a household name. To me it is a crypto that isn’t intimidating for those new to the world of crypto. I think many look at Dogecoin as the crypto of the people, for the people & that is an huge advantage that will be one of the most important contributing factors to take Doge to the top....or should I say, make Doge the top dog! 😁 
#TheTopDog
#ThatsMyDawg 
#InTheDogHouse
#WhoLetTheDogOut
(a little humor never hurts!)
 
“If it don’t make dollars, it don’t make sense”

**Comment by CountingCoins** [comment]
If a title determined ability we wouldn’t be where we are today! It takes a brilliant minded individual to do the things he has done, regardless of his role or title any of his endeavors. If he had a team of bioengineers that developed a brain chip then what’s the difference in having a team of crypto-economic engineers further develop Doge. Neuralink wasn’t the first to experiment with brain chips but it’s the only one that has made it this far. Cryto-economic engineers didn’t develop technology, “an army of mechanical, material, electrical, software engineers did” but that only means they didn’t create a tool that is allows for future advancement. I’m not saying Elon Musk is the magic wand for Doge but he has a proven track record of doing the once unimaginable (or you may prefer, played a role in the once unimaginable). There is no need to discredit what he or anyone else has accomplished or been a part of accomplishing, according to a title. I’m not sure that those who have this kind of thought process are the best suited for taking Doge above & beyond. If the plan isn’t to do the unimaginable then it Doge will be left behind, because other crypto’s will. Elon has the undeniable drive inside him to do what’s never been done & to me that type of person is a huge asset, he will find the best of the best crypto-economic developers to get there. We must also take into account that Elon having Aspergers is undoubtedly one the main reasons for his success. Everyone with Aspergers do not posses the same traits but apparently there are traits he posses that allow him the ability to do what some of us can not fathom. 

Just a few Aspergers traits that could possibly play a role in Elon’s success

are enthusiastic and have a propensity for obsessive research, thus developing a broad and deep base of knowledge in subjects of interest
are persistent, and when they set their minds to something or make a promise, they can usually be trusted to follow through
can listen to people’s problems and provide a fresh perspective, offering pure assessments based on the information provided
have an acute sensitivity that supports creative talents
have one or more highly developed talents
stick to their positions, even in the face of intense social pressure
tend to become proficient in the technological media required for lucrative employment in the “information age“
have exceptional memories
have extreme endurance

> 
> mechanical, chemical, material, electrical, software) engineers did
> 
> 
> 
Thank You,
Amanda Hunt

**Comment by bernTOAST** [comment]
@delbonis is a jealous little incompetent bum. He hasn't contributed anything meaningful in code to anything yet acts like he's some sort of gift. He's unemployed and is mad no one will hire him for his useless skills. So he says things to make himself feel important like above, which no realistic adult doing anything important would believe that horse shit.  Get back to the 🎪🤡 you fucking idiot.

**Comment by CountingCoins** [comment]
First of all, it’s she!! I stated earlier that I was not a developer. I do not write code, I was simply offering a idea & if I’m not mistaken that is acceptable. I’m not sure if you say bum, unemployed & mad because no one will hire “him” because you have been in that situation many times. There is one thing you got right, I don’t have a job, I own the company & a very successful IT company at that. Many years of 14 to 16 hour days of hard work eventually paid off & I was able to bring in some well qualified individuals to run the company for me, which is why I’m able to do whatever I wish each day like reply to a email of this nature. I understand that many who’s field of expertise is in the realm of writing code, programming, software development etc...can’t walk & chew gum at the same time. I was just trying to offer my perspective so please excuse me if offering a few ideas offended you. I can see they are inferior to what you must have helped Doge accomplish! Thank you for what you have done for Doge! I know it will be a great feeling when you receive recognition for your contribution. Yes that’s sarcasm, because if you have time to send me that email you must not be have ran out of ideas to help make Doge untouchable.
