### ISSUE TITLE
[feat] Create an automated NFT rewards program

### ISSUE THREAD

**Issue by digital-flowers** [dogecoin/dogecoin#2185]
# Feature Request

**Describe the Feature Request**
I think it will be cool to create an NFT reward system based on the number of blocks minted or the number of transactions, think about it the same as the traditional  "customer No. 100" rewards in supermarkets.

- I think this feature will boost the transactions since everyone wants to be that lucky person to get the NFT since it's one of its kind and it will mean a lot.

**Describe Preferred Solution**

We have several options to create those NFTs:
- The NFT can be an image template with the Doge logo and the number of transactions achieved e.g (1K,1M,1B,...)
- The NFT can be a predefined doge memes 
- The NFT can be a meme that is decided by the community each time we release a new version 
- The NFT can be the most liked meme on the r/dogecoin

**Additional Context**
I have a really good experience working on the NFT market, I can help with whatever I can if we decided to implement this, here is my latest fun project :)   

https://thebitcats.com 

<img width="400" alt="Screenshot 2021-05-27 at 3 25 12 PM" src="https://user-images.githubusercontent.com/5216291/119783398-be164300-beff-11eb-83cd-61b654d3f3f3.png">

**Comment by ThisIsMyDogeAccount** [comment]
Sorry this is not the place to talk about this

Section 2.b 
https://github.com/dogecoin/dogecoin/issues/2110

But definitely bring this post over to reddit,

https://reddit.com/dogecoindev

**Comment by digital-flowers** [comment]
Thanks :)
