### ISSUE TITLE
[feat] make it limited for now

### ISSUE THREAD

**Issue by PriyatamNayak** [dogecoin/dogecoin#2188]
# Feature Request

**Describe the Feature Request**

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by AbcSxyZ** [comment]
https://github.com/dogecoin/dogecoin/issues/2003#issuecomment-847304810

> Limiting the supply has been discussed many times.
[1] #1674 (recent issue)
[2] https://www.reddit.com/r/dogecoindev/comments/la1hk3/continuation_of_1674/

To promote myself, I wrote about economic impact of deflation : https://github.com/dogecoin/dogecoin/issues/1963#issuecomment-843617890

If you want to see other issue/discuss about limiting the supply : https://github.com/dogecoin/dogecoin/issues?q=is%3Aissue++is%3Aclosed+supply+limit+
