### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by Ashjo80** [dogecoin/dogecoin#2197]
Did Dogecoin use the ecosystem? If it's not. What's the pospolity to make it happen. As all we know without ecosystem their will be no future for the coin.

**Comment by patricklodder** [comment]
The other day I asked the ecosystem and they told me they love to be used more by Dogecoin. But no abuse please. So, less scammers, more real applications, is about it. ❤️

**Comment by Ashjo80** [comment]
No one going to answer 😕
