### ISSUE TITLE
[feat] Snapshot of current state

### ISSUE THREAD

**Issue by sirapm** [dogecoin/dogecoin#2202]
When a new node/user join and start, they have to play forward years of data that can take days or weeks. It would be nice if the nodes could generate a snapshot on a daily or weekly or monthly schedule. This would speed up the data usage, processing, significantly lower power usage and get people up to speed quickly. Basically, for a new user, they technically don't need several year old data as they just created a new certificate. 

Apart from snapshots, maybe also add a choice when first starting up,
Do you want: 
1) All historical data
2) Data from the creation date of your private key
3) Manually enter a "start date"

1) would be for people like me that want to help and run a public node. (Need to build a new server in my DMZ first and move my docker node to it.)
2) would be for most people.
3) why not.

If snapshots are not possible (don't yet know the data format) would a query based solution work for users (not looking at mining at this stage). I.e. "give me all data you have for my public key xxxxxxxxxxx....? Or would that break the "distributed" principles? Or a hybrid?

Cheers
Martin

**Comment by ealcober** [comment]
Hello how can I help on dev? thanks!!!

**Comment by patricklodder** [comment]
Duplicate-ish of #2016

**Comment by sirapm** [comment]
Thanks @patricklodder 
I searched for it but slightly different wording. 
Cheers
Martin
