### ISSUE TITLE
why use this repository.  please explain it. 

### ISSUE THREAD

**Issue by ryihan** [dogecoin/dogecoin#2205]

**Comment by AbcSxyZ** [comment]
Why use a Github repository ? A place is needed to work on the source code of dogecoin. The software ([forked](https://en.wikipedia.org/wiki/Fork_(software_development)) from bitcoin/litecoin) used by miners to validate transactions and add new blocks to the doge blockchain.

If you wan't to understand what is github, you can take a look at this [article](https://www.thebalancecareers.com/what-is-github-and-why-should-i-use-it-2071946).
> GitHub is a hosting site where developers and programmers can upload the code they create and work collaboratively to improve it.
