### ISSUE TITLE
I hope that adding a second-hand goods trading function to DogeCoin will enable DogeCoin to cut into the goods exchange link.[feat] 

### ISSUE THREAD

**Issue by xiangbobozhenghao** [dogecoin/dogecoin#2206]
# Feature Request

**Describe the Feature Request**

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by DakshBarad10159** [comment]
I too agree with you, We should expand doge to the area of DeCom(Decentralised Commerce)

**Comment by xiangbobozhenghao** [comment]
Maybe Elon can be persuaded to publish Tesla peripheral products on the wallet's commodity exchange page. Support dog coin Tesla charging payment.

**Comment by xiangbobozhenghao** [comment]
The more perfect idea is: Roof solar excess electric power passed Tesla charge piles, trading dog dog coins, dog coins can be used to charge this to complete the cleaning energy currency system, which will be a perfect currency cycle system . I hope that Ilon can see this idea.

**Comment by DakshBarad10159** [comment]
i believe we focus to deliver a good idea and prototype not just to impress elon but, something accepted by all contributors and good for all

**Comment by patricklodder** [comment]
You can do all this today, no need to change anything to Dogecoin Core. For an example implementation that was done YEARS ago, check out https://www.suchlist.com

Please discuss this on https://www.reddit.com/r/dogecoindev/ - and let us know there if you need help with designing an escrow system.
