### ISSUE TITLE
Increase value of one doge compared to fiat currencies

### ISSUE THREAD

**Issue by DakshBarad10159** [dogecoin/dogecoin#2207]
The value of a cryptocurrency compared to a fiat currency is governed by only one LAW
 
The supply-demand equation, based on the demand of a crypto and its supply(new crypto coins produced due to mining) the price of cryptocoin against fiat currencies is fixed, due to large blockreward in dogecoin, the supply side is very high, but if we decrease the block reward size, we can increase the value of a dogecoin to more than a US Dollar very soon.

I propose we either decrease block reward or find other methods to increase the value...

**Comment by AbcSxyZ** [comment]
Limiting the supply is a good idea to increase the value of Dogecoin compared to fiat, potentially a bad idea to create a (crypto)currency (bitcoin is more a store of value than a currency).

From my pov, btc give a wrong paradigm regarding this question of deflation vs inflation. In the currency/fiat world, deflation is a threat, in the crypto"currency" world, it's a goal. Find the mistake.

If you want to increase the value, understand doge & spread the world :)

#2003 (comment)
> Limiting the supply has been discussed many times.
[1] #1674 (recent issue)
[2] https://www.reddit.com/r/dogecoindev/comments/la1hk3/continuation_of_1674/

To promote myself, I wrote about economic impact of deflation : #1963 (comment)

If you want to see other issue/discuss about limiting the supply : https://github.com/dogecoin/dogecoin/issues?q=is%3Aissue++is%3Aclosed+supply+limit+
