### ISSUE TITLE
Expand dogecoin to DecentralisedCommerce

### ISSUE THREAD

**Issue by DakshBarad10159** [dogecoin/dogecoin#2208]
before the invention of E-commerce, internet was limited to only few organisations with access to computer resources, and very few private companies, mainly in the sector of information and banking.

But with the use of internet for Electronic commerce, its user base expanded, more private companies started to use it as a tool and more and more individuals joined the internet as users.

Ethereum has prospered and made a lot of development in the area of DeFi, but if we can upgrade dogecoin to be exclusively used in the area of DeCom we can increase its scope of usage tremendously.

Another area of potential growth can be in the field of social media, but since the size of content produced every minute on present social media platforms is a lot bigger than our entire dogecoin blockchain, we should focus on DeCom

**Comment by patricklodder** [comment]
Dogecoin already supports decentralized commerce! No code changes needed! Thanks!
