### ISSUE TITLE
Delete if irrelevant (first time developer motivation)

### ISSUE THREAD

**Issue by Im-Mr-Chris** [dogecoin/dogecoin#2212]
I can't get this out of my head. Not because I have a good amount of doge, but because the tech is here. 

We have a crazy amount of resources in our pockets and we can communicate with each other from random parts of the globe. 

If we really want to see doge become something that isn't just valuable to us, but the young minds of the future. They will look back on these centralized platforms and study what we worked on, who said what, and several other questions we wouldn't be able to think of, considering what information we currently have in our perspective. 

Look, what I'm trying to do is to spark something in some young or old mind out on the internet. Idk who this will reach, but the fact that I'm only trying to drop some insight as to what the future holds for us,  that's what makes me step up and speak out like a fool. 

If there's anything I can offer, it's a few things that have somewhat changed my life and how I understand a relationship between understanding and how binary is pretty much just nature. Here's a short list. 

- Clear out anything that isn't related to blockchain or innovation. 

- unsubscribe from any of your yt "next gen news anchors" that talk about price action

- if you have a day job like me, try and compound your time with work and learning. 

Naval Podcast - This man is truly a genius of his own kind. He explains philosophy, technology, and business. 

https://open.spotify.com/show/7qZAVw03FuurfYnWIWwkHY?si=HcgWPw5zTPOSsmKZIt7IwA

What Bitcoin did - I very much admire the insight he sees. Up until the moment I realized a rt I did. Then it was a battle with myself. It set my mind straight. 

https://open.spotify.com/show/0mWUJuONiilW5JSBBFZ0s7?si=X6nE48uwTsqVhGjS0oDVig

MIT OpenCourse Spring 2018 (dated but still good quality info)

https://youtube.com/playlist?list=PLUl4u3cNGP61KHzhg3JIJdK08JLSlcLId

-Certainty and uncertainty 

-Twin prime conjectures (prime numbers)
Conways Game of life (zero player game)

-some patterns will go on forever, die, regenerate, stay constant, etc. 

-bonding curves

-things that are "un-decidable" *spelling

Lex Friedman - he asks the most incredible questions. His rants are golden because they're natural curiosity in motion

https://youtu.be/3x1b_S6Qp2Q

Audiobooks 
- How innovation works by Matt Ridley 
- The Bitcoin Standard by Saifedean Ammous 

Idk...I could go on about this all day. But I'm still at work and I've got equipment down that I need to get back online. But if I can share some of my understanding about anything, please don't hesitate to reach out. I tend to work around the clock so time doesn't matter much. 

Ironic....how ironic...I'm a mechatronic technician for a copper wire manufacture for the Turkish. Reminds me of rich dad poor dad. 

-Chris

Edit: I should probably be a little more aggressive about feeling shy or whatever. 

Dude...nobody cares if you're 8 or 80 years old. High school dropout, college dropout, whatever you use. If you're here, it's because you actually have an interest in the technology. Most of the youtubers peek in here to watch how progress is. The whole world is watching us. Sure i probably put myself on the most ultimate dox and self blast, but it was something that I haven't seen happen in any other of the forums. 

We can't just let the youtubers do all the hype. They're our fans, we can make shit happen here. For real! In front of the entire world. Cmon guys...we got this. 

I'll shut up now. 

Edit 2: added some audiobooks

**Comment by AbcSxyZ** [comment]
This issue, as you said, isn't really relevant here. It's interesting for educational purpose about Dogecoin/cryptos and more, but it's not an issue related to the source code of Dogecoin. If there is a place to speak about educational resources, it's possibly [r/dogeducation](https://www.reddit.com/r/dogeducation/), but I'm not sure if it's really active and have the audience it deserves.

Someone [posted on Reddit](https://www.reddit.com/r/dogecoindev/comments/no6a69/i_think_we_need_a_startfromnowhere_video_guide_to/) is intent to give educational resources to the Dogecoin community, it's for me related with your goal here.

He said:
> I think we should prepare the high quality coders of the future, even if it may be a seed sowed now that is reaped a year or two into the future. I argue this is what differentiates this community from the other gatekeeping ones.

I [replied to him](https://www.reddit.com/r/dogecoindev/comments/no6a69/i_think_we_need_a_startfromnowhere_video_guide_to#t1_gzyi5in), to let him know there is a lack of guidance actually from how to contribute, what's going on as well as how to get educational resources. Probably by having more guidance and more well-defined places for Dogecoin community, you will be able to speak about these topics in right place with interested people !

Some work to do to share correctly this kind of resources :)

**Comment by Im-Mr-Chris** [comment]
Hey, thanks for sharing that information with me.  

Your response helped me with some research if I'm being honest.  
Yes, I agree that there's not really an issue with coding. Idk what got into me, something just told me to say that here.

I'm finally understanding how to use Reddit (i know, after all these years lol).
That article I actually ran into prior to this as well.

I'll see what inspiration or motivation I can get going on over in that subreddit.

Thanks again for helping me collect some insight.

**Comment by google-meet-meat** [comment]
I certainly hope that "the young minds of the future" do not become fixated on a global pump and dump scheme with little use as an actual currency.

**Comment by AbcSxyZ** [comment]
Dogecoin is accepted in multiple place. With some payment method like [Bitpay](https://twitter.com/BitPay/status/1393193127393992710) and [Flexa](https://twitter.com/FlexaHQ/status/1390351448962179072), it's thousands of business where you can pay with doge.

I actually just shared a list of business accepting doge in this [issue](https://github.com/dogecoinisawesome-dot-com/DogecoinIsAwesome.com/issues/25) for the site [dogecoinisawesome](https://dogecoinisawesome.com/).

Also, different fundraising campaign have been done with Dogecoin, there is a spirit about Do Only Good Every day, stuff like that can happen spontaneously.

Dogecoin, at his beginning, was also widely used as a tip method, in 2013 at his launch there were more Dogecoin transaction than bitcoin transaction. A comparison of [dogetipbot & bitcointipbot](https://i.imgur.com/DgIyRgZ.png) on Reddit. 
Multiple small project are currently sharing their wallet to be tipped, for example content creator nowadays lack of good & friendly method, possibly a way where Dogecoin can (also) go, idk.

There is some currency use case, it can expand, it can crash. The future is a lot of unknowns, hasn't the unexpected happened already ?
