### ISSUE TITLE
"Zoom link"-like wallet installation/payment

### ISSUE THREAD

**Issue by Drael64** [dogecoin/dogecoin#2216]
I'll attempt to be concise. One major obstacle to cryptocurrency as a payment option is that most civilian counterparties do not have wallets ready to accept payment. Most people are not crypto-natives. 

I had the thought - what if a payment could operate like a zoom link? You send the individual a DM, or an email with a link - that link will link to a wallet set up (on whichever preferred platform, such as phone or PC), and that wallet automatically receives said payment?

This simple method made zoom the common method, over pre-existing video chat platforms, the counterparty interaction and app install rolled into a bundle. 

Doable? Too complex? Could it be done with lightning?

**Comment by Im-Mr-Chris** [comment]
I may be out of my place on this one. 

From what I understand, this leaves far too many footprints. 

In reality, I feel that it would or could be very difficult to scale. Solely because of the third party code. 

I could be wrong of course.

**Comment by rnicoll** [comment]
This would basically be a Metamask for Dogecoin, wouldn't it? https://metamask.io/

I wonder if there's a third party wallet that fits the description, anyone got suggestions?

**Comment by Drael64** [comment]
> This would basically be a Metamask for Dogecoin, wouldn't it? https://metamask.io/
> 
> I wonder if there's a third party wallet that fits the description, anyone got suggestions?

I guess it's sort of smart contract-y? Could be something like a lighting invoice that gets automatically invoiced when the user installs their wallet (so that the sender then has to approve still)?

**Comment by delbonis** [comment]
>and that wallet automatically receives said payment?

Yeah this is the tricky part, @Im-Mr-Chris is right.  If all you have is a link, there's no way to cryptographically commit the funds you want to send to the other party (since they haven't used any program to generate something you could use for that) without an unacceptable level of trust.  And if just *knowledge* of the link gives you access to the funds, then it's very very risky to copy paste the link around since *anything* that can access your clipboard could steal the funds (not just other programs on your PC, but all your browser extensions, and the (untrusted!) js on any page you happen to open between copying the link and pasting it into your browser).  There's a few tricks you might be able to do like *also* requiring also giving a sufficiently long password, but that's still easy for sniffers to detect and makes it less seamless.

**Comment by Im-Mr-Chris** [comment]
> >and that wallet automatically receives said payment?
> 
> 
> 
> Yeah this is the tricky part, @Im-Mr-Chris is right.  If all you have is a link, there's no way to cryptographically commit the funds you want to send to the other party (since they haven't used any program to generate something you could use for that) without an unacceptable level of trust.  And if just *knowledge* of the link gives you access to the funds, then it's very very risky to copy paste the link around since *anything* that can access your clipboard could steal the funds (not just other programs on your PC, but all your browser extensions, and the (untrusted!) js on any page you happen to open between copying the link and pasting it into your browser).  There's a few tricks you might be able to do like *also* requiring also giving a sufficiently long password, but that's still easy for sniffers to detect and makes it less seamless.

That shouldn't be too hard to re with hash-cat. 

I'm pretty interested in what Charles and Vitalic provided us with. That article was far more than elaborate and Charles literally did our homework for us. 

It's decentralized, it's not sponsored, it's  so much valuable information that would have taken us years to figure out. 

I'm not a blockchain developer or anything of that sort btw. Just trying to put ideas together for mental image.

**Comment by LarryLeonidas** [comment]
I don't think Metamask does this.

Haven't heard of anything like this and it's an interesting idea. To your point, sending a link that downloads a preconfig wallet and auto-receives, the simplest route might be a web/hot wallet, maybe a Cloud Multidoge, that only provisions and notifies, keys are not stored. Stepping through this, if Receiver is a first time Doge user and Sender existing:

1. Sender - Goes to cloud Multidoge and enters Receiver email/phone, link is sent
2. Receiver - Gets email/text and opens link to Cloud Multidoge
3. Receiver - Does quick MFA check
4. Receiver - ECDSA key pair generated and downloaded (wallet)
5. Receiver - Secures private key
6. Receiver - Cloud Multidoge auto-sends to email/text sender "ready to receive w/address" 
7. Sender - Sends amount to new address
8. Cloud Multidoge scans network and confirms via email/text when block is written

I'd think anything beyond this would be going towards something akin to Lightning network, might have holding wallets etc. Also, 2 and 6 are likely a big attack vector, would need tight security. Overall, I think the Multidoge property has a lot of potential.

**Comment by aiontrust** [comment]
No one needs to reinvent Metamask, but maybe you do. How about a Metadoge?

I've been working on an app that I thjink maybe useful her. I'm not a developer so you can laugh if you must, lol. I've been working in C# and Visual Studio and so far I've taught myself quite a bit. My limited experience and knowledge in this field force me to keep trying to learn new things to make the app do what I need. But there is still a lot that I don't know and it would take me years to catch up. Here's the project: https://github.com/aiontrust/cointips

It's a QR cold wallet scanner app. It would work just as Trust Wallet or SafePal but very minimal - single screen, no exchanges, no DApps, no confusion. I wanted to make this as a way to be able to tip people in crypto, specifically my own token. Whether they had an existing wallet or little to no knowledge of crypto, they would have access through this. 

- DogeTips, dogebucks, or any physical storage of the asset would make it real for people. No link or any need for computer. With a paper not, they would at least know they have something to look forward to. 

When they scan the code it would either direct them to the app or app store to download. In the app they would see how much $DOGE was on the paper. Think of all the people sharing physical $DOGE that they loaded into the paper wallet themselves. Major stocking stuffer! 

The app would only be temporary but it would hold the currency for as long as they needed. No rush or pressure to do any additional step. My question here is... does it a key? I don't see everyone rushing to learn about seedphrases though we all might have several. If they do get, or have, a wallet already then they can move their coins whenever they're ready. 

What am  I missing?  Hmmm.. Idk. Please keep in mind that I intended this for a multilevel project I'm working on for my company but I think it applies.  It works perfect for DOGE.  I think someone on twitter recently mentioned how dogecoin was perfect for tipping. If anyone wants to help me develop the app, I would appreciate  very much! Also, it would work perfect as a DApp if we could get a  Doge Smart Contract! https://github.com/aiontrust/cointips

**Comment by AbcSxyZ** [comment]
Hi @aiontrust, a tipping bot would be an interesting development, huge potential !
Actually, it's not the most appropriate place to speak about it, this repo is related to the Dogecoin Core, the software who let a node of the network running and implement the Dogecoin protocol (derivate from [Bitcoin protocol](https://en.bitcoin.it/wiki/Protocol_documentation)). Your app is build on top of it, your situation is not related to his source code 😉.

You're in the ideation step, I do not know any existing projects or discussions about the topics to redirect you, but some relative ideas evolves probably not so far.
You should take a look at the [Discord](https://discord.gg/dogecoin), possibly in the #-dev channel, it would be a more appropriate place to discuss the topic !

> does [the app] need a key?

Do you mean the private key ? Your app will need to manage the user private key, it's a necessity to sign transaction and to send money. But you don't necessary have to generate yourself the key, you can just import an existing one.
But you are not working with cold wallet anymore :) A better understanding of the technology will help you to imagine a more awesome app ! If you want a useful resource, take a look at *[Mastering Bitcoin](https://github.com/bitcoinbook/bitcoinbook)*.

**Comment by ReverseControl** [comment]
@Drael64 @AbcSxyZ @aiontrust @Im-Mr-Chris @LarryLeonidas This is a topic that merits discussion, thought and time. Please move it to the discussion section (https://github.com/dogecoin/dogecoin/discussions) so you may hash out your ideas there. The Issue section is for more actionable items.
