### ISSUE TITLE
[feat] Continue MultiDoge development or develop its alternative

### ISSUE THREAD

**Issue by TngSam** [dogecoin/dogecoin#2220]
# Feature Request

Hey there! Sorry if I post it in the wrong repo, but MultiDoge repo is abandoned. I downloaded MultiDoge for OS X but when I opened it - it crashed (Mac M1). Seems like this project was abandoned. I wanted to download Dogecoin Core then, but I can't afford 56 GB of my SSD for blockchain storage.

I'm wondering, it would be cool if I will be able to create my DOGE wallet without need of syncing with blockchain (like lightweight wallet).

Or maybe anyone can advice me any other trusted DOGE wallet? Thank you in advance.

By the way, I can help with macOS and iOS development using Swift. DOGE to the moon 🚀

**Comment by DemonRx** [comment]
@TngSam https://my.dogechain.info/#/overview

**Comment by TngSam** [comment]
> @TngSam https://my.dogechain.info/#/overview

Thank you!
