### ISSUE TITLE
Decide on alert support for 1.21

### ISSUE THREAD

**Issue by rnicoll** [dogecoin/dogecoin#2231]
Bitcoin Core removed the legacy alert system prior to Bitcoin Core 0.14, and for Dogecoin Core 1.14 we re-introduced the alerts ourselves. We need to decide if we want alerts in Dogecoin Core 1.21, and if so commit 41c868f47e671dc5009cd47496c39c13ae36306b will need to be adapted to 1.21. If not, we can remove the note in `src/net_process.cpp` around line 2469.

**Comment by patricklodder** [comment]
I'm a fan of with leaving it out as it has not been used in almost 7 years. Reduces (optics of) centralization too.
