### ISSUE TITLE
[feat] Sort Nodes by Data Sent or Received and or by Upload/Download speed

### ISSUE THREAD

**Issue by Jamesedward11** [dogecoin/dogecoin#2240]
# Feature Request

**Describe the Feature Request**
In U torrent, or, technically Nano-torrent. When downloading the files of a torrent, you can sort the other people who are Seeding/Leeching on the file by categories, such as Client, IP (not sure how though), Uploaded Data, Downloaded Data, Upload Speed, Download Speed, Flags, and how much of the file they have. half of these thing's are unnecessary, but I tend to like having additional info on which client is leaching or Seeding hardest.

Basically what I'm asking for is the ability to sort Clients in the debug menu by Data Sent/Received or Data Sent/Received in set time.

**Describe Preferred Solution**
The addition of Extra categories that sit next to the ping of the client that simply reads the sent data, and received data sent from clients.

**Describe Alternatives**
a decent alternative would to be to show a Real time graph of the clients connected in either Red or Green (correlating to the data graph) on the network traffic screen. The more a user downloads, the more red they are, the more a user uploads, the more green they are.

**Comment by chromatic** [comment]
I'll look into this.

**Comment by patricklodder** [comment]
Merged into 1.14.4-dev with #2243
