### ISSUE TITLE
Skip getauxblock tests when wallet disabled

### ISSUE THREAD

**Issue by rnicoll** [dogecoin/dogecoin#2246]
The Xenial no-wallet runs fail in Travis because `getauxblock` is only present if the wallet is present, but the `auxpow_mining.py` tests run anyway. See:

https://travis-ci.com/github/dogecoin/dogecoin/jobs/511041147

Recommendation:

Introduce the test skip logic from https://github.com/namecoin/namecoin-core/blob/master/test/functional/auxpow_mining.py#L31

**Comment by DickyMardhany** [comment]
Oke sir

**Comment by mmicael1** [comment]
@rnicoll https://github.com/mmicael1/dogecoin/pull/1/commits/7f359b483d5fd73e26fdb17359cbdd2a56f10d2e

**Comment by mmicael1** [comment]
@rnicoll Now the tests are passing
https://github.com/mmicael1/dogecoin/commit/1199561d3471922338f709d6db6ac6d89f7d871f

**Comment by rnicoll** [comment]
Confirmed working with that commit cherry-picked, thanks! https://travis-ci.com/github/dogecoin/dogecoin/jobs/511279093
