### ISSUE TITLE
[bug] Potential security issue with the released binaries

### ISSUE THREAD

**Issue by FSys77** [dogecoin/dogecoin#2263]
I just noticed that the file sizes of the executables differ, depending where they are from. For example:

dogecoin-qt.exe:

When taken from the installer (dogecoin-1.14.3-win64-setup-unsigned.exe) the file size is:
33.735.184 bytes

When taken from the zip file (dogecoin-1.14.3-win64.zip) the file size is:
33.735.711 bytes

Same for all the other executables, they all slightly differ.

I checked with older releases, for example 1.10.0, and there the file sizes of the extracted executables are exactly the same in the setup.exe and the .zip version.

Is there something fishy going on recently?

**Comment by maxware66** [comment]
Hi,
i’ve downloaded the binary for MacOS and it has been detected the malware CoinMiner.... Is it normal ?

**Comment by patricklodder** [comment]
> i’ve downloaded the binary for MacOS and it has been detected the malware CoinMiner.... Is it normal ?

This is caused by malware packaging mining software rather than our mining software packaging malware, so we get flagged as a false positive. What anti malware software reports this?

**Comment by maxware66** [comment]
> > i’ve downloaded the binary for MacOS and it has been detected the malware CoinMiner.... Is it normal ?
> 
> This is caused by malware packaging mining software rather than our mining software packaging malware, so we get flagged as a false positive. What anti malware software reports this?

CleanMyMac

**Comment by patricklodder** [comment]
> CleanMyMac

You'll want to contact the authors of that software and file a false positive with them. I tried searching for a standardized way to that that with them but have had no luck with that so far - maybe there is some more detailed contact information inside the app?

**Comment by maxware66** [comment]
Yes maybe, i'll try to find it

Il 07/06/21 00:04, Patrick Lodder ha scritto:

**Comment by ReverseControl** [comment]
@maxware66 What is the status on this? I sent them a tweet.  https://twitter.com/LionesEscanor/status/1427947714591997954?s=20

**Comment by slightlyskepticalpotat** [comment]
After I stripped off the debug symbols from both of the executables, they are both 33,735,184 bytes large and bit-for-bit identical. Nothing malicious is happening here.

**Comment by ReverseControl** [comment]
@FSys77 As @slightlyskepticalpotat confirmed what is going on here. I will close this issue.
