### ISSUE TITLE
[vulnerability] A newly appended block header should not build on an invalid chain

### ISSUE THREAD

**Issue by yixiao5428** [dogecoin/dogecoin#2280]
Currently, a new header descendant from an invalid block is still accepted.

A possible solution is to get the ancestor of the block, check the validity of the block indexes, and return error is failed, in the `AcceptBlockHeader()` function of `src/validation.cpp` after [line 3171](https://github.com/dogecoin/dogecoin/blob/master/src/validation.cpp#L3171).

Similar fix from Bitcoin: https://github.com/bitcoin/bitcoin/commit/015a5258adffb0cf394f387a95ac9c8afc34cfc3.

Reported by `6004ed5feaa31ae9df36b5dbc60f0fa53255a5fb734334082c6d202405fc738c`.

**Comment by ReverseControl** [comment]
@rnicoll  @patricklodder  Given we took care of this in #2297 we can close this one and remove it from the 1.14.4 board. Thanks.

**Comment by ReverseControl** [comment]
@patricklodder Close this one.
