### ISSUE TITLE
[vulnerability] Do not connect a corrupted block

### ISSUE THREAD

**Issue by yixiao5428** [dogecoin/dogecoin#2281]
In the `ConnectBlock()` function of `src/validation.cpp`, it misses the check for whether the block is corrupted or not. If the block is corrupted, it should be abort immediately, otherwise it will repeat trying to connect the corrupted block.

A possible solution is to add a corruption check inner the `if` statement of [line 1771](https://github.com/dogecoin/dogecoin/blob/master/src/validation.cpp#L1771) in `src/validation.cpp`.

Similar fix from Bitcoin: https://github.com/bitcoin/bitcoin/commit/0e7c52dc6cbb8fd881a0dd57a6167a812fe71dc4.

Reported by `6004ed5feaa31ae9df36b5dbc60f0fa53255a5fb734334082c6d202405fc738c`.

**Comment by ReverseControl** [comment]
@patricklodder  Per #2286 , ca we please close this and remove it from the 1.14.4 release queue?

**Comment by patricklodder** [comment]
The "vulnerability" still exists, so I don't think it's wise to close this. I've removed the PR and this issue from the 1.14.4 project board - should still get fixed though.

**Comment by patricklodder** [comment]
Fixed with #2286
