### ISSUE TITLE
[vulnerability] Disconnect stalling peers after timeout of header sync

### ISSUE THREAD

**Issue by yixiao5428** [dogecoin/dogecoin#2282]
Though we have a detection for block download stalling in `SendMessages()` of `src/net_processing.cpp` at [line 3201](https://github.com/dogecoin/dogecoin/blob/master/src/net_processing.cpp#L3201), the timeout for header sync remain unchecked.

This check should be also added to the `SendMessages()` function, and disconnect the stalling peer after timeout.

Similar fix from Bitcoin: https://github.com/bitcoin/bitcoin/commit/76f74811c44b5119d5c19364b0594d423248ac0e.

Reported by `6004ed5feaa31ae9df36b5dbc60f0fa53255a5fb734334082c6d202405fc738c`.

**Comment by micaelmalta** [comment]
@patricklodder can we close this issue as it s merged?

**Comment by ReverseControl** [comment]
@patricklodder @rnicoll @michilumin We can close this one.

**Comment by patricklodder** [comment]
Fixed with #2306
