### ISSUE TITLE
[feat] Tutorial/Hints/Tips and Tricks Section/Window/Popup

### ISSUE THREAD

**Issue by DimiFW** [dogecoin/dogecoin#2293]
Hello shiberinos and deverinos, I recently had the idea that maybe Dogecoin Core could include some kind of useful hints, tips and tricks section for the Wallet. I had the idea to do this as a popup with a "don't show this again" checkmark or including it into the loading screen like video games do, but after looking at the wallet I actually found the perfect spot.

![image](https://user-images.githubusercontent.com/8593098/121545515-e4150a80-ca0a-11eb-9077-d87d9f8dc188.png)
(Really ugly concept art, obviously you could make it look way nicer)

You could implement it in the lower right corner and either make it switch the tip on every start up or make it switch through all the tips in a certain interval like every (few) minute(s) or so. Or have a small arrow left and right to switch through it. Can even still have a "hide this" checkmark box in the corner to hide it.

These tips could be everything from "Never share your wallet.dat file/your private key with anyone" or "Make sure to always update to the newest version" or "Backup your wallet.dat/private key to prevent losing your coins" or "Make sure to follow Ross on Twitch" or whatever you can come up with, there are many possible things you could add here. Even small "tutorials" how to actually backup your stuff could fit into there.

This will certainly still not prevent everyone from losing their coins, but I think it can help at least some to remind them to better watch out over their stuff.

Maybe some of you have an even better idea how to properly implement something like that without making it too obnoxious, feel free to discuss :)

**Comment by AbcSxyZ** [comment]
It would be really nice to have some explanation for people about how to use Dogecoin in overall !
Educate people about private/public key, about safety measure. I think there is also some information to give about different kind of wallets, Dogecoin Core is one of them, but you have the lightweight wallet vs full nodes, custodial vs non custodial, cold vs hot, etc.

Different type of information would be important to give to manage well Dogecoin. It can be interesting to have it in the dogecoin core, but it could really have different form, and coming from multiple places.
In a way, a lot of dogecoin users don't use the dogecoin core wallet, I don't think it would be the most appropriate place.

Actually, some documentations work have to be done, I suggested a [Docs4Doge](https://github.com/dogecoin/dogecoin/issues/2271) initiative to rebuild it for developer & contributors.
I'm speaking briefly about doing a **user guide** to give this kind of information, it would be really a great stuff to do !
In my mind, [dogecoin.com](https://dogecoin.com/) seem to be a good place, but it's just a personal opinion :)

I'm agree with the idea of doing some tutorial/hints/tips :rocket:

**Comment by alamshafil** [comment]
I like this idea! I can help out creating this in a pull request if the devs agree to add it.

**Comment by pennyfea** [comment]
Is this issue closed are there any more feature requests?

**Comment by ReverseControl** [comment]
@patricklodder Close this issue.

**Comment by patricklodder** [comment]
Implemented with #2308, released with 1.14.4!
