### ISSUE TITLE
Relevance of qt4 dependency for build instructions

### ISSUE THREAD

**Issue by AbcSxyZ** [dogecoin/dogecoin#2316]
I was reading the installation instructions and thinking about how to simplify it.

Different information within the docs are old, and I'm not able to find the current state of qt4/qt5 support, but qt4 seem dying.

**Releases dates:**
`qt5` : 19 December 2012
`qt4` : 28 June 2005

Wouldn't it be better to keep only `qt5` as recommended dependency, removing `qt4` references ?
To reduce doc content & the mixing of version information. I don't know if it impacts the code, if legacy code have to be removed.

**Comment by fmhc** [comment]
+1, i have looked at Qt development a bit this week, Qt6 is the newest and they changed some license politics I guess; did not look into that deeper. But Qt5 seems to be open source for the parts we need and it gets updates... There were issues with Qt5, see https://github.com/dogecoin/dogecoin/issues/2338 - i made a PR to upgrade from 5.7 to the newest 5.15

**Comment by patricklodder** [comment]
"Formally" we have supported qt4 with 1.14 before (for self-compile, docs / best effort compat only), so I would support dropping this with 1.21 if we do not inherit a support drop from Bitcoin. 

@fmhc Thanks for the QT5 PR!

**Comment by ReverseControl** [comment]
@patricklodder What is the status of this?

**Comment by AbcSxyZ** [comment]
Closing in favor of https://github.com/dogecoin/dogecoin/pull/2339
