### ISSUE TITLE
[Enhancement] Percentage/ETA in Progress Bar

### ISSUE THREAD

**Issue by alexleeelkins** [dogecoin/dogecoin#233]
Hello, can I please suggest putting a percentage indicator as well as an estimated time remaining countdown in the progress bar rather than just "...weeks behind"?

This would help to find out what time operations would ACTUALLY take and I believe would make newcomers a little less overwhelmed with new things.

**Comment by just-an-dev** [comment]
this will be add in 1.14 :)
