### ISSUE TITLE
[bug] berkeleydb 5.1 - package has no installation candidate

### ISSUE THREAD

**Issue by sabotagebeats** [dogecoin/dogecoin#2351]
# Bug Report

**Current behavior:**
```
$ sudo apt-get install libdb5.1-dev libdb5.1++-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libdb5.1++-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package libdb5.1-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libdb5.1-dev' has no installation candidate
E: Package 'libdb5.1++-dev' has no installation candidate
```

**Expected behavior**
successful installation

**Steps to reproduce:**
on Ubuntu 20.04LTS on WSL2 windows 10:
```
sudo apt-get install libdb5.1-dev libdb5.1++-dev
```

**Screenshots**
N/A

**Dogecoin Core version**
1.14.4-dev

**Machine specs**
- OS: Windows 10 WSL2 Ubuntu 20.04LTS

**Extra information**
fixed by using instructions here: 
https://www.reddit.com/r/dogecoindev/comments/n40avq/cant_install_berkelydb_51_during_set_up_of_dev/
for development I used 
```
sudo apt-get install libdb5.3-dev libdb5.3++-dev
./configure --with-incompatible-bdb
```
however it is recommended to build it yourself
https://github.com/dogecoin/dogecoin/blob/master/doc/build-unix.md#berkeley-db

**Comment by sabotagebeats** [comment]
This issue is to help anyone who gets stuck on that in the future. Closing.

**Comment by fmhc** [comment]
another hint here: https://gist.github.com/tpmccallum/0d5974bfbae03f6cd0b4a107c4f454f8 this shows how to get rid of the issue you will face when trying to compile the libdb5.1-dev ;)
