### ISSUE TITLE
DOGE marketplace

### ISSUE THREAD

**Issue by whowantstobeadogenaire** [dogecoin/dogecoin#2354]
What if we create an online marketplace wherein people can buy and sell used products in exchange for DOGE? An interface similar to Facebook marketplace or other consumer to consumer sales applications might be viable. Just an idea I had and felt could help generate significant value for the coin. Please share your thoughts

**Comment by patricklodder** [comment]
Great idea! See https://suchlist.com

Closing this - these discussions are better had at https://www.reddit.com/r/dogecoindev/
