### ISSUE TITLE
Docker node setup

### ISSUE THREAD

**Issue by Rasika9596** [dogecoin/dogecoin#2366]
I've set up the dogecoin docker node using https://github.com/getdelta/doge-docker. The container is running but I'm not able to find the volume mapping. Can anyone please help me where the data will be dumped which I can map with the volume? Or docker run command with required ports and volume mapping? 

Is there any official docker hub available that will be updated with the latest releases?

**Comment by AbcSxyZ** [comment]
Your issue is unclear for me, if you want to share a volume with your host, you will have to specify it when you run a docker command. If you don't do it manually, you won't have any volume mapped : https://docs.docker.com/storage/volumes/

By default, `datadir` location is under `$HOME/.dogecoin`, and you can change it using `-datadir` option. It will depend on which user they choose. If I'm not wrong they didn't create any user, so it's launched under root, datadir should be inside `/root/.dogecoin` directory.

About "official" docker image, see my answer to your other issue : https://github.com/dogecoin/dogecoin/issues/2367#issuecomment-874234821

**Comment by Rasika9596** [comment]
Yes, I want to map the volume, and that I'll specify with the docker run command. But I'm not sure which location I can map with the volume. 
So, the blockchain data will be stored in /root/.dogecoin/data folder which I can map? But I'm not able to see such a folder yet. Could you please confirm from the below screenshot?

![image](https://user-images.githubusercontent.com/61308915/124718670-f4de7080-df23-11eb-8ba0-3f9c7990e8a8.png)

**Comment by AbcSxyZ** [comment]
You should play with docker to understand how volume works :)

In my PR I have a command like that : 
```
sudo docker run -v  $(pwd)/data:/dogecoin/.dogecoin
```
You will need something like that :
```
sudo docker run -v /path/in/your/host:/path/in/your/container docker_image
```

>  But I'm not able to see such a folder yet. 

You're experiencing issue with a [hidden folder](https://devconnected.com/how-to-show-hidden-files-on-linux/), that's why you don't find it :)
`ls -a` will display `.dogecoin` folder.

**Comment by Rasika9596** [comment]
Thank you, this will help!

**Comment by ryihan** [comment]
> Yes, I want to map the volume, and that I'll specify with the docker run command. But I'm not sure which location I can map with the volume. 
> So, the blockchain data will be stored in /root/.dogecoin/data folder which I can map? But I'm not able to see such a folder yet. Could you please confirm from the below screenshot?
> 
> ![image](https://user-images.githubusercontent.com/61308915/124718670-f4de7080-df23-11eb-8ba0-3f9c7990e8a8.png)
> 

This command run powershall for better performance.

**Comment by Rasika9596** [comment]
Hello,

I tried node setup using [https://github.com/getdelta/doge-docker](url) and Dockerfile given here [https://github.com/dogecoin/dogecoin/pull/2337/files](url) which is not merged yet but that's fine.
And I'm able to build the image and ran using sudo docker run -d -p 22555:22555 -p 22556:22556 -e RPCUSER=test -e RPCPASSWORD=123456 -v $(pwd)/data:/dogecoin/.dogecoin dogenode
But for both, the node is not syncing. Can anyone please confirm that is because of the ports issue from the below screenshot of logs or anything else?

<img width="960" alt="1" src="https://user-images.githubusercontent.com/61308915/124914197-b2915e00-e00d-11eb-8114-6301c6abc9c3.PNG">
<img width="960" alt="2" src="https://user-images.githubusercontent.com/61308915/124914213-b6bd7b80-e00d-11eb-8772-eb83b7b6d4b2.PNG">

**Comment by bblackbeard** [comment]
Your logs show binding failed.
Try specifying BOTH rpcbind and rpcallowip to localhost
rpcbind = 127.0.0.1
rpcallowip = 127.0.0.1

**Comment by Rasika9596** [comment]
Thanks. But after doing this also the same logs.

I tried below both,
sudo docker run -d -p 22555:22555 -p 22556:22556 -e RPCUSER=test -e RPCPASSWORD=123456 -e RPCBIND=127.0.0.1 -e RPCALLOWIP=127.0.0.1 -v $(pwd)/data:/dogecoin/.dogecoin dogenode-from-dockerfile

sudo docker run -d -p 22555:22555 -p 22556:22556 -e RPCUSER=test -e RPCPASSWORD=123456 -e RPCALLOWIP=0.0.0.0/0 -v $(pwd)/data:/dogecoin/.dogecoin dogenode-from-dockerfile

**Comment by AbcSxyZ** [comment]
Your logs are ending after `dnsseed thread exit` ? It's freezing or exiting ?
Tried your commands, do not experience issue.

```
2021-07-09 09:57:24 50 addresses found from DNS seeds
2021-07-09 09:57:24 dnsseed thread exit
2021-07-09 09:57:25 receive version message: /Shibetoshi:1.14.3/: version 70015, blocks=3805029, us=86.220.51.113:38856, peer=0
2021-07-09 09:57:25 receive version message: /Shibetoshi:1.21.0/: version 70016, blocks=3805029, us=86.220.51.113:54152, peer=1
2021-07-09 09:57:27 receive version message: /Shibetoshi:1.14.3/: version 70015, blocks=3805029, us=86.220.51.113:38056, peer=2
2021-07-09 09:57:28 Pre-allocating up to position 0x100000 in rev00000.dat
2021-07-09 09:57:28 UpdateTip: new best=82bc68038f6034c0596b6e313729793a887fded6e92a31fbdf70863f89d9bea2 height=1 version=0x00000001 log2_work=21.000022 tx=2 date='2013-12-08 03:55:27' progress=0.000000 cache=0.0MiB(1tx)
2021-07-09 09:57:28 UpdateTip: new best=ea5380659e02a68c073369e502125c634b2fb0aaf351b9360c673368c4f20c96 height=2 version=0x00000001 log2_work=21.584985 tx=3 date='2013-12-08 03:55:33' progress=0.000000 cache=0.0MiB(2tx)
2021-07-09 09:57:28 UpdateTip: new best=76f80a8a81e6f6669d340651723b874f97395c4dbda200f8b024df4c6566a92c height=3 version=0x00000001 log2_work=22.000022 tx=4 date='2013-12-08 03:55:40' progress=0.000000 cache=0.0MiB(3tx)
2021-07-09 09:57:28 UpdateTip: new best=df363f95151d8c38b1cf0ee8375d571c9a869d9e37489ba058982ace19bcdee4 height=4 version=0x00000001 log2_work=22.32195 tx=5 date='2013-12-08 03:55:43' progress=0.000000 cache=0.0MiB(4tx)
2021-07-09 09:57:28 UpdateTip: new best=f21dc70cb44c180261e31a222202678602d605e7697332cb2395386fa309ad3b height=5 version=0x00000001 log2_work=22.584985 tx=6 date='2013-12-08 03:55:49' progress=0.000000 cache=0.0MiB(5tx)
2021-07-09 09:57:28 UpdateTip: new best=f34986a114a2f58f48ce5593e5e6006666243fb003a2ffa489d980d8de825428 height=6 version=0x00000001 log2_work=22.807377 tx=7 date='2013-12-08 03:55:52' progress=0.000000 cache=0.0MiB(6tx)
2021-07-09 09:57:28 UpdateTip: new best=3ca7e813da5c72b0817c4d4789cd4896f49baf5e40f67a59a63a63ea2498d604 height=7 version=0x00000001 log2_work=23.000022 tx=8 date='2013-12-08 03:55:57' progress=0.000000 cache=0.0MiB(7tx)
2021-07-09 09:57:28 UpdateTip: new best=ed6b216e69b57915eda3a43036016c5667b35d61606f1c61ba10fb17c0e7a063 height=8 version=0x00000001 log2_work=23.169947 tx=9 date='2013-12-08 03:56:07' progress=0.000000 cache=0.0MiB(8tx)
[...]
```

**Comment by Rasika9596** [comment]
Yes, `dnsseed thread exit` is the last log I can see.

If you're not experiencing then maybe this is with ports issue for me or what?
Anyhow, I've raised a ticket to our firewall team for the 22555 and 22556 ports, once this is done will give it a try again.

Meanwhile, if you feel this is a different issue please let me know.

**Comment by AbcSxyZ** [comment]
Maybe your environment, if you're in a "complex" one. As mentioned by @bblackbeard, your binding failed, you've those lines in your logs :
```
libevent: getaddrinfo: address family for nodename not supported
Binding RPC on address ::1 port 22555 failed.
```

But your binding on 22556 seem to work :
```
Bound to [::]:22556
Bound to 0.0.0.0:22556
```

**Comment by Rasika9596** [comment]
Yes, I also checked it. But after trying @bblackbeard suggestion also it didn't work. 
For now, waiting on the firewall ticket to get the ports open, will get back with the output after that. Thank You!

**Comment by xanimo** [comment]
> Yes, I also checked it. But after trying @bblackbeard suggestion also it didn't work.
> For now, waiting on the firewall ticket to get the ports open, will get back with the output after that. Thank You!

are you still experiencing difficulties with this?

**Comment by Rasika9596** [comment]
Hello,

Node started syncing after opening both of the ports and it reached 3847136 blocks but after that, it stopped syncing. 
Can anyone please help me with the below logs what could be a problem?

```
dogecoin_container | 2021-08-19 06:10:20 Dogecoin version v1.14.3
dogecoin_container | 2021-08-19 06:10:20 InitParameterInteraction: parameter interaction: -blocksonly=1 -> setting -whitelistrelay=0
dogecoin_container | 2021-08-19 06:10:20 Assuming ancestors of block 77e3f4a4bcb4a2c15e8015525e3d15b466f6c022f6ca82698f329edef7d9777e have valid signatures.
dogecoin_container | 2021-08-19 06:10:20 ParameterInteraction: parameter interaction: -blocksonly=1 -> setting -walletbroadcast=0
dogecoin_container | 2021-08-19 06:10:20 Default data directory /dogecoin/.dogecoin
dogecoin_container | 2021-08-19 06:10:20 Using data directory /dogecoin/.dogecoin
dogecoin_container | 2021-08-19 06:10:20 Using config file /dogecoin/.dogecoin/dogecoin.conf
dogecoin_container | 2021-08-19 06:10:20 Using at most 125 automatic connections (1048576 file descriptors available)
dogecoin_container | 2021-08-19 06:10:20 Using 32 MiB out of 32 requested for signature cache, able to store 1048576 elements
dogecoin_container | 2021-08-19 06:10:20 Using 4 threads for script verification
dogecoin_container | 2021-08-19 06:10:20 scheduler thread start
dogecoin_container | 2021-08-19 06:10:20 HTTP: creating work queue of depth 16
dogecoin_container | 2021-08-19 06:10:20 Config options rpcuser and rpcpassword will soon be deprecated. Locally-run instances may remove rpcuser to use cookie-based auth, or may be replaced with rpcauth. Please see share/rpcuser for rpcauth auth generation.
dogecoin_container | 2021-08-19 06:10:20 HTTP: starting 128 worker threads
dogecoin_container | 2021-08-19 06:10:20 Using BerkeleyDB version Berkeley DB 5.1.29: (October 25, 2011)
dogecoin_container | 2021-08-19 06:10:20 Using wallet wallet.dat
dogecoin_container | 2021-08-19 06:10:20 init message: Verifying wallet...
dogecoin_container | 2021-08-19 06:10:20 CDBEnv::Open: LogDir=/dogecoin/.dogecoin/database ErrorFile=/dogecoin/.dogecoin/db.log
dogecoin_container | 2021-08-19 06:10:20 Bound to [::]:22556
dogecoin_container | 2021-08-19 06:10:20 Bound to 0.0.0.0:22556
dogecoin_container | 2021-08-19 06:10:20 Cache configuration:
dogecoin_container | 2021-08-19 06:10:20 * Using 128.0MiB for block index database
dogecoin_container | 2021-08-19 06:10:20 * Using 8.0MiB for chain state database
dogecoin_container | 2021-08-19 06:10:20 * Using 888.0MiB for in-memory UTXO set (plus up to 286.1MiB of unused mempool space)
dogecoin_container | 2021-08-19 06:10:20 init message: Loading block index...
dogecoin_container | 2021-08-19 06:10:20 Opening LevelDB in /dogecoin/.dogecoin/blocks/index
dogecoin_container | 2021-08-19 06:10:20 Opened LevelDB successfully
dogecoin_container | 2021-08-19 06:10:20 Using obfuscation key for /dogecoin/.dogecoin/blocks/index: 0000000000000000
dogecoin_container | 2021-08-19 06:10:20 Opening LevelDB in /dogecoin/.dogecoin/chainstate
dogecoin_container | 2021-08-19 06:10:20 Opened LevelDB successfully
dogecoin_container | 2021-08-19 06:10:20 Using obfuscation key for /dogecoin/.dogecoin/chainstate: dca79ffc1e1e8d9f
dogecoin_container | 2021-08-19 06:10:50 LoadBlockIndexDB: last block file = 334
dogecoin_container | 2021-08-19 06:10:50 LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=12291, size=97599687, heights=3834854...3847136, time=2021-07-31...2021-08-09)
dogecoin_container | 2021-08-19 06:10:50 Checking all blk files are present...
dogecoin_container | 2021-08-19 06:10:50 LoadBlockIndexDB: transaction index enabled
dogecoin_container | 2021-08-19 06:10:51 LoadBlockIndexDB: hashBestChain=106df30243d339185ad8ad43598185ec2bd6e25e2e45887b5391d2d8993aa13e height=3847136 date=2021-08-09 06:38:45 progress=0.994907
dogecoin_container | 2021-08-19 06:10:51 init message: Rewinding blocks...
dogecoin_container | 2021-08-19 06:11:02 init message: Verifying blocks...
dogecoin_container | 2021-08-19 06:11:02 Verifying last 6 blocks at level 3
dogecoin_container | 2021-08-19 06:11:02 [0%]...[16%]...[33%]...[50%]...[66%]...[83%]...[99%]...[DONE].
dogecoin_container | 2021-08-19 06:11:03 No coin database inconsistencies in last 7 blocks (198 transactions)
dogecoin_container | 2021-08-19 06:11:03  block index           42586ms
dogecoin_container | 2021-08-19 06:11:03 CTxMemPool::ReadFeeEstimates(): unable to read policy estimator data (non-fatal)
dogecoin_container | 2021-08-19 06:11:03 init message: Loading wallet...
dogecoin_container | 2021-08-19 06:11:03 nFileVersion = 1140300
dogecoin_container | 2021-08-19 06:11:03 Keys: 102 plaintext, 0 encrypted, 102 w/ metadata, 102 total
dogecoin_container | 2021-08-19 06:11:03  wallet                   21ms
dogecoin_container | 2021-08-19 06:11:03 setKeyPool.size() = 100
dogecoin_container | 2021-08-19 06:11:03 mapWallet.size() = 0
dogecoin_container | 2021-08-19 06:11:03 mapAddressBook.size() = 1
dogecoin_container | 2021-08-19 06:11:03 mapBlockIndex.size() = 3847149
dogecoin_container | 2021-08-19 06:11:03 nBestHeight = 3847136
dogecoin_container | 2021-08-19 06:11:03 init message: Loading addresses...
dogecoin_container | 2021-08-19 06:11:03 torcontrol thread start
dogecoin_container | 2021-08-19 06:11:03 Imported mempool transactions from disk: 0 successes, 0 failed, 0 expired
dogecoin_container | 2021-08-19 06:11:03 Loaded 37482 addresses from peers.dat  90ms
dogecoin_container | 2021-08-19 06:11:03 init message: Loading banlist...
dogecoin_container | 2021-08-19 06:11:03 init message: Starting network threads...
dogecoin_container | 2021-08-19 06:11:03 net thread start
dogecoin_container | 2021-08-19 06:11:03 init message: Done loading
dogecoin_container | 2021-08-19 06:11:03 addcon thread start
dogecoin_container | 2021-08-19 06:11:03 opencon thread start
dogecoin_container | 2021-08-19 06:11:03 dnsseed thread start
dogecoin_container | 2021-08-19 06:11:03 msghand thread start
dogecoin_container | 2021-08-19 06:11:14 Loading addresses from DNS seeds (could take a while)
dogecoin_container | 2021-08-19 06:11:15 50 addresses found from DNS seeds
dogecoin_container | 2021-08-19 06:11:15 dnsseed thread exit
```

**Comment by xanimo** [comment]
i can't find anything wrong actually. i think you are good to go!

**Comment by ReverseControl** [comment]
@Rasika9596 was your issue resolved?
