### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by Rasika9596** [dogecoin/dogecoin#2367]
Could you please provide support for the docker image for node setup or by adding docker file to build the image? Or is there anything already available that is official and updated with the latest?

**Comment by AbcSxyZ** [comment]
Hi,
There is actually pull requests to implement Dockerfile. Nothing is "officially" available and work is in progress, take a look at https://github.com/dogecoin/dogecoin/pull/2337.

Feel free to leave comments if you're experiencing any issue, to suggest an improvement, or to simply give feedback :)

**Comment by Rasika9596** [comment]
Oh, that's great! Thanks!

Any rough deadline for this to go live? I'm waiting on this.

**Comment by AbcSxyZ** [comment]
No idea, features are released when they are ready, not on a specific date :wink: 

It's included in 1.14 milestone, perhaps it will be available on the next minor release, will depend on the community.

**Comment by Rasika9596** [comment]
Sure, Thanks!

**Comment by patricklodder** [comment]
See: https://github.com/dogecoin/docker
