### ISSUE TITLE
Methods to generate signed message and verify it

### ISSUE THREAD

**Issue by Rasika9596** [dogecoin/dogecoin#2379]
Hello,

Is there any node independent library/methods available for generating random key pair(private and public key), sign a message with the private key, and verify a message with the public key, original message, and signed message?

I got node-dogecoin but it requires the node to connect with. Is there any other library I can use?

**Comment by patricklodder** [comment]
Assuming you want this in nodejs - same answer as [the last part of this answer](https://github.com/dogecoin/dogecoin/issues/2376#issuecomment-876665283): you can use [bitcoinjs-lib](https://www.npmjs.com/package/bitcoinjs-lib) with [these params](https://github.com/BlockIo/block_io-nodejs/blob/081caf2af1b6d318d490fc73feb66df90e7c7512/data/networks.js#L15-L38)
