### ISSUE TITLE
Add "dogecoin developers" wallet on README.md

### ISSUE THREAD

**Issue by AbcSxyZ** [dogecoin/dogecoin#2384]
I jump on the opportunity of the [previous tweet](https://twitter.com/dogecoin_devs/status/1413610253405589505?s=20) from Dogecoin devs to bring the topic :
![wallet_dogedevs](https://user-images.githubusercontent.com/34010605/125169063-cde4a080-e1a8-11eb-9dc6-8572821750e2.png)

**Would you add the wallet on the README.md ?**  
The following one : AC8Q9Z4i4sXcbW7TV1jqrjG1JEWMdLyzcy

First, I support the idea ! To reward work of developer, to give incentive for the development of new features, whatever. I would love to see people who work on Dogecoin being paid, to let people dedicate their time for the long term survival of Dogecoin.

Would be great to give visibility to this wallet, make it more accessible *(also twitter bio :wink: ?)*. There was a time when people were disappointed that they couldn't give away money :smile: !

But it comes with some question of governance. Would be great to have some explanation about how the fund is working, that's a more delicate part of the transparency !
To let people understand where they send money, which contributor could receive money, when and how it's done, etc.

**Some potential big moves to do for the funding of the Dogecoin software(s), his open source ecosystem !**

Edit : Am I having reading trouble or did you really collect 23 million Dogecoins in 45 minutes ?

**Comment by AdvaitDhingra** [comment]
So one would just add this address under something like "Support the developers"? I'd like to try this issue.

**Comment by AbcSxyZ** [comment]
Adding the wallet to the README is not a big deal.

What is more important from my point of view is to have some explanation about how it's used. They said there is transparency, but transparency is not restricted to showing the amount of money.

Personally, I would never send money to this address and recommend doing it until I do not have any information about who manage the account and the purpose of the collected money.

**Comment by ReverseControl** [comment]
@AbcSxyZ I strongly support your position on this matter. My wallet, for the README as a developer, DNoeNGVT3miw1gk2DpksvDe8W1Ub5bakag.

**Comment by ReverseControl** [comment]
I am closing this issue as it is non-technical in nature and beyond the scope of the Issue section. Feel free to open up a discussion on this topic.
