### ISSUE TITLE
How does Dogecoin relay transaction

### ISSUE THREAD

**Issue by GamingWithFarhan** [dogecoin/dogecoin#2386]
Hello,
This is just a question not a issue or something like that I just need to know this for my knowledge...

I was wondering that, I know that every node on the network has a copy of a Dogecoin blockchain. But how do they update it? Like for example let’s say Dogecoin stored my transactions on my local machine. But how does other nodes get this transaction if it’s not hosted online and only stored locally? I’m searching the internet for abkut 3 days and I didn’t found the answer. The only thing I found was that the blockchain is stored locally. 

And another question is like how are all the address stored? Like what if I sent my amount in a wrong address how will the system know if it’s right or wrong

I hope you guys will answer the answer to the questions for me

**Comment by patricklodder** [comment]
Hi! It works with peer-to-peer relay, see https://en.wikipedia.org/wiki/Bitcoin_network#Process
