### ISSUE TITLE
[feat] Why not restore the number of dogecoin to a limited number?

### ISSUE THREAD

**Issue by liu-xuewen** [dogecoin/dogecoin#2404]
# Feature Request

**Describe the Feature Request**
Why not restore the number of dogecoin to a limited number?

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by AbcSxyZ** [comment]
Take a look at https://github.com/dogecoin/dogecoin/discussions/2402
