### ISSUE TITLE
Why this transaction still unconfirmed ? the satoshi per byte is enough

### ISSUE THREAD

**Issue by deceive3w** [dogecoin/dogecoin#2405]
I found a transaction with a fee in decimal with satoshi per byte is enough. but it does not have a confirmation? why?

https://blockchair.com/dogecoin/transaction/893ef62fe6205f21866216e1bb3bb5a52530c378bd0cf5a51193cb50332a234d

https://blockchair.com/dogecoin/transaction/a0a30b8843d4de417b027c7ea079b78e181d0355b9b067c44030c5e043dd0a46

rounded fee with the same satoshi per byte get confirmed quickly
https://blockchair.com/dogecoin/transaction/ff3a50ccdce6068ac2857f403342671e089ed8e9475930eb470dcdc3f32f72e5

**Comment by AbcSxyZ** [comment]
I guess you should have enough fees, shouldn't be an issue.
I tried to see on dogechain & an other site, they do no show me your transactions...

**Which wallet are you using to send your coins ?** Maybe you can try to cancel it with a double transaction.

**Comment by patricklodder** [comment]
The fee needs to be rounded up for it to be relayed. So at 3,277 bytes, the minimum fee for relay is 4 DOGE right now.

In the [new fee policy proposal](https://github.com/dogecoin/dogecoin/discussions/2347), I wrote the alternative approach of doing away with the rounding, to allow for a more precise fee requirement and kill the skew where smaller transactions pay for larger ones within the 1kb range.

**Comment by deceive3w** [comment]
> The fee needs to be rounded up for it to be relayed. So at 3,277 bytes, the minimum fee for relay is 4 DOGE right now.
> 
> In the [new fee policy proposal](https://github.com/dogecoin/dogecoin/discussions/2347), I wrote the alternative approach of doing away with the rounding, to allow for a more precise fee requirement and kill the skew where smaller transactions pay for larger ones within the 1kb range.

I see thanks, new policy fee is so helpful when we are consolidate unspent transactions it's so expensive now

**Comment by patricklodder** [comment]
> new policy fee is so helpful when we are consolidate unspent transactions it's so expensive now

Do you have more information about your use case for consolidation? Helps me understand the needs better so I can advocate for you :-)

**Comment by deceive3w** [comment]
> > new policy fee is so helpful when we are consolidate unspent transactions it's so expensive now
> 
> Do you have more information about your use case for consolidation? Helps me understand the needs better so I can advocate for you :-)

I'm from exchanger, we have many address, when we send transaction with big amount will have a lot input.
