### ISSUE TITLE
[bug] i cant receive my dogecoins on dogecoin core wallet HELP

### ISSUE THREAD

**Issue by Skorpiozz** [dogecoin/dogecoin#2424]
i have doge coin core wallet what how they recommend it can expand till more than 10gb and downloading etc
i have wallet
i make prasscode and i know it and its working and i change it so its wallet pass or prasscode or key i know it
after i made the prasscode it appear the account with lock and say its encrypted 
i try to transfear my dogcoins i mined already and unmineable is very leged i make alot transaction from it and take no time so my favorit for mining 
anyway on the dogcoin corewallet my wallet appear and alot anothers 
i try to make the unmineable to my wallet on dogecoin core but not success i tried alotathings like use consol to open the lock maybe it close the transaction by the code 
walletpassphrase * my passprass   and time in secounds so i write 99999999
and after i see the lock is opened 
i try to make the trasaction from unmineable and wait nothing recived 
and the coins after one minute from send the coing appear again on my wallet on unmineable and zero on my wallet of dogcoincore
i need solution 
how i can recive it on my dogcoincore 
i know my wallet
same pc
same windows
i know the passphrase and the lable of lock its opened 
whats wrong ??
if unmineable not leged website it will waste my coins but because the tranaction not happened the coins back on 
how to get my coins from unmineable to my dogecoincore wallet 
or is there away to transfear that amount from unmineable to other wallet ? also i read i cant change after mining ...
now my 30 dog coin stuck on unmineable which its very leged website i mined alot coins choba bat dog to other wallets 
but on my dogcoin core wallet the first wallet ever i made i cant recieve thats funny

**Comment by patricklodder** [comment]
is your wallet fully synchronized? You can see this by going to Debug Console, and on the first tab it will tell you how many blocks you have locally.

**Comment by Skorpiozz** [comment]
yes sir the green line what it was toke forever finished and the blocks on my hdd is over 50 gb

**Comment by Skorpiozz** [comment]
3830121 blocks till this minute

**Comment by Skorpiozz** [comment]
dogechain i try to log in and they ask me password i right the passphrase its different from the password 
other way of log in wallet on dogechain.com is private key 
how to get the private key and my info encrypted all filels 0/-*9+dsf+d6g+f6g+s9d+
i think if i disable the encryption i will be able to search the private key
what command de-crypt the dogecoin core from my wallet ?
or just show the private key itself
so i log in the website i never been on website but i belive if i log in the wallet on the site it will be somehow option recive or de recieve ..

**Comment by patricklodder** [comment]
so you have given the mining pool your address from core, it should be picked up. 

Do they give you a transaction id / hash for your withdrawal?

**Comment by Skorpiozz** [comment]
no sir the pool is unmineable they have application small and nice human interference thats how it attracted me to use their pool 
i am exceeds the limit of the withdrow which is 30.94 doge 
the limit is 30 
so i can withdrow . when i click withdrow normally like how i do with the same app other wallets other coins immedietly the number become 0 so it means the coins transfeared 

in theis wallets of dogecoincore never got 1 transaction 

on the pool unmineable after it shows 0 
by one minute with refresh the app or their website the 30.94 appear like no transaction happened ....
i tried them and all unmineable transactions immedietly recived  ( withdrow )
but this dogecoinwallet core is zero and dont accept no transaction ...so wierdo app 
after download 50 gb and loading hours i caand get my coing my much secured wallet every lolz

**Comment by Skorpiozz** [comment]
sadly the pool with no customer support unmineable,com 
but they reliable that much withdrow not successed they return the balance

**Comment by Skorpiozz** [comment]
i wanna recive the coins then transfere them to coin base


if i know the coin base 6 monthes earlier i wont start mining with the dogecoin core wallet shiiiiiiiiiiiiiit

**Comment by Skorpiozz** [comment]
maybe they are 12 usd  but i was cpu mining i got fuckkkked to get those 30 coin . on coin base i have around 500 coin doge 
because i bought some and now i am ethashing with external board 4 gpuz +6 gb videocards
but those 30 coin i was cpu 
they toke monthes of 24/7

**Comment by patricklodder** [comment]
if you check the address that you withdrew to at https://sochain.com/DOGE - do you see the amount?

**Comment by Skorpiozz** [comment]
i should write the wallet in the box ?

**Comment by Skorpiozz** [comment]
i tried the url inclodes the wallet the url of the pool 
was not found 
i tried just the wallet address 
also was not found

**Comment by Skorpiozz** [comment]
https://unmineable.com/coins/DOGE/address/DMVFHcHKqz8CTpqzHtr9SnV9RNYLCecgYG

**Comment by Skorpiozz** [comment]
30 coin hanged on the pool because the wallet dogecoin hardcore is mad lol

**Comment by patricklodder** [comment]
`DMVFHcHKqz8CTpqzHtr9SnV9RNYLCecgYG` is not a valid Dogecoin address.

Which version of Dogecoin Core did you use to generate this?

**Comment by Skorpiozz** [comment]
114 its the first address its automatic genetated for me to recive i got it from dogcoin core ... i used it for mining

**Comment by Skorpiozz** [comment]
8 houra from now i will screen ahoot my dogecoin core with the sevral wallets they generated for me and this wallet was the first they generate and its one of them . thank you pal for being communicative and afford my bad english 😎

**Comment by Skorpiozz** [comment]
![dogecoin core 1 14 3   x46 ](https://user-images.githubusercontent.com/88051370/127361111-faa03422-2cdc-49fb-8079-c427782e38b8.jpg)

**Comment by Skorpiozz** [comment]
i am fucked ...
DMVFHcHKqz8CTpqzHtr9SnV9RNyLCecgYG
DMVFHcHKqz8CTpqzHtr9SnV9RNYLCecgYG

middle Y its y instead ... 
now its not dogecoin core issue 

is there a way to communicate unmineable.com support system ?
explain for them this odd situation .. ?

**Comment by Skorpiozz** [comment]
ok i sent them on support@unmineable.com
explaind everything with pictures and the problem was because manual writing instead of copy paste and the mistake is same letter just upper lower case issue 
if they accept then i got my effort 
if they didnt accept i am not mad at it i carry my own responsibility on my mistakes and i will keep use unmineable because they are trusted other pools  will disappear transaction amound if the awall add wrong and the pool will take it for the owners ............



thank you mr patricklodder you was helpful to open my eye on this tiny mistake 
it was manual writing 4 laptops u know ... 

thank you :)

**Comment by Skorpiozz** [comment]
**nooooooooo waaaaaaaaaaaaay   thats a donation ???? or from the team 
its donation because its not 30.94    :D   
who made this ?? 
maaaaaaaaaaaaaaaaaaaaaaaaaaaaaan   :D
**

![no way  ](https://user-images.githubusercontent.com/88051370/127367019-00b2aaf5-7384-4ca9-adfb-5c7950f1f817.jpg)

**Comment by Skorpiozz** [comment]
Thats whats UP .. 
The first HUNGARIAN shop accept just
DOGE   
thats my ownship store babieeeeeeeh 😎😎

![
![20210729_081403](https://user-images.githubusercontent.com/88051370/127445398-eabc7ff8-02ed-4dc4-bc25-8aa0cb7ac3a8.jpg)
![20210729_081406](https://user-images.githubusercontent.com/88051370/127445428-311dd641-65c5-4815-a8c8-759ca48f24bb.jpg)
Uploading 20210729_081102.jpg…]()

**Comment by Skorpiozz** [comment]
![20210729_081102](https://user-images.githubusercontent.com/88051370/127446147-cc22baea-de2c-4a6b-8cbf-5e614e407985.jpg)
![20210729_081406](https://user-images.githubusercontent.com/88051370/127446167-6b5057a4-9dbf-452e-beb3-cdd5ff95aef0.jpg)
