### ISSUE TITLE
Can't send a test amount of < 100 Doge to check address is correct

### ISSUE THREAD

**Issue by wrapperband** [dogecoin/dogecoin#2445]
I have tried to send 20 and 100 Doge, £3.6 and £18 - with fees of 1 Doge/kb

to   DAo622suZgJf8F2Gm5yYWPvvv55UwN5wng

as test sends, before sending  the main amount. It is fully synced, peered and 500kB/s network.

I abandoned the first one tx as, after hours of messing, it was not in any mem pool explorer, I opened ports, addnode and tried everything I could think of or research.

This is the error message on the transaction :

0/unconfirmed, not in memory pool, abandoned

I abandoned that one and tries the 100 Doge

There seems to be an issue that no transaction with a fee of 1 doge is  allowed on the mem pool, if the amount is less than 100 Doge.

# Bug Report

**Current behavior:**

Status: 0/offline, has not been successfully broadcast yet
Date: 10/08/2021 21:04
To: DAo622suZgJf8F2Gm5yYWPvvv55UwN5wng
Debit: -99.00000000 DOGE
Transaction fee: -1.00000000 DOGE
Net amount: -100.00000000 DOGE
Transaction ID: 58b46087a17cad906aa8e560440ddc648fbf0807fe0886ed1af16f78fdcbdd4e
Transaction total size: 226 bytes
Output index: 0

**Expected behaviour**

I expect the transactions with such a massive fee to get into the mem pool (at least)

I think you are rejecting all transactions less than 100 doge.

**Steps to reproduce:**

send a test amount less than 100 doge

Issue with dust fee system?

This block has a 1 Doge transaction ~5k ????
https://dogeblocks.com/block/93ab175356b1c3902afc6f78914b86ff5a0d6532c605991d0073bc1246c0faef

**Dogecoin Core version**

Dogecoin Core version v1.14.3 (64-bit)

**Machine specs**

Description:    Ubuntu 20.04.2 LTS

- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

**Comment by patricklodder** [comment]
Hi! Do you have the raw transaction preserved?

**Comment by wrapperband** [comment]
01000000018d3811d5c24b18877c7857717021137073d98e74fba08c9d085d71dfdb1023875e0000006b483045022100f06847d409c19d699283de16b52cb93fd2ca0eb16c62c938335876aae5c23dcc02207e8e0b07ed527cae5f4c687f22d9e76dc0e6db8240b71adcff3eb42f144d24c3012102426a9d3d40ccbbfd8267b345b18597486a0041d0a3760814f5b85c1fdb96ccfefeffffff020003164e020000001976a9143e08001dbb1263b4c8081d6e482b78ac344afe3788ac78e34e06000000001976a914afeb2c15b32a75fda24d556d696ec93f86de4f0e88ac38bc3a00

**Comment by patricklodder** [comment]
I see no reason for this tx to not be processed by mempool / relay, so this looks like a networking issue.

If you're using dogecoind, what is the output of `dogecoin-cli getnetworkinfo`?

If you're using dogecoin-qt, go to `help->debug window->"peers" tab` and then does it list any peers? And if yes, what version?

**Comment by wrapperband** [comment]
As I said - I am fully synced and have lots of peers currently ~14 - having addnode(d) as well - mostly 1.14.3

getnetworkinfo
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }

  | { "version": 1140300, "subversion": "/Shibetoshi:1.14.3/", "protocolversion": 70015, "localservices": "0000000000000005", "localrelay": true, "timeoffset": -1, "networkactive": true, "connections": 19, "networks": [ { "name": "ipv4", "limited": false, "reachable": true, "proxy": "", "proxy_randomize_credentials": false }, { "name": "ipv6", "limited": false, "reachable": true, "proxy": "", "proxy_randomize_credentials": false }, { "name": "onion", "limited": true, "reachable": false, "proxy": "", "proxy_randomize_credentials": false } ], "relayfee": 1.00000000, "incrementalfee": 0.00001000, "localaddresses": [ { "address": "85.211.187.108", "port": 22556, "score": 1200 } ], "warnings": "" }

**Comment by wrapperband** [comment]
2021-08-10 20:04:30 AddToWallet 58b46087a17cad906aa8e560440ddc648fbf0807fe0886ed1af16f78fdcbdd4e  new
2021-08-10 20:04:31 CommitTransaction(): Transaction cannot be broadcast immediately, bad-txns-inputs-spent

Could the second one have failed because the first wasn't removed from mempool and I need to run -zapwallettxes and -rescan??

**Comment by patricklodder** [comment]
I just did further research, I missed that that input was already spent:

`872310dbdf715d089d8ca0fb748ed973701321707157787c87184bc2d511388d:94` has been spent in `718d6f3159178a85317350d7d48503d23ff1d5a6f84cbae4a516f645a8eb2f9b` on Nov 25, 2017 - [see for example chain.so](https://chain.so/tx/DOGE/718d6f3159178a85317350d7d48503d23ff1d5a6f84cbae4a516f645a8eb2f9b)

Could the second one have failed because the first wasn't removed from mempool and I need to run -zapwallettxes and -rescan??

you definitely need to `-zapwallettxes` and `-rescan`, yes.

**Comment by patricklodder** [comment]
1 - I parsed the tx you pasted with dogecoin-tx: `

$ build/dogecoin-tx -json  01000000018d3811d5c24b18877c7857717021137073d98e74fba08c9d085d71dfdb1023875e0000006b483045022100f06847d409c19d699283de16b52cb93fd2ca0eb16c62c938335876aae5c23dcc02207e8e0b07ed527cae5f4c687f22d9e76dc0e6db8240b71adcff3eb42f144d24c3012102426a9d3d40ccbbfd8267b345b18597486a0041d0a3760814f5b85c1fdb96ccfefeffffff020003164e020000001976a9143e08001dbb1263b4c8081d6e482b78ac344afe3788ac78e34e06000000001976a914afeb2c15b32a75fda24d556d696ec93f86de4f0e88ac38bc3a00

Outputs this:

```
{
    "txid": "58b46087a17cad906aa8e560440ddc648fbf0807fe0886ed1af16f78fdcbdd4e",
    "hash": "58b46087a17cad906aa8e560440ddc648fbf0807fe0886ed1af16f78fdcbdd4e",
    "version": 1,
    "locktime": 3849272,
    "vin": [
        {
            "txid": "872310dbdf715d089d8ca0fb748ed973701321707157787c87184bc2d511388d",
            "vout": 94,
            "scriptSig": {
                "asm": "3045022100f06847d409c19d699283de16b52cb93fd2ca0eb16c62c938335876aae5c23dcc02207e8e0b07ed527cae5f4c687f22d9e76dc0e6db8240b71adcff3eb42f144d24c3[ALL] 02426a9d3d40ccbbfd8267b345b18597486a0041d0a3760814f5b85c1fdb96ccfe",
                "hex": "483045022100f06847d409c19d699283de16b52cb93fd2ca0eb16c62c938335876aae5c23dcc02207e8e0b07ed527cae5f4c687f22d9e76dc0e6db8240b71adcff3eb42f144d24c3012102426a9d3d40ccbbfd8267b345b18597486a0041d0a3760814f5b85c1fdb96ccfe"
            },
            "sequence": 4294967294
        }
    ],
    "vout": [
        {
            "value": 99.00,
            "n": 0,
            "scriptPubKey": {
                "asm": "OP_DUP OP_HASH160 3e08001dbb1263b4c8081d6e482b78ac344afe37 OP_EQUALVERIFY OP_CHECKSIG",
                "hex": "76a9143e08001dbb1263b4c8081d6e482b78ac344afe3788ac",
                "reqSigs": 1,
                "type": "pubkeyhash",
                "addresses": [
                    "DAo622suZgJf8F2Gm5yYWPvvv55UwN5wng"
                ]
            }
        }, 
        {
            "value": 1.05833336,
            "n": 1,
            "scriptPubKey": {
                "asm": "OP_DUP OP_HASH160 afeb2c15b32a75fda24d556d696ec93f86de4f0e OP_EQUALVERIFY OP_CHECKSIG",
                "hex": "76a914afeb2c15b32a75fda24d556d696ec93f86de4f0e88ac",
                "reqSigs": 1,
                "type": "pubkeyhash",
                "addresses": [
                    "DMBGWszvWtw3ALLYm712KGuwWgXxgL5L65"
                ]
            }
        }
    ],
    "hex": "01000000018d3811d5c24b18877c7857717021137073d98e74fba08c9d085d71dfdb1023875e0000006b483045022100f06847d409c19d699283de16b52cb93fd2ca0eb16c62c938335876aae5c23dcc02207e8e0b07ed527cae5f4c687f22d9e76dc0e6db8240b71adcff3eb42f144d24c3012102426a9d3d40ccbbfd8267b345b18597486a0041d0a3760814f5b85c1fdb96ccfefeffffff020003164e020000001976a9143e08001dbb1263b4c8081d6e482b78ac344afe3788ac78e34e06000000001976a914afeb2c15b32a75fda24d556d696ec93f86de4f0e88ac38bc3a00"
}
```

2 - I checked if the listed input (`872310dbdf715d089d8ca0fb748ed973701321707157787c87184bc2d511388d:94`) is still spendable: `dogecoin-cli gettxout 872310dbdf715d089d8ca0fb748ed973701321707157787c87184bc2d511388d 94`

and as this returns nothing, it means that this is not spendable anymore. (compare with output 99 in that same transaction to see the difference)

3 - I then went on SoChain and checked what's up with the [input tx](https://chain.so/tx/DOGE/872310dbdf715d089d8ca0fb748ed973701321707157787c87184bc2d511388d) visually, and it gave me [this](https://chain.so/tx/DOGE/718d6f3159178a85317350d7d48503d23ff1d5a6f84cbae4a516f645a8eb2f9b) as the tx the output was spent in

**Comment by wrapperband** [comment]
Cheers,
