### ISSUE TITLE
1.14.4-dev gitian built binaries pre-check

### ISSUE THREAD

**Issue by patricklodder** [dogecoin/dogecoin#2462]
I've tagged [v1.14.4-stage-rc3](https://github.com/patricklodder/dogecoin/tree/v1.14.4-stage-rc3) off of 59da28cb06fdb569fbb4d3975c01686a88f8ab11 - which is currently the tip of v1.14.4-dev - and gitian-built it. It would be great to know if there are any issues on the gitian built binaries, I've not uploaded installers, just zipped binaries:

### Binaries:
- aarch64 linux: [dogecoin-1.14.4-aarch64-linux-gnu.tar.gz](https://github.com/dogecoin/dogecoin/files/7010750/dogecoin-1.14.4-aarch64-linux-gnu.tar.gz)
- armhf linux: [dogecoin-1.14.4-arm-linux-gnueabihf.tar.gz](https://github.com/dogecoin/dogecoin/files/7010758/dogecoin-1.14.4-arm-linux-gnueabihf.tar.gz)
- 32-bit intel linux [dogecoin-1.14.4-i686-pc-linux-gnu.tar.gz](https://github.com/dogecoin/dogecoin/files/7010759/dogecoin-1.14.4-i686-pc-linux-gnu.tar.gz)
- 64-bit intel linux [dogecoin-1.14.4-x86_64-linux-gnu.tar.gz](https://github.com/dogecoin/dogecoin/files/7010778/dogecoin-1.14.4-x86_64-linux-gnu.tar.gz)
- 64-bit intel macOS [dogecoin-1.14.4-osx64.tar.gz](https://github.com/dogecoin/dogecoin/files/7010761/dogecoin-1.14.4-osx64.tar.gz)
- 32-bit windows [dogecoin-1.14.4-win32.zip](https://github.com/dogecoin/dogecoin/files/7010764/dogecoin-1.14.4-win32.zip)
- 64-bit windows [dogecoin-1.14.4-win64.zip](https://github.com/dogecoin/dogecoin/files/7010752/dogecoin-1.14.4-win64.zip)

### SHA256 checksums:
```
f2e2a638a9caa49f8e221b47d6cca45d5f0e3580b239524fb1b4bf6d9d59ad3e  dogecoin-1.14.4-aarch64-linux-gnu.tar.gz
bfe947e381a12a81ce708d3baa4a97a516ac6100485ae70670d482591a391d03  dogecoin-1.14.4-arm-linux-gnueabihf.tar.gz
427e3159276e43760853a2708eab8fcebd985d9f4af72958a02c96cf5b467343  dogecoin-1.14.4-i686-pc-linux-gnu.tar.gz
6a8ae545308e775aaf13d57f56096735ec3f2b352bbae87e0a66967d952035eb  dogecoin-1.14.4-osx64.tar.gz
3d549d382e33b71aee26113281fc6aae78f8333bb2d06701724c393122054a66  dogecoin-1.14.4-win32.zip
19dcca6df7cc62e4434580e85a6e364f005229eb2a5db2a51d57cf586806b9b2  dogecoin-1.14.4-win64.zip
f773d84a1a29a39def90408a2ca0ca075d417c56086bbbf7bd3c1443f38d629a  dogecoin-1.14.4-x86_64-linux-gnu.tar.gz
```

### How to help

If you want to check if this works on your platform (especially: (older) raspberry pi's, a Switch, or a 32-bit windows or linux - where 64-bit linux and windows have already been verified), just download the binary and let everyone know what OS you ran it on and if you ran into any issues (or none). Note that it's likely for the binaries to be flagged as a potentially unwanted software by anti-virus products, as it contains coin mining logic, and it makes no sense to whitelist this pre-release.

**Comment by patricklodder** [comment]
I've verified working binaries `dogecoind` from `dogecoin-1.14.4-x86_64-linux-gnu.tar.gz` successfully on clean installs of:
- Ubuntu 20.04
- Ubuntu 21.04
- Fedora 34
- CentOs 8
- Debian 11

And `dogecoind` and `dogecoin-qt` from `dogecoin-1.14.4-osx64.tar.gz` successfully on macOS 11.3.1

**Comment by xanimo** [comment]
currently syncing testnet on a raspberry pi 4 on raspbian buster. no issues seen so far.

**Comment by xanimo** [comment]
> currently syncing testnet on a raspberry pi 4 on raspbian buster. no issues seen so far.

confirmed full testnet sync overnight on:
Raspberry Pi 4 Model B Rev 1.4
ARMv7 Processor rev 3
Raspbian GNU/Linux 10 (buster)

**Comment by patricklodder** [comment]
As I'm currently convinced that:

1. The issues reported with CI artifacts (glibc traces on armhf and segfaults on i686) did not carry over to gitian built binaries, and
2. At least the linux hashes are deterministic

I consider this resolved for #2460 but will leave this open for any further comments until we fixate the v1.14.4 release.

**Comment by patricklodder** [comment]
Closing this as v1.14.4 is tagged. Thanks to everyone that helped out with this!

**Comment by ReverseControl** [comment]
For the record, my hashes after gitian build:

```Generating report
f2e2a638a9caa49f8e221b47d6cca45d5f0e3580b239524fb1b4bf6d9d59ad3e  dogecoin-1.14.4-aarch64-linux-gnu.tar.gz
bfe947e381a12a81ce708d3baa4a97a516ac6100485ae70670d482591a391d03  dogecoin-1.14.4-arm-linux-gnueabihf.tar.gz
427e3159276e43760853a2708eab8fcebd985d9f4af72958a02c96cf5b467343  dogecoin-1.14.4-i686-pc-linux-gnu.tar.gz
6a8ae545308e775aaf13d57f56096735ec3f2b352bbae87e0a66967d952035eb  dogecoin-1.14.4-osx64.tar.gz
135780ca1ec45bf93d48c05e127feed38e320f37ff764748d9f137a5202dd409  dogecoin-1.14.4-osx-unsigned.dmg
b6b602eeb279589cc397f61501efb8da0954b3671c5e58ceabd703d3e62af1ba  dogecoin-1.14.4-osx-unsigned.tar.gz
1befde973f5bb4c20924a7b976d40a29725433397e1ea3f63630f0cbb3a33b4e  dogecoin-1.14.4.tar.gz
3d549d382e33b71aee26113281fc6aae78f8333bb2d06701724c393122054a66  dogecoin-1.14.4-win32.zip
19dcca6df7cc62e4434580e85a6e364f005229eb2a5db2a51d57cf586806b9b2  dogecoin-1.14.4-win64.zip
f773d84a1a29a39def90408a2ca0ca075d417c56086bbbf7bd3c1443f38d629a  dogecoin-1.14.4-x86_64-linux-gnu.tar.gz
```

@michilumin
