### ISSUE TITLE
Refresh README introduction sentence

### ISSUE THREAD

**Issue by AbcSxyZ** [dogecoin/dogecoin#2471]
The README is having a rework, I guess changing the introduction sentence to let people understand easily what is dogecoin and his core specifically would be great. I guess it's not something intuitive.

Something which may be understood by non-technical users and having something less cryptic than
> Dogecoin is a cryptocurrency like Bitcoin, although it does not use SHA256 as its proof of work (POW). Taking development cues from Tenebrix and Litecoin, Dogecoin currently employs a simplified variant of scrypt.

I'm starting a suggestion, feel free to improve or suggest one.

> Dogecoin is a cryptocurrency based on a Shiba Inu meme. Descendant of Bitcoin and Litecoin, it's a proof of work crypto who use a scrypt algorithm. Dogecoin Core software allows shibes to run a node of the network.

**Comment by QuickMythril** [comment]
my suggestion for a quick re-write that includes info from both intros:
> Dogecoin is a cryptocurrency, based on a Shiba Inu meme.  It was derived from Bitcoin (using PoW), and Litecoin (using the Scrypt hashing algorithm).  Dogecoin Core software allows users (called shibes) to run a node of the network.

**Comment by AbcSxyZ** [comment]
I guess we should have something without any parenthesis.

Also, I add previous note from a discuss on Discord, if it can be useful.
> But quickly, what I've in mind, this way we can think litecoin don't use PoW, and shibes may be implicit, having parentesis is not usefull from my pov
And give a hint that dogecoin is a fork from bitcoin/litecoin seem important

**Comment by QuickMythril** [comment]
ok here's (hopefully) an improvement:
> Dogecoin is a community-based cryptocurrency, originating with a Shiba Inu meme. It was derived from Bitcoin and Litecoin code, using the PoW Scrypt hashing algorithm. Dogecoin Core software allows users, called shibes, to run a node of the blockchain network.

**Comment by ReverseControl** [comment]
@QuickMythril So far, I like @QuickMythril  the most.

**Comment by justdaksh** [comment]
Here is an professional layout of the aforesaid subject:

> Dogecoin is a community-driven cryptocurrency that was inspired by a Shiba Inu meme. It was created using the Scrypt hashing method for Proof of Work, and it was adapted from Bitcoin and Litecoin code. The Dogecoin Core software allows users, known as shibes, to manage a blockchain network node.

**Comment by AbcSxyZ** [comment]
It sounds good, it's definitively more explicit than what the repo currently have :)

Idk if we can reach more people and discuss longer, we can perhaps do a PR to suggest the change. If anyone wants to do it.

I would agree to use it like that, but just some details who come to my mind, I would like to get your opinion.

### Make users word explicit or implicit ?

> The Dogecoin Core software allows users, known as shibes, to manage a blockchain network node.

Do you really want to specify the word "users" explicitly ? it will concern people who don't understand, look really formal, we may skip it.
In my mind, just using shibes can be great to, to also have a lighter sentence.

> The Dogecoin Core software allows shibes to manage a blockchain network node.

### Inverse two last sentences ?

I think it may be great to write it in this order :
>  The Dogecoin Core software allows users, known as shibes, to manage a blockchain network node. It was created using the Scrypt hashing method for Proof of Work, and it was adapted from Bitcoin and Litecoin code. 

We first explain what is the core, and then go into some internal details like POW. It let more barbarians words come later, to keep non-technical users reading the 2 first sentences at first, and eventually forget the last one.

*With my suggestions, it may end up with :*
> Dogecoin is a community-driven cryptocurrency that was inspired by a Shiba Inu meme. The Dogecoin Core software allows shibes to manage a blockchain network node. It was created using the Scrypt hashing method for Proof of Work, and it was adapted from Bitcoin and Litecoin code.

**Comment by patricklodder** [comment]
Minor flow changes and conciseness...

> Dogecoin is a community-driven cryptocurrency that was inspired by a Shiba Inu meme. The Dogecoin Core software allows ~~shibes~~ **_anyone_** to ~~manage~~ **_operate_** a **_node in the Dogecoin_** blockchain network**_s_** ~~node.~~ ~~It was created using~~ **_and uses_** the Scrypt hashing method for Proof of Work~~, and it was~~ **_. It is_** adapted from Bitcoin **_Core_** and other cryptocurrencies~~Litecoin code~~.

Resulting in:

> Dogecoin is a community-driven cryptocurrency that was inspired by a Shiba Inu meme. The Dogecoin Core software allows anyone to operate a node in the Dogecoin blockchain networks and uses the Scrypt hashing method for Proof of Work. It is adapted from Bitcoin Core and other cryptocurrencies.

I removed Litecoin as a source because nowadays we have adapted more code from Namecoin than Litecoin, so I settled for "and other cryptocurrencies"

**Comment by AbcSxyZ** [comment]
I suggested a PR implementing this improvement, see https://github.com/dogecoin/dogecoin/pull/2570.
