### ISSUE TITLE
Compiling dogecoin-dev-1.14.5 on Gentoo Linux

### ISSUE THREAD

**Issue by victorsk2019** [dogecoin/dogecoin#2499]
Hi everyone,

I am getting the following error when attempting to build Dogecoin Core dev-1.14.5 on Gentoo Linux: 

`  CXX      qt/dogecoin_qt-bitcoin.o
In file included from qt/bitcoin.cpp:9:
qt/bitcoingui.h:14:10: fatal error: QLabel: No such file or directory
   14 | #include <QLabel>
      |          ^~~~~~~~
compilation terminated.
make[2]: *** [Makefile:8751: qt/dogecoin_qt-bitcoin.o] Error 1
make[2]: Leaving directory '/home/doge/NetBeansProjects/dogecoin/dogecoin-dev-1.14.5/dogecoin/src'
make[1]: *** [Makefile:9897: all-recursive] Error 1
make[1]: Leaving directory '/home/doge/NetBeansProjects/dogecoin/dogecoin-dev-1.14.5/dogecoin/src'
make: *** [Makefile:688: all-recursive] Error 1`

With the following configure options:

`./configure --prefix=/home/doge/projects/dogecoin --enable-cxx --with-incompatible-bdb CPPFLAGS="-I/usr/include/db5.3" CFLAGS="-I/usr/include/db5.3" QT_CFLAGS="-I/usr/include/qt5 -I/usr/include/qt5/QtCore" QT_LIBS="-L/usr/lib64/qt5" PKG_CONFIG_PATH="/usr/lib64/qt5" --with-gui=qt5
`

The following QT packages I got installed:

`ls /var/db/pkg/* | grep qt`
`/var/db/pkg/dev-qt:
qtchooser-66
qtconcurrent-5.15.2-r1
qtcore-5.15.2-r3
qt-creator-4.15.1
qtdbus-5.15.2-r1
qtdeclarative-5.15.2-r1
qtgui-5.15.2-r2
qthelp-5.15.2
qtnetwork-5.15.2-r2
qtprintsupport-5.15.2-r1
qtquickcontrols-5.15.2
qtquicktimeline-5.15.2
qtscript-5.15.2
qtsql-5.15.2-r1
qtsvg-5.15.2
qttest-5.15.2-r1
qtwidgets-5.15.2-r1
qtx11extras-5.15.2
qtxml-5.15.2-r1
qtxmlpatterns-5.15.2
`

And I have also modified bitcoin-qt.pro as follows:

`QT += \
    printsupport
      \
    core
      \
    gui`

However, I am still getting compilation error as noted above.

# Feature Request

**Describe the Feature Request**
To be able to easily and effortlessly install Dogecoin Core, and all its required dependencies, in Gentoo using "emerge" command such as:

`emerge --ask dogecoin-qt` or `"USE=gui wallet" emerge --ask =net-p2p/dogecoin-dev-1.14.5`

**Describe Preferred Solution**
Create ebuild files and Dogecoin repositories in /var/db/repos/gentoo/net-p2p/ similar to already existing repository for bitcoin `/var/db/repos/gentoo/net-p2p/bitcoind` or `/var/db/repos/gentoo/net-p2p/bitcoin-qt`

**Describe Alternatives**
I have created a separate repository for dogecoin /var/db/repos/dogecoin and /var/db/repos/dogecoin-dev where I am testing my own custom ebuilds for installing dogecoin packages but first I need to figure out how to compile it the traditional way without any errors.

**Related Code**
We can use Gentoo bitcoin ebuilds as a template for creating ebuilds for Doge, but, again, I need to solve compiler error with QT first.

**Additional Context**
There are also official ebuilds available in Gentoo for litecoin: `/var/db/repos/gentoo/net-p2p/litecoind/` and ethereum: `net-p2p/go-ethereum`.  I believe that Dogecoin should have the same.

Thank you!

**Comment by victorsk2019** [comment]
Just a quick note that I was able to compile Dogecoin Core development version with qt5 gui, so the reported compiler issue is resolved.  What seems to have solved the problem (somehow) is installing 'plasma-meta' packages (I use xfce desktop environment) and afterwards dogecoin-qt was built with just this configure command:

`./configure --prefix=/home/doge/projects/dogecoin --enable-cxx --with-incompatible-bdb CPPFLAGS="-I/usr/include/db5.3" CFLAGS="-I/usr/include/db5.3" --with-gui=qt5`

I'll work on the requested feature on my own to see if it is possible to incorporate Doge repositories in Gentoo because I think it would be really cool if Dogecoin sources could be installed simply by using 'emerge' commands 🚀

**Comment by Chaudhrycool** [comment]
🚀🚀🚀🚀

**Comment by Mahandrafhwn** [comment]
Unsubscribe please🙏
