### ISSUE TITLE
[feat] Update from Doge Core app

### ISSUE THREAD

**Issue by CaptainTheDoge** [dogecoin/dogecoin#2504]
# Feature Request

**Describe the Feature Request**
To be able to update Dogecoin Core from the app.

**Describe Preferred Solution**
The option to update from the app/toggle for auto update.

**Describe Alternatives**
A notification that a update is available for the app and a clear link of where to update.

**Additional Context**
QOL

**Comment by patricklodder** [comment]
See: https://github.com/dogecoin/dogecoin/issues/296
