### ISSUE TITLE
“Dogecoin Core.app” can’t be opened because Apple cannot check it for malicious software (macOS)

### ISSUE THREAD

**Issue by sidan5** [dogecoin/dogecoin#2513]
Attaching the screenshot of the error (This also shown as BitcoinMiner [PUP] by AVG antivirus).

Went to Settings -> Security & Privacy -> Open Anyway (there was a new button for approving).

I guess there should be a better way so the OS could validate the application file.

![Screen Shot 2021-09-01 at 12 46 13](https://user-images.githubusercontent.com/1595490/131651103-f0ee168e-77b5-478c-a525-e6a39d043cd0.png)

**Comment by Danny-dK** [comment]
Possible indication for solution in #1870 at https://github.com/dogecoin/dogecoin/issues/1870#issuecomment-848829083
Also same topic at #1864 #1687
@ReverseControl (for issue moderation as indicated in https://github.com/dogecoin/dogecoin/issues/1962#issuecomment-910286156)

**Comment by victorsk2019** [comment]
Hi.  I've also got a Mac and I saw this message.  
Seems like it could be resolved as mentioned here:
https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution

I could take a look at it but I'm running Dogecoin Core 1.14.4 production wallet on my Mac so I'm a bit hesitant to tinker with it (hence I'm running Gentoo on VirtualBox for development #2499 ;)).

**Comment by michilumin** [comment]
We have to follow Apple's dev procedures to get this actually certified. Similar process for getting signing on Windows.  It can't really be done in an 'open source' way, an individual or entity has to hold the cert. So, we're looking into that, for now there *is* a workaround; I believe if you Ctrl-RightClick and open the dogecoin-qt app it should open without any trouble.

Fully aware that we need to get signing/certs/notarizing - but again this is more of a procedural / policy / "business" issue that can't be solved with raw code, as the process is pretty biased towards businesses and companies. Doesn't mean we can't figure out a way, just have to figure out the best way to swing it. (such as an individual in the repo holding the certs.)

**Comment by ReverseControl** [comment]
@Danny-dK Thank you. The broader situation on this issue is as @michilumin described. For the time being, we will group issues similar to this one under the ``false positive`` flag. When a solution to the broader issue is implemented, we will review each issue and close them as appropriate.

**Comment by ayman** [comment]
I'm having this issue on Mac OS 12 (Monterey)...it DogeCoin Core ran just fine on Big Sur before upgrading.  While _potentially dangerous_, a workaround is as follows:

`sudo xattr -rc /Applications/Dogecoin-Qt.app`

**Comment by patricklodder** [comment]
Fixed with [1.14.6](https://github.com/dogecoin/dogecoin/releases/tag/v1.14.6) - use `dogecoin-1.14.6-osx-signed.dmg` for the notarized version.
