### ISSUE TITLE
[bug] Debug window Network Traffic Tab and Peers Tab bugs.

### ISSUE THREAD

**Issue by ReverseControl** [dogecoin/dogecoin#2523]
# Bug Report

**Current behavior:**

First: when the sliding bar at the bottom is moved, all the graphed data disappears. We should save this data in memory and replot it as the user slides the bar.
![net](https://user-images.githubusercontent.com/6852543/132065786-38beb8c1-40b8-4ce8-9a86-6fc47682d2a8.png)

Second: The Bytes sent column appears to never go up above 1GB although my node has uploaded 21GB of data. The sent/received data should be the historical data sent/received to that node on this run and should be displayed correctly. It appears to be a bug. I don't know if the current system disconnects nodes to after sending them 1GB of data. Which, if that is the case, I would like to hear the reasoning for it.

![Peers](https://user-images.githubusercontent.com/6852543/132065797-86e3f50d-faff-4d86-9b28-7eb34e069a20.png)

**Expected behavior**

1. Replot received/sent data as the slide bar is moved.
2. Display historical sent/received data on the Peers tab even if it goes beyond 1GB.

**Steps to reproduce:**

1. Slide the bar on the Help -> Debug Window -> Network Traffic Tab and the current plot data disappears.
2. If the Full Node runs for long enough no peer shows more than 1 GB of sent data under the Peers Tab.

**Screenshots**

See above.

**Dogecoin Core version**

Version 1.14.4.

**Machine specs**
- OS: Ubuntu 20.04
- CPU: Intel x86_64
- RAM: 64GB
- Disk size: A lot.
- Disk Type (HD/SDD): SSD

**Extra information**

@rnicoll

**Comment by ReverseControl** [comment]
**Update**

It appears what is happening is that it only shows GB when it changes one GB unit at a time. This is too coarse, I think we should make it to update every MB or so for the GB unit, and show a couple of decimal places, or leave it in MB even when we get to the GB range.
![Screenshot from 2021-09-04 08-36-52](https://user-images.githubusercontent.com/6852543/132094702-7e9a06ca-6920-41d9-bbda-1a5f5ad8b007.png)

**Comment by ReverseControl** [comment]
@sinetek I think so. I have a slight preference for MB as well. Unless there is a strong opposition to it, I suggest this implementation.

**Comment by chromatic** [comment]
@ReverseControl can you try the linked PR? I played with it a little bit and it feels mostly okay, but you're in a better position to see if it's what you had in mind. Thanks!

**Comment by alamshafil** [comment]
I believe this issue should be closed now since #2934 has been merged.

**Comment by patricklodder** [comment]
Correct. Closing!
