### ISSUE TITLE
[feat] Update leveldb source

### ISSUE THREAD

**Issue by chromatic** [dogecoin/dogecoin#2531]
# Feature Request

**Describe the Feature Request**

The [leveldb](https://github.com/google/leveldb) source code included at `src/leveldb/` is out of date with regard to upstream. When compiled, it produces a warning:

```
leveldb/util/logging.cc: In function ‘bool leveldb::ConsumeDecimalNumber(leveldb::Slice*, uint64_t*)’:
leveldb/util/logging.cc:58:40: warning: comparison of integer expressions of different signedness: ‘const int’ and ‘long unsigned int’ [-Wsign-compare]
   58 |           (v == kMaxUint64/10 && delta > kMaxUint64%10)) {
      |                                  ~~~~~~^~~~~~~~~~~~~~~
```

**Describe Preferred Solution**

Investigate whether it is possible to update the included version of `leveldb` and, if so, which version to update to. Note that the code which produces this warning [updated upstream in April 2018](https://github.com/google/leveldb/commit/a0008deb679480fd30e845d7e52421af72160c2c#diff-a9edca4ce766f117f1dacc8aaf2ddbff534eb77779d9d03194edbcde5172a8c2),

Note that [Bitcoin uses leveldb version 1.22](https://github.com/bitcoin/bitcoin/blob/master/src/leveldb/include/leveldb/db.h#L19) while Dogecoin uses 1.19.

**Comment by patricklodder** [comment]
There are still some warnings left when I compile with gcc 9, but we're completely up-to-date with this vs Bitcoin Core 0.22.0.

@chromatic is this resolved for you at this time?

**Comment by chromatic** [comment]
The warning is resolved. Thanks for the PR; I'll close.
