### ISSUE TITLE
[feat] Rewards for running a full node

### ISSUE THREAD

**Issue by bingoko** [dogecoin/dogecoin#2569]
Could we add a new feature to allow the hoster of the full node can receive a small amount reward to incentivise more and more hoster to join?

**Comment by hzkxf4** [comment]
I would like to see this as well.

**Comment by patricklodder** [comment]
How would you like to fund these rewards?

**Comment by hzkxf4** [comment]
Thank you for responding. I apologize in advance if my limited understanding of things crypto makes my suggestion idiotic.  Is there much 'dust' in doge transactions?  Could a common dust bin address be created to collect all dust and distribute it to active nodes whenever the accumulated dust reaches a threshold where the bin is full and an even distribution can be made?  I have no idea if this is feasible.  
Thanks again for the response and your work!

**Comment by patricklodder** [comment]
That's an interesting idea that I haven't heard before. I'm converting this to discussions, because there are a lot of additional things we'd need to explore (mainly: how to prove that the node was up and how to prevent cheating)

This issue will be closed and reopened in discussions.
