### ISSUE TITLE
Mining a transaction

### ISSUE THREAD

**Issue by malingzhao** [dogecoin/dogecoin#2583]
I has a rawtransaction, because of the low fee, The transaction can not be confirmed, And It is a offline transaction, And it has 1 month, what can I do to confirmed this transaction. For bitcoin, there are many miner pool, But in DogeCoin I can not found any mine pool, can you give me some suggestions

**Comment by patricklodder** [comment]
How low is your fee? If it's over 0.01 DOGE/kb you can probably re-relay your transaction and get it mined. If under, most clients have only a 24h mempool retention policy, so you can re-create the transaction and spend those outputs with a higher fee.

**Comment by vannieuwenhovej** [comment]
Can you link the tx hash?

**Comment by patricklodder** [comment]
The steps to resolve (from [the 1.14.6 release discussion](https://github.com/dogecoin/dogecoin/discussions/3054#discussioncomment-5292130)) are as follows and should be performed before upgrading to 1.14.5 or later:

#### Purging all pending wallet transactions automatically

To automatically purge all pending transactions, restart `dogecoind` or `dogecoin-qt` once, with the `-zapwallettxes=1` option, eg:

```console
$ dogecoind -zapwallettxes=1

> Dogecoin-Qt.exe -zapwallettxes=1
```

#### Manually searching for and removing pending wallet transactions

To manually check and remove pending transactions, use the `listtransactions` RPC call, either using dogecoin-cli, or from the Debug console. Look for transactions with 0 confirmations, or filter them with `jq`, like so:

```console
$ dogecoin-cli listtransactions "*" 100000 0 | jq -r '.[] | select(.confirmations == 0)'
{
  "account": "",
  "address": "D9gEMMtCNT5GHvFvSQMjfSnbZFRRUjjDPX",
  "category": "send",
  "amount": -420.69,
  "vout": 0,
  "confirmations": 0, <---- this means the transaction has never been mined
  "trusted": true,
  "txid": "47a84a30159ed15d36e91ef6ae161fe5254aa9c2c906dc614d5aba03659e65ed",
  "walletconflicts": [],
  "time": 1678343421,
  "timereceived": 1678343421,
  "bip125-replaceable": "no",
  "abandoned": false <---- this means the transaction is stuck and has not been purged from the wallet
} 
```

These transactions can then be removed with `abandontransaction` individually, if desired:

```console
$ dogecoin-cli abandontransaction 47a84a30159ed15d36e91ef6ae161fe5254aa9c2c906dc614d5aba03659e65ed
```

#### Post-upgrade checks

After abandoning transactions, it should be safe to update the software to version 1.14.6. If you want to double check after you upgraded the software, you can mimic the 1.14.2 dust relay rules by setting the hard dust limit when starting dogecoind or dogecoin-qt with `-harddustlimit=1`. This sets the minimum amount of DOGE in a transaction output to 1.0 and rejects any transactions that attempt to transfer lower amounts. Alternatively, you can run the software once while not connected to the internet. 1.14.6 ships with a new `liststucktransactions` RPC method that can be used to check if there are still stuck transactions in the wallet:

```console
$ src/dogecoin-cli liststucktransactions
[]
```

-----

If this did not resolve this issue, please leave a comment here and we'll reopen it.
