### ISSUE TITLE
[feat] Extra /src directory in rpc-tests.py line 221

### ISSUE THREAD

**Issue by victorsk2019** [dogecoin/dogecoin#2592]
Hi everyone,

There seems to be an extra /src directory being appended to BUILDIR for '--srcdir' value in rpc-tests.py on line 221.  I presume this is done to account for default Dogecoin Core binary files locations when '--prefix' specifier at configure stage is not used.  However, in cases when custom locations of Dogecoin Core binary files are specified, this '/src' directory is appended as extra non-existent subdirectory in some situations.  

My understanding is that a correct BUILDIR value can be specified at ~~runtime~~  command-line, for example: `"rpc-tests.py --srcdir="/opt/dogecoin/bin"` 
But it is rather awkward since there is a 'test_config.py' where BUILDIR can be set permanently.  But as mentioned, the presence of extra '/src' directory on line 221 in 'rpc-tests.py' is causing errors for non-existent '--srcdir' value when 'rpc-tests.py' is run.

I suggest removing extra "/src" directory and leave it up to the user to specify BUILDIR in 'test_config.py' as follows:

`SRCDIR="/opt/dogecoin/src/dogecoin-1.14.5-dev"`
`BUILDDIR="/opt/dogecoin/bin"` <-- here, '/src' directory would be appended making it '/opt/dogecoin/bin/src' if it is not removed from 'rpc-tests.py'

I made a commit on my repository 1.14.5 with a suggested minor fix:
https://github.com/victorsk2019/dogecoin/commit/829e533593917a63dbd9b383f44319bdfef30144

Should PR be submitted for this?

Thanks.

**Comment by patricklodder** [comment]
Hi! That line is only to deduct the build dir (is the root directory of the repo) and then point to the binaries in `src/`. But you can override this with `--srcdir=<your path to dogecoind/dogecoin-cli/dogecoin-tx>` rather than trying to use env variables? 

Why don't you want to use the command line argument?

**Comment by victorsk2019** [comment]
> Why don't you want to use the command line argument?

Hi.  It's more convenient, in my opinion.  Not sure if it can be identified right away.  Took me some time to find --srcdir as command-line argument it as I was getting error messages with rpc-tests.py with original values set for BUILDIR.
