### ISSUE TITLE
This is a bug: Talked to the miner. What's happening is this:

### ISSUE THREAD

**Issue by didlie** [dogecoin/dogecoin#2593]
Talked to the miner. What's happening is this:

1. Block n is mined.
2. Nodes remove all transactions in block n from the mempool.
3. The miner's node sends the block template for n+1 is sent to their miners. As the mempool is empty, the template is empty.
4. If it's mined before the next template is sent, it generates an empty block.

The template refresh is up to 55 seconds currently, which means if a block is mined in under 55 seconds (give or take) it can come out empty.

So; they're looking at reducing the refresh interval. However, keep in mind this only happens because we have partially full blocks, if the blocks start filling up the "overflow" transactions will be in the next block.

_Originally posted by @rnicoll in https://github.com/dogecoin/dogecoin/issues/2585#issuecomment-927260742_

**Comment by didlie** [comment]
https://dogechain.info/block/3913811 ---- more empty transactions crediting this miner with diluting 10,000 Dogecoin. https://dogechain.info/block/3913807

**Comment by patricklodder** [comment]
Currently, miner sovereignty to choose what to include in a block is a feature, not a bug. Please use discussions if you want to challenge that.
