### ISSUE TITLE
dogecoin-cli listaccounts | documentation?

### ISSUE THREAD

**Issue by persisty** [dogecoin/dogecoin#2596]
Hi,
Sorry if this is a stupid Q. I'm running a dogecoin core 1.14.4 for a few days.
dogecoin-cli getconnectioncount is between 30 and 70 at any time.

I can't find any docs on commands.

e.g.
dogecoin-cli listaccounts
gives me
error code: -32601
error message:
Method not found

Any good reference links would be helpful. Thanks in advance

**Comment by AbcSxyZ** [comment]
Hi,

Current documentation lack information about commands in overall, no real usage & syntax docs. For now, you will have to search information on Internet, query google. It may be useful to check bitcoin documentation too.

There is also a PR in progress about the topic, to create a getting started section inside the documentation to start using `dogecoind`, `dogecoin-cli` at least. You won't find all answers but it may help you :)
Take a look at https://github.com/dogecoin/dogecoin/pull/2568.

And feel free to give a feedback or a review if you see possible mistake/improvement :heart:

**Comment by persisty** [comment]
> Hi,
> 
> Current documentation lack information about commands in overall, no real usage & syntax docs. For now, you will have to search information on Internet, query google. It may be useful to check bitcoin documentation too.
> 
> There is also a PR in progress about the topic, to create a getting started section inside the documentation to start using `dogecoind`, `dogecoin-cli` at least. You won't find all answers but it may help you :) Take a look at #2568.
> 
> And feel free to give a feedback or a review if you see possible mistake/improvement ❤️

Thanks. Looking at it.
1.  Any idea what error 32601 means?
2. Is it possible that some methods do not work for some time after a node comes up?

dogecoin-cli listaccounts
gives me
error code: -32601
error message:
Method not found

**Comment by AbcSxyZ** [comment]
> 2. Is it possible that some methods do not work for some time after a node comes up?

I'm not sure about it, but it may be possible depending on the commands, and also by what you mean by "working". For example, `listunspent` need to have download enough of the blockchain to track your transactions, otherwise it "won't work".

Also, you may have some commands who are available on Bitcoin Core and not in Dogecoin Core.

**Comment by patricklodder** [comment]
@persisty you may want to try `dogecoin-cli help` and `dogecoin-cli help <command>`
