### ISSUE TITLE
[bug] libdb_cxx headers missing

### ISSUE THREAD

**Issue by alfirus** [dogecoin/dogecoin#2642]
# Bug Report

**Current behavior:**
configure: error: libdb_cxx headers missing, Dogecoin Core requires this library for wallet functionality (--disable-wallet to disable wallet functionality)

**Expected behavior**
Compile completed

**Steps to reproduce:**

**Screenshots**
https://www.dropbox.com/s/x2ue6t5p9vho2lf/Screenshot%202021-10-24%2007.17.16.png?dl=0

**Dogecoin Core version**
Latest

**Machine specs**
- OS: Ubuntu 18
- CPU: 4 cores
- RAM: 8 GB
- Disk size: 180GB
- Disk Type (HD/SDD): HD

**Extra information**

**Comment by xanimo** [comment]
So you need to either install the dependencies for bdb yourself or build from depends. The following will build depends:
```
make NO_QT=1 -C depends \
&& ./autogen.sh \
&& ./configure \
--prefix=`pwd`/depends/x86_64-pc-linux-gnu \
--without-gui \
--disable-gui-tests \
&& make
```
