### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by Mylifeloading94** [dogecoin/dogecoin#2643]
I'm using the core app. The wallet fully synced but didn't send to my trust wallet address but was still withdrawn from the application. I know my phrase code and have my wallet.dat file. 
![20211026_013053](https://user-images.githubusercontent.com/93205338/138895483-a094a3cd-7a3d-4f2b-992a-ba4b379f0f60.jpg)

**Comment by patricklodder** [comment]
Closing this here as was identified to not be related to Dogecoin Core. Feel free to comment if you need any more support and we'll reopen the issue
