### ISSUE TITLE
[feat] Improve error message for `submitblock`

### ISSUE THREAD

**Issue by rllola** [dogecoin/dogecoin#2651]
# Feature Request

**Describe the Feature Request**

Improve the error message for `submitblock` when there is an issue with the coinbase transaction.

**Describe Preferred Solution**

The current error message indicate "Block does not start with a coinbase"
There is 2 possibilities for this error to be returned :
* No transaction
* We have a transaction but it doesn't fit the coinbase transaction standard

We could improve the error message by indicating that there is either no transaction or that there is one but is it not a transaction and even return as data the problematic transaction to facilitate debugging.

**Related Code**
See https://github.com/dogecoin/dogecoin/blob/master/src/rpc/mining.cpp#L788-L790

**Additional Context**
Good error messages are good.

**Comment by victorsk2019** [comment]
Would it solve it to just split this condition?

    if (block.vtx.empty())
    {
        throw JSONRPCError(RPC_DESERIALIZATION_ERROR, "No transaction");
    } 

    if (!block.vtx[0]->IsCoinBase())
    {
        throw JSONRPCError(RPC_DESERIALIZATION_ERROR, "Block does not start with a coinbase");
    }

**Comment by chromatic** [comment]
That looks close to what I'd propose. The existing Dogecoin code exactly matches [Bitcoin's behavior in this scenario](https://github.com/bitcoin/bitcoin/blob/master/src/rpc/mining.cpp#L983-L985).

My only concern is people relying on the wording of the message for the first case (no transaction in block). Maybe it's better to change the first message to `Block does not start with a coinbase: no transaction in block`?

**Comment by patricklodder** [comment]
The rules for a block are:

1. There should always be a **valid** coinbase transaction
2. The coinbase transaction should always be the first transaction in the block

So even though the message kind of covers that, I get how it can be improved to be easier to understand. Note that the intent of this check is pre-validation to save clock cycles, see a44a6a15 for the rationale.

How about:

```
if (block.vtx.empty())
{
    throw JSONRPCError(RPC_DESERIALIZATION_ERROR, "Block does not contain a coinbase transaction");
} 

if (!block.vtx[0]->IsCoinBase())
{
    throw JSONRPCError(RPC_DESERIALIZATION_ERROR, "Block does not start with a valid coinbase transaction");
}
```

**Comment by patricklodder** [comment]
Tagged for 1.14.5 because this is not a lot of work - if someone could please PR, that'd be cool.

**Comment by rllola** [comment]
That looks great :+1: 

To answer your concern @chromatic. I have seen some developers who do that and it is a bad practice (no judgement here). There is associated with it an error code and this one won't changed though. They can easily switch to this.

See 
https://github.com/dogecoin/dogecoin/blob/master/src/rpc/protocol.h#L48

Good practice would be to be able to handle all `RPCErrorCode` in this file.

**Comment by patricklodder** [comment]
@rllola as #2653 has been merged, I'm closing this, but if you have any further concerns, feel free to reopen this issue.
