### ISSUE TITLE
Open items for 1.14.5 release

### ISSUE THREAD

**Issue by patricklodder** [dogecoin/dogecoin#2655]
Listing for transparency, let me know if I missed anything.

### Must-haves
- [x] #2666 (fixes CVE)
- [x] #2673 (fixes CVE)

### Should-haves (either we merge or reject these):

- [x] #2568
  - [x] Needs #2664
  - [x] Needs #2668
- [x] #2653
- [x] #2654

### Could-haves (non-blocking but would be good to get in, otherwise push to 1.14.6):

- [x] #2491
- [x] Postponed to 1.14.6: #2579
- [x] Postponed to 1.14.6: #2648

### Maintenance tasks to get to release (after finalizing release content above):

- [x] #2657
- [x] #2658
- [x] #2669
- [x] #2662
- [x] Write release notes
  - [x] #2492
  - [x] #2663
  - [x] #2667
- [x] #2670
- [x] Tag v1.14.5
- [x] Gitian build
- [x] Fast-fwd 1.14-maint 
- [x] Fast-fwd master
- [x] Upload binary release

### Post-release tasks
- [x] Create 1.14.6-dev
- [x] #2679
- [x] Rebase open PRs

**Comment by AbcSxyZ** [comment]
For the gitian build of  https://github.com/dogecoin/dogecoin/pull/2579, it relies on a pending request in [devrandom/gitian-builder](https://github.com/devrandom/gitian-builder/pull/253) repo to get `--disable-apt-cacher` option. Idk if you would prefer to wait to merge #2579, or if we keep a script who always use apt-cacher and create a new PR to disable cache whenever https://github.com/devrandom/gitian-builder/pull/253 is included (if it is but they were interested).

**Comment by patricklodder** [comment]
Added #2666 as it contains a fix for #2665 as must have.

**Comment by patricklodder** [comment]
Moved #2648 to could-haves because it is seeing contention, and #2661 already writes out the entire recommendation. The release notes and messaging will also clearly iterate the fee recommendation, so the need is lower. Can settle this for 1.14.6 - @AbcSxyZ are you okay with that?

**Comment by AbcSxyZ** [comment]
However you want guys. I thought it can be great to add information about fees easily accessible through the documentation. Maybe you can just add a sentence to link with `doc/fee-recommendation` in the `README`, at the bottom of the usage section ? It's simple and may facilitate access to the information

**Comment by Frankwhitee** [comment]
Keep up the good work D

**Comment by patricklodder** [comment]
Added #2673 as must-have - it fixes the CVE reported in #2672

**Comment by rnicoll** [comment]
I'll tag in about an hour unless there's objections or someone beats me to it!

**Comment by patricklodder** [comment]
@rnicoll No objections! Feel free to tag at your convenience.

**Comment by upperhandy** [comment]
Exciting times!

**Comment by rnicoll** [comment]
@patricklodder Tagged, Gitian build running, signatures should be up shortly.

**Comment by a10554** [comment]
Good job. When is it expected to be available for download ?

**Comment by upperhandy** [comment]
@a10554 soon

**Comment by patricklodder** [comment]
fast-forwarded 1.14-maint and created 1.14.6-dev while we wait for the signed 1.14.5 macOS binaries to be created & verified

**Comment by patricklodder** [comment]
# 🥳

**Comment by a10554** [comment]
sweet
