### ISSUE TITLE
[feat] Updated Chinese README.md Translation

### ISSUE THREAD

**Issue by slightlyskepticalpotat** [dogecoin/dogecoin#2688]
# Feature Request

**Describe the Feature Request**
It would be nice to have an updated Chinese translation of the README, as the English version has been improved through Docs4Doge but the Chinese one has not.

**Describe Preferred Solution**
See above. 

**Describe Alternatives**
Alternatively, we could keep the outdated Chinese translation or remove it entirely. 

**Related Code**
[README.md](https://github.com/dogecoin/dogecoin/blob/master/README.md).

**Comment by Mohammedasif786** [comment]
Yeah really?

**Comment by MVShishkov** [comment]
Please check my pull request #2798 and my comment

**Comment by Mohammedasif786** [comment]
Who are you?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by MVShishkov** [comment]
> Who are you? Get Outlook for Android<https://aka.ms/AAb9ysg>
> […](#)

Hi! My name is Maksim and I am from Russia and can read, write, speak and listen in the Chinese. Also I am a former electric&electronic and IT developer. My successful projects are LADA Connect, eCall (ERA-GLONASS) ITELMA, Connected FORD Russia, Connected Mercedes and KIA for Motor-Car Europe.
I hope that my knowledge and skills will benefit the community!) Feel free to write me and ask me!)

**Comment by Mohammedasif786** [comment]
Ok I will check ✔ it?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Mohammedasif786** [comment]
Are you software engineer

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by MVShishkov** [comment]
> Are you software engineer Get Outlook for Android<https://aka.ms/AAb9ysg>
> […](#)

Yep, but former electronic software and hardware engineer, IT software engineer. Now in charge of DEV department for Connected industry (IoT).

**Comment by Mohammedasif786** [comment]
will you help me to learn how to become a developer?

**Comment by MVShishkov** [comment]
I think it will not be the problem nowadays, as lots of studying information on the internet, which you can search on the google, for example. Take the project and issues, surf the net on how can you can solve it. My very first project was in the university related to the remote control of the in-vehicle device by means of the infrared channel and high-frequency (around 2 Ghz) channel using remote control board. It was my diploma project about 10 years ago. I chose this topic (distant remote control) and studied it. You can do the same (chose the topic and studied it). Good luck!

**Comment by raggingsoldier** [comment]
That is a vague question developer for what? You need to know your goals. This guy sounds like a C++ developer is that what you want. Best bet would be take classes

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by raggingsoldier** [comment]
My advice is get a degree and certifications, For languages you want to know. This guys advice isn’t the greatest because most if not all self devs have bad habits and most companies won’t hire because they don’t wanna re-train them.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Mohammedasif786** [comment]
thanks for this tip!
Where are you from ?

**Comment by raggingsoldier** [comment]
I’m from the states now reside in japan. I work as a freelance full stack developer and cyber security specialist.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Mohammedasif786** [comment]
Great!

**Comment by MVShishkov** [comment]
My major is automated technologies in the automotive industry and I chose the remote control topic, because I believed that it would revolutionize the world and now it is the IoT. It was 11 years ago. Like that I have learned C, C++, C#, Java, Phyton, swift, Matlab. But, in conclusion, choose the topic and deeply study it from different sides. You can even go the university and professors might help you like helped me. Good luck!
