### ISSUE TITLE
[bug] build error

### ISSUE THREAD

**Issue by bagasik** [dogecoin/dogecoin#2690]
Hello.
My system centos-release-7-6.1810.2.el7.centos.x86_64.
dogecoin build error.
# cd /mnt/dogecoin_install/
# git clone https://github.com/dogecoin/dogecoin
# cd dogecoin/
# ./autogen.sh
# ./configure
# make
Making all in src
make[1]: Вход в каталог `/mnt/dogecoin_install/dogecoin/src'
make[2]: Вход в каталог `/mnt/dogecoin_install/dogecoin/src'
make[3]: Вход в каталог `/mnt/dogecoin_install/dogecoin'
make[3]: Выход из каталога `/mnt/dogecoin_install/dogecoin'
make[3]: Вход в каталог `/mnt/dogecoin_install/dogecoin/src/secp256k1'
make[3]: Выход из каталога `/mnt/dogecoin_install/dogecoin/src/secp256k1'
  CXX      rpc/libdogecoin_server_a-server.o
rpc/server.cpp: В функции «void RPCServer::OnPreCommand(boost::function<void(const CRPCCommand&)>)»:
rpc/server.cpp:61:62: ошибка: «boost::placeholders» не был декларирован
     g_rpcSignals.PreCommand.connect(boost::bind(slot, boost::placeholders::_1));
                                                              ^
rpc/server.cpp: В функции «void RPCServer::OnPostCommand(boost::function<void(const CRPCCommand&)>)»:
rpc/server.cpp:66:63: ошибка: «boost::placeholders» не был декларирован
     g_rpcSignals.PostCommand.connect(boost::bind(slot, boost::placeholders::_1));
                                                               ^
rpc/server.cpp: В функции-члене «std::vector<std::basic_string<char> > CRPCTable::listCommands() const»:
rpc/server.cpp:520:39: ошибка: «boost::placeholders» не был декларирован
                                boost::placeholders::_1) );
                                       ^
make[2]: *** [rpc/libdogecoin_server_a-server.o] Ошибка 1
make[2]: Выход из каталога `/mnt/dogecoin_install/dogecoin/src'
make[1]: *** [all-recursive] Ошибка 1
make[1]: Выход из каталога `/mnt/dogecoin_install/dogecoin/src'
make: *** [all-recursive] Ошибка 1
[root@coins234]#

What to do in this case?

**Comment by patricklodder** [comment]
which version of boost do you have installed? You can find it with:

```
grep "define BOOST_LIB_VERSION" /usr/include/boost/version.hpp 
```

**Comment by bagasik** [comment]
#define BOOST_LIB_VERSION "1_53"

**Comment by patricklodder** [comment]
The minimum version you'll want is 1_63, I've personally tested until 1_76 so far - if CentOS doesn't provide anything higher than 1_53, you can download and compile it from https://sourceforge.net/projects/boost/files/boost/1.63.0

**Comment by bagasik** [comment]
new error.
  CXX      libdogecoin_common_a-dogecoin-fees.o
In file included from /usr/local/include/boost/signals2/detail/null_output_iterator.hpp:14:0,
                 from /usr/local/include/boost/signals2/connection.hpp:22,
                 from /usr/local/include/boost/signals2/signal.hpp:22,
                 from txmempool.h:28,
                 from dogecoin-fees.cpp:11:
/usr/local/include/boost/function_output_iterator.hpp:14:102: замечание: #pragma message: This header is deprecated. Use <boost/iterator/function_output_iterator.hpp> instead.
 BOOST_HEADER_DEPRECATED("<boost/iterator/function_output_iterator.hpp>")
                                                                                                      ^
  AR       libdogecoin_common.a
make[3]: Вход в каталог `/mnt/dogecoin_install/dogecoin/src/univalue'
make[3]: *** Нет правила для сборки цели `%reldir%/lib/univalue.cpp', требуемой для `%reldir%/lib/libunivalue_la-univalue.lo'.  Останов.
make[3]: Выход из каталога `/mnt/dogecoin_install/dogecoin/src/univalue'
make[2]: *** [univalue/libunivalue.la] Ошибка 2
make[2]: Выход из каталога `/mnt/dogecoin_install/dogecoin/src'
make[1]: *** [all-recursive] Ошибка 1
make[1]: Выход из каталога `/mnt/dogecoin_install/dogecoin/src'
make: *** [all-recursive] Ошибка 1

**Comment by patricklodder** [comment]
I'm able to reproduce this error on a centos:7 docker image, am still looking for the root cause and why this doesn't happen on ubuntu18-21.

**Comment by patricklodder** [comment]
The problem with CentOS 7 is that it has `automake-1.13` and we need at least `automake-1.14` for it to understand `%reldir%`.

I can build on CentOS 7 with the following sequence (Dockerfile):

```
FROM centos:7
WORKDIR /build
RUN yum install -y autoconf pkgconfig make which gcc-c++ openssl-devel libevent-devel libdb-devel libdb-cxx-devel git bzip2
RUN yum erase -y automake
RUN curl -L -O https://gateway.ipfs.io/ipns/k2k4r8k7m201lblz207p1hd3tmt7szpywgoglxu5b5bp653bhi450h52/depends-sources/boost_1_63_0.tar.bz2 # cuz source forge down ugh
RUN curl -L -O https://ftpmirror.gnu.org/automake/automake-1.16.5.tar.xz
RUN curl -L -O  https://ftpmirror.gnu.org/libtool/libtool-2.4.6.tar.gz
RUN git clone https://github.com/dogecoin/dogecoin.git
RUN tar xfv boost_1_63_0.tar.bz2 && tar xfv automake-1.16.5.tar.xz && tar xfv libtool-2.4.6.tar.gz
WORKDIR /build/boost_1_63_0
RUN ./bootstrap.sh --without-icu --with-libraries=chrono,filesystem,program_options,system,thread,test && ./b2 && ./b2 install
WORKDIR /build/automake-1.16.5
RUN yum install -y perl-Thread-Queue.noarch && ./configure && make && make install
WORKDIR /build/libtool-2.4.6
RUN ./configure && make && make install
WORKDIR /build/dogecoin
RUN ACLOCAL_PATH=/usr/share/aclocal ./autogen.sh
RUN ./configure && make

```

so for @bagasik, this would probably mean the following based on where we left off:
```
yum install perl-Thread-Queue.noarch
yum erase automake
curl -L -O https://ftpmirror.gnu.org/automake/automake-1.16.5.tar.xz
curl -L -O  https://ftpmirror.gnu.org/libtool/libtool-2.4.6.tar.gz
tar xfv automake-1.16.5.tar.xz
tar xfv libtool-2.4.6.tar.gz
cd automake-1.16.5
./configure && make && make install
cd ../libtool-2.4.6
./configure && make && make install
```

and then in the dogecoin root:

```
make distclean
ACLOCAL_PATH=/usr/share/aclocal ./autogen.sh
./configure
make
```

and done.

I'll turn this into a centos7 guide.

**Comment by patricklodder** [comment]
@bagasik did the above work for you?

**Comment by bagasik** [comment]
> did the above work for you?

Thanks, all worked well.
