### ISSUE TITLE
[feat] Add an RPC method showing wallet transactions that are not in the mempool

### ISSUE THREAD

**Issue by patricklodder** [dogecoin/dogecoin#2721]
# Feature Request

_Follow-up from discussions with @rnicoll and Binance's ops team_

**Describe the Feature Request**

Add a method to the RPC that lists all transactions in the wallet that do not have a mempool entry.

**Describe Preferred Solution**

1. Select all transactions in the wallet with exactly 0 confirmations
2. Filter out everything that is in the local node's mempool
3. Display (depending on flag) either the transaction hash, the transaction hex, or a JSON representation of the transaction, preferably including wallet metadata as done with `gettransaction`

**Additional Context**

This will help prevent situations where wallet operators do not know that there are stuck transactions in their wallets.

**Comment by qlpqlp** [comment]
Thank you :) I have learned that lesson lol with the 0 confirmations do the lack of peers on my node :)

Also maybe add the information on the wallet that the transaction can be delay bettwin 10 to 30 minuts to revert or even 30 days if the lower fees are not acepted by any node.

**Comment by patricklodder** [comment]
> Also maybe add the information on the wallet that the transaction can be delay bettwin 10 to 30 minuts to revert or even 30 days if the lower fees are not acepted by any node.

The transaction should stay in your local mempool for 24 hours. Did it not re-propagate after you got connected to new peers?

Also, I have a solution prototyped for the policy discrimination functionality that @mishaboar and I were [discussing](https://github.com/dogecoin/dogecoin/discussions/2624#discussioncomment-1509482) earlier. Will try to PR over the next couple of days.

**Comment by rnicoll** [comment]
Occurs do we need a backport of this to 1.14.4 (1.14.4.1?) for any exchanges wanting to verify before upgrade?

**Comment by patricklodder** [comment]
> do we need a backport of this to 1.14.4

Alternatively, an operator could set either `-blocksonly` or `-walletbroadcast=0`, and set `-harddustlimit=1.0`, when doing the upgrade from any dogecoind < 1.14.5 that uses the wallet.

In any case, if we decide to do a backport release, we need to assess other things, most importantly security fixes, too. So that would be a little more effort than just back porting this single patch and I'm not sure if it's worth it given the above. 

> for any exchanges

PS: Since you specifically mentioned exchanges... are you in contact with custodial operators that actually use the dogecoind wallet? Did you receive any indication from any operator that they want this? Because the best thing to do is not upgrade the wallet, but instead get an HSM to store key material in, craft those transactions with any of the bitcoin libraries out there, or even dogecoin-tx, and run a `-disablewallet` node...

**Comment by victorsk2019** [comment]
There's an RPC call `gettxout` that has number of confirmations in its JSON returning value.  Given a list of transactions they want to check for 0 confirmations, just invoke `gettxout` repetitively in a loop for each txId and if confirmations == 0 then display the transaction.  They could implement it as a cron job that runs at certain intervals?

**Comment by patricklodder** [comment]
@victorsk2019 does that work for transactions that do not generate change?
