### ISSUE TITLE
I have no idea to run the source code, which IDE can I use  for developing?

### ISSUE THREAD

**Issue by jesuasir007** [dogecoin/dogecoin#2722]
please help about this topic ,how to build and debug the source code in which ide like Xcode,visualstudio,cygwin ..etc

can you give the procedure  ?

**Comment by rnicoll** [comment]
Although you can build on Windows/OS X, my general advice is that using Linux (I use a Linux VM) is the least terrible option. There's a guide to building it on Linux at https://github.com/dogecoin/dogecoin/blob/master/doc/build-unix.md, which should get you started at least.

**Comment by jesuasir007** [comment]
how can i edit the code ?
