### ISSUE TITLE
Attribute Qt::AA_EnableHighDpiScaling  [bug] 

### ISSUE THREAD

**Issue by keefer223** [dogecoin/dogecoin#2776]
running dogecoin-qt or dogecoin-qt -server the following issue is displayed on the screen:

keefer@yiimp:~/dogecoin$ ./dogecoin-qt -server
Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.

this appears to be a core coding issue. searching the web there are a few fixes but they all require re-coding some of the dogecoin, which should be resolved by the developers. Fixing the issue on my system doesn't help the rest of the community. 

**verified prerequisites installed, 
recompile dogecoin from source** 

./configure --with-gui
make

make check:

PASS: test/object
PASS: test/unitester
PASS: test/no_nul
============================================================================
Testsuite summary for univalue 1.0.4
============================================================================
# TOTAL: 3
# PASS:  3
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
make[6]: Leaving

# Bug Report

**Current behavior:**
other than the screen display, Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
no other obvious issues, but I suspect to see other issues after the wallet finishes sync

**Expected behavior**
not a clue other than the coding issue.

**Steps to reproduce:**
sudo apt-get install libminiupnpc-dev
sudo apt-get install libzmq3-dev -y
sudo apt install libdb5.3++-dev libdb5.3++ libdb5.3-dev -y
sudo apt-get install libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler libqrencode-dev -y
sudo apt-get install libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-program-options-dev libboost-test-dev libboost-thread-dev -y
sudo apt-get install build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils -y
sudo apt-get install g++-11-multilib gcc-11-multilib -y
sudo apt-get install autoconf automake binutils-gold ca-certificates curl faketime git-core libtool pkg-config python bison -y

./configure --with-gui
make

make check:

**Screenshots**
keefer@yiimp:~/dogecoin$ netstat -tulpn
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:587           0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:11211         0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:53            0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      -                   
tcp6       0      0 ::1:53                  :::*                    LISTEN      -                   
tcp6       0      0 :::22                   :::*                    LISTEN      -                   
tcp6       0      0 :::80                   :::*                    LISTEN      -                   
tcp6       0      0 :::443                  :::*                    LISTEN      -                   
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           -                   
udp        0      0 127.0.0.1:53            0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:68              0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:55586           0.0.0.0:*                           -                   
udp6       0      0 :::5353                 :::*                                -                   
udp6       0      0 ::1:53                  :::*                                -                   
udp6       0      0 :::53393                :::*                                -                   
udp6       0      0 :::546                  :::*                                -                   
keefer@yiimp:~/dogecoin$ ./dogecoin-qt
Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
keefer@yiimp:~/dogecoin$ ./dogecoin-qt
Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
keefer@yiimp:~/dogecoin$ ./dogecoin-qt -server
Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.

**Dogecoin Core version**
<!-- List the version number/commit ID, v1.14.5.0.0-31afd1331
**Machine specs**
- OS:  Debian 11
- CPU:  (dual) Dual-core Intel Xeon Processor 5150
- RAM: 8 gb ea.
- Disk size: 1tb/1tb
- Disk Type (HD/SDD): both HD/SDD

**Extra information**
dogecoin.conf

rpcuser=xxxxxxxx
rpcpassword=xxxxxxxxxxxxxxxxxxxxxxxxx
rpcport=22556

listen=0 

rpcthreads=8
rpcallowip=127.0.0.1
# onlynet=ipv4
maxconnections=150
daemon=1
gen=0

alertnotify=echo %s | mail -s "Dogecoin alert!" cryptomining2023@outlook.com
blocknotify=blocknotify nextgenmining.net:3433 146 %s

**Comment by chromatic** [comment]
Bitcoin addressed this with [PR #16254](https://github.com/bitcoin/bitcoin/pull/16254). See the linked PR.

**Comment by ReverseControl** [comment]
@chromatic @patricklodder, it seems the code fix is here (https://github.com/bitcoin/bitcoin/commit/099e4b9ad3d9967051d5c3d45c6315d1b30fea05). Should this be ported for 1.14.6 or 1.21?

**Comment by chromatic** [comment]
@ReverseControl Yep, PR #16524 is against 1.14.6.

**Comment by patricklodder** [comment]
Fixed with #2778
