### ISSUE TITLE
[bug] Incorrect translations and missing translations in file dogecoin/src/qt/locale/bitcoin_ko_KR.ts

### ISSUE THREAD

**Issue by steve-cw-chung** [dogecoin/dogecoin#2799]
# Bug Report

**Current behavior:**

Incorrect translations and missing translations in file dogecoin/src/qt/locale/bitcoin_ko_KR.ts
**Expected behavior**

**Steps to reproduce:**

**Screenshots**

**Dogecoin Core version**

**Machine specs**
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

**Extra information**

**Comment by steve-cw-chung** [comment]
I corrected the incorrect translations and added all the missing translations.

**Comment by patricklodder** [comment]
Fixed with https://github.com/dogecoin/dogecoin/pull/2807
