### ISSUE TITLE
Korean translation still contains "bitcoin" in source strings

### ISSUE THREAD

**Issue by patricklodder** [dogecoin/dogecoin#2821]
_Originally posted by @dogespacewizard in https://github.com/dogecoin/dogecoin/issues/2529#issuecomment-999727051_:

I'm not very good with code so im not sure the right terms for this or even if this is relevant to your post or if its reiterating what you need but but there are 4 instances in the file for the <source> line that use the word 'Bitcoin' instead of 'Dogecoin' in comparison with the bitcoin_en.ts file, the translation for each of these lines however correctly have the Korean term for Dogecoin = "도지코인"

I could replace the instances of "Bitcoin" being used in the 4 <source> lines with "Dogecoin" if needed 

![image](https://user-images.githubusercontent.com/89301283/147127860-bb295b52-6b18-4a01-80b7-8bf589a47789.png)
![image](https://user-images.githubusercontent.com/89301283/147127873-3945e253-629c-4561-99a5-ddd21340a420.png)
![image](https://user-images.githubusercontent.com/89301283/147127889-e6514ec6-9ddb-4d1d-913a-96b1f35a8a6f.png)
![image](https://user-images.githubusercontent.com/89301283/147127898-85829e7e-0d22-4cd6-983b-dc53747b27fc.png)

---------

We should investigate why this happened, and if this happened on other translations that were updated with #2589 as well.

**Comment by dogespacewizard** [comment]
my apologies im not exactly sure why but after double checking the file it seems that the 4 instances are correctly marked as Dogecoin

im fairly new to github so i think the issue was on my end
again my apologies

**Comment by patricklodder** [comment]
Okay ❤️

**Comment by Ufakeimdope** [comment]
https://open.spotify.com/track/49BdaEKbK8wgcjCiZFn8Mb?si=M7tHTJi8RuW4P8MImhC9iw&utm_source=copy-link
