### ISSUE TITLE
Dogecoin transaction has been disappeared [bug] 

### ISSUE THREAD

**Issue by ikamran** [dogecoin/dogecoin#2838]
I have send some dogefrom dogecoin core server which i had installed for more than a year,

#dogecoin-cli sendtoaddress .DBdu1m77om6gu9hLGnZrhrHrjyAu722ima 150.477 "" "" true
d4143c93e93845a2662129504271457c3b715039013431f335446af33d163b15

I got txid and I thouht everything is okay after more than an hour I see no transaction on dogecoin explorer and also 

I see transaction has been done in my server.
pleade somebody tell me what is the issue on dogecoin?

Dogecoin Core RPC client version v1.14.0.0-gea4a3c5e16 is installed on Ubuntu server
#dogecoin-cli listtransactions
.....
..
..
.
  {
    "account": "",
    "address": "DBdu1m77om6gu9hLGnZrhrHrjyAu722ima",
    "category": "send",
    "amount": -150.47700000,
    "vout": 0,
    "fee": -2.00000000,
    "confirmations": 0,
    "trusted": true,
    "txid": "d4143c93e93845a2662129504271457c3b715039013431f335446af33d163b15",
    "walletconflicts": [
    ],
    "time": 1644329691,
    "timereceived": 1644329691,
    "bip125-replaceable": "no",
    "abandoned": false
  }
]

**Comment by patricklodder** [comment]
Hi! You're using a very old version and there is a bug in 1.14.0 that may send dust outputs that get rejected by later versions. 

I suspect this is the case for you here, would you mind sharing the full transaction hex? You can get it with `dogecoin-cli gettransaction d4143c93e93845a2662129504271457c3b715039013431f335446af33d163b15`

**NOTE: PLEASE DON'T UPDATE YET!** - we have to assess what transactions are in your wallet before you do that, I'll write you a process here to make sure how to exactly do this if this turns out to be a case of the 1.14.0 dust issue.

**Comment by ikamran** [comment]
root@ltc:/home/ltcsrvuser# dogecoin-cli gettransaction d4143c93e93845a2662129504271457c3b715039013431f335446af33d163b15
{
  "amount": -150.47700000,
  "fee": -2.00000000,
  "confirmations": 0,
  "trusted": true,
  "txid": "d4143c93e93845a2662129504271457c3b715039013431f335446af33d163b15",
  "walletconflicts": [
  ],
  "time": 1644329691,
  "timereceived": 1644329691,
  "bip125-replaceable": "no",
  "details": [
    {
      "account": "",
      "address": "DBdu1m77om6gu9hLGnZrhrHrjyAu722ima",
      "category": "send",
      "amount": -150.47700000,
      "vout": 0,
      "fee": -2.00000000,
      "abandoned": false
    }
  ],
  "hex": "0100000003fc64b592f7371458821848711c429a14dd3cbc1b7d4f93c4c87ba5cf6c2f526a000000006b483045022100e67095733a62da4f976b392b3fa0db75870bf49b3661231e63e386dd7a6248bc02201f58125cc919bdb7ef88bd3103dc0e99d98fd21903f8cea754b9ff4467f80da301210359e6982e47adad1c1eae09f886e5dae6bcf5bbc2ba2186195f73ca105f84e3c9feffffff6a5b285dc3a74c70ceed9e04d1b8b2628a7b038966587ba61a0ad0dd0b3b1b5f000000006a4730440220518bfbe01b27961b36bf9aef2335afe9908b20d71a62833e5651fff2489d1d7502205f9706815bb1904727dd00dc6087663d76beefaa18db0bbb70a3777d626b4a3801210359e6982e47adad1c1eae09f886e5dae6bcf5bbc2ba2186195f73ca105f84e3c9feffffff97c52dc393fee58db7b8ed331b353f5004bb9dfc79eb9b572a07222785b6203f000000006b48304502210098a81f94866d4555f33c55e4e33a8a559503e9a3024cbab7eaf97b304c593831022074f873efd3fa954cd907038251f768265e9ee9c493584aa79963e5e7d823584b012103d2acd7a3614e7d36d8f97eb8ff9ebf8363d53943ab4e8900bc3f1efa8c4b9b5ffeffffff0220aee980030000001976a91447433242ae213c931b7cdf09e37e6da5af6336d988ac3a270000000000001976a9146f38fe8e51711e81ae31d83a4b5fe2d299e3301188acc67f3e00"
}

**Comment by ikamran** [comment]
after your post i tried:
https://live.blockcypher.com/doge/pushtx/
and used the above "Transaction Hex", tried to broadcast transaction
I got:
Error validating transaction: Transaction with hash d4143c93e93845a2662129504271457c3b715039013431f335446af33d163b15 already exists..

**Comment by patricklodder** [comment]
@ikamran this is indeed a low fee change output. It attempts to send 0.00010042 DOGE to a change address. 

Here's my recommendation to resolve, upgrade and make sure your funds don't get spent again by anyone other than you (and as a bonus, pay much lower fees from now on):
1. Check if you have any other transactions with no confirmations, easiest to do this with `jq` (`sudo apt-get install jq` if you don't have that). Assuming you have made less than 100,000 transactions from your wallet, the command line you want to do is:

```console
$ dogecoin-cli listtransactions "*" 100000 0 | jq -r '.[] | select(.confirmations == 0) | [.txid, .amount] | join (" ")'

...
d4143c93e93845a2662129504271457c3b715039013431f335446af33d163b15 -150.47700000
```

if you have more than 100,000 transactions in this wallet, you can change the last parameter to skip 100000 at a time, eg `dogecoin-cli listtransactions "*" 100000 100000` and so on. Note that EACH transaction in this list is currently stuck, but to unstuck it AND keep your funds secure, you're going to have to do some labor.

2. Save the list
3. For each transaction in the list, note down the inputs and outputs, use this:

**inputs:**

```console
$ dogecoin-cli gettransaction <txid> | jq -r .hex | xargs dogecoin-tx -json | jq -r '.vin[] | [.txid, .vout] | join(":") '
6a522f6ccfa57bc8c4934f7d1bbc3cdd149a421c71481882581437f792b564fc:0
5f1b3b0bddd00a1aa67b586689037b8a62b2b8d1049eedce704ca7c35d285b6a:0
3f20b6852722072a579beb79fc9dbb04503f351b33edb8b78de5fe93c32dc597:0
```

and **outputs:**

```console
$ dogecoin-cli gettransaction <txid> | jq -r .hex | xargs dogecoin-tx -json | jq -r '.vout[] | [.value, .scriptPubKey.addresses[]] | join(":") '
150.477:DBdu1m77om6gu9hLGnZrhrHrjyAu722ima
0.00010042:DFHBpb82Cxbxj9TUomiUDA6FmwPhFStYg7
```

4. Disable each transaction from the list in step 1: `dogecoin-cli abandontransaction <txid>`
5. Shut down dogecoind
6. Upgrade to 1.14.5 by [downloading the binary](https://github.com/dogecoin/dogecoin/releases/tag/v1.14.5) or from source using `make clean` and then `git checkout v1.14.5`.
7. Restart your dogecoind
8. For each transaction in the list in step 2, create a change address, and send all the inputs there, like this:

```console
$ dogecoin-cli getrawchangeaddress
DMuFnBkn8KgkE5aHW2zCPKDETKUHuBkrTW

$ dogecoin-tx -create in=6a522f6ccfa57bc8c4934f7d1bbc3cdd149a421c71481882581437f792b564fc:0 in=5f1b3b0bddd00a1aa67b586689037b8a62b2b8d1049eedce704ca7c35d285b6a:0 in=3f20b6852722072a579beb79fc9dbb04503f351b33edb8b78de5fe93c32dc597:0 outaddr=150.47700000:DMuFnBkn8KgkE5aHW2zCPKDETKUHuBkrTW | xargs dogecoin-cli signrawtransaction

{
  "complete": true,
  "hex": "<large hex string>"
}

$ dogecoin-tx sendrawtransaction <large hex string>
<new txid>
```

alternatively, you can try to send your entire balance from `dogecoin-cli getbalance` to a new address, but be aware that this will expose every address in your wallet that has coin in it as belonging to the same person, so you'll de-anonymize yourself.

9. Now you can resend any transactions you want to repeat that got stuck, by using `sendtoaddress` like you're used to.

**Comment by victorsk2019** [comment]
Change output is not at index 0 😢

**Comment by ikamran** [comment]
> ```
> dogecoin-cli listtransactions "*" 100000 0 | jq -r '.[] | select(.confirmations == 0) | [.txid, .amount] | join (" ")'
> ```

I am tryng to do steps you said but for me the first command shows error:

```
root@ltc:/home/ltcsrvuser# dogecoin-cli listtransactions "*" 100000 0 | jq -r '.[] | select(.confirmations == 0) | [.txid, .amount] | join (" ")'
error: join is not defined
.[] | select(.confirmations == 0) | [.txid, .amount] | join (" ")
                                                       ^^^^
1 compile error
root@ltc:/home/ltcsrvuser#

```
Sorry for that I coundt use this command for unknown reason

**Comment by patricklodder** [comment]
> first command shows error

Looks like an older version of `jq`. You can remove the last pipe and the `join (" ")` so it will become:

```
dogecoin-cli listtransactions "*" 100000 0 | jq -r '.[] | select(.confirmations == 0) | [.txid, .amount]'
```

> also unable to abandontransaction !

I forgot that 1.14.0 still has a default 10 day mempool 🤓, and that stops you from abandoning it. If after running the above command this is the only transaction with the issue (that's expected because you only have the single change utxo) the best way forward is then to:

1. skip straight to step 5
2. Do the 1.14.5 install
3. when restarting under step 7, start as `dogecoind -mempoolexpiry=1` - this will set your mempool to expire everything older than 1 hour
4. now do `dogecoin-cli abandontransaction "d4143c93e93845a2662129504271457c3b715039013431f335446af33d163b15"`
5. just resend the entire transaction, minus 0.01 DOGE for fee

**Comment by ikamran** [comment]
```
root@ltc:/home/ltcsrvuser# dogecoin-cli listtransactions "*" 100000 0 | jq -r '.[] | select(.confirmations == 0) | [.txid, .amount]'
[
  "33ad85b9b2bfb5f642506b1116639ed8c69189b5f7e1ea1db56b966161dcd3f8",
  -3072.19662058
]
[
  "aa6a5e32efd25aa15a8c0effe0f3f3ec26692d804ae7c8f2f34d0d21e8eceef7",
  -1785.71428571
]
[
  "1060e8994e974395419056868bc221bb4532af81ede7e9ca618f82d3d99e3b25",
  -1190.47619047
]
[
  "512efb737625d307cca1bb02a5b995506ea600c3ab95faf774bc9199b1a0e568",
  -1
]
[
  "0d923214c1f1dcea23a286046c4c54a8dd9547d1e02242f95e159ebabf98219d",
  -2
]
[
  "d1887df28baa1ae8a8b19aabfe7aaa47239eb54ba832b0d373d6840740a8e5cf",
  -1000
]
[
  "d4143c93e93845a2662129504271457c3b715039013431f335446af33d163b15",
  -150.477
]
root@ltc:/home/ltcsrvuser#

```

the above is the result of 

`dogecoin-cli listtransactions "*" 100000 0 | jq -r '.[] | select(.confirmations == 0) | [.txid, .amount]'`

it seems I have lot more stucked transactions right?

**Comment by ikamran** [comment]
now my balance shows 

```
root@ltc:~/.dogecoin# dogecoin-cli getbalance
7060.31828022
root@ltc:~/.dogecoin# dogecoin-cli sendtoaddress DQc3koWSgQ5FjTkRiU4GdRJyVzMiuTaEdg 1
4d6d88658d4ff4aada799f425f832c21432162cfa56f277cb75f14cda7c6e515
root@ltc:~/.dogecoin#

```

I also did the same before running "dogecoind -mempoolexpiry=1" I got txid dedcuted from balance but nothing showed on 
block explorer 
d551dff9dbfe96fcf2935ebc41709488cacc78bb27832464c4938615bb8eb1ff


to test out i start the current version with "dogecoind -mempoolexpiry=1" and send transcation 
it deduct from balance and shows txid but nothing appear in blockexplorer

Please help me to get these coin from the wallet and upgrade it 
anyway i can not get any coins from core server

**Comment by patricklodder** [comment]
You can check if they're stuck or abandoned by doing `gettransaction` on them - under `details.abandoned`. if they're not abandoned, you can `abandontransaction` them and see fresh utxo.

**Comment by ikamran** [comment]
> You can check if they're stuck or abandoned by doing `gettransaction` on them - under `details.abandoned`. if they're not abandoned, you can `abandontransaction` them and see fresh utxo.

I see, I sent you all debug information to be able to help me
now I see my balance
I tied to send, it sent and give me txtid, but actually nothing is showing on blockchain explorer
https://chain.so/tx/DOGE/4d6d88658d4ff4aada799f425f832c21432162cfa56f277cb75f14cda7c6e515

Can you give me the solution?
i have wallet.dat
the issue now is I can not send anything 
Is my coins safe?

**Comment by patricklodder** [comment]
> Please help me to get these coin from the wallet and upgrade it

- `dogecoin-cli stop`
- backup your `.dogecoin/wallet.dat` to somewhere secure - just in case
- download 1.14.5 from https://github.com/dogecoin/dogecoin/releases/tag/v1.14.5 (e.g. `curl -L -O https://github.com/dogecoin/dogecoin/releases/download/v1.14.5/dogecoin-1.14.5-x86_64-linux-gnu.tar.gz`) 
- untar it with `tar zxfv  dogecoin-1.14.5-x86_64-linux-gnu.tar.gz`)
- copy the contents of dogecoin-1.14.5/bin over where your dogecoin binaries are now (find the path with `which dogecoind`)
- run `dogecoind -mempoolexpiry=1`
- run `dogecoin-cli abandontransaction d551dff9dbfe96fcf2935ebc41709488cacc78bb27832464c4938615bb8eb1ff` (if it still has not been mined after 1 hour) and `dogecoin-cli abandontransaction d4143c93e93845a2662129504271457c3b715039013431f335446af33d163b15`
- now you can just use `sendtoaddress` and your transactions should get mined after a couple of blocks at most.

**Comment by ikamran** [comment]
> > Please help me to get these coin from the wallet and upgrade it
> 
> * `dogecoin-cli stop`
> * backup your `.dogecoin/wallet.dat` to somewhere secure - just in case
> * download 1.14.5 from https://github.com/dogecoin/dogecoin/releases/tag/v1.14.5 (e.g. `curl -L -O https://github.com/dogecoin/dogecoin/releases/download/v1.14.5/dogecoin-1.14.5-x86_64-linux-gnu.tar.gz`)
> * untar it with `tar zxfv  dogecoin-1.14.5-x86_64-linux-gnu.tar.gz`)
> * copy the contents of dogecoin-1.14.5/bin over where your dogecoin binaries are now (find the path with `which dogecoind`)
> * run `dogecoind -mempoolexpiry=1`
> * run `dogecoin-cli abandontransaction d551dff9dbfe96fcf2935ebc41709488cacc78bb27832464c4938615bb8eb1ff` (if it still has not been mined after 1 hour) and `dogecoin-cli abandontransaction d4143c93e93845a2662129504271457c3b715039013431f335446af33d163b15`
> * now you can just use `sendtoaddress` and your transactions should get mined after a couple of blocks at most.
> 
> > Is my coins safe?
> 
> yes.
First of all, I am very appreciate for your help, now dogecoin is really superfast, really changed with very low transactions, unbelievable
you helped me a lot, I hope you be sucess in all your life buddy
 
just for sure I am asking last question
can I then start like before
dogecoind --daemon ?

**Comment by patricklodder** [comment]
in that case use `dogecoind -mempoolexpiry=1 -daemon`
