### ISSUE TITLE
[feat] Allow send < 1 Doge wen using  fundrawtransaction

### ISSUE THREAD

**Issue by qlpqlp** [dogecoin/dogecoin#2846]
# Feature Request

Wen creating an Raw Transaction, and using the fundrawtransaction, we cant send less then 1 Doge. It show be able to send at least 0.1 Doge :)

**Describe the Feature Request**
Be able to fundrawtransaction lower then 1 Doge

**Describe Preferred Solution**
send bigger then 0.02 Doge (i know, spam is a problem :P)

**Describe Alternatives**
Don't know any outher lol

**Related Code**
fundrawtransaction()

**Additional Context**
for future currency of earth it should be able to do micro transactions, there are times we need to pay less then 1 Doge :P
we have to think another alternative to stop "SPAM" :)

**Comment by patricklodder** [comment]
You can change the `-discardthreshold` of your wallet to something under 1 DOGE if you have 1.14.5. Note that currently, only a couple of pools will accept and mine transactions with outputs under 1 DOGE, so it will take a little longer for your transaction to get confirmed. 

Once more pools accept lower output amounts, we can change the wallet default configuration. I did a transaction with a < 1 DOGE output yesterday, which took 3 blocks to get mined, so we're not there yet, but we're definitely getting there.

**Comment by qlpqlp** [comment]
Much Thanks, Great News! :)

For small candy, or coffee grains stores for exemple, it's needed the amount minimum of 0.1 Doge equivalent for exemple to 0.1 Euros or 0.1 USD
