### ISSUE TITLE
[bug] Hello developers, can you solve the problem of scaling display in Win11 system

### ISSUE THREAD

**Issue by carlray1988** [dogecoin/dogecoin#2855]
Hello developers, can you solve the problem of scaling display in Win11 system, my 4k screen, when the system scaling settings 300%, dogecoin software fonts and windows are not displayed properly, thank you!

**Comment by chromatic** [comment]
PR #2778 will be in 1.14.6 and subsequent releases. If you're comfortable testing code under development, you could compile and give it a try.

I'm not sure anyone's making preview releases for any platform yet though, so if you're not comfortable compiling and testing on your own, perhaps you can follow up after the release or preview release?

**Comment by patricklodder** [comment]
I'm running a gitian build on d483dfba for windows, will supply executable.

**Comment by patricklodder** [comment]
Gitian gives me these archives:

```
7de5e2a8d57dee64affee6f45453956742e9d23e437b6dfa7ed9e2163f0be24a  dogecoin-1.14.6-win32-debug.zip
ffe471b49d1d787fe8574a1c734d219b602f6933636f029ce352a01ae5f26c11  dogecoin-1.14.6-win32.zip
ff48eef161eae81dd029c6eb8bf868d0d94a407ccfa9458fe92a5b4d8bd7d9ce  dogecoin-1.14.6-win64-debug.zip
256691135206592f294b25edda327782ca54120247864db454b12490423f0a4e  dogecoin-1.14.6-win64.zip
```

You can download them here: https://gateway.ipfs.io/ipfs/QmekRgJ8mK1UcWMPxQBBT4WjZjiezcqGkW6TNzmywk2DTc

Please let us know if this version solves the issue. If it doesn't, we might be able to solve it when we update QT (which is on the to do list)
