### ISSUE TITLE
Start calling dogecoin doggy coin 

### ISSUE THREAD

**Issue by TrapMinister** [dogecoin/dogecoin#2862]
# Feature Request

**Describe the Feature Request**

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by patricklodder** [comment]
Hi! You can call it whatever you want, but for now, let's stick with the spelling as-is. Saves confusion.

**Comment by TrapMinister** [comment]
My point is you are confused, the spelling is fine, seems people cannot
read.
