### ISSUE TITLE
[bug] dogecoin-cli getaddressinfo command doesn't work

### ISSUE THREAD

**Issue by EV6999** [dogecoin/dogecoin#2878]
# Bug Report

**Current behavior:**

dogecoin-cli getaddressinfo command doesn't work
**Expected behavior**

Can't find any related information about dogecoin-cli getaddressinfo command deprecated
**Steps to reproduce:**

**Screenshots**

**Dogecoin Core version**

**Machine specs**
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

**Extra information**

**Comment by patricklodder** [comment]
`getaddressinfo` is not implemented in 1.14. It never has been implemented for Dogecoin Core, so it's not deprecated, this is why there is no notice of such event.

It will be introduced with 1.21, but we could look into backporting it. What exactly did you want to use it for?

**Comment by EV6999** [comment]
Thank you @patricklodder . 
I want to get these two information for a given address. Is there any other way to get them?
"ismine" : true|false,            (boolean) If the address is yours.
"iswatchonly" : true|false,       (boolean) If the address is watchonly.
