### ISSUE TITLE
[bug] build/ci: focal and g++-9-cross are broken for ARMv82+crypto

### ISSUE THREAD

**Issue by patricklodder** [dogecoin/dogecoin#2879]
# Bug Report

**Current behavior:**

Currently, the CI fails when compiling ARMv82 experimental using focal/g++-9. This seems to be an issue in the `libgcc-9-dev-arm64-cross` ubuntu package. , but that doesn't explain why we didn't see this before.)

**Steps to reproduce:**

See for example [CI#627/aarch64-linux-sha512-experimental](https://github.com/dogecoin/dogecoin/runs/5527795411?check_suite_focus=true#step:11:796)

**Solution:**

It looks like [the issue got fixed in the meantime on the gcc repo](https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=8c92fcb13a4979232787f0476bf7469ccbb03617), but this has not been picked up for focal yet. gcc 10.3, does not have this issue.

We could use the `g++-10-aarch64-linux-gnu` package, which installs `libgcc-10-dev-arm64-cross`, see [my CI#740](https://github.com/patricklodder/dogecoin/runs/5636255928?check_suite_focus=true#step:11:736) for a successful run

As it is unlikely that we'll ever release a 1.14.x built with focal (due to that breaking macOS compatibility) switching to gcc 10 should not be too big an issue in this case. We will have to live with a high probability (already, but this makes it worse) that this feature cannot go out of experimental for 1.14, and can only be released on a major release where we can do breaking changes, i.e. with 1.21.

Alternatively we can mess around with the dependency system and build our own gcc.

@edtubbs any thoughts / preference?

**Comment by chromatic** [comment]
Maybe this is a terrible idea, but would shipping only that patched header *locally* be less intrusive? It'd be a shame to keep this experimental all the way until the 1.21 release. I bet there's a way to include that header file only for ARM builds.

**Comment by patricklodder** [comment]
We'd need to patch the file under `/usr/lib/gcc-cross/aarch64-linux-gnu/9/include/arm_acle.h` so that's a sudo operation. 

Note that the main problem re: getting this out of experimental is that we'd need to build on focal due to gcc 9 (or 10), so we'd have to figure out a way to retain macOS sdk version compatibility. We can give that a renewed effort, but I am cautious to spend enormous time on that, which may be better spent on doing 1.21. We have a year left on bionic / 1.14 right now, and focal would extend that, but it will always come at the cost of progress with 1.21 (which will bring lots of improvements if we can do it right) - so I'm not 100% sure if it's worth it.

**Comment by patricklodder** [comment]
@chromatic I am starting to realize I misread your comment last night. Did you mean that we may be able to put `arm_acle.h` into `src/compat` and include that in the `src/crypto/sha-*.cpp` files instead? May even solve issue with having to use gcc 9 if we're lucky.

**Comment by patricklodder** [comment]
I have a PR at #2882 that implements the above. Fixes the issue for Ubuntu's GCC 9.4 headers, but it does not make this work on gcc 7. If we want that, we'll need to extend the header selection in `src/compat/arm_acle_selector.h` from that PR, to add gcc-7 compliant functionality (a lot of the builtin functions have been reworked between gcc 7 and 8, so would be a larger effort.)

**Comment by patricklodder** [comment]
This is now fixed with #2907.
