### ISSUE TITLE
[Suggestion] Prompt for password on wallet generation

### ISSUE THREAD

**Issue by felixvd** [dogecoin/dogecoin#289]
Hi,

I think everyone agrees that no one should leave their wallet unencrypted. In fact, I wonder why the client allows unencrypted wallets at all.

When a new wallet is generated, the dialogue for encrypting the wallet should be started automatically afterwards. It would also be good if the popup mentioned the importance of encrypting your wallet and setting a strong password.

I think this would protect new and inexperienced users from being burned by many forms of malware and intrusion, and go a long way in terms of user experience. Would be glad to know what you think.

Cheers

**Comment by ketsa** [comment]
Please - at least leave the option open for a blank password.
Who knows if more coins have been lost to forgotten passwords or malware/hacks.
