### ISSUE TITLE
[bug] autogen.sh warns

### ISSUE THREAD

**Issue by Krimchanin** [dogecoin/dogecoin#2904]
# Bug Report

autogen.sh warns about the GZIP_ENV variable and the 'mm.o' target being overridden in macOS, with automake 1.15.1 installed.

Makefile.am:12: warning: user variable 'GZIP_ENV' defined here ...
/usr/share/automake-1.15/am/distdir.am: ... overrides Automake variable 'GZIP_ENV' defined here
src/Makefile.am: installing 'build-aux/depcomp'
src/Makefile.am:502: warning: user target '.mm.o' defined here ...
/usr/share/automake-1.15/am/depend2.am: ... overrides Automake target '.mm.o' defined here
parallel-tests: installing 'build-aux/test-driver'
pool@pool-server:~/dogecoin$ ^C
pool@pool-server:~/dogecoin$ ^C
pool@pool-server:~/dogecoin$ ./autogen.sh... overrides Automake target '.mm.o' defined here

**Comment by patricklodder** [comment]
Thanks! 

There are some upstream fixes available for this that we can backport into 1.14 (and are already part of 1.21): bb9ab0fc
