### ISSUE TITLE
[feat] Prune block storage on Dogecoin Core GUI

### ISSUE THREAD

**Issue by sidan5** [dogecoin/dogecoin#2928]
# Feature Request

**Description:** Add support for *Prune block storage* to reduce full node size. Currently the blockchain data size is more than 50 GB and counting. Other wallets have this mode enabled on the GUI. it would be great to adapt that.

**Solution:** Have prune block storage option on the GUI

**Alternatives:** Can probably set that up from command line or using conf file but it's not trivial (if that would work).

**More Information:** Attached screenshot of this feature from Bitcoin Core Wallet.
![Screen Shot 2022-04-16 at 21 43 13](https://user-images.githubusercontent.com/1595490/163687493-3b309e43-bfc2-4b70-8f74-bf9e0d647916.png)

**Comment by chromatic** [comment]
Good news; this is underway in #2923!

**Comment by Administratordes** [comment]
Hello GoodDay if you need any help or assistance regarding to any issue at all please don’t hesitate to contact the LiveChat Support https://direct.lc.chat/14065185/

**Comment by chromatic** [comment]
This feature will be available in 1.14.6. Thanks for reporting!
