### ISSUE TITLE
[feat] 1.21 testnet synchronization

### ISSUE THREAD

**Issue by victorsk2019** [dogecoin/dogecoin#2990]
Hi everyone,

I would like to propose a "temporary" synchronization fix for Dogecoin Core 1.21 that may allow us to further work and improve 1.21 which is otherwise made impossible due to this current synchronization impediment.

According to [BlockChair Explorer](https://blockchair.com/dogecoin/nodes), there are currently only 2 version 1.21 nodes running.  The issue, as I understand it, is when my 1.21 local node is attempting to synchronize with another 1.21 version, it cannot obtain more blocks past 371337 block on mainnet and 158100 on testnet because other 1.21 nodes are facing the same problem.  It is, in essence, a case of "blind leading the blind" 😮.  What happens is my 1.21 node is sending protocol version 70016, the other 1.21 node is replying with _verack_ and they both are stuck with the same issue being unable to get past aforementioned block numbers and synchronize fully.

Added: The idea is, in theory, is that once 1.14.5 node receives protocol version 1.14.5 from 1.21 node, it will acknowledge it (_verack_) assuming that it is dealing with 1.14.5 node and send 1.21 node additional blocks.

# Feature Request

**Describe the Feature Request**
What I propose is that we (temporarily) change protocol version of 1.21 from 70016 to 70015 and make the 1.21 node work off of 1.14.5 chain. 

**Describe Preferred Solution**
 In version.h of Dogecoin Core 1.21 make the following change:

`static const int PROTOCOL_VERSION = 70015`

Additionally, implement the following values for testnet part in chainparams.cpp:

```
checkpointData =  {
            {   
                { 0, uint256S("0xbb0a78264637406b6360aad926284d544d7049f45189db5664f3c4d07350559e")},
                { 483173, uint256S("0xa804201ca0aceb7e937ef7a3c613a9b7589245b10cc095148c4ce4965b0b73b5")},
                { 591117, uint256S("0x5f6b93b2c28cedf32467d900369b8be6700f0649388a7dbfd3ebd4a01b1ffad8")},
                { 658924, uint256S("0xed6c8324d9a77195ee080f225a0fca6346495e08ded99bcda47a8eea5a8a620b")},
                { 703635, uint256S("0x839fa54617adcd582d53030a37455c14a87a806f6615aa8213f13e196230ff7f")},
                { 1000000, uint256S("0x1fe4d44ea4d1edb031f52f0d7c635db8190dc871a190654c41d2450086b8ef0e")},
                { 1202214, uint256S("0xa2179767a87ee4e95944703976fee63578ec04fa3ac2fc1c9c2c83587d096977")},
                { 1250000, uint256S("0xb46affb421872ca8efa30366b09694e2f9bf077f7258213be14adb05a9f41883")},
                { 1500000, uint256S("0x0caa041b47b4d18a4f44bdc05cef1a96d5196ce7b2e32ad3e4eb9ba505144917")},
                { 1750000, uint256S("0x8042462366d854ad39b8b95ed2ca12e89a526ceee5a90042d55ebb24d5aab7e9")},
                { 2000000, uint256S("0xd6acde73e1b42fc17f29dcc76f63946d378ae1bd4eafab44d801a25be784103c")},
                { 2250000, uint256S("0xc4342ae6d9a522a02e5607411df1b00e9329563ef844a758d762d601d42c86dc")},
                { 2500000, uint256S("0x3a66ec4933fbb348c9b1889aaf2f732fe429fd9a8f74fee6895eae061ac897e2")},
                { 2750000, uint256S("0x473ea9f625d59f534ffcc9738ffc58f7b7b1e0e993078614f5484a9505885563")},
                { 3062910, uint256S("0x113c41c00934f940a41f99d18b2ad9aefd183a4b7fe80527e1e6c12779bd0246")},
                { 3286675, uint256S("0x07fef07a255d510297c9189dc96da5f4e41a8184bc979df8294487f07fee1cf3")},
                { 3445426, uint256S("0x70574db7856bd685abe7b0a8a3e79b29882620645bd763b01459176bceb58cd1")}
            }  
        };

        chainTxData = ChainTxData{
            // Data from RPC: getchaintxstats 4096 a113c41c00934f940a41f99d18b2ad9aefd183a4b7fe80527e1e6c12779bd024
            /* nTime    */ 1613217942,
            /* nTxCount */ 4186373,
            /* dTxRate  */ 0.05,
        };
```
(moved from 1.14.5).  During my tests, I believe I have seen ~~`getinfo`~~ `getnetworkinfo` returning version 1.14.5 on my 1.21 installation. 

If this is an acceptable solution, and allows full synchronization on 1.21 testnet using 1.14.5 testnet chain, it will allow us to work off this chain with version 1.21 while further modifying it with Dogecoin-specific consensus parameters and a separate AuxPOW data structure implemented in 1.14.5.  Once 1.21 is configured with Dogecoin-specific chain and consensus parameters, we would then switch back to 1.21 protocol version and work off that instead.

I hope this doesn't sound like a total nonesense 🤣  I will welcome any feedback, or if there are any better suggestions, please do share them.  Thank you.

**Comment by patricklodder** [comment]
It will work once the code is in, why do you need a 1.21 node now?

**Comment by victorsk2019** [comment]
I don't "need" 1.21 node _per se_.  It just seems like a fun challenge to make it synchronize and 1.21 version offers additional features like creation of new wallets so I'd like to see it functional sooner rather than later 😃

**Comment by patricklodder** [comment]
If you want to make it synchronize, including wallet, let's fix pr #2977 it's a good step towards that goal.

There is no point in trying to make 1.21 work if then we get 300 oopsies when we do a softfork on 1.21.1. Instead, we have to do it right now, or we'll miss things - and missing things will cost users actual money. As it did with 1.14.

As soon as I have the currently pressing 1.14.6 work out of the way, I'll be all over 1.21 and helping you getting this milestone done.

**Comment by victorsk2019** [comment]
Thank you.  I am working on https://github.com/dogecoin/dogecoin/pull/2977 as well, just thought to bring this idea forward in case it could be found useful.  Note: I meant to work only on testnet, without touching mainnet.  I guess I am not going to win a Nobel Prize with this idea, eh? 😜

**Comment by patricklodder** [comment]
Sorry, no Nobel prices. But you'll get the shibe-of-the-day award for fixing 2977 ❤️
