### ISSUE TITLE
[feat] The ability to set the uacomment through the Dogecoin Core UI

### ISSUE THREAD

**Issue by alamshafil** [dogecoin/dogecoin#3020]
# Feature Request

**Describe the Feature Request**
As requested by @CalisCihan (Salty_Word_624) on Twitter, they want the ability to set the `uacomment` through the Dogecoin Core UI instead of having to manually edit the `dogecoin.conf` file.

**Describe Preferred Solution**
Implement a input field in `optionsdialog.ui` to allow some to input a custom `uacomment`.

**Describe Alternatives**
Put input field in another location in the UI.

**Related Code**
![image](https://user-images.githubusercontent.com/36016500/176200390-242171e7-5fb5-4022-8a0c-f8c3c6502369.png)
This is a visualization, can be put anywhere.

**Additional Context**
Shibes want to reward dogecoin node runners and be able to track such nodes runners.
[Twitter Link](https://twitter.com/CalisCihan/status/1541755519404331008)

**Comment by patricklodder** [comment]
Bob and Alice have replied to #3019. They are from the future.

**Comment by alamshafil** [comment]
Thanks for insight! Hope the community can learn from it. Sounds good to me :+1:
