### ISSUE TITLE
Changed code siganture in release 1.14.6?

### ISSUE THREAD

**Issue by suschizu** [dogecoin/dogecoin#3064]
# Bug Report

Can you confirm that the code signature has changed? 
download: https://github.com/dogecoin/dogecoin/releases/download/v1.14.6/dogecoin-1.14.6-osx-signed.dmg

**Current behavior:**
EXPECTED Maximilian Keller (LM5Q6S44JJ)

**Expected behavior**
FOUND Patrick Lodder (UHX689FLJ9)

**Steps to reproduce:**
code sign -dv --verbose=4 path/to/app

**Dogecoin Core version**
1.14.6

**Comment by patricklodder** [comment]
Confirm. Before, the signature was done by @langerhans, and this time it was done by me (@patricklodder)

**Comment by suschizu** [comment]
thanks for the fast confirmation :)

**Comment by patricklodder** [comment]
I have copied this Q&A to the release discussion at #3054 for more visibility.

I'll also think of a way to communicate this better next release.
