### ISSUE TITLE
[bug] Invalid settings in dogecoind.service

### ISSUE THREAD

**Issue by acerix** [dogecoin/dogecoin#3065]
# Bug Report

**Current behavior:**
Starting the service gives warnings of invalid settings.

**Expected behavior**
No warnings.

**Steps to reproduce:**
1. systemd 251 (251.3-1-arch) on Arch Linux
2. `systemctl start dogecoind`
3. `systemctl stop dogecoind`
4. `systemctl status dogecoind`

**Dogecoin Core version**
1.14.6

**Machine specs**
- OS: Arch Linux (Linux mun 5.18.12-zen1-1-zen \# 1 ZEN SMP PREEMPT_DYNAMIC Fri, 15 Jul 2022 15:33:04 +0000 x86_64 GNU/Linux)

**Extra information**
```
/usr/lib/systemd/system/dogecoind.service:22: Unknown key name 'StartLimitIntervalSec' in section 'Service', ignoring.
/usr/lib/systemd/system/dogecoind.service:30: Invalid memory limit '3g', ignoring: Invalid argument
```

**Comment by patricklodder** [comment]
Fixed with #3066
