### ISSUE TITLE
[bug] maxTxFee is not set to -maxtxfee if -disablewallet is also active

### ISSUE THREAD

**Issue by junderw** [dogecoin/dogecoin#3087]
# Bug Report

**Current behavior:**
Setting `-maxtxfee=1000.00` has no effect when `-disablewallet` is also active.

**Expected behavior**
Since sendrawtransaction RPC endpoint is also affected by maxtxfee, it should take effect even when CWallet is never initialized.

**Steps to reproduce:**
1. Start dogecoind with `-maxtxfee=1000.00` and `-disablewallet`
2. Use an external wallet to create a valid batch transaction with an absolute fee > 100 DOGE
3. Send it using the sendrawtransaction RPC
4. Get the absurd-high-fee error

**Screenshots**
None

**Dogecoin Core version**
v1.14.6

**Machine specs**
- OS: Ubuntu 20.04
- CPU: AWS vCPU (EC2)
- RAM: 8GB
- Disk size: 1000GB
- Disk Type (HD/SDD): HD

**Extra information**
The only place in the source that checks the -maxtxfee runtime arg is [here](https://github.com/dogecoin/dogecoin/blob/v1.14.6/src/wallet/wallet.cpp#L3964-L3977), but at the top of the function it does an early `return true` if -disablewallet is active.

**Comment by patricklodder** [comment]
Thank you!

**Comment by patricklodder** [comment]
Closing this as remaining work is tracked in #3090.
