### ISSUE TITLE
Dogecoin Core 1.14.6 Error Launching on Mac OS Ventura Beta 5

### ISSUE THREAD

**Issue by Cyclic** [dogecoin/dogecoin#3101]
![image](https://user-images.githubusercontent.com/553800/185274386-27207e96-fe0f-441d-9fd8-047c9490e2a8.png)

**Comment by alamshafil** [comment]
Which version of Dogecoin Core 1.14.7 did you install? The signed or the unsigned one? The signed build (`dogecoin-1.14.6-osx-signed.dmg`) has been notarized by Apple and *should* not display the error above. I am not too familiar with macOS, so please correct me if I am wrong. 

More infomation about the signed and unsigned builds for macOS can be found here: https://github.com/dogecoin/dogecoin/discussions/3054

**Comment by patricklodder** [comment]
@Cyclic If you did use the signed binary, could you please let us know the output of the following?

```sh
codesign -vvv --deep --strict /Applications/Dogecoin-Qt.app/Contents/MacOS/Dogecoin-Qt
```

That should tell us if there is anything we need to change for Ventura compatibility.

**Comment by etherx-dev** [comment]
can confirm doesn't work at first, right click on dogecoin and open and then crashes. but once it appears in the launchpad just click the icon and works.

**Comment by patricklodder** [comment]
> can confirm doesn't work at first, right click on dogecoin and open and then crashes

Is this performed inside the .dmg Finder window where you drag the .app file to the Applications folder?
