### ISSUE TITLE
dogecoin-cli cant connect to rpc

### ISSUE THREAD

**Issue by Noobslayer123** [dogecoin/dogecoin#3104]
i ve getting this issue since yesterday
![image](https://user-images.githubusercontent.com/79126456/185862864-f2fe6c06-83ba-4682-95b1-0323ed5ca65a.png)

**Comment by patricklodder** [comment]
@Noobslayer123 We'll need some more information to troubleshoot this with you:

1. What version do you use?
2. What is reported in debug.log around when you do this and when it first started? (you should be able to find that file in `%AppData%\Dogecoin`)

**Comment by Noobslayer123** [comment]
solved by waiting a day from running `dogecoind -server` 😁
