### ISSUE TITLE
[bug] 1.14.6 with 0 Inbounds - 8 Outbounds after 24-48h of running the node

### ISSUE THREAD

**Issue by cezardoob** [dogecoin/dogecoin#3111]
Hello!

With the 1.14.6 version, I often get 0 Inbounds after 1 or 2 days of running the node successfully and I have to restart it in order to get inbounds, although 22556 port is always open and fiber connection has 100% uptime. Didn't had this issue with previous versions (since 1.14.3) and always had minimum of 1 inbound and a maximum of 20 - 30 inbounds.

SS> https://ibb.co/54CN70f - https://ibb.co/NNhqpLJ

Don't know if it's OK to attach debug file here, pls help.

Thanks!

**Comment by DemonRx** [comment]
Hi!

You can use https://gist.github.com/ to paste your debug.log file and link here.

Also, what is the operating system it running on ?

**Comment by cezardoob** [comment]
> Hi!
> 
> You can use https://gist.github.com/ to paste your debug.log file and link here.
> 
> Also, what is the operating system it is running on ?

Hello! 

I'm running it on Win 10 Pro x64 21H2 https://gist.github.com/cezardoob/72b4fd0713842dd1edd069f9e93da13f

Thx!

**Comment by cezardoob** [comment]
Hello!

UPNP is always disabled from my ONT and the node seems to be working fine from yesterday, got peers and traffic :)
 I will add debug=net if I see 0 inbounds again and have to restart the node.

Thanks a lot, guys! I appreciate your help!

**Comment by patricklodder** [comment]
Alright. I'll close the issue for now - just let us know if it occurs again, and we'll reopen it.
