### ISSUE TITLE
Wallet Dimensions Skewed 

### ISSUE THREAD

**Issue by Eumaios1212** [dogecoin/dogecoin#3121]
I've just recently downloaded Dogecoin Core 1.14.6 for Linux. When I run it, however, the wallet GUI is massive, while letters of words within the wallet are minuscule. Spent a couple hours working on it with admins within Dogecoin's Discord channel. No luck. They suggested I post here. Not sure what else to try.

![Screenshot from 2022-09-24 14-35-37](https://user-images.githubusercontent.com/109111017/192117574-5e5e78b1-476d-43f4-9f9a-8010d31a2eb4.png)

![Device   OS](https://user-images.githubusercontent.com/109111017/192117588-51ad0b13-1528-48d3-8fac-9a6feafb7d0a.png)

Thank you.

**Comment by patricklodder** [comment]
Since you have an Nvidia card in there, this may be one of the known issues with the current Qt version we use. Could you try launching `dogecoin-qt` from a terminal and playing with these 2 environment variables:

```bash
export QT_SCALE_FACTOR=1
export QT_AUTO_SCREEN_SCALE_FACTOR=0
```

Please let us know if anything changes when setting these.

**Comment by Eumaios1212** [comment]
Yes, this worked! Thank you for getting back to me so quickly.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by patricklodder** [comment]
> Is this expected?

Yes, it is. How do you launch `dogecoin-qt` normally? You should add these environment variables to the launcher so that it picks it up every time, rather than setting this globally, so that it only does that for the Dogecoin wallet and software using different versions of Qt are not affected by this little "hack".

> Maybe I should switch GPUs?

Not needed. We can make this work, I'm sure.

**Comment by Eumaios1212** [comment]
To launch, I just go to the GUI folder, right click and "run". I'm happy to do it another way.

How would I go about adding those variables to the launcher? A config file somewhere?

Thank you.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by patricklodder** [comment]
You should be able to take the contributed `.desktop` file from [here](https://raw.githubusercontent.com/dogecoin/dogecoin/master/contrib/debian/dogecoin-qt.desktop) and change the `Exec=` line to be (with your dogecoin-qt path, not `/path/to/`):

 ```ini
Exec=env QT_SCALE_FACTOR=1 QT_AUTO_SCREEN_SCALE_FACTOR=0 /path/to/dogecoin-qt %u
```

Then opening the `.desktop` file should apply the variables for you every time.

**Comment by Eumaios1212** [comment]
When I attempt to create a .desktop file with the following lines, I'm told "Error writing Doge.desktop: Permission denied"

Name=Dogecoin Core
Comment=Connect to the Dogecoin P2P Network
Exec=env QT_SCALE_FACTOR=1 QT_AUTO_SCREEN_SCALE_FACTOR=0 /media/shawn/UbuntuSSD/Doge/dogecoin-1.14.6/bin>
Terminal=false
Type=Application
Icon=dogecoin128
MimeType=x-scheme-handler/dogecoin;
Categories=Office;Finance;

I'm sure I'm making a simple error. I'm only in week two of using any Linux distro--migrating from Windows (where Doge worked fine).

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by leuqarte** [comment]
To where are you creating/writing the .desktop file?

**Comment by Eumaios1212** [comment]
I assumed here:

/usr/share/applications

Perhaps I misunderstood. It is unfortunate that I am having to learn Linux/Ubuntu at the same time as fix this problem. I appreciate your patience with my ignorance.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by patricklodder** [comment]
You should be able to put it in `~/.local/share/applications` to not need to make changes with `root` and keep everything in user space. If that doesn't exist yet, do:

```bash
mkdir -p ~/.local/share/applications
```

**Comment by Eumaios1212** [comment]
Ok, I created and placed this .desktop file in this folder. It still does not load properly. Above it was mentioned that I should "open the .desktop file". I'm not sure what that means. To start the wallet and daemon, don't I have to run Dogecoin-qt ?

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by alamshafil** [comment]
This is how I did it on my end:

1. Make the folder
```bash
mkdir -p ~/.local/share/applications
```

2. Create the `dogecoin.desktop`
```bash
nano ~/.local/share/applications/dogecoin.desktop
 ```
 
 Contents (make sure to update Exec line to location of dogecoin-qt)
 ```
 [Desktop Entry]
Name=Dogecoin Core
Comment=Connect to the Dogecoin P2P Network
Comment[de]=Verbinde mit dem Dogecoin peer-to-peer Netzwerk
Comment[fr]=Dogecoin, monnaie virtuelle cryptographique pair à pair
Comment[tr]=Dogecoin, eşten eşe kriptografik sanal para birimi
Exec=env QT_SCALE_FACTOR=1 QT_AUTO_SCREEN_SCALE_FACTOR=0 /path/to/dogecoin-qt %u
Terminal=false
Type=Application
Icon=dogecoin128
MimeType=x-scheme-handler/dogecoin;
Categories=Office;Finance;
 ```
 
 3. (optional) Update desktop database
 ```bash
 update-desktop-database
 ```
 4. (optional, need **root**) Install dogecoin icon
 ```bash
wget https://raw.githubusercontent.com/dogecoin/dogecoin/master/share/pixmaps/dogecoin128.png # download icon
sudo install -Dm644 dogecoin128.png /usr/share/pixmaps/dogecoin128.png # install icon
rm dogecoin128.png # delete icon since installed
 ```
 
 Result (GNOME desktop):
 
![Screenshot from 2022-10-11 21-33-45](https://user-images.githubusercontent.com/36016500/195229245-f66ff628-0cc6-488e-97dc-66a8ee712662.png)
