### ISSUE TITLE
[feat] Remove hard-coded paper size in printer configuration

### ISSUE THREAD

**Issue by chromatic** [dogecoin/dogecoin#3152]
# Feature Request

The current Dogecoin Core Qt printer setup has a hard-coded page size of A4 ([1.14.7-dev link to source code](https://github.com/dogecoin/dogecoin/blob/1.14.7-dev/src/qt/utilitydialog.cpp#L360). For people with other paper sizes (letter, in the US, for example), this may render printable items slightly off the page.

**Describe Preferred Solution**

The ideal solution is to let Qt auto-detect the preferred page size. Qt suggests this may be possible in the [QPrinter documentation](https://doc.qt.io/qt-5/qpagesize.html#details):

> A QPageSize instance may also be obtained by querying the supported page sizes for a print device. In this case the localized name returned is that defined by the printer itself. Note that the print device may not support the current default locale language.

**Describe Alternatives**

Alternately, we could prompt the user for a paper size.

I'm comfortable coding this myself, but I'd like to review the feature idea and suggested implementation with others before doing so. (I'm also happy to review a pull request if someone else wants to code it.)

**Comment by jadijadi** [comment]
Can this be closed? It seems the PR #3239 have fixed it.
