### ISSUE TITLE
question about lost dogecoin REVISITED

### ISSUE THREAD

**Issue by ckoretsky** [dogecoin/dogecoin#3177]
### Discussed in https://github.com/dogecoin/dogecoin/discussions/3061

<div type='discussions-op-text'>

<sup>Originally posted by **ckoretsky** July 21, 2022</sup>
hi, im sorry to bother anyone,  i dont know where else to ask help finding my dogecoin.  I have this from coinbase.  and I was running dogecoin core on both my computers at the time,  silly since i know nothing about how it all works.  thanks if anyone can help

email:  ckoretsky@berkeley.edu
![image](https://user-images.githubusercontent.com/21155303/180288551-6a922528-5641-4371-b238-590231e4dbf7.png)

![Screenshot 2022-07-214111806](https://user-images.githubusercontent.com/21155303/180288917-cc82ab72-9450-47ce-99e3-6f4ae82968dc.png)
</div>

**Comment by ckoretsky** [comment]
OK I'll try this again.  i had a dogecoin node on both of my computers a year or so ago.  I could see the much receive and much send buttons then.  I hit much receive and did all the other stuff to get the dogecoin in my wallet.  i forgot about it for 6 months or so,  moved around my ssd cards and cpus and gpus,  I was mining for awhile too.  Then when I went back to see the dogecoin,  I just downloaded and installed the node and started it up, but the money wasn't there, on either computer,  also no evidence of it.  I may have put some more in,  but i don't remember.  I vaguely remember having 10,000 dogecoin, or 2,000.00 at the time, having made two big deposits,  i don't remember them being from coinbase pro, but i did send an email to them, and only them, to ask about the dogecoin.  so it must have been from them.  

Now when I download and install or reinstall dogecoin core on either computer,  i can't see the much receive or much send.  I could before, and there was no money in them.  So I don't know coudl it be on an ssd mv card, the little ones,  I did have to replace one of them because it was damaged.  so does that mean its gone?

**Comment by patricklodder** [comment]
Did you copy the data directory from your old SSD to the new SSD? If not, you'll want to try to recover the file `wallet.dat` from your `C:\Users\<youruser>\Application Data\Dogecoin` folder on the old SSD - this contains your keys.

**Comment by ckoretsky** [comment]
I sent the ssd in and got a replacement from the warranty. I'm sure it must have been backed up somewhere but before I go through every hard drive I have, can you tell from looking on the block chain if I have any dogecoin and how much. Is that possible to know?

**Comment by patricklodder** [comment]
I'm closing this, as a (partial) resolution seems to have been found in #3061 - let's keep it all in one place.
