### ISSUE TITLE
unable to compile dogecoin core in debian 12 bookworm

### ISSUE THREAD

**Issue by evil-user** [dogecoin/dogecoin#3210]
Hi I am a newbie , I am trying Unix build from https://github.com/dogecoin/dogecoin/blob/master/doc/build-unix.md#build-configuration , i have installed all required libraries and optional libraries as well as dependencies for build system.
I gave git clone https://github.com/dogecoin/dogecoin.git
then ./autogen.sh
i gave ./configure --with-gui , ./configure --disable-hardening , ./configure --enable-debug
then when i give make i get following error:-

qt/paymentserver.cpp:556:70: error: macro "Q_FOREACH_IMPL" passed 4 arguments, but takes just 3
  556 |     Q_FOREACH(const PAIRTYPE(CScript, CAmount)& sendingTo, sendingTos) {
      |                                                                      ^
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic.h:41,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qrefcount.h:43,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearray.h:44,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QByteArray:1,
                 from qt/paymentrequestplus.h:17,
                 from qt/paymentserver.h:35,
                 from qt/paymentserver.cpp:6:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h:1125: note: macro "Q_FOREACH_IMPL" defined here
 1125 | #define Q_FOREACH_IMPL(variable, name, container)             \
      | 
qt/paymentserver.cpp: In static member function ‘static void PaymentServer::LoadRootCAs(X509_STORE*)’:
qt/paymentserver.cpp:143:45: warning: ‘static void QSslSocket::setDefaultCaCertificates(const QList<QSslCertificate>&)’ is deprecated [-Wdeprecated-declarations]
  143 |         QSslSocket::setDefaultCaCertificates(certList);
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/qt5/QtNetwork/qsslconfiguration.h:62,
                 from /usr/include/x86_64-linux-gnu/qt5/QtNetwork/QSslConfiguration:1,
                 from /usr/include/x86_64-linux-gnu/qt5/QtNetwork/qnetworkaccessmanager.h:49,
                 from /usr/include/x86_64-linux-gnu/qt5/QtNetwork/QNetworkAccessManager:1,
                 from qt/paymentserver.cpp:35:
/usr/include/x86_64-linux-gnu/qt5/QtNetwork/qsslsocket.h:184:31: note: declared here
  184 |     QT_DEPRECATED static void setDefaultCaCertificates(const QList<QSslCertificate> &certificates);
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~
qt/paymentserver.cpp:145:52: warning: ‘static QList<QSslCertificate> QSslSocket::systemCaCertificates()’ is deprecated: Use QSslConfiguration::systemCaCertificates() [-Wdeprecated-declarations]
  145 |         certList = QSslSocket::systemCaCertificates();
      |                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/usr/include/x86_64-linux-gnu/qt5/QtNetwork/qsslsocket.h:186:100: note: declared here
  186 |     QT_DEPRECATED_X("Use QSslConfiguration::systemCaCertificates()") static QList<QSslCertificate> systemCaCertificates();
      |                                                                                                    ^~~~~~~~~~~~~~~~~~~~
qt/paymentserver.cpp: In member function ‘void PaymentServer::handleURIOrFile(const QString&)’:
qt/paymentserver.cpp:418:24: warning: ‘QByteArray& QByteArray::append(const QString&)’ is deprecated: Use QString's toUtf8(), toLatin1() or toLocal8Bit() [-Wdeprecated-declarations]
  418 |             temp.append(uri.queryItemValue("r"));
      |             ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qhashfunctions.h:44,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h:47,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QList:1,
                 from qt/paymentrequestplus.h:18:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:1511:20: note: declared here
 1511 | inline QByteArray &QByteArray::append(const QString &s)
      |                    ^~~~~~~~~~
qt/paymentserver.cpp: In member function ‘bool PaymentServer::processPaymentRequest(const PaymentRequestPlus&, SendCoinsRecipient&)’:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h:1133:5: error: ‘Q_FOREACH_IMPL’ was not declared in this scope
 1133 |     Q_FOREACH_IMPL(variable, Q_FOREACH_JOIN(_container_, __LINE__), container)
      |     ^~~~~~~~~~~~~~
/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h:1133:5: note: in definition of macro ‘Q_FOREACH’
 1133 |     Q_FOREACH_IMPL(variable, Q_FOREACH_JOIN(_container_, __LINE__), container)
      |     ^~~~~~~~~~~~~~
qt/paymentserver.cpp: In member function ‘void PaymentServer::fetchPaymentACK(CWallet*, SendCoinsRecipient, QByteArray)’:
qt/paymentserver.cpp:664:34: warning: ‘int google::protobuf::MessageLite::ByteSize() const’ is deprecated: Please use ByteSizeLong() instead [-Wdeprecated-declarations]
  664 |     int length = payment.ByteSize();
      |                  ~~~~~~~~~~~~~~~~^~
In file included from /usr/include/google/protobuf/any.h:38,
                 from /usr/include/google/protobuf/generated_message_util.h:52,
                 from qt/paymentrequest.pb.h:26,
                 from qt/paymentrequestplus.h:10:
/usr/include/google/protobuf/message_lite.h:381:7: note: declared here
  381 |   int ByteSize() const { return internal::ToIntSize(ByteSizeLong()); }
      |       ^~~~~~~~
make[2]: *** [Makefile:7348: qt/libdogecoinqt_a-paymentserver.o] Error 1
make[1]: *** [Makefile:9818: all-recursive] Error 1
make: *** [Makefile:694: all-recursive] Error 1

**Comment by evil-user** [comment]
I much interested in solving this issue https://github.com/dogecoin/dogecoin/issues/3182 which occurs in GUI , am i doing compilation steps wrong any help will be appreciated. Also for development should i follow Compiling using packaged dependencies or Compiling using system-provided libraries

**Comment by evil-user** [comment]
Used Ubuntu 18.04 issue is not present there.

**Comment by chromatic** [comment]
@evil-user Now that we've merged #3207 to the 1.14.7-dev branch, can you try compiling again from that branch and see if it has solved your issue?

**Comment by netpipe** [comment]
this issue still exists on opensuse 15.5
