### ISSUE TITLE
dogecoin qt sendrawtransaction but it seems to be not broadcasted

### ISSUE THREAD

**Issue by RasoulKhosravi** [dogecoin/dogecoin#3230]
Version: 1.14.6
    Python: 3.10
    OS: linux

I'm trying to make the transaction

`{ "amount": -1.19770000, "fee": -0.00230000, "confirmations": 0, "trusted": true, "txid": "97e9886378b483659efd361bc9aebcc12a8b5f996d91ca089e6966d69631a77e", "walletconflicts": [ ], "time": 1677483818, "timereceived": 1677483818, "bip125-replaceable": "no", "details": [ { "account": "", "address": "nbAumtiQQD5sTrcnrvt6CeZb4WNA1K3jN4", "category": "send", "amount": -0.62475343, "vout": 0, "fee": -0.00230000, "abandoned": false }, { "account": "", "address": "nsFUNwdL2R8uxXvsMkWn8EbMkgVphV5tM7", "category": "send", "amount": -0.15629619, "vout": 1, "fee": -0.00230000, "abandoned": false }, { "account": "", "address": "nUHRsyzk7ZoCqHxCpovPfQ7ERNMH8hogXQ", "category": "send", "amount": -0.11805354, "vout": 2, "fee": -0.00230000, "abandoned": false }, { "involvesWatchonly": true, "account": "", "address": "noyns9fzBULJiV3k9FrdSeqZBmb9T98KgP", "category": "send", "amount": -0.00000001, "label": "w2", "vout": 3, "fee": -0.00230000, "abandoned": false }, { "account": "", "address": "nfLqRE4GXwXT5E2wkvqdKYWCRVsTx1E7T5", "category": "send", "amount": -0.08563377, "vout": 4, "fee": -0.00230000, "abandoned": false }, { "account": "", "address": "nfJ25Jdgz88XfHL7QNRmxGDvztmzVUi3bt", "category": "send", "amount": -0.21296306, "vout": 5, "fee": -0.00230000, "abandoned": false } ], "hex": "0100000001abeb54e260dc7ae54d67292dd0c1d523d26524b1a08c58092f8da1795a5c707c010000006a47304402201b3c61ac796138f2851cada4ea58b235374e321f7f2a0d28c476e225ae97e540022001f39ccf1880e977561fa1ccd30f6274f2033ffeb2b3f424af0439e62fa0d5210121039334767f475d776b90af75734cbcdcd1ffcb03faf3d9b33d045ff0d56204a4deffffffff064f4cb903000000001976a9144c8c5e95ef205189aed35868eb177c6d5a5b6e0088ac337dee00000000001976a914fceb43380711d6c36b59f8522d9277265c261be588acaa22b400000000001976a91400ff1d7b589f7ad2e7bdea80d105fbf583f58d6a88ac01000000000000001976a914d90ba954f736dd9e1a4faabb020b5ee1f386e3f088acb1aa8200000000001976a9147a4d6550480e7299da31ba7001987db26d92e8b888acb2f44401000000001976a91479c50b22956bbeec03fc0964ff030a224e2e3ae188ac00000000" }`

# dogecoin qt cannot broadcast it !!!
It prints the hash of the transaction, but the transaction never appears at block explorer, so seems to be not broadcasted

**Comment by RasoulKhosravi** [comment]
yes, that s right in this case. when I raised the amount it was solved.

**Comment by chromatic** [comment]
Glad to hear it! Are you comfortable with us closing this issue, @RasoulKhosravi? Or is there something we should investigate further?
