### ISSUE TITLE
Fatal Errors in MacOS Installation

### ISSUE THREAD

**Issue by Bhaney44** [dogecoin/dogecoin#3246]
Hi,

I am continuously running into a fatal error in Dogecoin Core installation.

`make: *** No targets specified and no makefile found.  Stop.`

I have run:

```
$./autogen.sh
$./configure
$make
```

with several variations and fix attempts that simply do not have an effect on the outcome.

# Bug Report

**Current behavior:**

Attempting to install Dogecoin Core via: `Make`

`make: *** No targets specified and no makefile found.  Stop.`

**Expected behavior**

Proper installation.

**Steps to reproduce:**

To reproduce follow the [Installation Steps ](https://github.com/dogecoin/dogecoin/blob/master/doc/Building-Dogecoin-1.14-for-Mac.md) for MacOS.

**Machine specs**
- OS:

**Comment by donpdonp** [comment]
make is saying there is no `Makefile` (which is built by configure). Either make is being run from the wrong directory, or the `./configure` step failed in which case the output will need to be part of the ticket to know what went wrong.

**Comment by Bhaney44** [comment]
Thank you very much @donpdonp 

Yes. You are correct. `./configure` is failing. Here is the error:

`configure: error: libdb_cxx headers missing, Dogecoin Core requires this library for wallet functionality (--disable-wallet to disable wallet functionality)`

**Comment by Security2965** [comment]
> > `configure: error: libdb_cxx headers missing, Dogecoin Core requires this library for wallet functionality (--disable-wallet to disable wallet functionality)`
> 
> Currently, the only way I have personally been able to make this work on a Mac natively is by passing `--with-incompatible-bdb` to `./configure` and using brew bdb. The `contrib/install_db5.sh` does not work for me on either x86_64 or arm64 Macs, as it errors out on runtime. This is an open issue.
> 
> Note that when you use an incompatible bdb version, wallets will not be portable, so use that with caution.

**Comment by Bhaney44** [comment]
> > `configure: error: libdb_cxx headers missing, Dogecoin Core requires this library for wallet functionality (--disable-wallet to disable wallet functionality)`
> 
> Currently, the only way I have personally been able to make this work on a Mac natively is by passing `--with-incompatible-bdb` to `./configure` and using brew bdb. The `contrib/install_db5.sh` does not work for me on either x86_64 or arm64 Macs, as it errors out on runtime. This is an open issue.
> 
> Note that when you use an incompatible bdb version, wallets will not be portable, so use that with caution.

I ran:

`./configure  --with-incompatible-bdb`

And got the same error:

`configure: error: libdb_cxx headers missing, Dogecoin Core requires this library for wallet functionality (--disable-wallet to disable wallet functionality)`

I may try again once I am able to get a new machine. In the meantime, please feel free to share a link here if a fix is found.

**Comment by Bhaney44** [comment]
> ./configure --with-incompatible-bdb

Yes. Thanks for your help. I just ran it:

```
$brew install berkeley-db@5
$./autogen.sh
$./configure
```
but got the same error.

`configure: error: libdb_cxx headers missing, Dogecoin Core requires this library for wallet functionality (--disable-wallet to disable wallet functionality)`
