### ISSUE TITLE
WinXP DLL import regression on 1.14.6

### ISSUE THREAD

**Issue by patricklodder** [dogecoin/dogecoin#3276]
_Originally posted by @edtubbs in https://github.com/dogecoin/dogecoin/issues/3222#issuecomment-1587898348_

Running `test_dogecoin.exe` from `dogecoin-1.14.7-win32.zip` generates this error on Windows XP Pro (Version 2002, Service Pack 3) with a Pentium 4 @ 2.80 GHz: "The procedure entry point if_nametoindex could not be located in the dynamic link library IPHLPAPI.DLL."

According to this discussion (https://github.com/libevent/libevent/pull/1111), if_nametoindex function is only supported from Windows Vista onwards.  We can probably remove this dependency to make core compatible with XP. I can dig deeper if needed.

----

This regression towards WinXP compatibility has likely been introduced with the libevent update done for 1.14.6. The above referenced pull could be a potential workaround (i.e. via `depends/patches` in lieu of an upstream fix) to deal with it.

It was not caught when building the new lief-based symbol check scripts, because 1.14.6 was used as the base for that, so any prior regressions have not been caught.

**Comment by edtubbs** [comment]
Running `test_dogecoin.exe` from `dogecoin-1.14.6-win32.zip` passes with `*** No errors detected` on Windows 7 Ultimate (Service Pack 1) with a Atom N270 @ 1.60 GHz

**Comment by patricklodder** [comment]
Implemented documentation with #3417.
