### ISSUE TITLE
[bug] qa: Qt payment server unit test depends on datadir

### ISSUE THREAD

**Issue by patricklodder** [dogecoin/dogecoin#3285]
It appears that PaymentServerTests executed in `src/qt/test/paymentservertests.cpp` use the datadir to succeed. This is risky because the datadir can contain production data and, as proven by @chromatic's finding in #3222, can cause unexpected test failures. Perhaps it would be an idea to refactor this and make these unit tests run independent from the filesystem. 

----

_Originally posted by @chromatic in https://github.com/dogecoin/dogecoin/issues/3222#issuecomment-1603468248_

Contents of `src/test-suite.log`:

```
********* Start testing of URITests *********
Config: Using QtTest library 5.15.3, Qt 5.15.3 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 11.3.0), ubuntu 22.04
PASS   : URITests::initTestCase()
PASS   : URITests::uriTests()
PASS   : URITests::cleanupTestCase()
Totals: 3 passed, 0 failed, 0 skipped, 0 blacklisted, 0ms
********* Finished testing of URITests *********
********* Start testing of PaymentServerTests *********
Config: Using QtTest library 5.15.3, Qt 5.15.3 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 11.3.0), ubuntu 22.04
PASS   : PaymentServerTests::initTestCase()
FAIL!  : PaymentServerTests::paymentServerTests() Caught unhandled exception
   Loc: [qtestcase.cpp(1939)]
Totals: 1 passed, 1 failed, 0 skipped, 0 blacklisted, 24ms
********* Finished testing of PaymentServerTests *********
terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
  what():  boost::filesystem::create_directory: File exists: "/home/chromatic/.dogecoin"
FAIL qt/test/test_dogecoin-qt (exit status: 134)
```

_Originally posted by @chromatic in https://github.com/dogecoin/dogecoin/issues/3222#issuecomment-1605204774_

I fixed my error; my `.dogecoin` directory was not mounted properly.

**Comment by chromatic** [comment]
In my testing (mounting and unmounting my datadir's filesystem), the only place the `PaymentServer` test depends on the datadir is in getting the IPC server name.

Because I'm the one who wrote that code, I'll take the first swing at fixing the bug here.
