### ISSUE TITLE
ZMQ 6.0 consumers may not integrate with our 4.0 ZMQ providers

### ISSUE THREAD

**Issue by patricklodder** [dogecoin/dogecoin#3295]
_Originally posted by @SamirBitzees in https://github.com/dogecoin/dogecoin/discussions/3282#discussioncomment-6384338_

I have issue with zmq When I am trying to listen incoming transaction using zeromq using version ("zeromq": "^6.0.0-beta.17")
Unable to listen incoming transaction.

-----

It would be good if we can validate this with a zmq 6.0 counterpart (using the qa/rpc-tests logic?)

Open to suggestions what the best approach is here.

**Comment by alamshafil** [comment]
I have used zeromq 5.3.1 `("zeromq": "^5.3.1")` which is the latest version in the 5.x branch and works fine for me.

The package README.md on npmjs.com states that 5.x is the stable branch and 6.x is a complete rework. (https://www.npmjs.com/package/zeromq) 

Since 6.x branch the complete rework, it breaks code written using the 5.x branch. The reason it is not working could be that the code was written in the 5.x style instead of new 6.x style.

I will try to test zeromq 6.0 (NodeJS bindings) and see what happens.

**Comment by alamshafil** [comment]
I can confirm zeromq 6 (`"zeromq": "^6.0.0-beta.17"`) works without errors if written in new syntax.

Dogecoin options:
```
./src/qt/dogecoin-qt -zmqpubhashtx=tcp://127.0.0.1:9000
```

JS code:
```js
const zmq = require("zeromq")

async function run() {
  const sock = new zmq.Subscriber

  sock.connect("tcp://127.0.0.1:9000")
  sock.subscribe("hashtx")
  console.log("Subscriber connected to port 9000")

  for await (const [topic, msg] of sock) {
    console.log("Received hashtx:", msg.toString('hex'))
  }
}

run()
```

Screenshot:
![image](https://github.com/dogecoin/dogecoin/assets/36016500/3790eb9f-9dc6-40c3-8df9-c88dae263501)

For reference, here is the same code written using the 5.x branch:
```js
const zmq = require("zeromq")

var sock = zmq.socket("sub")

sock.connect("tcp://127.0.0.1:9000");
sock.subscribe("hashtx")
console.log("Subscriber connected to port 9000")

sock.on('message', (topic, msg) => {
    console.log("Received hashtx:", msg.toString('hex'))
})
```

**Comment by SamirBitzees** [comment]
May know what configuration u have set in your config, because still its
not listening

**Comment by SamirBitzees** [comment]
I am trying to listen incoming transactions  using zeromq I first tried to listen transaction using latest version but not work. Then tried with 5.3.1, 5.3.0 but that also not worked. 
Here is my script...

  var zmq = require("zeromq"),
  sock = zmq.socket("sub");
  sock.connect("tcp://52.66.249.25:29000");
  sock.subscribe('hashtx');
  console.log("Subscriber connected to port 29000");
  sock.on("message", function (topic, message) {
    console.log(topic.toString(), message.toString('hex'));
  });

## In above script RPC Host : "52.66.249.25" but that not worked. So then I change host in config and make changes in script and set host : 127.0.0.1 but from this port also i unable to listen an incoming transactions.

## Here is my config file. 
  testnet=1
[test]
txindex=1
listen=1
server=1
rest=1
rpcbind=0.0.0.0
zmqpubrawblock=tcp://52.66.249.25:29000
zmqpubrawtx=tcp://52.66.249.25:29000
zmqpubhashtx=tcp://52.66.249.25:29000
zmqpubhashblock=tcp://52.66.249.25:29000
rpcallowip=0.0.0.0/0
rpcuser=" " 
rpcpassword=" "
rpcport=18332

**Comment by SamirBitzees** [comment]
Can I get Any update for above issue....

**Comment by SamirBitzees** [comment]
Not has been resolved using zmq..

**Comment by SamirBitzees** [comment]
@patricklodder @alamshafil   
One more doubt has not been resolved that how we can perform multisig transaction on dogecoin, And how we can create multisig wallet..
