### ISSUE TITLE
[feat] Backport/Import Bitcoin's share/rpcauth/rpcauth.py

### ISSUE THREAD

**Issue by chromatic** [dogecoin/dogecoin#3352]
# Feature Request

Bitcoin has deprecated `share/rpcuser/rpcuser.py` in favor of [share/rpcauth/rpcauth.py](https://github.com/bitcoin/bitcoin/blob/master/share/rpcauth/rpcauth.py). In particular, the latter has an improved user experience and, more importantly, uses cryptographically secure random numbers for generating passwords. The existing `rpcuser.py` uses the insecure Python `random` module.

**Describe Preferred Solution**

We should at least borrow Bitcoin's code, even if we don't deprecate the existing utility in favor of the new filename and location.

**Comment by chromatic** [comment]
If we can agree on which approach we prefer -- either keeping the existing Dogecoin path and filename or deprecating that and suggesting people use the new path and filename -- then it's a great first issue.

I lean slightly toward keeping the existing path and filename and replacing its body with the body of the new file, but that's only because of backwards compatibility with existing guides and documentation. I don't feel strongly; if there are forward compatibility concerns (easier to backport changes from Bitcoin or other similar codebases), I can live with that.

**Comment by azavorozhin** [comment]
Seems not good

**Comment by patricklodder** [comment]
fixed with #3388
