### ISSUE TITLE
MultiSig

### ISSUE THREAD

**Issue by man-tfwnogf** [dogecoin/dogecoin#336]
Does Dogecoin support multi-sig transactions? I tried to create one but the funds aren't showing up in my generated MultiSig address:

http://dogechain.info/address/A3YeGE1MCRfj7c8SFs7oAtKYDLzsTXX7GC

http://dogechain.info/tx/caa22d4321b5f4dfa5843ef994a3c241fc8836c24d65125b2c34632ac082dd7e

Thanks

**Comment by rnicoll** [comment]
As per last comment, this is now in general use in standard client

**Comment by SamirBitzees** [comment]
> multisig works fine with 1.8, I use it every day.

Do we have any documentation to perform multisig transaction on dogecoin. 
like any github repo etc.
