### ISSUE TITLE
[bug] 1.21-dev compilation with GCC 13

### ISSUE THREAD

**Issue by victorsk2019** [dogecoin/dogecoin#3377]
# Bug Report

Good day!

I've encountered some Dogecoin Core 1.21 compilation issues as I wanted to examine more closely https://github.com/dogecoin/dogecoin/issues/2951 notes.

**Current behavior:** 
In `support/lockedpool.cpp`:
```support/lockedpool.cpp: In member function ‘void Arena::free(void*)’:
support/lockedpool.cpp:102:20: error: ‘runtime_error’ is not a member of ‘std’
  102 |         throw std::runtime_error("Arena: invalid or double free");
      |                    ^~~~~~~~~~~~~
support/lockedpool.cpp:25:1: note: ‘std::runtime_error’ is defined in header ‘<stdexcept>’; did you forget to ‘#include <stdexcept>’?
   24 | #include <algorithm>
  +++ |+#include <stdexcept>
```
`util/string.h`:
```
./util/string.h:84:50: error: ‘uint8_t’ was not declared in this scope
   84 |                                 const std::array<uint8_t, PREFIX_LEN>& prefix)
      |                                                  ^~~~~~~
./util/string.h:17:1: note: ‘uint8_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
   16 | #include <vector>
  +++ |+#include <cstdint>
```
`/util/bip32.h`:
```
./util/bip32.h:13:75: error: ‘uint32_t’ was not declared in this scope
   13 | NODISCARD bool ParseHDKeypath(const std::string& keypath_str, std::vector<uint32_t>& keypath);
      |                                                                           ^~~~~~~~
./util/bip32.h:11:1: note: ‘uint32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
   10 | #include <vector>
  +++ |+#include <cstdint>
```
**Expected behavior**
Program should compile normally without these errors.

**Steps to reproduce:**
- GCC version: `gcc (Gentoo 13.2.1_p20230826 p7) 13.2.1 20230826`
- protobuf: `23.3-r2` (libprotoc 23.3)
- configure options:
`./configure --prefix=${HOME}/projects/dogecoin-1.21-dev  --disable-bench --disable-tests CXXFLAGS="-std=c++14"`
This is because the latest version of `protobuf` that I am using requires C++ standard to be at least 14.

**Dogecoin Core version**
1.21

**Machine specs**
- OS: Calculate Linux (Gentoo-based)
- CPU: Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz
- RAM: 6
- Disk size: 500GB
- Disk Type (HD/SDD): HDD

These errors can be easily fixed by modifying these files to include required headers.  I'll be happy to submit a PR that fixes these issues, if necessary.  

Probably my GCC version is causing these errors (I had to implement similar GCC 13 patch in my other project to fix it).  I think it may be a good idea to make 1.21 support newer GCC versions, and, perhaps, support C++ 14 standard also?  

Thank you,
Victor.

**Comment by patricklodder** [comment]
What version of boost are you compiling against?

**Comment by victorsk2019** [comment]
> What version of boost are you compiling against?
Hi,
I'm using `boost-1.81.0-r1` .

**Comment by patricklodder** [comment]
- The first issue in `support/lockedpool.cpp` is the same error we fixed in #3335 for 1.14, feel free to PR that.
- The errors in `util/` are odd, I will try to reproduce these on Debian Sid to get some more insights

> support C++ 14 standard also

1.21-dev requires c++17, this should be compatible with the protobuf requirement? I'm not sure what is causing errors for you? What error made you add the `CXXFLAGS="-std=c++14"`?

**Comment by victorsk2019** [comment]
> What error made you add the `CXXFLAGS="-std=c++14"`?

I was getting `Protobuf only supports C++14 and newer` when building 1.14.6 and 1.21 using installed version of `protobuf-23.3-r2`, so adding this CXXFLAGS option fixes this error.  

> 1.21-dev requires c++17, this should be compatible with the protobuf requirement

Hmm, interesting.  I just quickly checked and there is `--enable-c++17` configure option.  I wasn't using this option but I am certain protobuf should be compatible with c++17 if used 👍

**Comment by patricklodder** [comment]
>  I just quickly checked and there is --enable-c++17 configure option

My bad that I forgot this wasn't the default - but yes this should help.

**Comment by patricklodder** [comment]
> The errors in util/ are odd, I will try to reproduce these on Debian Sid to get some more insights

I was able to reproduce this also on Debian w/ gcc13, consistently. I'm not sure what changed (something with `--enable-cheaders` defaults for glibstdc++?) and I'd want to investigate a bit further and figure out how we can best manage naive implementation on our side. However, in the meantime let's add the headers because they should be there. Would appreciate if you could do a PR for this. It'll be blocked by #3350 initially but as soon as that goes in, it can go through.

Re: protobuf, since it's not a dependency for 1.21, it is not related to this issue.
