### ISSUE TITLE
QA: Cross OS Build Testing & Documentation 

### ISSUE THREAD

**Issue by georgeartem** [dogecoin/dogecoin#3470]
This issue arises from discussion in #3437 to assist with understanding which OS flavors are "in scope" for core developer support and documented as "clean" for new developer onboarding.

Per @patricklodder it is recommended to start with linux distributions that already have documented build guides and work outwards with creating guides and documenting known issues for (hopefully) all builds represented in the Minimum (pre-compiled binary) OS documentation. 

Broadly speaking, for each maintained version, "Core QA" will create a Dockerfile and run a build each time dependencies are updated. 

When something fails "Core QA" will document failures by opening an issue with the Dockerfile for senior members of the core development team to reproduce the errors, warnings etc. and work through a solution.

Alternatively, if "Core QA" is feeling advanced they are free to take on and work through the issue themselves by submitting PRs with support from senior members of the team.

**Comment by patricklodder** [comment]
> which OS flavors are "in scope" for core developer support

"core developer" -> "community", because community > titles

> "Core QA"

Why does this activity need this title/group?

**Comment by georgeartem** [comment]
maybe it does, maybe it doesn't, it's just a label.

**Comment by patricklodder** [comment]
Okay, I guess. Moving this to discussions, because this is not a software or process issue.
