### ISSUE TITLE
Transactions are successsful but I receive nothing!

### ISSUE THREAD

**Issue by SaitamaTechno** [dogecoin/dogecoin#3475]
I run dogecoind and dogecoin-cli in local network linux and also in cloud linux, everything looks working.
 I can create wallets and I want to send doge into them I sent 1 doge to the local one and then I sent 0.2doge to the cloud one. And I didnt receive anything. the cloud one has open port to the public internet thats why I also used it. one of them has 75 confirmation and the other one has 15 confirmation but I got nothing why?
 
 I sent doges from block.io website
 
 txid for 1doge:
 https://sochain.com/tx/DOGE/b8cb47685a71f26f33f4cdb822750826c8fa2f191e91f14debeee55a93ac0f7a
 txid for 0.2doge:
 https://sochain.com/tx/DOGE/d9be1cfc3aeefa5d11f3b8d6a882f7d03fe256bafcfda40ac5bd45b44e99234d
 
 I am on the main network by:
 dogecoin-cli getblockchaininfo

**Comment by patricklodder** [comment]
I see these transactions on my nodes. On the node with your wallet, could you please let us know:

- `dogecoin-cli getblockchaininfo` and check the value for `blocks` to be > `5,123,502`
- `dogecoin-cli getwalletinfo` should give you a `txcount` of > 1 
- `dogecoin-cli listunspent` should list these
- How do you query your balance?

**Comment by SaitamaTechno** [comment]
hello, I think it is because of synchronizing, my node is not complete. I am new to it, i didnt know the reason before I open the issue. But now I have another issue, my dogecoin server keeps stoping after like 5 minutes. How do i publish the node without downloading all blockchain? I used pruning but it looks it still tries to download everything .

Here you may find some information:


root@c85teybxy2:~# free -h
               total        used        free      shared  buff/cache   available
Mem:           1.9Gi       1.3Gi        69Mi       0.0Ki       530Mi       460Mi
Swap:             0B          0B          0B
root@c85teybxy2:~# dogecoin-cli getblockchaininfo
{
  "chain": "main",
  "blocks": 99531,
  "headers": 4021995,
  "bestblockhash": "d72a15c276f105f18d6b490fb426118050f8d91a679283aa004fc703a572c7c6",
  "difficulty": 2005.936100016067,
  "mediantime": 1392317908,
  "verificationprogress": 0.03029031921381798,
  "initialblockdownload": true,
  "chainwork": "00000000000000000000000000000000000000000000000003cf84a2fc082dcc",
  "size_on_disk": 2594468165,
  "pruned": true,
  "pruneheight": 0,
  "automatic_pruning": true,
  "prune_target_size": 2411724800,
  "softforks": [
    {
      "id": "bip34",
      "version": 2,
      "reject": {
        "status": false
      }
    },
    {
      "id": "bip66",
      "version": 3,
      "reject": {
        "status": false
      }
    },
    {
      "id": "bip65",
      "version": 4,
      "reject": {
        "status": false
      }
    }
  ],
  "bip9_softforks": {
    "csv": {
      "status": "defined",
      "startTime": 1462060800,
      "timeout": 1493596800,
      "since": 0
    }
  },
  "warnings": ""
}
root@c85teybxy2:~# dogecoin-cli getbalance ""
bash: dogecoin-calance: command not found
root@c85teybxy2:~# dogecoin-cli getbalance "*"
0.00000000
root@c85teybxy2:~#


And also my config file:
rpcuser=myusername
rpcpassword=mypasswd
dbcache=4
prune=2300

addnode=superfastdoge.ddns.net
addnode=us-1.wowsuchfast.com
addnode=us-2.wowsuchfast.com
addnode=dnf-1.gbf.re
addnode=dnf-2.gbf.re
addnode=dnf-3.gbf.re
addnode=dnf-4.gbf.re
addnode=dnf-beta.gbf.re
addnode=dnf-alpha.gbf.re
addnode=dnf-test.gbf.re
addnode=doge1-eu.langerhans.de
addnode=doge2-eu.langerhans.de
addnode=doge3-eu.langerhans.de
addnode=doge4-eu.langerhans.de
addnode=doge1-us-wa.hadamservices.com
addnode=doge2-us-wa.hadamservices.com
addnode=doge3-us-wa.hadamservices.com
addnode=doge4-us-wa.hadamservices.com
addnode=doge5-us-va.hadamservices.com
addnode=doge6-us-va.hadamservices.com
addnode=doge7-us-va.hadamservices.com
addnode=doge8-us-va.hadamservices.com
addnode=1.seed.dogecoin.gg
addnode=2.seed.dogecoin.gg
addnode=3.seed.dogecoin.gg
addnode=4.seed.dogecoin.gg
addnode=doge-node.com
addnode=dogenode.eu
addnode=dogenode.from-tx.com

**Comment by patricklodder** [comment]
> But now I have another issue, my dogecoin server keeps stopping after like 5 minutes.

Could you check the bottom of `debug.log` after it's shut down? Should be:

```
tail -n 50 ~/.dogecoin/debug.log
```

> ```
> "blocks": 99531,
> ```

this is why your balance is still zero, you're over 5 million blocks behind.

> config
>
> ```
> dbcache=4
> ..
> addnode=[blah]
> ```

- Why do you have a 4 mb cache?
- Why do you have all these addnode?

**Comment by SaitamaTechno** [comment]
5 million blocks, yeah as i said I understand it after opening the issue.

is that 4mb cache, wow i need to make it more! I Thought my vps server (2gb RAM) does not have enough ram when i see it fails in 5 minutes, and I searched somebody make dbcache 4 and said everything works fine. Then i did so. 

Addnodes are for faster downloading the blockchain i think, again I saw it on the internet.

**Comment by patricklodder** [comment]
> Thought my vps server (2gb RAM) does not have enough RAM.

I saw the 2GB. It's really low and your node may get killed for being out of memory, but per the above, I'd need to see the bottom of your log to help further investigate.

> Addnodes are for faster downloading the blockchain i think

If everyone uses the same nodes, then the rest of the network is idle. Since even my newer Xeons cannot serve 125 peers with current network demand, it may be faster to not use addnode at all, or at least you'll have better chance of hitting an idle node instead of the subset of nodes multiple people are using.

Better to not add nodes because someone on the internet says so either, as it could help an attacker eclipse attack your node.

**Comment by SaitamaTechno** [comment]
this is the error I get when the server is down:
root@c85teybxy2:~# dogecoin-cli getblockchaininfo
error: couldn't connect to server: unknown (code -1)
(make sure server is running and you are connecting to the correct RPC port)

do you know the reason?

These are the last lines of my debug.log:

2024-03-15 08:30:05 UpdateTip: new best=b7dc155c624f93ad3e546852491eea5bfe3a06984e1b27b00910bce1a02433e6 height=100297 version=0x00000001 log2_work=57.959054 tx=7532745 date='2014-02-14 09:15:01' progress=0.030406 cache=46.4MiB(136748tx)
2024-03-15 08:30:05 UpdateTip: new best=6301cde5d205c497db621829ec2f869ef2b55d8313e7400e84c1f7753b0f6151 height=100298 version=0x00000001 log2_work=57.959091 tx=7533015 date='2014-02-14 09:17:57' progress=0.030407 cache=46.5MiB(137037tx)
2024-03-15 08:30:05 UpdateTip: new best=e18a9fda9c006fe5ccb5e1d7ffb5b7217c38cac6e7e6fb6fb1c81738d51588f7 height=100299 version=0x00000002 log2_work=57.959129 tx=7533114 date='2014-02-14 09:19:07' progress=0.030408 cache=46.5MiB(137133tx)
2024-03-15 08:30:05 UpdateTip: new best=5e26550f3b2e1352564a36a4bd39311ec34dffee5109d1fc1625d1915ec86668 height=100300 version=0x00000002 log2_work=57.959167 tx=7533197 date='2014-02-14 09:20:25' progress=0.030408 cache=46.5MiB(137191tx)
2024-03-15 08:30:06 UpdateTip: new best=fab44c3ce4d4bae52f81e80b012a9da96fabb0cbe316e58f4de7af743410e615 height=100301 version=0x00000001 log2_work=57.959204 tx=7533451 date='2014-02-14 09:21:43' progress=0.030409 cache=46.6MiB(137467tx)
2024-03-15 08:30:06 Pre-allocating up to position 0x200000 in rev00017.dat

**Comment by patricklodder** [comment]
This could mean it gets OOM-killed (as there is no indication of a clean shutdown)

Try:

```
dmesg -T | grep killed
```

**Comment by SaitamaTechno** [comment]
nothing is printed

**Comment by SaitamaTechno** [comment]
hello, I created a new server with 4gb of ram and downloaded all the blockcahin pruning 50gb. I am now able to receive and sign transactions. perhaps the problem was pruning. because i started the core server without pruning then I restarted it with pruning, it caused failure. Now i learned that i need to delete all the blockchain and download all from scratch. I havent tried 2gb version yet. But i will try and we'll see. Since I found  my solution I will close the issue as solved. Also, thanks for your effort!

**Comment by georgeartem** [comment]
@RnoHach for the sake of lurking

**Comment by SaitamaTechno** [comment]
hey @patricklodder  , it looks the problem is because of the limited ram. the issue remains for 2gb ram. it fails after some time. I also checked the used ram it goes almost 1.8gb/1.9gb. When it continues it increases up to 1.9/1.9 and goes out of ram. I also did some reducing ram steps and I think it was written by you, @patricklodder . It looks like it works at the begining but after some time it again runs out of ram and also very slow initialising. So I again created a 4gb ram vps server and i am downloading the blockchain. 

"verificationprogress": 0.088
and ram usage= 2.4gb probably by dogecoin node.

You can check my node by clicking:
<a href="http://154.53.180.195/">http://154.53.180.195/</a>
and also for checking ram:
<a href="http://154.53.180.195/ram">http://154.53.180.195/ram</a>
it will be available until initialising finished.
