### ISSUE TITLE
Don't manage to launch dogecoind as a service

### ISSUE THREAD

**Issue by GaloisField2718** [dogecoin/dogecoin#3553]
Hello, 

I want to create a service to run dogecoind in background and restart automatically if the server is down. 

So, I created doge user and dogecoin group. 
As recommended in `./init/dogecoind.service` I created `/etc/dogecoin/dogecoin.conf` and `/var/lib/dogecoin` which is owned by doge:dogecoin. 

The service is defined by: 
```
[Unit]
Description=Dogecoin Daemon
After=network.target
StartLimitIntervalSec=120
StartLimitBurst=5

[Service]
ExecStart=/usr/bin/dogecoind -conf=/etc/dogecoin/dogecoin.conf -datadir=/var/lib/dogecoin
User=doge
Group=dogecoin
#WorkingDirectory=/home/doge
#KillSignal=SIGINT
Restart=on-failure
#RestartSec=5
TimeoutStopSec=60
TimeoutStartSec=5

### Restrict access to host file system.
#
# Hide the entire root file system by default, and *only* mount in exactly what is needed.
#

TemporaryFileSystem=/:ro

# Add core dependencies
BindReadOnlyPaths=/etc/ /lib/ /lib64/

# Add daemon paths
BindReadOnlyPaths=/usr/bin/dogecoind /etc/dogecoin/
BindPaths=/var/lib/dogecoin

### Restrict access to system.

#NoNewPrivileges=true
PrivateTmp=true
PrivateDevices=true
PrivateUsers=true
DevicePolicy=closed
ProtectHome=true
ProtectHostname=true
ProtectControlGroups=true
ProtectClock=true
ProtectKernelModules=true
ProtectKernelTunables=true
ProtectKernelLogs=true
RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6 AF_NETLINK
RestrictNamespaces=true
RestrictRealtime=true
RestrictSUIDSGID=true
MemoryDenyWriteExecute=true
LockPersonality=true

[Install]
WantedBy=multi-user.target
```

The configuration file is: 
```
blocknotify=echo\ %s
daemon=1
reindex=1
txindex=1
externalip=xxx
rescan=1
walletrbf=1
walletnotify=echo\ \'In wallet notify %s, %i\'
logips=1
server=1
rest=1

[main]

[test]

[signet]

[regtest]
```

Error in `debug.log`: 
2024-06-07 09:13:27 Opening LevelDB in /var/lib/dogecoin/chainstate
2024-06-07 09:13:27 Opened LevelDB successfully
2024-06-07 09:13:27 Wrote new obfuscate key for /var/lib/dogecoin/chainstate: 40d4ec2b0fa1d3ce
2024-06-07 09:13:27 Using obfuscation key for /var/lib/dogecoin/chainstate: 40d4ec2b0fa1d3ce
2024-06-07 09:13:27 Initializing databases...
2024-06-07 09:13:27 init message: Verifying blocks...
2024-06-07 09:13:27 Shutdown requested. Exiting.

`sudo systemctl status dogecoind`:
○ dogecoind.service - Dogecoin Daemon
     Loaded: loaded (/etc/systemd/system/dogecoind.service; disabled; preset: enabled)
     Active: inactive (dead)

Jun 07 11:13:27 v2202404220968263483 systemd[1]: Started dogecoind.service - Dogecoin Daemon.
Jun 07 11:13:27 v2202404220968263483 systemd[1]: dogecoind.service: Deactivated successfully.

I don't understand why is it stopping at launch! 
If you have any idea about it I take ^^

**Comment by GaloisField2718** [comment]
Also what I don't understand is: when I launch the command `/usr/bin/dogecoind -conf=/etc/dogecoin/dogecoin.conf -datadir=/var/lib/dogecoin` from doge user it works good.

**Comment by GaloisField2718** [comment]
> Hmmm, idk, but am wondering what would happen if you ran this without `daemon=1` in your dogecoin.conf file.

I can try but I suppose the same as when I run `dogecoind` nothing display and everything in the debug.log. 

I will try!

**Comment by patricklodder** [comment]
> I can try but I suppose the same 

Yes. It makes it fork off into the background.

Systemd needs you to not do that. The suggestion to remove `daemon=1` should fix it.

**Comment by GaloisField2718** [comment]
> > I can try but I suppose the same
> 
> Yes. It makes it fork off into the background.
> 
> Systemd needs you to not do that. The suggestion to remove `daemon=1` should fix it.

Yes totally!! Thank you very much I never think about this! 🙏
