### ISSUE TITLE
[bug] Contact information for Security Disclosures missing

### ISSUE THREAD

**Issue by murchandamus** [dogecoin/dogecoin#3556]
Hi,

Bitcoin Core contributors are planning a number of [vulnerability disclosures](https://bitcoinops.org/en/newsletters/2024/06/07/#upcoming-disclosure-of-vulnerabilities-affecting-old-versions-of-bitcoin-core) affecting old Bitcoin Core versions starting next month. Dogecoin may be affected by some of these vulnerabilities.

# Bug Report

**Current behavior:**

It is unclear how to contact maintainers of this project for security disclosures.

**Expected behavior**

The project provides a contact for disclosing security vulnerabilities.

**Comment by patricklodder** [comment]
Would appreciate getting a security heads up - will propose a SECURITY.md tonight.

**Comment by murchandamus** [comment]
Super, thanks for the quick turnaround.

**Comment by patricklodder** [comment]
Closing this as the security policy has been on `master` for a while now.
