### ISSUE TITLE
[solved] Maximum 8 peers available no matter setmaxconnection - windows gui

### ISSUE THREAD

**Issue by Arginoto** [dogecoin/dogecoin#3636]
ISSUES MISSING IMPORTANT INFORMATION MAY BE CLOSED WITHOUT INVESTIGATION.

# Bug Report

**Current behavior:**
setmaxconnections shows true, yet there are only maximum 8 connections

**Expected behavior**
Connections should be as you set in setmaxconnections commmand

**Steps to reproduce:**
setmaxconnections any number greater than 8

**Screenshots**
![image](https://github.com/user-attachments/assets/cde8030a-ac21-416f-aa16-8107c465e312)
![image](https://github.com/user-attachments/assets/24d1376e-3d2d-416c-bdf2-517c216be78a)

**Dogecoin Core version**
1.14.8 

**Machine specs**
- OS: windows 11
- CPU: i7 gen12
- RAM: 24gb
- Disk size: 1tb
- Disk Type ssd):

**Extra information**

**Comment by CryptoEconomize** [comment]
I have 11 without setting a maxconnections.  Same version and GUI.

![image](https://github.com/user-attachments/assets/86076847-b093-4d19-96a5-45aa636cfb87)

**Comment by Auuuk** [comment]
> I have 11 without setting a maxconnections. Same version and GUI.
> 
> ![image](https://private-user-images.githubusercontent.com/6612446/364439724-86076847-b093-4d19-96a5-45aa636cfb87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0ODU1MTQsIm5iZiI6MTcyNTQ4NTIxNCwicGF0aCI6Ii82NjEyNDQ2LzM2NDQzOTcyNC04NjA3Njg0Ny1iMDkzLTRkMTktOTZhNS00NWFhNjM2Y2ZiODcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDRUMjEyNjU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDZjNTkxYTExOTE0ZGIyOWIwYjk4NzA3YzgwYWMyMTkxYjc2ZTE0MjRlMDgxN2M0OGI3YmE5MzJmNWNlNWMzNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jjIFrv3l20_5Eupcu6iaA2oTrEToJiaVrOypxW6Mt1k)

Interesting, that must mean its on my end, i have tried to use my network with other p2p services, those seem to be okay, yet with doge node i never ever had more than 8 peers

**Comment by CryptoEconomize** [comment]
By chance are you not allowing incoming connections?  I think if you are outbound only it isn't using the setmaxconnections limit.  At least thats what it seems like as I tested it without incoming connections.  So maybe its a setmaxconnections for incoming.  If just outgoing might still limit to 8.  Not 100% positive though.

**Comment by Auuuk** [comment]
> By chance are you not allowing incoming connections? I think if you are outbound only it isn't using the setmaxconnections limit. At least thats what it seems like as I tested it without incoming connections. So maybe its a setmaxconnections for incoming. If just outgoing might still limit to 8. Not 100% positive though.

So far im operating doge node for about month, i never had more than 8 out connections (no more than 8peers) and never had single in connection ever

**Comment by CryptoEconomize** [comment]
Do you have the box checked to allow incoming connections?

![image](https://github.com/user-attachments/assets/c88a34e7-c3a3-4c7e-989d-83d8fe54a5c9)

**Comment by Auuuk** [comment]
Yes, it has been on all time, still i never seen no in connections ever

**Comment by Auuuk** [comment]
adding checkbox to "Map port using UPnP" fixed my issue, i have more peers now, that was not bug but user error. Thank you for support!!

**Comment by CryptoEconomize** [comment]
That was going to be my next suggestion.  Glad you got it resolved!
