### ISSUE TITLE
[bug] "Error opening block database."

### ISSUE THREAD

**Issue by danielocdh** [dogecoin/dogecoin#3645]
# Bug Report

**Current behavior:**

On launch I was presented with "Error opening block database." "Do you want to rebuild the block database now?" "OK" "Abort"
I pressed OK and not only the database but the blocks and chainstate data/folders were destroyed

**Expected behavior**

A clearer message that denoted that the blocks and chainstate folder will also be destroyed and the whole blocks will need to be downloaded again

**Steps to reproduce:**

Have an outdated database folder with updated blocks and chainstate folders
Start the client
Press "OK" on the "Do you want to rebuild the block database now?" prompt

**Dogecoin Core version**

1.14.8 (64-bit)

**Machine specs**
- OS: Windows 10
- CPU: Ryzen 5 1600X
- RAM: 64gb Crucial ECC
- Disk size: 500GB
- Disk Type (HD/SDD): SSD

**Comment by Anish-M-code** [comment]
@danielocdh can you please elaborate more on how to reproduce this issue , if i were to do fresh install of dogecoin.

**Comment by danielocdh** [comment]
> @danielocdh can you please elaborate more on how to reproduce this issue , if i were to do fresh install of dogecoin.

sorry I forgot about this report, sadly I don't have logs but the problem was about permissions on my setup, the files were fine and after fixing the permissions on my setup everything works fine

I always ran one client at a time, first as a regular user(windows from a linux share) and a second client in linux docker/root, the second client changed permissions/owner so when I ran the first client again the file permissions were insufficient for it. And that's what lead to the prompt
