### ISSUE TITLE
Too easy to send incorrect amounts

### ISSUE THREAD

**Issue by rnicoll** [dogecoin/dogecoin#365]
Raising this mostly for my own notes...

As illustrated by Moolah sending 20MDoge instead of 2MDoge ( http://www.reddit.com/r/dogecoin/comments/218vl3/i_just_accidentally_donated_20m_of_my_own_doge_to/ ), it's uncomfortably easy to miscount zeroes and send the wrong amount. In effect, this is the opposite problem to the one BTC has, where you have to watch zeroes after the decimal point.

Suggest adding drop-down units field when sending Doge, with options for:

MilliDoge
Doge
KiloDoge
MegaDoge

Obviously this field should reset to "Doge" after every use, to avoid massively over-sending.

As a further safety, when confirming transaction amount it should be specified as a percentage of total funds available, as well as an absolute quantity. Other suggestions welcomed (for example configurable warning/confirmation thresholds on sending large amounts).

**Comment by patricklodder** [comment]
@rnicoll can we close this?

**Comment by rnicoll** [comment]
Yes, so much yes.
