### ISSUE TITLE
Mined Transaction Details in Dogecoin-QT is wrong

### ISSUE THREAD

**Issue by iamdez** [dogecoin/dogecoin#464]
When I have a mined transaction I see the following description:

Generated coins must mature 50 blocks before they can be spent. When you generated this block, it was broadcast to the network to be added to the block chain. If it fails to get into the chain, its state will change to "not accepted" and it won't be spendable. This may occasionally happen if another node generates a block within a few seconds of yours.

**Comment by langerhans** [comment]
That is fixed in 1.10 now as it uses the same constant to calculate.
