### ISSUE TITLE
Block/WalletNotify Flashing Console Window on Windows

### ISSUE THREAD

**Issue by brcolow** [dogecoin/dogecoin#477]
I am using the -walletnotify option in my doge.conf to call a java program (just a simple .jar that databases the transaction id). The one issue is that this makes a window pop up and minimize anything that is running in full-screen (but even when not in full-screen just having it pop-up and disappear in a flash is very distracting). 

This was discussed on stackoverflow and Jori seems to propose a working solution, so I will pass that on here: http://bitcoin.stackexchange.com/questions/23999/blocknotify-walletnotify-but-without-the-console-window

If that is indeed a fix, this would be fantastic and really help me in working on my project. Thanks.

**Comment by ReverseControl** [comment]
I am closing this issue as out-of-date. Should this issue become relevant again, it can be opened again.
