### ISSUE TITLE
OS X: Unable to reopen the window after closing it

### ISSUE THREAD

**Issue by langerhans** [dogecoin/dogecoin#519]
Opening this as known issue.
Closing the Core window with the red X hides it as expected, but it can't be brought back afterwards. Only exiting and reopening fixes this.

Probably caused by the combination of Qt5 and OS X 10.6.  

I want to suggest dropping 10.6 support with 1.7.2. It is not supported by Apple anymore and probably not very much used amongst our userbase.

**Comment by patricklodder** [comment]
fixed with 1.10, closing
