### ISSUE TITLE
Boost link error while compiling on Ubuntu 12.04.4 LTS

### ISSUE THREAD

**Issue by pinovero** [dogecoin/dogecoin#530]
# ./configure

... check list ...
checking for boostlib >= 1.20.0... yes
checking whether the Boost::System library is available... yes
checking for exit in -lboost_system... yes
checking whether the Boost::Filesystem library is available... yes
checking for exit in -lboost_filesystem... yes
checking whether the Boost::Program_Options library is available... yes
checking for exit in -lboost_program_options-mt... yes
checking whether the Boost::Thread library is available... yes
checking for exit in -lboost_thread... yes
checking whether the Boost::Chrono library is available... no
checking whether the Boost::Unit_Test_Framework library is available... yes
configure: error: Could not link against boost_thread !

already tried ./configure --without-boost
...
checking for miniupnpc/upnperrors.h... yes
checking for main in -lminiupnpc... (cached) yes
checking whether the Boost::System library is available... yes
configure: error: Could not find a version of the library!

**Comment by tanusreechatterjee** [comment]
This is the error I got during the building of NFD in ubuntu 14.04. Tried many options but could not resolve it. Please help me in this regard. Please check the following.

Checking for boost linkage  : Could not link against boost libraries using supplied options 
The configuration failed
(complete log in /home/tanusree/nlsr/NFD/build/config.log)

**Comment by patricklodder** [comment]
@tanusreechatterjee please use the depends system, it will make sure you are linking against the correct versions of dependencies. See also https://github.com/dogecoin/dogecoin/blob/master/depends/README.md

For example when building for 64-bit linux, on 64-bit linux:
```
pushd depends
make
popd
./autogen.sh
./configure --prefix=`pwd`/depends/x86_64-unknown-linux-gnu
make
```
