### ISSUE TITLE
dogecoin-1.7.1 compile error

### ISSUE THREAD

**Issue by githubuser404** [dogecoin/dogecoin#563]
# ./configure --disable-ipv6 --with-boost=/usr/local/boost-1.55.0
# make
...
...
make[4]: Entering directory `/root/dogecoin-1.7.1/src/test'
  CXXLD  test_dogecoin
/usr/lib/gcc/i486-linux-gnu/4.4.3/../../../../lib/Scrt1.o: In function `_start':
(.text+0x28): undefined reference to `main'
collect2: ld returned 1 exit status
make[4]: *** [test_dogecoin] Error 1

Relevant infos
# dpkg -S /usr/lib/Scrt1.o
libc6-dev: /usr/lib/Scrt1.o

# dpkg -p libc6-dev
Package: libc6-dev
Priority: optional
Section: libdevel
Installed-Size: 18792
Maintainer: Ubuntu Core developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: i386
Source: eglibc
Version: 2.11.1-0ubuntu7.13
Provides: libc-dev
Depends: libc6 (= 2.11.1-0ubuntu7.13), libc-dev-bin (= 2.11.1-0ubuntu7.13), linux-libc-dev
Recommends: gcc | c-compiler
Suggests: glibc-doc, manpages-dev
Conflicts: binutils (<< 2.17cvs20070426-1)
Size: 4897040
Description: Embedded GNU C Library: Development Libraries and Header Files
 Contains the symlinks, headers, and object files needed to compile
 and link programs which use the standard C library.
Homepage: http://www.eglibc.org
Original-Maintainer: GNU Libc Maintainers <debian-glibc@lists.debian.org>

# gcc -v
Using built-in specs.
Target: i486-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.4.3-4ubuntu5.1' --with-bugurl=file:///usr/share/doc/gcc-4.4/README.Bugs --enable-languages=c,c++,fortran,objc,obj-c++ --prefix=/usr --enable-shared --enable-multiarch --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.4 --program-suffix=-4.4 --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-plugin --enable-objc-gc --enable-targets=all --disable-werror --with-arch-32=i486 --with-tune=generic --enable-checking=release --build=i486-linux-gnu --host=i486-linux-gnu --target=i486-linux-gnu
Thread model: posix
gcc version 4.4.3 (Ubuntu 4.4.3-4ubuntu5.1) 

Any other info you require?

**Comment by langerhans** [comment]
This should be obsolete by now.
