### ISSUE TITLE
Invalid, weaker fork can trigger safemode on correct fork

### ISSUE THREAD

**Issue by Earlz** [dogecoin/dogecoin#566]
I'm a dev of Fractalcoin, which is cloned from commit e362de3e815c8d114e202190b222e6100f98a4e7 of Dogecoin. We experienced a problem where safemode was triggered. A planned fork happened, and around 70% of the network hashing power was on the new fork. So, difficulty remained fairly sane, actually increasing compared to before the fork. However, the old fork was still getting blocks minted (due to difficulty adjustment of course). 

The fork checking code saw both forks after about 14 blocks into the fork and turned on safemode. The old fork was clearly weaker, with lower difficulty, and was also clearly invalid due to a difference in block rewards. However, the fork checking code does not ensure that a fork is valid, nor does it use anything but raw block height. 

Safemode being activated further compounded the problem, because RPC calls used by pools were disabled, causing mining on the new valid fork to stop. The first thing we tried to get mining back going is to add a checkpoint to the code after the fork point. This worked for a while, but safemode was triggered again, despite it clearly being invalid due to checkpoints not matching. The only final solution we could come up with is to use `-disablesafemode` and/or to disable the fork checking code temporarily. 

My expectations for fork checking include the follow:

1. Ignore forks that are invalid, according to checkpoint, block reward, etc
2. Only judge fork power based on cumulative difficulty, not just block height. Because otherwise mining on the proper fork will be stopped with a relatively modest hashrate of 5-10%. Basically enough to mint 14 blocks (of any difficulty) within the timespan of the proper fork minting 72 blocks. 

Another (separate issue) is that safemode disabling mining is very unsafe. It's usually mining that will bring a coin out of safemode. Purposefully making the network get stuck in the case something wrong happens does not sound like good behavior. (I think that's an upstream bitcoin issue though)

**Comment by rnicoll** [comment]
Not sure what to do with this - do we want to permanently increase the value? Might be simplest to push a PR to Bitcoin to make the value actually depend on block time, fix it permanently that way. Tagging for 1.10.1

**Comment by patricklodder** [comment]
I'd prefer fixing this asap rather than in 1.10.1 as a v3 block supermajority may result in minority forks, as happened with bitcoin at this fork

**Comment by Earlz** [comment]
Just to note, this issue isn't so major anymore in upstream bitcoin. In 0.10 (iirc) they no longer disable mining and info related RPC calls when safemode is activated. Some people (at least one exchange op, and a few other people) would actually prefer safemode to be activated temporarily around a hardfork point to make sure the network is stable before resuming normal transaction activity. In other altcoins though, I've had good luck by just increasing the fork warning values, with no unexpected safemode triggering

**Comment by rnicoll** [comment]
I'll do a value tweak in 1.10 and then see if I can fix it upstream.

**Comment by patricklodder** [comment]
#1229 fixed this.
