### ISSUE TITLE
Wallet options allow 0 DOGE fee

### ISSUE THREAD

**Issue by langerhans** [dogecoin/dogecoin#661]
![image](https://cloud.githubusercontent.com/assets/5160000/4024721/8d1d4802-2bd6-11e4-8967-6595b3200576.png)

The input box should now be limited to >= 1 DOGE as a fee is mandatory now. Not sure if we may remove it altogether? Opening this here as reminder and for discussion. Targeting 1.8.1.

**Comment by rnicoll** [comment]
#1278 should solve this, more or less; zero-fee option was moved into the send tab, and I've simply ripped the option out. Please close if you're happy.

**Comment by patricklodder** [comment]
Confirm fixed.
