### ISSUE TITLE
RPC calls are slow

### ISSUE THREAD

**Issue by Joter85** [dogecoin/dogecoin#670]
I have upgraded Windows wallet to version 1.8 and now RPC calls are sometimes slow. Server CPU load is max 5%, memory 50%, SSD no transfer at all. RPC calls are running from same machine that wallet is running on.
Yesterday I got same problem, then it started to work fine... today again slow... maybe it will speed up soon... I don't think server is a problem.
Wallet has around 2500 addresses.

*EDIT*
Wallet stops responding to any RPC calls after a while (12 hours in my case). After restart of service it works ok. 
I have increased rpcthreads from default 4 to 50. Maybe this should help... Will report.

**Comment by patricklodder** [comment]
@rnicoll is this still relevant?

**Comment by Joter85** [comment]
No, we are still running this with 50 RPC threads. It works fine, haven't tried to lower it.
