### ISSUE TITLE
Cannot configure 1.8 on MacOSX Mavericks (10.9.4)

### ISSUE THREAD

**Issue by PeterOdeus** [dogecoin/dogecoin#699]
Hi. Here's what I get when I follow the MacPorts-only path at https://github.com/dogecoin/dogecoin/blob/master/doc/build-osx.md and trying ``./configure --enable-debug``

```
...
checking for Berkeley DB C++ headers... /opt/local/include/db51/
checking for main in -ldb_cxx-5.1... no
checking for main in -ldb_cxx... no
configure: error: libdb_cxx missing
```

Pretty much lost here. It doesn't make any difference if I install QT4, as per the guideline, does it?

Please advice.

**Comment by rnicoll** [comment]
Can we close this now?
