### ISSUE TITLE
DOGE parameters for wrapper

### ISSUE THREAD

**Issue by xeniacx** [dogecoin/dogecoin#700]
We are trying to track down Dogecoin's parameters so we can configure [BitcoinLib](https://github.com/GeorgeKimionis/BitcoinLib) to support Doge.

The parameters required can be found [here](https://github.com/GeorgeKimionis/BitcoinLib/pull/16/files#diff-7a9f2fd724ab95c26deb5eced5b3d724R115) and are:

```
TransactionSizeBytesContributedByEachInput = 148;
TransactionSizeBytesContributedByEachOutput = 34;
TransactionSizeFixedExtraSizeInBytes = 10;
FreeTransactionMaximumSizeInBytes = 1;               // Are there any free transactions?
FreeTransactionMinimumOutputAmountInCoins = 1; 
FreeTransactionMinimumPriority = 230400000;        
FeePerThousandBytesInCoins = 1;
MinimumTransactionFeeInCoins = 1;
MinimumNonDustTransactionAmountInCoins = 0.001M;
TotalCoinSupplyInCoins = 100000000000;
EstimatedBlockGenerationTimeInMinutes = 1;
BlocksHighestPriorityTransactionsReservedSizeInBytes = 16000;
BlockMaximumSizeInBytes = 1000000;
BaseUnitName = "Koinu";
BaseUnitsPerCoin = 100000000;
CoinsPerBaseUnit = 0.00000001M;
CoinReleaseHalfsEveryXInYears = 4;
DifficultyIncreasesEveryXInBlocks = 2016;
```

We would be grateful if somebody could provide us with the correct values.

**Comment by rnicoll** [comment]
Just realised I haven't got back to you about this after my last comment - did that all work? Need any more help?

**Comment by GeorgeKimionis** [comment]
Hey @rnicoll appreciate your concern, we have used these values for dogecoin: https://github.com/GeorgeKimionis/BitcoinLib/blob/5930afa4517c18f8b9fd724df3bdd2f8f2b91710/CoinWrapper/CoinParameters/Base/CoinParameters.cs#L136 it would be nice if you could review them, thanks!

**Comment by rnicoll** [comment]
Looks fine... Having just been over our version of consensus parameters with a fine tooth comb, I know there's some fiddly stuff, I'll try to grab your library and run in-depth tests at some point. No idea when, unfortunately, my schedule is rather bug-driven (i.e. I get to the next task when bugs stop appearing in the current one)

**Comment by GeorgeKimionis** [comment]
@rnicoll  sounds good, your input will be much appreciated.
