### ISSUE TITLE
Stop relaying free TXes

### ISSUE THREAD

**Issue by rnicoll** [dogecoin/dogecoin#703]
At the moment we're seeing a lot of spam from crazy-cheap transactions. Given 1.8 stops these from being generated by default, I think we can now disable the support for them. Propose:
- In main.cpp around like 910, set "allow free" passed to GetMinFee() to false.
- Remove legacy fee rules from wallet.cpp around line 1410
- Reduce minimum send/relay tx fees to 10000000 (main.cpp around line 59)

Default TX fee should remain at 1000000000.

Note that we must be certain there's no fork risk as a result, and that mined transactions do not fail as a result. Pools will want to mine their own zero-fee txes and are welcome to do so as normal.

**Comment by patricklodder** [comment]
To illustrate an additional issue with 1.10: 

0 fee gets relayed and mined but anything between 0 and 1 doge per kb does not get relayed. We need to do something about that, moving to milestone 1.11
