### ISSUE TITLE
Compile 1.8 ,Encountered an error

### ISSUE THREAD

**Issue by cqtenq** [dogecoin/dogecoin#705]
I am compiling dogecoin-1.8, have some undefined reference about UPNP. But I had made miniupnpc-1.9.

make[3]: Entering directory /D/BTC/Dev/dogecoin-master/src' CXXLD bitcoind.exe libbitcoin_server.a(net.o): In functionZ13ThreadMapPortv':
d:\BTC\Dev\dogecoin-master\src/net.cpp:1066: undefined reference to _imp__upnpDiscover' d:\BTC\Dev\dogecoin-master\src/net.cpp:1073: undefined reference to_imp__UPNP_GetValidIGD'

also  CPPFLAGS = "-DMINIUPNP_STATICLIB -DSTATICLIB"

**Comment by patricklodder** [comment]
This should have been fixed in both 1.8.3 and 1.10.0. Can you confirm?
