### ISSUE TITLE
new suggeted features 

### ISSUE THREAD

**Issue by wralenezi** [dogecoin/dogecoin#711]
Hey Guys,
My friends and I have a list of features we would like to implement on dogecoin, and it would be great if i get some feedback to determine weather i should proceed with the development of these features : 
1. Transaction history USD converter
to have a label next the amounts (eg: Total Balance,Transaction history) in USD 
1. Recurring payment feature
   to scehdule payments 
2. Transaction label
   to add a transaction label in the transaction history 
3. Dynamic fee based on transaction amount
4. Automatic wallet backup
5. Import wallet (.dat file) rather than having to move it to the folder manually
6. balance history line chart
   to display a line chart of the balance over time

Thank you,

**Comment by IeuanG** [comment]
>1. Transaction history USD converter

Not all people live in the US, and implementing all currencies would end up with a massive amount of dependencies on centralized systems to be able to retrieve the price. Of course these can be updated, but this just seems like a feature that would require too much maintenance, checking and updating IMO. 

How can you be sure that the price of all currencies are correct / valid?
