### ISSUE TITLE
Max orphan blocks problem when syncing.

### ISSUE THREAD

**Issue by simondlr** [dogecoin/dogecoin#717]
I've recently started resyncing (from about April this year) and getting 1.8. Twice now I've run into a problem where it seems to get stuck in the debug.log at processing new blocks.

ProcessBlock: ORPHAN BLOCK 751, prev=hash
ProcessBlock: ORPHAN BLOCK 751, prev=new hash
ProcessBlock: ORPHAN BLOCK 751, prev=another hash
ProcessBlock: ORPHAN BLOCK 751, prev=etc

When this happens. I close Dogecoin-QT and open it up again and starts syncing properly again.

I suspect it is because the max orphan blocks in memory was set to 750.

As far as I understand the point is to keep orphans in memory until the parents have been found/synced and attaching them. Over time, this gets larger and larger until it potentially reaches the hardcoded max (750).

When max orphans get reached, it starts deleting a random orphan and adding the new orphan into memory... potentially dropping an orphan that would've linked up the chain. Thus slowing down the chain sync considerably as it has to wait again for the correct combo of orphaned blocks to be in memory for the chain to link up?

I see Bitcoin is experiencing this as well: https://github.com/bitcoin/bitcoin/issues/4353

There seems to be temporary fix but which shifts it to another problem. See discussion here: https://github.com/bitcoin/bitcoin/pull/4431

**Comment by rnicoll** [comment]
This is in Dogecoin Core 1.10, and brings sync time down to about 3 hours (on an EC2 node writing to SSD, to be fair)

**Comment by patricklodder** [comment]
This is no longer an issue with 1.10, closing.
