### ISSUE TITLE
file makefile.unix

### ISSUE THREAD

**Issue by ksander1** [dogecoin/dogecoin#722]
When installing, I ran into a problem:
make -j2 -f makefile.unix USE_UPNP=1 USE_IPV6=0 -e PIE=1
As indicated here need a file makefile.unix
  I could not find it in the distributive purse dogecoin. Maybe there kaky another file is responsible for the request, or you are installing on another? Maybe the file can be copied from another location?

**Comment by jaelcorp** [comment]
Thanks for all this
