### ISSUE TITLE
Compiling on Ubuntu 14.10

### ISSUE THREAD

**Issue by xaoseric** [dogecoin/dogecoin#738]
Just compiled on Ubuntu 14.10. libboost1.54-all-dev works fine on Ubuntu 14.10. A swap file will be needed, otherwise you will run out of memory

Instructions for making a swap file should be added:
https://meta.discourse.org/t/create-a-swapfile-for-your-linux-server/13880

**Comment by prestotron** [comment]
Added some documentation to the unix build instructions.

If it gets merged then you will be all set.
