### ISSUE TITLE
RPC call for Merged Mining

### ISSUE THREAD

**Issue by whattheflux** [dogecoin/dogecoin#778]
Hi, not sure if this is the right place to ask.

I have set up a Litecoin python-stratum-mining pool that I only use for myself with an MPOS front end.

I would like to merge mine dogecoin using AuxPOW, but I don't care about displaying the hashrate on the front end of MPOS.

If there a command line parameter for running dogecoind that will receive auxPOW input from my running litecoin daemon.

The way I see it (the dumbed down version) is that stratum-mining is submitting shares to the LTC network via my running litecoin daemon which is in turn running on RPC Port: 1234

Can I just configure my dogecoin.conf to receive the input from the Litecoind ??? Looking at the source, this seems possible, I just can't find the command.

**Comment by langerhans** [comment]
No, it receives the blocks from the same source. litecoind doesn't know about anything auxpow. it's completely transparent for it.  
This also means your stratum does actually need support auxpow. I'm not sure if the current version actually does that (?).  

You need a running dogecoind and it'll get the blocks through the RPC interface just like litecoind does.
