### ISSUE TITLE
Is the ComputeMinWork function wrong for the new difficulty adjustments?

### ISSUE THREAD

**Issue by scmorse** [dogecoin/dogecoin#783]
I'm not 100% sure that it is, but with some quick napkin math, it seems like the ComputeMinWork function isn't correct. 

I would expect that this:

<pre>
// Maximum 10% adjustment...
bnResult = (bnResult * 110) / 100;
// ... in best-case exactly 4-times-normal target time
nTime -= nTargetTimespanNEW*4;
</pre>

Should be this:

<pre>
// Maximum 50% adjustment...
bnResult = (bnResult * 150) / 100;
// ... in best-case exactly 5-times-normal target time
nTime -= nTargetTimespanNEW*5;
</pre>

I got this because if <code>nActualTime = 5*nTargetTimespanNEW</code>, then <code>nModulatedTime = (retargetTimespan + (retargetTimespan/2)</code>, which is the maximum it can be. When it attains this maximum, `bnNew` is increased by 50%.

**Comment by rnicoll** [comment]
At a glance I can't see anything wrong with your logic, but have to admit I came onboard after Digishield was implemented, so am unaware of the exact theory underlying it. It could be that across 4 minute intervals it's smoothed to within 10% (which is what the code seems to expect).

**Comment by scmorse** [comment]
It might be a safety feature. Just because the difficulty in the chain could theoretically decrease by 50% every block, it doesn't mean that it actually will with any real likelihood. But still, it seems that if the difficulty were lowered at a significantly fast rate, it could cause some clients who were catching up to refuse correct blocks. They would probably just accept it later, however, when it is processed at the tip of the chain. 

As the comment indicats, this function is for "fill up memory by spamming with bogus blocks" attacks.

**Comment by rnicoll** [comment]
It looks like Bitcoin Core has removed the code, check and error entirely in 0.11, neatly eliminating the problem entirely. Thanks for letting us know, though!
