### ISSUE TITLE
[COMPATIBILITY] For FreeBSD, rename le32enc/dec and be32enc/dec

### ISSUE THREAD

**Issue by stolendata** [dogecoin/dogecoin#787]
On FreeBSD, Boost's inclusions of le32enc, le32dec, be32enc and be32dec conflict with Dogecoin's own declarations present in scrypt.cpp and scrypt.h, resulting in a failure to compile.

Suggestion: rename Dogecoin's declarations, perhaps by prefixing as scrypt_le32enc or similar.

**Comment by langerhans** [comment]
Fixed in #793
