### ISSUE TITLE
dogecoin/src/$ make -f makefile.unix use_upnp =-

### ISSUE THREAD

**Issue by redakai** [dogecoin/dogecoin#832]
ubuntu version 14.10
after using this command i get this error
dogecoin/src/$ make -f makefile.unix use_upnp =-
make: ***empty variable name.  stop.

**Comment by rnicoll** [comment]
The build system is based on the Bitcoin Core 0.9 build environment, rather than the older versions that use "make -f..."

Have a look at https://github.com/dogecoin/dogecoin/blob/1.9-dev/doc/build-unix.md for instructions
