### ISSUE TITLE
Links down at doc/bootstrap.md document.

### ISSUE THREAD

**Issue by erm3nda** [dogecoin/dogecoin#898]
I watch that site today to get again that file and is not anymore.
Do you know any other download source for that file? (Not torrent)

**Comment by langerhans** [comment]
Link is here: https://bootstrap.chain.so/  
Thanks for the notification!

**Comment by erm3nda** [comment]
Please try it yourself before tell me about a link wich is say is not valid.
I've checked all your mirrors.

Seems that website is no longer allowing file download or it's not published yet under another url.
I don't know where to download it without torrent.

I was able to download that file 1 week ago. That's so recent. Check it.

**Comment by langerhans** [comment]
It's back up.

**Comment by erm3nda** [comment]
Thank you
